import { NextRequest } from "next/server";
import { apiError, assertSameOrigin, cleanText, json, readJson, validEmail } from "@/lib/server/http";
import { requireSession } from "@/lib/server/session";
import { authorize } from "@/lib/server/rbac";
import { withTenant } from "@/lib/server/db";
import { inviteUser } from "@/lib/server/invitations";
type InviteBody={email?:unknown;role?:unknown};
export async function GET(){try{const s=await requireSession();authorize(s,"users:read");const data=await withTenant(s.organizationId,s.userId,async c=>{const members=(await c.query("select m.user_id,m.role,m.status,m.created_at,u.display_name name,u.email from organization_memberships m join app_users u on u.id=m.user_id where m.organization_id=$1 and m.status='active' order by m.created_at",[s.organizationId])).rows;const invitations=(await c.query("select id,email,role,status,expires_at,created_at from organization_invitations where organization_id=$1 order by created_at desc",[s.organizationId])).rows;const account=(await c.query("select e.max_users user_limit,s.plan from organization_entitlements e join organization_subscriptions s on s.organization_id=e.organization_id where e.organization_id=$1",[s.organizationId])).rows[0];return {members,invitations,userLimit:account?.user_limit??1,plan:account?.plan??"trial"}});return json(data)}catch(error){return apiError(error)}}
export async function POST(request:NextRequest){try{assertSameOrigin(request);const s=await requireSession();authorize(s,"users:manage");const b=await readJson<InviteBody>(request,8192);const email=cleanText(b.email,320).toLowerCase();const role=cleanText(b.role,40)||"member";if(!["admin","finance","hr","project_manager","manager","member","reader"].includes(role))return json({error:"role_invalid",message:"Ungültige Rolle."},400);if(!validEmail(email))return json({error:"email_invalid",message:"Bitte gültige E-Mail-Adresse eingeben."},400);const result=await inviteUser(s,email,role,request.headers.get('Idempotency-Key')??'');return json(result,201)}catch(error){return apiError(error)}}
