import { NextRequest } from "next/server";
import { randomUUID } from "node:crypto";
import { apiError, assertSameOrigin, cleanText, json, readJson, validEmail } from "@/lib/server/http";
import { requireSession } from "@/lib/server/session";
import { authorize } from "@/lib/server/rbac";
import { withTenant } from "@/lib/server/db";
import { inviteUser } from "@/lib/server/service-role";
type InviteBody={email?:unknown;role?:unknown};
export async function GET(){try{const s=await requireSession();authorize(s,"users:read");const data=await withTenant(s.organizationId,s.userId,async c=>{const members=(await c.query("select user_id,role,created_at from organization_memberships where organization_id=$1 order by created_at",[s.organizationId])).rows;const invitations=(await c.query("select id,email,role,status,expires_at,created_at from organization_invitations where organization_id=$1 order by created_at desc",[s.organizationId])).rows;const account=(await c.query("select user_limit,plan from organizations where id=$1",[s.organizationId])).rows[0];return {members,invitations,userLimit:account?.user_limit??1,plan:account?.plan??"trial"}});return json(data)}catch(error){return apiError(error)}}
export async function POST(request:NextRequest){try{assertSameOrigin(request);const s=await requireSession();authorize(s,"users:manage");const b=await readJson<InviteBody>(request,8192);const email=cleanText(b.email,320).toLowerCase();const role=b.role==="admin"?"admin":"member";if(!validEmail(email))return json({error:"email_invalid",message:"Bitte gültige E-Mail-Adresse eingeben."},400);const id=randomUUID();await withTenant(s.organizationId,s.userId,c=>c.query("insert into organization_invitations(id,organization_id,email,role,status,expires_at,created_by_user_id) values($1,$2,$3,$4,'pending',now()+interval '7 days',$5)",[id,s.organizationId,email,role,s.userId]));try{await inviteUser(email,{organization_id:s.organizationId,role,invitation_id:id})}catch(error){await withTenant(s.organizationId,s.userId,c=>c.query("update organization_invitations set status='revoked' where id=$1 and organization_id=$2",[id,s.organizationId]));throw error}return json({ok:true,id},201)}catch(error){return apiError(error)}}
