"use client";
import {useRef,useState} from "react";
import Image from "next/image";
import {useRouter} from "next/navigation";
import Link from "next/link";
import {ArrowLeft,Camera,FileClock,Paperclip,Send,Trash2,Upload} from "lucide-react";
import {apiFetch,isProductionMode} from "@/lib/client/runtime";
import {createSupportTicket,type SupportAttachment} from "@/lib/pilot-store";
import {notify} from "@/lib/notify";
import {captureSupportScreenshot,collectSupportDiagnostics,type SupportDiagnostics} from "@/lib/support/diagnostics";

type UploadedAttachment=SupportAttachment&{uploadId?:string};
const MAX_FILES=5;
const MAX_LOCAL_SIZE=2*1024*1024;
function formatBytes(value:number){if(value<1024)return `${value} B`;if(value<1024*1024)return `${(value/1024).toFixed(1)} KB`;return `${(value/1024/1024).toFixed(1)} MB`}
function fileToDataUrl(file:File){return new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result||""));r.onerror=()=>reject(r.error);r.readAsDataURL(file)})}

export default function SupportNew(){
 const router=useRouter();const fileInput=useRef<HTMLInputElement>(null);const cameraInput=useRef<HTMLInputElement>(null);
 const [v,setV]=useState({category:"Frage",subject:"",description:"",priority:"Normal"});const [busy,setBusy]=useState(false);const [diagnostics,setDiagnostics]=useState<SupportDiagnostics|null>(null);const [screenshot,setScreenshot]=useState<string>("");const [captureBusy,setCaptureBusy]=useState(false);const [attachments,setAttachments]=useState<UploadedAttachment[]>([]);const [uploading,setUploading]=useState(false);
 async function capture(){setCaptureBusy(true);try{const img=await captureSupportScreenshot();setScreenshot(img);notify("Screenshot wurde angehängt.")}catch(e){notify(e instanceof Error?e.message:"Screenshot konnte nicht erstellt werden.","danger")}finally{setCaptureBusy(false)}}
 function attachDiagnostics(){setDiagnostics(collectSupportDiagnostics());notify("Technische Diagnose wurde angehängt.")}
 async function addFiles(files:FileList|null){if(!files?.length)return;const remaining=MAX_FILES-attachments.length;if(remaining<=0){notify(`Maximal ${MAX_FILES} Anhänge pro Ticket.`,"danger");return}setUploading(true);try{const next:UploadedAttachment[]=[];for(const file of Array.from(files).slice(0,remaining)){if(isProductionMode()){const form=new FormData();form.append("file",file);const r=await apiFetch<{item:{id:string;fileName:string;mimeType:string;sizeBytes:number}}>("/api/support/attachments",{method:"POST",body:form});next.push({...r.item,uploadId:r.item.id})}else{if(file.size>MAX_LOCAL_SIZE){notify(`${file.name}: im lokalen Modus maximal 2 MB.`,"danger");continue}const dataUrl=await fileToDataUrl(file);next.push({id:`local-${Date.now()}-${next.length}`,fileName:file.name,mimeType:file.type||"application/octet-stream",sizeBytes:file.size,dataUrl})}}setAttachments(x=>[...x,...next]);if(next.length)notify(`${next.length} Anhang${next.length===1?"":"änge"} hinzugefügt.`)}catch(e){notify(e instanceof Error?e.message:"Anhang konnte nicht hochgeladen werden.","danger")}finally{setUploading(false);if(fileInput.current)fileInput.current.value="";if(cameraInput.current)cameraInput.current.value=""}}
 async function removeAttachment(item:UploadedAttachment){try{if(isProductionMode()&&item.uploadId)await apiFetch(`/api/support/attachments/${item.uploadId}`,{method:"DELETE"});setAttachments(x=>x.filter(y=>y.id!==item.id))}catch(e){notify(e instanceof Error?e.message:"Anhang konnte nicht entfernt werden.","danger")}}
 async function submit(e:React.FormEvent){e.preventDefault();if(!v.subject.trim()||!v.description.trim())return;setBusy(true);try{const payload={...v,diagnostics:diagnostics||undefined,screenshot:screenshot||undefined,attachmentIds:attachments.map(a=>a.uploadId).filter(Boolean),attachments:isProductionMode()?undefined:attachments};if(isProductionMode()){const r=await apiFetch<{item:{id:string}}>("/api/support",{method:"POST",body:JSON.stringify(payload)});router.push(`/support/${r.item.id}`)}else{const t=createSupportTicket(payload);router.push(`/support/${t.id}`)}notify("Supportticket erstellt.")}catch(e){notify(e instanceof Error?e.message:"Ticket konnte nicht erstellt werden.","danger")}finally{setBusy(false)}}
 return <div className="page"><Link className="back-link" href="/support"><ArrowLeft size={17}/>Zurück</Link><section className="module-heading"><div><div className="eyebrow">Support</div><h1>Ticket erstellen</h1><p>Beschreibe das Anliegen kurz. Diagnose, Screenshot und Anhänge sind freiwillig.</p></div></section><form className="workspace-card support-form" onSubmit={submit}><div className="form-grid"><label><span>Kategorie</span><select value={v.category} onChange={e=>setV({...v,category:e.target.value})}><option>Frage</option><option>Fehler</option><option>Bedienung</option><option>Abrechnung</option><option>Sicherheit</option><option>Idee</option></select></label><label><span>Priorität</span><select value={v.priority} onChange={e=>setV({...v,priority:e.target.value})}><option>Niedrig</option><option>Normal</option><option>Hoch</option><option>Kritisch</option></select></label><label className="full"><span>Betreff *</span><input value={v.subject} onChange={e=>setV({...v,subject:e.target.value})} maxLength={180} required/></label><label className="full"><span>Beschreibung *</span><textarea rows={8} value={v.description} onChange={e=>setV({...v,description:e.target.value})} required/></label></div>
 <section className="support-capture-card"><div><strong>Hilfreiche Zusatzinformationen</strong><span>Freiwillig. Technische Daten werden redigiert; Passwörter, Cookies und Tokens werden nicht mitgesendet.</span></div><div className="support-capture-actions"><button type="button" className="secondary-button" onClick={attachDiagnostics}><FileClock size={16}/>{diagnostics?"Diagnose aktualisieren":"Diagnose anhängen"}</button><button type="button" className="secondary-button" onClick={capture} disabled={captureBusy}><Camera size={16}/>{captureBusy?"Aufnahme läuft …":screenshot?"Screenshot ersetzen":"Screenshot aufnehmen"}</button><button type="button" className="secondary-button" onClick={()=>fileInput.current?.click()} disabled={uploading||attachments.length>=MAX_FILES}><Paperclip size={16}/>{uploading?"Wird hochgeladen …":"Datei anhängen"}</button><button type="button" className="secondary-button support-camera-file" onClick={()=>cameraInput.current?.click()} disabled={uploading||attachments.length>=MAX_FILES}><Camera size={16}/>Foto aufnehmen</button></div>
 <input ref={fileInput} className="visually-hidden" type="file" multiple accept="image/png,image/jpeg,image/webp,application/pdf,text/plain,text/csv" onChange={e=>void addFiles(e.target.files)}/><input ref={cameraInput} className="visually-hidden" type="file" accept="image/*" capture="environment" onChange={e=>void addFiles(e.target.files)}/>
 {diagnostics&&<div className="support-attachment-pill"><span>Diagnose · {diagnostics.recentEvents.length} technische Ereignisse</span><button type="button" onClick={()=>setDiagnostics(null)} aria-label="Diagnose entfernen"><Trash2 size={14}/></button></div>}
 {attachments.length>0&&<div className="support-file-list">{attachments.map(a=><div key={a.id}><Upload size={15}/><span><strong>{a.fileName}</strong><small>{formatBytes(a.sizeBytes)}</small></span><button type="button" onClick={()=>void removeAttachment(a)} aria-label={`${a.fileName} entfernen`}><Trash2 size={14}/></button></div>)}</div>}
 {screenshot&&<div className="support-screenshot-preview"><Image src={screenshot} alt="Screenshot Vorschau" width={720} height={420} unoptimized/><button type="button" className="secondary-button" onClick={()=>setScreenshot("")}><Trash2 size={15}/>Screenshot entfernen</button></div>}</section><button className="primary-button" disabled={busy||uploading}><Send size={17}/>{busy?"Wird erstellt …":"Ticket senden"}</button></form></div>
}
