"use client";
import {useState} from "react";import Image from "next/image";import {useRouter} from "next/navigation";import Link from "next/link";import {ArrowLeft,Camera,FileClock,Send,Trash2} from "lucide-react";import {apiFetch,isProductionMode} from "@/lib/client/runtime";import {createSupportTicket} from "@/lib/pilot-store";import {notify} from "@/lib/notify";import {captureSupportScreenshot,collectSupportDiagnostics,type SupportDiagnostics} from "@/lib/support/diagnostics";
export default function SupportNew(){
 const router=useRouter();const [v,setV]=useState({category:"Frage",subject:"",description:"",priority:"Normal"});const [busy,setBusy]=useState(false);const [diagnostics,setDiagnostics]=useState<SupportDiagnostics|null>(null);const [screenshot,setScreenshot]=useState<string>("");const [captureBusy,setCaptureBusy]=useState(false);
 async function capture(){setCaptureBusy(true);try{const img=await captureSupportScreenshot();setScreenshot(img);notify("Screenshot wurde angehängt.")}catch(e){notify(e instanceof Error?e.message:"Screenshot konnte nicht erstellt werden.","danger")}finally{setCaptureBusy(false)}}
 function attachDiagnostics(){setDiagnostics(collectSupportDiagnostics());notify("Technische Diagnose wurde angehängt.")}
 async function submit(e:React.FormEvent){e.preventDefault();if(!v.subject.trim()||!v.description.trim())return;setBusy(true);try{const payload={...v,diagnostics:diagnostics||undefined,screenshot:screenshot||undefined};if(isProductionMode()){const r=await apiFetch<{item:{id:string}}>("/api/support",{method:"POST",body:JSON.stringify(payload)});router.push(`/support/${r.item.id}`)}else{const t=createSupportTicket(payload);router.push(`/support/${t.id}`)}notify("Supportticket erstellt.")}catch(e){notify(e instanceof Error?e.message:"Ticket konnte nicht erstellt werden.","danger")}finally{setBusy(false)}}
 return <div className="page"><Link className="back-link" href="/support"><ArrowLeft size={17}/>Zurück</Link><section className="module-heading"><div><div className="eyebrow">Support</div><h1>Ticket erstellen</h1><p>Beschreibe das Anliegen kurz. Technische Diagnose und Screenshot kannst du freiwillig anhängen.</p></div></section><form className="workspace-card support-form" onSubmit={submit}><div className="form-grid"><label><span>Kategorie</span><select value={v.category} onChange={e=>setV({...v,category:e.target.value})}><option>Frage</option><option>Fehler</option><option>Bedienung</option><option>Abrechnung</option><option>Sicherheit</option><option>Idee</option></select></label><label><span>Priorität</span><select value={v.priority} onChange={e=>setV({...v,priority:e.target.value})}><option>Niedrig</option><option>Normal</option><option>Hoch</option><option>Kritisch</option></select></label><label className="full"><span>Betreff *</span><input value={v.subject} onChange={e=>setV({...v,subject:e.target.value})} maxLength={180} required/></label><label className="full"><span>Beschreibung *</span><textarea rows={8} value={v.description} onChange={e=>setV({...v,description:e.target.value})} required/></label></div><section className="support-capture-card"><div><strong>Technische Informationen</strong><span>Nur technische Metadaten, Route und letzte Fehlerereignisse. Keine Passwörter oder Cookies.</span></div><div className="support-capture-actions"><button type="button" className="secondary-button" onClick={attachDiagnostics}><FileClock size={16}/>{diagnostics?"Diagnose aktualisieren":"Diagnose anhängen"}</button><button type="button" className="secondary-button" onClick={capture} disabled={captureBusy}><Camera size={16}/>{captureBusy?"Aufnahme läuft …":screenshot?"Screenshot ersetzen":"Screenshot aufnehmen"}</button></div>{diagnostics&&<div className="support-attachment-pill"><span>Diagnose angehängt · {diagnostics.recentEvents.length} Ereignisse</span><button type="button" onClick={()=>setDiagnostics(null)} aria-label="Diagnose entfernen"><Trash2 size={14}/></button></div>}{screenshot&&<div className="support-screenshot-preview"><Image src={screenshot} alt="Screenshot Vorschau" width={720} height={420} unoptimized/><button type="button" className="secondary-button" onClick={()=>setScreenshot("")}><Trash2 size={15}/>Screenshot entfernen</button></div>}</section><button className="primary-button" disabled={busy}><Send size={17}/>{busy?"Wird erstellt …":"Ticket senden"}</button></form></div>
}
