"use client";
import Link from "next/link";
import {ButtonLink} from "@/components/ui/button-link";import {useEffect,useState} from "react";import {Headphones,Plus,Search} from "lucide-react";import {apiFetch,isProductionMode} from "@/lib/client/runtime";import {listSupportTickets,type SupportTicket} from "@/lib/pilot-store";import {useLocale} from "@/components/locale-provider";import {supportCategoryLabel,supportPriorityLabel,supportStatusLabel} from "@/lib/support/labels";
export default function SupportList(){
 const {t}=useLocale();const [items,setItems]=useState<SupportTicket[]>([]);const [q,setQ]=useState("");
 useEffect(()=>{const load=async()=>{if(isProductionMode()){try{const r=await apiFetch<{items:SupportTicket[]}>("/api/support");setItems(r.items)}catch{setItems([])}}else setItems(listSupportTickets())};void load()},[]);
 const shown=items.filter(x=>`${x.number} ${x.subject} ${x.category} ${x.status}`.toLowerCase().includes(q.toLowerCase()));
 return <div className="page"><section className="module-heading"><div><div className="eyebrow">{t("Hilfe")}</div><h1>{t("Support")}</h1><p>{t("Fragen, Fehler und Sicherheitsmeldungen direkt mit dem Binso Support klären.")}</p></div><ButtonLink href="/support/neu"><Plus size={17}/>{t("Ticket erstellen")}</ButtonLink></section>
 <section className="workspace-card"><div className="support-search"><Search size={17}/><input placeholder={t("Tickets suchen …")} value={q} onChange={e=>setQ(e.target.value)}/></div>{shown.length?<div className="support-table"><div className="support-row head"><span>{t("Ticket")}</span><span>{t("Betreff")}</span><span>{t("Kategorie")}</span><span>{t("Priorität")}</span><span>{t("Status")}</span></div>{shown.map(x=><Link className="support-row" href={`/support/${x.id}`} key={x.id}><strong>{x.number}</strong><span>{x.subject}</span><span>{t(supportCategoryLabel(x.category))}</span><span>{t(supportPriorityLabel(x.priority))}</span><em>{t(supportStatusLabel(x.status))}</em></Link>)}</div>:<div className="empty-state"><Headphones size={28}/><strong>{t("Noch keine Supporttickets")}</strong><p>{t("Erstelle ein Ticket, wenn du Hilfe benötigst oder etwas nicht wie erwartet funktioniert.")}</p><Link href="/support/neu">{t("Erstes Ticket erstellen")}</Link></div>}</section></div>
}
