"use client";
import {useRef,useState} from "react";
import Image from "next/image";
import {useRouter} from "next/navigation";
import Link from "next/link";
import {ArrowLeft,Camera,FileClock,Paperclip,Send,Trash2,Upload} from "lucide-react";
import {apiFetch,isProductionMode} from "@/lib/client/runtime";
import {createSupportTicket,type SupportAttachment} from "@/lib/pilot-store";
import {notify} from "@/lib/notify";
import {captureSupportScreenshot,collectSupportDiagnostics,type SupportDiagnostics} from "@/lib/support/diagnostics";
import {useLocale} from "@/components/locale-provider";

type UploadedAttachment=SupportAttachment&{uploadId?:string};
const MAX_FILES=5;
const MAX_LOCAL_SIZE=2*1024*1024;
function formatBytes(value:number){if(value<1024)return `${value} B`;if(value<1024*1024)return `${(value/1024).toFixed(1)} KB`;return `${(value/1024/1024).toFixed(1)} MB`}
function fileToDataUrl(file:File){return new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result||""));r.onerror=()=>reject(r.error);r.readAsDataURL(file)})}

export default function SupportNew(){
 const {t}=useLocale();const router=useRouter();const fileInput=useRef<HTMLInputElement>(null);const cameraInput=useRef<HTMLInputElement>(null);
 const [v,setV]=useState({category:"Frage",subject:"",description:"",priority:"Normal"});const [busy,setBusy]=useState(false);const [diagnostics,setDiagnostics]=useState<SupportDiagnostics|null>(null);const [screenshot,setScreenshot]=useState<string>("");const [captureBusy,setCaptureBusy]=useState(false);const [attachments,setAttachments]=useState<UploadedAttachment[]>([]);const [uploading,setUploading]=useState(false);
 async function capture(){setCaptureBusy(true);try{const img=await captureSupportScreenshot();setScreenshot(img);notify(t("Screenshot wurde angehängt."))}catch(e){notify(e instanceof Error?e.message:t("Screenshot konnte nicht erstellt werden."),"danger")}finally{setCaptureBusy(false)}}
 function attachDiagnostics(){setDiagnostics(collectSupportDiagnostics());notify(t("Technische Diagnose wurde angehängt."))}
 async function addFiles(files:FileList|null){if(!files?.length)return;const remaining=MAX_FILES-attachments.length;if(remaining<=0){notify(`${t("Maximal")} ${MAX_FILES} ${t("Anhänge pro Ticket.")}`,"danger");return}setUploading(true);try{const next:UploadedAttachment[]=[];for(const file of Array.from(files).slice(0,remaining)){if(isProductionMode()){const form=new FormData();form.append("file",file);const r=await apiFetch<{item:{id:string;fileName:string;mimeType:string;sizeBytes:number}}>("/api/support/attachments",{method:"POST",body:form});next.push({...r.item,uploadId:r.item.id})}else{if(file.size>MAX_LOCAL_SIZE){notify(`${file.name}: ${t("im lokalen Modus maximal 2 MB.")}`,"danger");continue}const dataUrl=await fileToDataUrl(file);next.push({id:`local-${Date.now()}-${next.length}`,fileName:file.name,mimeType:file.type||"application/octet-stream",sizeBytes:file.size,dataUrl})}}setAttachments(x=>[...x,...next]);if(next.length)notify(`${next.length} ${next.length===1?t("Anhang hinzugefügt."):t("Anhänge hinzugefügt.")}`)}catch(e){notify(e instanceof Error?e.message:t("Anhang konnte nicht hochgeladen werden."),"danger")}finally{setUploading(false);if(fileInput.current)fileInput.current.value="";if(cameraInput.current)cameraInput.current.value=""}}
 async function removeAttachment(item:UploadedAttachment){try{if(isProductionMode()&&item.uploadId)await apiFetch(`/api/support/attachments/${item.uploadId}`,{method:"DELETE"});setAttachments(x=>x.filter(y=>y.id!==item.id))}catch(e){notify(e instanceof Error?e.message:t("Anhang konnte nicht entfernt werden."),"danger")}}
 async function submit(e:React.FormEvent){e.preventDefault();if(!v.subject.trim()||!v.description.trim())return;setBusy(true);try{const payload={...v,diagnostics:diagnostics||undefined,screenshot:screenshot||undefined,attachmentIds:attachments.map(a=>a.uploadId).filter(Boolean),attachments:isProductionMode()?undefined:attachments};if(isProductionMode()){const r=await apiFetch<{item:{id:string}}>("/api/support",{method:"POST",body:JSON.stringify(payload)});router.push(`/support/${r.item.id}`)}else{const ticket=createSupportTicket(payload);router.push(`/support/${ticket.id}`)}notify(t("Supportticket erstellt."))}catch(e){notify(e instanceof Error?e.message:t("Ticket konnte nicht erstellt werden."),"danger")}finally{setBusy(false)}}
 const categories=["Frage","Fehler","Bedienung","Abrechnung","Sicherheit","Idee"];
 const priorities=["Niedrig","Normal","Hoch","Kritisch"];
 return <div className="page"><Link className="back-link" href="/support"><ArrowLeft size={17}/>{t("Zurück")}</Link><section className="module-heading"><div><div className="eyebrow">{t("Support")}</div><h1>{t("Ticket erstellen")}</h1><p>{t("Beschreibe das Anliegen kurz. Diagnose, Screenshot und Anhänge sind freiwillig.")}</p></div></section><form className="workspace-card support-form" onSubmit={submit}><div className="form-grid"><label><span>{t("Kategorie")}</span><select value={v.category} onChange={e=>setV({...v,category:e.target.value})}>{categories.map(x=><option key={x} value={x}>{t(x)}</option>)}</select></label><label><span>{t("Priorität")}</span><select value={v.priority} onChange={e=>setV({...v,priority:e.target.value})}>{priorities.map(x=><option key={x} value={x}>{t(x)}</option>)}</select></label><label className="full"><span>{t("Betreff")} *</span><input value={v.subject} onChange={e=>setV({...v,subject:e.target.value})} maxLength={180} required/></label><label className="full"><span>{t("Beschreibung")} *</span><textarea rows={8} value={v.description} onChange={e=>setV({...v,description:e.target.value})} required/></label></div>
 <section className="support-capture-card"><div><strong>{t("Hilfreiche Zusatzinformationen")}</strong><span>{t("Freiwillig. Technische Daten werden redigiert; Passwörter, Cookies und Tokens werden nicht mitgesendet.")}</span></div><div className="support-capture-actions"><button type="button" className="ui-button ui-button-secondary ui-button-md" onClick={attachDiagnostics}><FileClock size={16}/>{diagnostics?t("Diagnose aktualisieren"):t("Diagnose anhängen")}</button><button type="button" className="ui-button ui-button-secondary ui-button-md" onClick={capture} disabled={captureBusy}><Camera size={16}/>{captureBusy?t("Aufnahme läuft …"):screenshot?t("Screenshot ersetzen"):t("Screenshot aufnehmen")}</button><button type="button" className="ui-button ui-button-secondary ui-button-md" onClick={()=>fileInput.current?.click()} disabled={uploading||attachments.length>=MAX_FILES}><Paperclip size={16}/>{uploading?t("Wird hochgeladen …"):t("Datei anhängen")}</button><button type="button" className="ui-button ui-button-secondary ui-button-md support-camera-file" onClick={()=>cameraInput.current?.click()} disabled={uploading||attachments.length>=MAX_FILES}><Camera size={16}/>{t("Foto aufnehmen")}</button></div>
 <input ref={fileInput} className="visually-hidden" type="file" multiple accept="image/png,image/jpeg,image/webp,application/pdf,text/plain,text/csv" onChange={e=>void addFiles(e.target.files)}/><input ref={cameraInput} className="visually-hidden" type="file" accept="image/*" capture="environment" onChange={e=>void addFiles(e.target.files)}/>
 {diagnostics&&<div className="support-attachment-pill"><span>{t("Diagnose")} · {diagnostics.recentEvents.length} {t("technische Ereignisse")}</span><button type="button" onClick={()=>setDiagnostics(null)} aria-label={t("Diagnose entfernen")}><Trash2 size={14}/></button></div>}
 {attachments.length>0&&<div className="support-file-list">{attachments.map(a=><div key={a.id}><Upload size={15}/><span><strong>{a.fileName}</strong><small>{formatBytes(a.sizeBytes)}</small></span><button type="button" onClick={()=>void removeAttachment(a)} aria-label={`${a.fileName} ${t("entfernen")}`}><Trash2 size={14}/></button></div>)}</div>}
 {screenshot&&<div className="support-screenshot-preview"><Image src={screenshot} alt={t("Screenshot Vorschau")} width={720} height={420} unoptimized/><button type="button" className="ui-button ui-button-secondary ui-button-md" onClick={()=>setScreenshot("")}><Trash2 size={15}/>{t("Screenshot entfernen")}</button></div>}</section><button className="ui-button ui-button-primary ui-button-md" disabled={busy||uploading}><Send size={17}/>{busy?t("Wird erstellt …"):t("Ticket senden")}</button></form></div>
}
