import type {Metadata} from "next";
import Link from "next/link";
import {LegalPage} from "@/components/legal-page";
import {legalConfig} from "@/config/legal";

export const metadata:Metadata={title:"AGB – Binso One",description:"Allgemeine Geschäftsbedingungen für Binso One.",alternates:{canonical:"/agb"}};

export default function Page(){
 return <LegalPage eyebrow="VERTRAG" title="Allgemeine Geschäftsbedingungen" intro="Diese AGB regeln die Nutzung von Binso One durch Unternehmen und selbständig Erwerbstätige in der Schweiz.">
  <section><h2>1. Geltungsbereich und Vertragspartner</h2><p>Diese Allgemeinen Geschäftsbedingungen gelten für Verträge über Binso One zwischen der Binso GmbH, Weissbadstrasse 8b, 9050 Appenzell, Schweiz, und geschäftlichen Kunden. Binso One richtet sich an Unternehmen, Organisationen und selbständig Erwerbstätige und ist nicht als Verbraucherangebot bestimmt.</p></section>
  <section><h2>2. Leistungsumfang</h2><p>Binso One ist eine cloudbasierte Business-Software. Der konkrete Funktionsumfang richtet sich nach dem gewählten Plan und dem jeweils in der Anwendung ausgewiesenen Leistungsumfang. Binso kann Funktionen weiterentwickeln, sofern der vertragliche Hauptzweck dadurch nicht wesentlich beeinträchtigt wird.</p></section>
  <section><h2>3. Registrierung und Kontosicherheit</h2><p>Der Kunde muss richtige und aktuelle Angaben machen und Zugangsdaten vertraulich behandeln. Für Konten können E-Mail-Verifikation, Mehrfaktor-Authentifizierung oder vergleichbare Sicherheitsmassnahmen vorgeschrieben werden. Handlungen über ein ordnungsgemäss authentifiziertes Konto werden dem Kunden zugerechnet, soweit nicht ein Missbrauch erkennbar war.</p></section>
  <section><h2>4. Kostenlose Testphase</h2><p>Neue produktive Kundenkonten erhalten grundsätzlich eine 14-tägige kostenlose Testphase, sofern im Angebot nichts anderes ausgewiesen ist. Für die Testphase ist keine Kreditkarte erforderlich. Ohne ausdrückliche Aktivierung eines kostenpflichtigen Abonnements erfolgt keine automatische Belastung. Nach Ablauf kann das Konto bis zur Aktivierung eines Abonnements in einen Nur-Lesen-Modus wechseln.</p></section>
  <section><h2>5. Kostenpflichtiges Abonnement und Vertragsabschluss</h2><p>Ein kostenpflichtiges Abonnement kommt zustande, wenn der Kunde in Binso One einen Plan und Abrechnungszeitraum auswählt, die anwendbaren Vertragsbedingungen bestätigt und den Stripe-Checkout erfolgreich abschliesst. Die im Checkout angezeigten Angaben können vor Abschluss geprüft und korrigiert werden. Die Zahlungsbestätigung bzw. Abonnementaktivierung wird elektronisch bestätigt.</p></section>
  <section><h2>6. Preise, Steuern und Zahlungsabwicklung</h2><p>Es gelten die im Zeitpunkt des Vertragsabschlusses ausgewiesenen Preise in CHF. Die öffentlichen Preisangaben beziehen sich auf die geschäftliche Nutzung. Allfällige gesetzlich geschuldete Steuern werden vor dem kostenpflichtigen Abschluss transparent ausgewiesen. Die Zahlungsabwicklung erfolgt über Stripe. Binso One speichert keine vollständigen Kartendaten.</p></section>
  <section><h2>7. Laufzeit, Verlängerung und Kündigung</h2><p>Monatsabonnemente laufen monatlich, Jahresabonnemente jährlich. Sie verlängern sich jeweils um den gewählten Abrechnungszeitraum, sofern sie nicht vor dessen Ende gekündigt werden. Eine Kündigung kann über das bereitgestellte Billing-Portal erfolgen. Der Zugriff bleibt grundsätzlich bis zum Ende der bereits bezahlten Periode bestehen.</p></section>
  <section><h2>8. Zahlungsverzug und Einschränkung</h2><p>Bei fehlgeschlagenen oder überfälligen Zahlungen kann Binso nach angemessener Frist Schreibfunktionen einschränken, das Konto in einen Nur-Lesen-Modus versetzen oder den Zugang sperren. Gesetzliche Ansprüche bleiben vorbehalten.</p></section>
  <section><h2>9. Kundendaten und zulässige Nutzung</h2><p>Der Kunde behält seine Rechte an den von ihm eingestellten Daten. Er ist dafür verantwortlich, dass deren Erhebung und Bearbeitung rechtmässig ist und dass er die erforderlichen Rechte besitzt. Unzulässig sind insbesondere rechtswidrige Inhalte, missbräuchliche Nutzung, Sicherheitsangriffe sowie eine Nutzung, welche die Plattform oder Dritte gefährdet.</p></section>
  <section><h2>10. Datenschutz und Auftragsbearbeitung</h2><p>Die Bearbeitung von Personendaten richtet sich nach der <Link href="/datenschutz">Datenschutzerklärung</Link>. Soweit Binso Personendaten im Auftrag des Kunden bearbeitet, gilt ergänzend die <Link href="/auftragsbearbeitung">Vereinbarung zur Auftragsbearbeitung</Link>. Eingesetzte Unterauftragsbearbeiter sind unter <Link href="/unterauftragsbearbeiter">Unterauftragsbearbeiter</Link> aufgeführt.</p></section>
  <section><h2>11. Verfügbarkeit, Wartung und Änderungen</h2><p>Binso betreibt die Plattform mit angemessener Sorgfalt. Eine ununterbrochene Verfügbarkeit wird ohne separate SLA-Vereinbarung nicht garantiert. Wartung, Sicherheitsupdates und notwendige technische Änderungen können vorübergehende Einschränkungen verursachen.</p></section>
  <section><h2>12. Geistiges Eigentum</h2><p>Alle Rechte an Binso One, Software, Marken, Designs und Dokumentationen verbleiben bei Binso bzw. den jeweiligen Rechteinhabern. Der Kunde erhält für die Vertragsdauer ein nicht übertragbares Nutzungsrecht im vereinbarten Umfang.</p></section>
  <section><h2>13. Haftung</h2><p>Binso haftet uneingeschränkt, soweit zwingendes Recht dies vorsieht, insbesondere für absichtlich oder grobfahrlässig verursachte Schäden. Soweit gesetzlich zulässig, ist die Haftung für leichte Fahrlässigkeit sowie für indirekte Schäden, Folgeschäden und entgangenen Gewinn ausgeschlossen. Im Übrigen ist die Haftung, soweit zulässig, auf die vom Kunden in den letzten zwölf Monaten für Binso One bezahlten Entgelte beschränkt.</p></section>
  <section><h2>14. Vertragsende und Daten</h2><p>Nach Vertragsende kann der Kunde seine Daten im Rahmen der verfügbaren Exportfunktionen sichern. Binso darf nicht mehr benötigte Kundendaten nach einer angemessenen Übergangs- und Sicherungsfrist löschen, soweit keine gesetzlichen Aufbewahrungspflichten, laufenden Verfahren oder berechtigten Sicherheitsgründe entgegenstehen. Daten, die Binso selbst als Verantwortlicher aus gesetzlichen Gründen aufbewahren muss, bleiben für die erforderliche Dauer gespeichert.</p></section>
  <section><h2>15. Änderungen dieser AGB</h2><p>Binso kann diese AGB für die Zukunft anpassen. Wesentliche Änderungen werden bestehenden Kunden in angemessener Frist vor Inkrafttreten mitgeteilt. Soweit eine ausdrückliche Zustimmung erforderlich ist, wird diese eingeholt.</p></section>
  <section><h2>16. Anwendbares Recht und Gerichtsstand</h2><p>Es gilt schweizerisches Recht unter Ausschluss kollisionsrechtlicher Normen, soweit zulässig. Ausschliesslicher Gerichtsstand ist, soweit gesetzlich zulässig, der Sitz der Binso GmbH in Appenzell. Zwingende Gerichtsstände bleiben vorbehalten.</p></section>
  <p className="legal-version">Version {legalConfig.termsVersion} · Stand: {legalConfig.versionDate}</p>
 </LegalPage>;
}
