import {NextRequest} from "next/server";import {withTransaction} from "@/lib/server/db";import {verifyStripeSignature} from "@/lib/server/stripe";import {apiError,json} from "@/lib/server/http";import {log} from "@/lib/server/logger";
export const runtime="nodejs";
type StripeObject=Record<string,unknown>&{id?:string;customer?:string;subscription?:string;client_reference_id?:string;metadata?:Record<string,unknown>;status?:string;current_period_end?:number;cancel_at_period_end?:boolean};
function subscriptionStatus(value:string){if(value==="active"||value==="trialing")return value==="trialing"?"trial":"active";if(value==="past_due")return "past_due";if(value==="canceled")return "cancelled";return null}
export async function POST(request:NextRequest){try{const payload=await request.text();const signature=request.headers.get("stripe-signature")||"";if(!verifyStripeSignature(payload,signature))return new Response("Invalid signature",{status:400});const event=JSON.parse(payload) as {id:string;type:string;data:{object:StripeObject}};let duplicate=false;await withTransaction(async c=>{
 const inserted=await c.query(`insert into billing_webhook_events(provider,external_event_id,event_type,status,payload,attempts) values('stripe',$1,$2,'received',$3::jsonb,1) on conflict(provider,external_event_id) do update set attempts=billing_webhook_events.attempts+1 returning processed_at`,[event.id,event.type,payload]);if(inserted.rows[0]?.processed_at){duplicate=true;return}
 const o=event.data.object;let orgId=String(o.metadata?.organization_id||o.client_reference_id||"");const customer=o.customer?String(o.customer):null;const subscription=o.subscription?String(o.subscription):(event.type.startsWith("customer.subscription.")&&o.id?String(o.id):null);
 if(!orgId&&customer){const r=await c.query<{organization_id:string}>(`select organization_id from organization_subscriptions where billing_customer_id=$1 limit 1`,[customer]);orgId=r.rows[0]?.organization_id||""}
 if(!orgId&&subscription){const r=await c.query<{organization_id:string}>(`select organization_id from organization_subscriptions where billing_subscription_id=$1 limit 1`,[subscription]);orgId=r.rows[0]?.organization_id||""}
 if(orgId){
  if(event.type==="checkout.session.completed")await c.query(`update organization_subscriptions set status='active',billing_customer_id=coalesce($1,billing_customer_id),billing_subscription_id=coalesce($2,billing_subscription_id),updated_at=now() where organization_id=$3`,[customer,subscription,orgId]);
  if(event.type==="customer.subscription.created"||event.type==="customer.subscription.updated"){const st=subscriptionStatus(String(o.status||""));await c.query(`update organization_subscriptions set status=coalesce($1,status),billing_customer_id=coalesce($2,billing_customer_id),billing_subscription_id=coalesce($3,billing_subscription_id),current_period_end=case when $4::bigint>0 then to_timestamp($4) else current_period_end end,cancel_at_period_end=coalesce($5,cancel_at_period_end),updated_at=now() where organization_id=$6`,[st,customer,subscription,Number(o.current_period_end||0),typeof o.cancel_at_period_end==="boolean"?o.cancel_at_period_end:null,orgId])}
  if(event.type==="customer.subscription.deleted")await c.query(`update organization_subscriptions set status='cancelled',cancel_at_period_end=false,cancelled_at=now(),updated_at=now() where organization_id=$1`,[orgId]);
  if(event.type==="invoice.payment_failed")await c.query(`update organization_subscriptions set status='past_due',updated_at=now() where organization_id=$1`,[orgId]);
  if(event.type==="invoice.paid")await c.query(`update organization_subscriptions set status='active',updated_at=now() where organization_id=$1 and status<>'cancelled'`,[orgId]);
 }
 await c.query(`update billing_webhook_events set status='processed',processed_at=now(),error=null where provider='stripe' and external_event_id=$1`,[event.id]);log("info","stripe_webhook_processed",{eventId:event.id,eventType:event.type,organizationId:orgId||undefined});
 });return json({received:true,duplicate})}catch(e){log("error","stripe_webhook_failed",{message:e instanceof Error?e.message:"unknown"});return apiError(e,request)}}
