import {NextRequest} from "next/server";import {withTransaction} from "@/lib/server/db";import {verifyStripeSignature} from "@/lib/server/stripe";import {apiError,json} from "@/lib/server/http";import {log} from "@/lib/server/logger";
export const runtime="nodejs";
type StripeObject=Record<string,unknown>&{id?:string;customer?:string;subscription?:string;client_reference_id?:string;metadata?:Record<string,unknown>;status?:string;current_period_end?:number;cancel_at_period_end?:boolean};
export async function POST(request:NextRequest){try{const payload=await request.text();const signature=request.headers.get("stripe-signature")||"";if(!verifyStripeSignature(payload,signature))return new Response("Invalid signature",{status:400});const event=JSON.parse(payload) as {id:string;type:string;data:{object:StripeObject}};let duplicate=false;await withTransaction(async c=>{
 const inserted=await c.query(`insert into webhook_events(provider,event_id,event_type,payload,attempts) values('stripe',$1,$2,$3::jsonb,1) on conflict(provider,event_id) do update set attempts=webhook_events.attempts+1 returning processed_at`,[event.id,event.type,payload]);if(inserted.rows[0]?.processed_at){duplicate=true;return}
 const o=event.data.object;let orgId=String(o.metadata?.organization_id||o.client_reference_id||"");const customer=o.customer?String(o.customer):null;const subscription=o.subscription?String(o.subscription):(event.type.startsWith("customer.subscription.")&&o.id?String(o.id):null);
 if(!orgId&&customer){const r=await c.query<{id:string}>(`select id from organizations where stripe_customer_id=$1 limit 1`,[customer]);orgId=r.rows[0]?.id||""}
 if(!orgId&&subscription){const r=await c.query<{id:string}>(`select id from organizations where stripe_subscription_id=$1 limit 1`,[subscription]);orgId=r.rows[0]?.id||""}
 if(orgId){
  if(event.type==="checkout.session.completed")await c.query(`update organizations set subscription_status='active',stripe_customer_id=coalesce($1,stripe_customer_id),stripe_subscription_id=coalesce($2,stripe_subscription_id),updated_at=now() where id=$3`,[customer,subscription,orgId]);
  if(event.type==="customer.subscription.created"||event.type==="customer.subscription.updated")await c.query(`update organizations set subscription_status=case when $1 in ('active','trialing') then 'active' when $1='past_due' then 'past_due' else subscription_status end,stripe_customer_id=coalesce($2,stripe_customer_id),stripe_subscription_id=coalesce($3,stripe_subscription_id),subscription_current_period_end=case when $4::bigint>0 then to_timestamp($4) else subscription_current_period_end end,cancel_at_period_end=coalesce($5,cancel_at_period_end),updated_at=now() where id=$6`,[String(o.status||""),customer,subscription,Number(o.current_period_end||0),typeof o.cancel_at_period_end==="boolean"?o.cancel_at_period_end:null,orgId]);
  if(event.type==="customer.subscription.deleted")await c.query(`update organizations set subscription_status='cancelled',cancel_at_period_end=false,updated_at=now() where id=$1`,[orgId]);
  if(event.type==="invoice.payment_failed")await c.query(`update organizations set subscription_status='past_due',updated_at=now() where id=$1`,[orgId]);
  if(event.type==="invoice.paid")await c.query(`update organizations set subscription_status='active',updated_at=now() where id=$1 and subscription_status<>'cancelled'`,[orgId]);
 }
 await c.query(`update webhook_events set processed_at=now(),processing_error=null where provider='stripe' and event_id=$1`,[event.id]);log("info","stripe_webhook_processed",{eventId:event.id,eventType:event.type,organizationId:orgId||undefined});
 });return json({received:true,duplicate})}catch(e){log("error","stripe_webhook_failed",{message:e instanceof Error?e.message:"unknown"});return apiError(e,request)}}
