import {requireSession} from '@/lib/server/session';
import {authorize} from '@/lib/server/rbac';
import {tenantCan,ownRecordOnly} from '@/lib/permissions';
import {withTenant} from '@/lib/server/db';
import {apiError,json} from '@/lib/server/http';
export async function GET(_request:Request,{params}:{params:Promise<{id:string}>}){try{const s=await requireSession();authorize(s,'customers:read');const {id}=await params;
 const items=await withTenant(s.organizationId,s.userId,async c=>{
 const sources=[`select created_at at,'Kunde erstellt' title,name detail from customers where organization_id=$1 and id=$2 and archived_at is null`,`select created_at at,'Kontakt hinzugefügt' title,name detail from customer_contacts where organization_id=$1 and customer_id=$2 and archived_at is null`];
 if(tenantCan(s.role,'invoices:read'))sources.push(`select created_at at,'Rechnung erstellt' title,invoice_no detail from invoices where organization_id=$1 and customer_id=$2 and archived_at is null`);
 if(tenantCan(s.role,'sales:read')){sources.push(`select created_at at,'Angebot erstellt' title,quote_no detail from quotes where organization_id=$1 and customer_id=$2 and archived_at is null`);sources.push(`select decision_at at,case status when 'accepted' then 'Angebot angenommen' else 'Angebot abgelehnt' end title,quote_no detail from quotes where organization_id=$1 and customer_id=$2 and archived_at is null and decision_at is not null and status in ('accepted','declined')`);}
 if(tenantCan(s.role,'payments:read'))sources.push(`select p.payment_date::timestamptz at,'Zahlung erhalten' title,i.invoice_no||' · '||p.amount::text||' '||i.currency detail from payments p join invoices i on i.id=p.invoice_id and i.organization_id=p.organization_id where p.organization_id=$1 and i.customer_id=$2 and p.archived_at is null and p.allocation_status='matched'`);
 if(tenantCan(s.role,'projects:read'))sources.push(`select created_at at,'Projekt erstellt' title,name detail from projects where organization_id=$1 and customer_id=$2 and archived_at is null`);
 if(tenantCan(s.role,'time:read'))sources.push(`select t.work_date::timestamptz at,'Arbeitszeit erfasst' title,t.hours::text||' h · '||coalesce(p.name,t.project_label,'Arbeitszeit')||' · '||t.person_name detail from time_entries t left join projects p on p.id=t.project_id and p.organization_id=t.organization_id where t.organization_id=$1 and t.customer_id=$2 and t.archived_at is null ${ownRecordOnly(s.role,'zeiterfassung')?'and t.created_by_user_id=$3':''}`);
 for(const [kind,table,number,permission] of [['invoice','invoices','invoice_no','invoices:read'],['offer','quotes','quote_no','sales:read']] as const){if(tenantCan(s.role,permission))sources.push(`select x.completed_at at,'${kind==='invoice'?'Rechnung':'Angebot'} versendet' title,d.${number} detail from document_deliveries x join ${table} d on d.id=x.document_id and d.organization_id=x.organization_id where x.organization_id=$1 and d.customer_id=$2 and x.kind='${kind}' and x.status='sent' and x.completed_at is not null`);}
 const needsUser=sources.some(source=>source.includes('$3'));return (await c.query(`select * from (${sources.join(' union all ')}) events order by at desc,title,detail limit 100`,needsUser?[s.organizationId,id,s.userId]:[s.organizationId,id])).rows;});return json({items});}catch(e){return apiError(e)}}
