export type IntegrationStatus={key:"database"|"storage"|"billing"|"email"|"banking"|"swiss_qr";label:string;configured:boolean;status:"operational"|"degraded"|"configured"|"not_connected"|"not_implemented";detail:string};
export function getIntegrationStatus():IntegrationStatus[]{const database=Boolean(process.env.DATABASE_URL);const storage=Boolean(process.env.AZURE_STORAGE_ACCOUNT&&(process.env.AZURE_STORAGE_SAS||process.env.IDENTITY_ENDPOINT));const stripe=Boolean(process.env.STRIPE_SECRET_KEY&&process.env.STRIPE_WEBHOOK_SECRET&&(process.env.STRIPE_PRICE_STARTER||process.env.STRIPE_PRICE_START)&&process.env.STRIPE_PRICE_BUSINESS&&(process.env.STRIPE_PRICE_PROFESSIONAL||process.env.STRIPE_PRICE_PRO));const email=Boolean(process.env.GRAPH_TENANT_ID&&process.env.GRAPH_CLIENT_ID&&process.env.GRAPH_CLIENT_SECRET&&process.env.GRAPH_SENDER_USER_ID);return [
 {key:"database",label:"Datenbank",configured:database,status:database?"operational":"not_connected",detail:database?"Azure Database for PostgreSQL konfiguriert":"DATABASE_URL fehlt"},
 {key:"storage",label:"Dateispeicher",configured:storage,status:storage?"configured":"not_connected",detail:storage?"Azure Blob Storage konfiguriert":"Azure Blob Storage noch nicht konfiguriert"},
 {key:"billing",label:"Zahlungsabwicklung",configured:stripe,status:stripe?"configured":"not_connected",detail:stripe?"Stripe Checkout, Portal und Webhook konfiguriert":"Stripe-Konfiguration unvollständig"},
 {key:"email",label:"E-Mail Service",configured:email,status:email?"configured":"not_connected",detail:email?"Microsoft Graph konfiguriert":"Microsoft Graph nicht vollständig konfiguriert"},
 {key:"banking",label:"Bankanbindung",configured:false,status:"not_implemented",detail:"Noch kein Bankprovider verbunden"},
 {key:"swiss_qr",label:"Swiss QR",configured:false,status:"not_implemented",detail:"Normkonforme QR-Erzeugung noch nicht produktiv implementiert"}];}
async function providerReachable(url:string,authorization:string){const started=performance.now();try{const response=await fetch(url,{headers:{Authorization:authorization},cache:"no-store",signal:AbortSignal.timeout(4000)});return {ok:response.ok,latencyMs:Math.round(performance.now()-started)}}catch{return {ok:false,latencyMs:Math.round(performance.now()-started)}}}
async function graphHealth(){const started=performance.now();try{const body=new URLSearchParams({client_id:process.env.GRAPH_CLIENT_ID!,client_secret:process.env.GRAPH_CLIENT_SECRET!,scope:"https://graph.microsoft.com/.default",grant_type:"client_credentials"});const tokenResponse=await fetch(`https://login.microsoftonline.com/${encodeURIComponent(process.env.GRAPH_TENANT_ID!)}/oauth2/v2.0/token`,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body,cache:"no-store",signal:AbortSignal.timeout(4000)});if(!tokenResponse.ok)return {ok:false,latencyMs:Math.round(performance.now()-started)};const token=(await tokenResponse.json() as {access_token:string}).access_token;const r=await fetch(`https://graph.microsoft.com/v1.0/users/${encodeURIComponent(process.env.GRAPH_SENDER_USER_ID!)}?$select=id`,{headers:{Authorization:"Bearer "+token},cache:"no-store",signal:AbortSignal.timeout(4000)});return {ok:r.ok,latencyMs:Math.round(performance.now()-started)}}catch{return {ok:false,latencyMs:Math.round(performance.now()-started)}}}
export async function getOperationalIntegrationStatus(){const base=getIntegrationStatus();return Promise.all(base.map(async item=>{if(item.key==="billing"&&item.configured){const h=await providerReachable("https://api.stripe.com/v1/account","Bearer "+process.env.STRIPE_SECRET_KEY);return {...item,status:h.ok?"operational" as const:"degraded" as const,detail:h.ok?`Stripe erreichbar · ${h.latencyMs} ms`:"Stripe aktuell nicht erreichbar",latencyMs:h.latencyMs};}if(item.key==="email"&&item.configured){const h=await graphHealth();return {...item,status:h.ok?"operational" as const:"degraded" as const,detail:h.ok?`Microsoft Graph erreichbar · ${h.latencyMs} ms`:"Microsoft Graph aktuell nicht erreichbar",latencyMs:h.latencyMs};}return {...item,latencyMs:null};}));}
