import { NextRequest } from "next/server";
import { apiError, assertSameOrigin, cleanText, json, readJson } from "@/lib/server/http";
import { requireSession } from "@/lib/server/session";
import { authorize } from "@/lib/server/rbac";
import { withTenant } from "@/lib/server/db";

type Body=Record<string,unknown>;
const fields=`vat_rate,payment_terms_days,iban,qr_iban,invoice_intro_text,invoice_footer_text,quote_intro_text,quote_footer_text`;
export async function GET(){try{const s=await requireSession();authorize(s,"organization:read");const item=await withTenant(s.organizationId,s.userId,async c=>(await c.query(`select ${fields} from organizations where id=$1`,[s.organizationId])).rows[0]);return json({item})}catch(e){return apiError(e)}}
export async function PATCH(request:NextRequest){try{assertSameOrigin(request);const s=await requireSession();authorize(s,"organization:write");const b=await readJson<Body>(request,16384);const vatRate=Number(b.vatRate),terms=Number(b.paymentTermsDays);if(!Number.isFinite(vatRate)||vatRate<0||vatRate>100)return json({error:"vat_invalid",message:"Ungültiger MwSt.-Satz."},400);if(!Number.isInteger(terms)||terms<0||terms>365)return json({error:"terms_invalid",message:"Ungültiges Zahlungsziel."},400);const vals=[vatRate,terms,cleanText(b.iban,40).replace(/\s/g,"")||null,cleanText(b.qrIban,40).replace(/\s/g,"")||null,cleanText(b.invoiceIntroText,2000)||null,cleanText(b.invoiceFooterText,2000)||null,cleanText(b.quoteIntroText,2000)||null,cleanText(b.quoteFooterText,2000)||null,s.organizationId];const item=await withTenant(s.organizationId,s.userId,async c=>(await c.query(`update organizations set vat_rate=$1,payment_terms_days=$2,iban=$3,qr_iban=$4,invoice_intro_text=$5,invoice_footer_text=$6,quote_intro_text=$7,quote_footer_text=$8,updated_at=now() where id=$9 returning ${fields}`,vals)).rows[0]);return json({item})}catch(e){return apiError(e)}}