export const ROUTES = {
  public: {
    home: '/',
    features: '/features',
    howItWorks: '/how-it-works',
    pricing: '/pricing',
    faq: '/faq',
    security: '/security',
    contact: '/contact',
    status: '/status',
    privacy: '/legal/privacy',
    terms: '/legal/terms',
    cookies: '/legal/cookies',
    imprint: '/legal/imprint',
  },
  auth: {
    signIn: '/sign-in',
    register: '/register',
    postLogin: '/post-login',
    onboarding: '/onboarding',
    adminAccess: '/admin-access',
  },
  app: {
    dashboard: '/dashboard',
    customers: '/customers',
    quotes: '/quotes',
    orders: '/orders',
    time: '/time',
    invoices: '/invoices',
    contracts: '/contracts',
    finance: '/finance',
    accounting: '/accounting',
    employees: '/employees',
    data: '/data',
    organization: '/organization',
    account: '/account',
    settings: '/settings',
    platform: '/platform',
  },
  platform: {
    home: '/platform',
    customers: '/platform/customers',
    subscriptions: '/platform/subscriptions',
    registrations: '/platform/registrations',
    leads: '/platform/leads',
    pilot: '/platform/pilot',
    support: '/platform/support',
    help: '/platform/help',
    analytics: '/platform/analytics',
    operations: '/platform/operations',
    incidents: '/platform/incidents',
    releases: '/platform/releases',
    dataLifecycle: '/platform/data-lifecycle',
    audit: '/platform/audit',
    operators: '/platform/operators',
    settings: '/platform/settings',
  },
} as const
