import { NextRequest } from "next/server";
import { requireSession } from "@/lib/server/session";
import { authorize } from "@/lib/server/rbac";
import { query } from "@/lib/server/db";
import { apiError,assertSameOrigin,json,readJson } from "@/lib/server/http";
import { asObject } from "@/lib/server/validation";
import type { TenantRole } from "@/lib/permissions";
export const runtime="nodejs";
export async function PATCH(request:NextRequest,{params}:{params:Promise<{id:string}>}){try{assertSameOrigin(request);const s=await requireSession();authorize(s,"users:manage");const {id}=await params;const body=asObject(await readJson(request,32_000));const target=(await query<{role:string}>(`select role from users where id=$1 and organization_id=$2`,[id,s.organizationId])).rows[0];if(!target)return json({error:"Nicht gefunden."},404);if(target.role==="owner"&&s.role!=="owner")return json({error:"Nur der Inhaber darf den Inhaber ändern."},403);const allowed=new Set<TenantRole>(["owner","admin","finance","hr","project_manager","member","reader"]);if(typeof body.role==="string"&&!allowed.has(body.role as TenantRole))return json({error:"Ungültige Rolle."},400);const requestedRole=(typeof body.role==="string"?body.role:target.role) as TenantRole;if(requestedRole==="owner"&&s.role!=="owner")return json({error:"Nur der Inhaber darf die Inhaberrolle vergeben."},403);if(id===s.userId&&body.active===false)return json({error:"Das eigene Konto kann nicht deaktiviert werden."},409);if(target.role==="owner"&&body.active===false){const owners=await query(`select count(*)::int count from users where organization_id=$1 and role='owner' and active=true`,[s.organizationId]);if(Number(owners.rows[0]?.count||0)<=1)return json({error:"Der letzte aktive Inhaber kann nicht deaktiviert werden."},409)}const r=await query(`update users set name=coalesce($1,name),role=$2,language=coalesce($3,language),active=coalesce($4,active),updated_at=now() where id=$5 and organization_id=$6 returning id,name,email,role,language,active`,[typeof body.name==="string"?body.name:null,requestedRole,typeof body.language==="string"?body.language:null,typeof body.active==="boolean"?body.active:null,id,s.organizationId]);return json({item:r.rows[0]})}catch(e){return apiError(e,request)}}
