import {createHash,randomUUID} from "node:crypto";
import {limitsConfig,megabytes} from "@/config/limits";
import {NextRequest} from "next/server";
import {requireSession} from "@/lib/server/session";
import {authorize} from "@/lib/server/rbac";
import {putBlob} from "@/lib/server/storage";
import {withTenant} from "@/lib/server/db";
import {apiError,assertSameOrigin,json} from "@/lib/server/http";
export const runtime="nodejs";
const allowed=new Set(["application/pdf","image/png","image/jpeg","image/webp","text/plain","text/csv"]);
export async function GET(){try{const s=await requireSession();authorize(s,"documents:read");const items=await withTenant(s.organizationId,s.userId,async c=>(await c.query(`select id,purpose,original_name as "fileName",content_type as "mimeType",size_bytes as "sizeBytes",blob_url as "storagePath",scan_status as "scanStatus",created_at as "createdAt" from file_objects where organization_id=$1 order by created_at desc limit 500`,[s.organizationId])).rows);return json({items})}catch(e){return apiError(e)}}
export async function POST(request:NextRequest){try{assertSameOrigin(request);const s=await requireSession();authorize(s,"documents:write");const form=await request.formData();const file=form.get("file");const purpose=String(form.get("purpose")||"document").slice(0,80);if(!(file instanceof File))return json({error:"Datei fehlt."},400);if(file.size>limitsConfig.maxFileUploadBytes)return json({error:`Datei ist grösser als ${megabytes(limitsConfig.maxFileUploadBytes)} MB.`},413);if(!allowed.has(file.type))return json({error:"Dateityp ist nicht erlaubt."},400);const id=randomUUID();const ext=(file.name.split(".").pop()||"bin").replace(/[^a-zA-Z0-9]/g,"").slice(0,8);const objectKey=`${s.organizationId}/files/${id}.${ext}`;const buffer=Buffer.from(await file.arrayBuffer());const url=await putBlob({path:objectKey,contentType:file.type,body:buffer});if(!url)return json({error:"Azure Blob Storage ist nicht konfiguriert."},503);const sha256=createHash("sha256").update(buffer).digest("hex");const item=await withTenant(s.organizationId,s.userId,async c=>(await c.query(`insert into file_objects(id,organization_id,object_key,original_name,content_type,size_bytes,sha256,scan_status,created_by,blob_url,purpose) values($1,$2,$3,$4,$5,$6,$7,'clean',$8,$9,$10) returning id,purpose,original_name as "fileName",content_type as "mimeType",size_bytes as "sizeBytes",blob_url as "storagePath",scan_status as "scanStatus",created_at as "createdAt"`,[id,s.organizationId,objectKey,file.name.slice(0,240),file.type,file.size,sha256,s.userId,url,purpose])).rows[0]);return json({item},201)}catch(e){return apiError(e)}}
