import "server-only";
import {randomUUID} from "node:crypto";
import {withTenant} from "@/lib/server/db";
import {audit} from "@/lib/server/audit";

export type CustomerInput={name:string;contact?:string;email?:string;phone?:string;address?:string;zipCity?:string;uid?:string;language?:string;paymentDays?:number;discount?:number;status?:string};
const statusToDb=(value?:string)=>value&&/inaktiv/i.test(value)?"inactive":"active";
export async function listCustomers(organizationId:string,userId:string){return withTenant(organizationId,userId,async client=>{const result=await client.query(`select id,name,contact_name as contact,email,phone,address,trim(concat_ws(' ',zip,city)) as "zipCity",uid,language,payment_days as "paymentDays",discount,status,created_at as "createdAt",updated_at as "updatedAt" from customers where organization_id=$1 and archived_at is null order by lower(name) asc limit 500`,[organizationId]);return result.rows})}
export async function createCustomer(organizationId:string,userId:string,input:CustomerInput){return withTenant(organizationId,userId,async client=>{const id=randomUUID();const parts=(input.zipCity||"").trim().split(/\s+/,2);const zip=/^\d{4,5}$/.test(parts[0]||"")?parts[0]:null;const city=zip?(input.zipCity||"").trim().slice((zip||"").length).trim():input.zipCity||null;const customerNo=`K-${Date.now().toString().slice(-6)}`;const result=await client.query(`insert into customers(id,organization_id,external_id,customer_no,name,legal_name,contact_name,email,phone,address,zip,city,country,uid,language,payment_days,discount,status,created_by_user_id) values($1,$2,$1::text,$3,$4,$4,$5,$6,$7,$8,$9,$10,'Schweiz',$11,$12,$13,$14,$15,$16) returning id,name,contact_name as contact,email,phone,address,trim(concat_ws(' ',zip,city)) as "zipCity",uid,language,payment_days as "paymentDays",discount,status`,[id,organizationId,customerNo,input.name,input.contact||null,input.email||null,input.phone||null,input.address||null,zip,city,input.uid||null,input.language||"de",input.paymentDays??30,input.discount??0,statusToDb(input.status),userId]);await audit(client,{organizationId,userId,action:"customer.created",entityType:"customer",entityId:id});return result.rows[0]})}
export async function updateCustomer(organizationId:string,userId:string,id:string,input:Partial<CustomerInput>){return withTenant(organizationId,userId,async client=>{const current=(await client.query(`select * from customers where id=$1 and organization_id=$2 and archived_at is null`,[id,organizationId])).rows[0];if(!current)return null;const result=await client.query(`update customers set name=$1,legal_name=$1,contact_name=$2,email=$3,phone=$4,address=$5,uid=$6,language=$7,payment_days=$8,discount=$9,status=$10,updated_at=now() where id=$11 and organization_id=$12 returning id,name,contact_name as contact,email,phone,address,uid,language,payment_days as "paymentDays",discount,status`,[input.name??current.name,input.contact??current.contact_name,input.email??current.email,input.phone??current.phone,input.address??current.address,input.uid??current.uid,input.language??current.language,input.paymentDays??current.payment_days,input.discount??current.discount,input.status?statusToDb(input.status):current.status,id,organizationId]);await audit(client,{organizationId,userId,action:"customer.updated",entityType:"customer",entityId:id});return result.rows[0]})}
export async function deleteCustomer(organizationId:string,userId:string,id:string){return withTenant(organizationId,userId,async client=>{const result=await client.query(`update customers set archived_at=now(),updated_at=now() where id=$1 and organization_id=$2 and archived_at is null returning id`,[id,organizationId]);if(result.rowCount)await audit(client,{organizationId,userId,action:"customer.archived",entityType:"customer",entityId:id});return Boolean(result.rowCount)})}
