import "server-only";
import {ApiError} from "@/lib/server/http";
import {randomUUID} from "node:crypto";
import type {PoolClient} from "pg";
import {withTenant} from "@/lib/server/db";
import {audit} from "@/lib/server/audit";
import {domainConfig} from "@/config/domain";

export type RecordInput={module:string;status:string;row:string[];fields:Record<string,string>;positions?:unknown[];metadata?:Record<string,unknown>};
export type RecordDto={id:string;module:string;status:string;row:string[];fields:Record<string,string>;positions?:unknown[];metadata:Record<string,unknown>;createdBy?:string|null;createdAt?:Date|string;updatedAt?:Date|string};

type Obj=Record<string,unknown>;
const moduleTables:Record<string,string>={
 kunden:"customers",offerten:"quotes",auftraege:"orders",projekte:"projects",zeiterfassung:"time_entries",spesen:"expenses",rechnungen:"invoices",zahlungen:"payments",mwst:"vat_periods",personal:"employees",lohn:"payroll_runs",lieferanten:"suppliers",eingangsrechnungen:"supplier_invoices",produkte:"products_services",buchhaltung:"accounting_entries",bank:"bank_transactions",aufgaben:"tasks",abwesenheiten:"absences",dokumente:"business_documents",vertraege:"contracts"
};
const money=(value:unknown)=>new Intl.NumberFormat("de-CH",{style:"currency",currency:"CHF"}).format(Number(value)||0);
const text=(value:unknown)=>typeof value==="string"?value:"";
const num=(value:unknown)=>{if(typeof value==="number")return Number.isFinite(value)?value:0;const normalized=text(value).replace(/[^0-9,.-]/g,"").replace(/[’']/g,"").replace(",",".");return Number(normalized)||0};
const yes=(value:unknown)=>["ja","true","1"].includes(text(value).trim().toLowerCase());
const iso=(value:unknown)=>value instanceof Date?value.toISOString().slice(0,10):text(value).slice(0,10);
const relations=(input:Partial<RecordInput>)=>{const m=input.metadata;const r=m&&typeof m.relations==="object"&&m.relations&&!Array.isArray(m.relations)?m.relations as Record<string,unknown>:{};return Object.fromEntries(Object.entries(r).map(([k,v])=>[k,text(v)])) as Record<string,string>};
const ext=()=>randomUUID();

async function pk(client:PoolClient,table:string,organizationId:string,externalId?:string|null){
 if(!externalId)return null;
 const allowed=new Set(Object.values(moduleTables));if(!allowed.has(table))throw new Error("invalid_relation_table");
 const r=await client.query<{id:string}>(`select id::text from ${table} where organization_id=$1 and external_id=$2 and archived_at is null limit 1`,[organizationId,externalId]);
 return r.rows[0]?.id||null;
}
async function external(client:PoolClient,table:string,organizationId:string,id?:string|null){if(!id)return "";const allowed=new Set(Object.values(moduleTables));if(!allowed.has(table))return "";const r=await client.query<{external_id:string}>(`select external_id from ${table} where organization_id=$1 and id=$2 limit 1`,[organizationId,id]);return r.rows[0]?.external_id||""}

function statusDb(moduleKey:string,value:string){const v=value.trim().toLowerCase();switch(moduleKey){
 case"kunden":case"lieferanten":case"produkte":return /inaktiv/.test(v)?"inactive":"active";
 case"projekte":return /abgeschlossen/.test(v)?"completed":/blockiert/.test(v)?"blocked":/storniert/.test(v)?"cancelled":/geplant/.test(v)?"planned":/laufend/.test(v)?"active":"in_progress";
 case"auftraege":return /abgeschlossen/.test(v)?"completed":/storniert/.test(v)?"completed":/bereit/.test(v)?"paused":"active";
 case"offerten":return /angenommen/.test(v)?"accepted":/abgelehnt/.test(v)?"declined":/abgelaufen/.test(v)?"expired":/entwurf/.test(v)?"draft":"sent";
 case"rechnungen":return /teil/.test(v)?"partial":/bezahlt/.test(v)?"paid":/überfällig/.test(v)?"overdue":/storniert/.test(v)?"cancelled":/entwurf/.test(v)?"draft":"sent";
 case"eingangsrechnungen":return /bezahlt/.test(v)?"paid":/freigegeben/.test(v)?"open":/überfällig/.test(v)?"review":"open";
 case"spesen":return /freigegeben/.test(v)?"approved":/verbucht/.test(v)?"posted":/abgelehnt/.test(v)?"rejected":"open";
 case"eingangsrechnungen":return /bezahlt/.test(v)?"paid":/überfällig/.test(v)?"review":/freigegeben|freigabe/.test(v)?"review":"open";
 case"aufgaben":return /erledigt/.test(v)?"done":/arbeit/.test(v)?"in_progress":"open";
 case"abwesenheiten":return /genehmigt/.test(v)?"approved":/abgelehnt/.test(v)?"rejected":"open";
 case"buchhaltung":return /verbucht/.test(v)?"posted":"draft";
 case"bank":return /zugeordnet/.test(v)?"matched":/verbucht/.test(v)?"booked":"open";
 case"mwst":return /abgeschlossen/.test(v)?"closed":/eingereicht/.test(v)?"filed":/vorbereitung/.test(v)?"prepared":"draft";
 case"lohn":return /bezahlt|ausgezahlt/.test(v)?"paid":/freigegeben|bereit/.test(v)?"approved":"draft";
 case"dokumente":return /archiviert/.test(v)?"archived":"current";
 case"vertraege":return /gekündigt|storniert/.test(v)?"cancelled":/abgelaufen/.test(v)?"ended":/entwurf/.test(v)?"draft":"active";
 default:return value;
 }}
function statusUi(moduleKey:string,value:string){switch(moduleKey){
 case"kunden":case"lieferanten":case"produkte":return value==="inactive"?"Inaktiv":"Aktiv";
 case"projekte":return ({planned:"Geplant",in_progress:"In Arbeit",active:"Laufend",blocked:"Blockiert",completed:"Abgeschlossen",cancelled:"Storniert"} as Record<string,string>)[value]||value;
 case"auftraege":return ({paused:"Bereit",active:"In Arbeit",completed:"Abgeschlossen"} as Record<string,string>)[value]||value;
 case"offerten":return ({draft:"Entwurf",sent:"Offen",accepted:"Angenommen",declined:"Abgelehnt",expired:"Abgelaufen",revised:"Überarbeitet"} as Record<string,string>)[value]||value;
 case"rechnungen":return ({draft:"Entwurf",sent:"Offen",partial:"Teilbezahlt",paid:"Bezahlt",overdue:"Überfällig",cancelled:"Storniert"} as Record<string,string>)[value]||value;
 case"spesen":return ({open:"Offen",approved:"Freigegeben",posted:"Verbucht",rejected:"Abgelehnt"} as Record<string,string>)[value]||value;
 case"eingangsrechnungen":return ({open:"Offen",review:"Zur Freigabe",paid:"Bezahlt"} as Record<string,string>)[value]||value;
 case"bank":return ({open:"Offen",matched:"Zugeordnet",booked:"Verbucht",ignored:"Ignoriert"} as Record<string,string>)[value]||value;
 case"mwst":return ({draft:"Entwurf",prepared:"In Vorbereitung",filed:"Eingereicht",paid:"Bezahlt",closed:"Abgeschlossen"} as Record<string,string>)[value]||value;
 case"lohn":return ({draft:"Entwurf",review:"Zur Prüfung",approved:"Bereit",paid:"Bezahlt",cancelled:"Storniert"} as Record<string,string>)[value]||value;
 case"aufgaben":return ({open:"Offen",in_progress:"In Arbeit",done:"Erledigt",cancelled:"Storniert"} as Record<string,string>)[value]||value;
 case"abwesenheiten":return ({open:"Offen",approved:"Genehmigt",rejected:"Abgelehnt",cancelled:"Storniert"} as Record<string,string>)[value]||value;
 case"buchhaltung":return value==="posted"?"Verbucht":"Entwurf";
 case"dokumente":return value==="archived"?"Archiviert":"Aktuell";
 case"vertraege":return ({draft:"Entwurf",active:"Aktiv",paused:"Pausiert",ended:"Abgelaufen",cancelled:"Gekündigt"} as Record<string,string>)[value]||value;
 default:return value;
 }}

async function lines(client:PoolClient,moduleKey:string,organizationId:string,parentId:string){
 const def=moduleKey==="offerten"?{table:"quote_lines",fk:"quote_id"}:moduleKey==="rechnungen"?{table:"invoice_lines",fk:"invoice_id"}:moduleKey==="vertraege"?{table:"contract_lines",fk:"contract_id"}:null;if(!def)return undefined;
 const r=await client.query(`select description,quantity::float8 as quantity,unit_price::float8 as "unitPrice",vat_rate::float8 as "vatRate" from ${def.table} where organization_id=$1 and ${def.fk}=$2 order by sort_order,id`,[organizationId,parentId]);return r.rows;
}
async function notes(client:PoolClient,organizationId:string,moduleKey:string,externalId:string){const r=await client.query<{note_text:string}>(`select note_text from entity_notes where organization_id=$1 and entity_type=$2 and entity_external_id=$3 order by created_at desc`,[organizationId,moduleKey,externalId]);return r.rows.map(x=>x.note_text)}
async function syncNotes(client:PoolClient,organizationId:string,userId:string,moduleKey:string,externalId:string,metadata?:Record<string,unknown>){if(!metadata||!Array.isArray(metadata.notes))return;const list=metadata.notes.filter((x):x is string=>typeof x==="string"&&x.trim().length>0);await client.query(`delete from entity_notes where organization_id=$1 and entity_type=$2 and entity_external_id=$3`,[organizationId,moduleKey,externalId]);for(const n of [...list].reverse())await client.query(`insert into entity_notes(organization_id,entity_type,entity_external_id,note_text,created_by_user_id) values($1,$2,$3,$4,$5)`,[organizationId,moduleKey,externalId,n,userId])}

async function rowToDto(client:PoolClient,moduleKey:string,organizationId:string,r:Obj):Promise<RecordDto>{
 const id=text(r.external_id);let status=statusUi(moduleKey,text(r.status));let row:string[]=[];let fields:Record<string,string>={};let metadata:Record<string,unknown>={relations:{}};let positions:unknown[]|undefined;
 switch(moduleKey){
  case"kunden":fields={"Firmenname":text(r.name),"Kontaktperson":text(r.contact_name),"E-Mail":text(r.email),"Telefon":text(r.phone),"Strasse und Nr.":text(r.address),"PLZ / Ort":[text(r.zip),text(r.city)].filter(Boolean).join(" "),"UID":text(r.uid),"Sprache":text(r.language)||"de","Zahlungsfrist":String(r.payment_days??30),"Rabatt %":String(r.discount??0),"Notiz":text(r.notes),Status:status};row=[fields["Firmenname"],fields["Kontaktperson"],fields["E-Mail"],money(r.revenue??0),status];break;
  case"projekte":metadata={relations:{customerId:await external(client,"customers",organizationId,text(r.customer_id)),managerId:await external(client,"employees",organizationId,text(r.manager_employee_id))}};fields={Projektname:text(r.name),Kunde:text(r.customer_name),Projektleitung:text(r.manager_name),"Team / Ressourcen":text(r.team_text),Budget:String(r.budget??0),Stundenbudget:String(r.hours_budget??0),"Fortschritt %":String(r.progress??0),Start:iso(r.start_date),Ende:iso(r.end_date),Status:status,Projektbeschreibung:text(r.notes)};row=[fields.Projektname,fields.Kunde,`${fields["Fortschritt %"]} %`,money(r.budget),status];break;
  case"produkte":fields={Bezeichnung:text(r.name),Typ:text(r.item_type)==="product"?"Artikel":"Leistung",Einheit:text(r.unit),"Preis CHF":String(r.unit_price??0),"MWST %":String(r.vat_rate??domainConfig.defaultVatRate),Status:status};row=[fields.Bezeichnung,fields.Typ,fields.Einheit,money(r.unit_price),status];break;
  case"auftraege":metadata={relations:{customerId:await external(client,"customers",organizationId,text(r.customer_id)),projectId:await external(client,"projects",organizationId,text(r.project_id))}};fields={Auftragsbezeichnung:text(r.name),Kunde:text(r.customer_name),Projekt:text(r.project_name),Auftragsvolumen:String(r.amount??0),Start:iso(r.start_date),"Geplantes Ende":iso(r.end_date),Status:status,Notiz:text(r.notes)};row=[fields.Auftragsbezeichnung,fields.Kunde,fields.Projekt||"–",money(r.amount),status];break;
  case"zeiterfassung":metadata={relations:{employeeId:await external(client,"employees",organizationId,text(r.employee_id)),projectId:await external(client,"projects",organizationId,text(r.project_id)),productId:await external(client,"products_services",organizationId,text(r.product_service_id))},invoicedBy:await external(client,"invoices",organizationId,text(r.invoiced_invoice_id))||undefined};fields={Datum:iso(r.work_date),Mitarbeiter:text(r.person_name),Projekt:text(r.project_name),Leistung:text(r.service_name)||text(r.description),Von:text(r.start_time).slice(0,5),Bis:text(r.end_time).slice(0,5),"Pause Minuten":String(r.break_minutes??0),"Dauer in Stunden":String(r.hours??0),Verrechenbar:r.billable?"Ja":"Nein",Status:r.approved?"Freigegeben":"Entwurf",Notiz:text(r.description)};row=[fields.Datum,fields.Projekt,fields.Leistung,`${fields["Dauer in Stunden"]} h`,fields.Status];status=fields.Status;break;
  case"spesen":metadata={relations:{employeeId:await external(client,"employees",organizationId,text(r.employee_id)),projectId:await external(client,"projects",organizationId,text(r.project_id))},invoicedBy:await external(client,"invoices",organizationId,text(r.invoiced_invoice_id))||undefined};fields={Datum:iso(r.expense_date),Mitarbeiter:text(r.employee_name),Beschreibung:text(r.description),Projekt:text(r.project_name),"Betrag CHF":String((Number(r.quantity)||1)*(Number(r.unit_price)||0)),Kategorie:text(r.category),Weiterverrechenbar:r.billable?"Ja":"Nein",Status:status};row=[fields.Datum,fields.Beschreibung,fields.Projekt||"–",money(fields["Betrag CHF"]),status];break;
  case"lieferanten":fields={Firmenname:text(r.name),Kontaktperson:text(r.contact_name),"E-Mail":text(r.email),Telefon:text(r.phone),Adresse:text(r.address),IBAN:text(r.iban),Zahlungsfrist:String(r.payment_days??30),Status:status};row=[fields.Firmenname,fields.Kontaktperson||"–",fields["E-Mail"]||"–",money(r.open_amount??0),status];break;
  case"eingangsrechnungen":metadata={relations:{supplierId:await external(client,"suppliers",organizationId,text(r.supplier_id)),orderId:await external(client,"orders",organizationId,text(r.order_id))}};fields={Rechnungsnummer:text(r.supplier_invoice_no),Lieferant:text(r.supplier_name),Datum:iso(r.invoice_date),Fällig:iso(r.due_date),"Betrag CHF":String(r.total_amount??0),Aufwandskonto:text(r.expense_account),Status:status};row=[fields.Rechnungsnummer,fields.Lieferant,fields.Fällig||fields.Datum,money(r.total_amount),status];break;
  case"personal":fields={Name:text(r.name),Funktion:text(r.title)||text(r.role),"E-Mail":text(r.email),Telefon:text(r.phone),Adresse:text(r.address),"AHV-Nr.":text(r.ahv_number),IBAN:text(r.iban),"Pensum %":String(r.workload_percent??100),Wochenstunden:String(r.weekly_hours??42),"Ferientage / Jahr":String(r.vacation_days??25),Eintritt:iso(r.start_date),"Monatslohn brutto CHF":String(r.monthly_gross??0),"Kinderzulage CHF":String(r.child_allowance??0),"Quellensteuer %":String(r.withholding_tax_rate??0),"BVG Abzug CHF":String(r.bvg_deduction??0),Status:r.active?"Aktiv":"Inaktiv"};status=fields.Status;row=[fields.Name,fields.Funktion,`${fields["Pensum %"]}%`,fields.Eintritt,status];break;
  case"aufgaben":metadata={relations:{customerId:await external(client,"customers",organizationId,text(r.customer_id)),projectId:await external(client,"projects",organizationId,text(r.project_id)),invoiceId:await external(client,"invoices",organizationId,text(r.invoice_id)),employeeId:await external(client,"employees",organizationId,text(r.assignee_employee_id))}};fields={Aufgabe:text(r.title),Kunde:text(r.customer_name),Projekt:text(r.project_name),Rechnung:text(r.invoice_no),Fällig:iso(r.due_date),Verantwortlich:text(r.assignee_name),Priorität:text(r.priority)==="critical"?"Kritisch":text(r.priority)==="high"?"Hoch":"Normal",Status:status};row=[fields.Aufgabe,fields.Projekt||fields.Kunde||fields.Rechnung||"Intern",fields.Fällig||"–",fields.Verantwortlich||"–",status];break;
  case"abwesenheiten":metadata={relations:{employeeId:await external(client,"employees",organizationId,text(r.employee_id))}};fields={Mitarbeiter:text(r.employee_name),Art:({vacation:"Ferien",sick:"Krankheit",unpaid:"Unbezahlt",military_civil:"Militär/Zivildienst",other:"Andere"} as Record<string,string>)[text(r.absence_type)]||text(r.absence_type),Von:iso(r.start_date),Bis:iso(r.end_date),Tage:String(r.days??0),Status:status};row=[fields.Mitarbeiter,fields.Art,`${fields.Von}–${fields.Bis}`,fields.Tage,status];break;
  case"buchhaltung":fields={Datum:iso(r.entry_date),Beleg:text(r.document_ref),Konto:text(r.account_no),Gegenkonto:text(r.contra_account_no),"Betrag CHF":String(r.amount??0),Status:status};row=[fields.Datum,fields.Beleg,fields.Konto,money(r.amount),status];break;
  case"bank":metadata={relations:{invoiceId:await external(client,"invoices",organizationId,text(r.invoice_id))}};fields={Datum:iso(r.booking_date),Konto:text(r.account_label),Text:text(r.description),"Betrag CHF":String(r.amount??0),Status:status};row=[fields.Datum,fields.Konto,fields.Text,money(r.amount),status];break;
  case"mwst":fields={Periode:text(r.period),Umsatzsteuer:String(r.output_vat??0),Vorsteuer:String(r.input_vat??0),Zahllast:String(r.payable??0),Status:status};row=[fields.Periode,money(r.output_vat),money(r.input_vat),money(r.payable),status];break;
  case"lohn":metadata={relations:{employeeId:await external(client,"employees",organizationId,text(r.employee_id))}};fields={Mitarbeiter:text(r.employee_name),Brutto:String(r.gross_amount??0),Abzüge:String(r.deduction_amount??0),Netto:String(r.net_amount??0),Periode:text(r.period),Status:status};row=[fields.Mitarbeiter,money(r.gross_amount),money(r.deduction_amount),money(r.net_amount),status];break;
  case"dokumente":metadata={relations:{customerId:await external(client,"customers",organizationId,text(r.customer_id)),projectId:await external(client,"projects",organizationId,text(r.project_id)),employeeId:await external(client,"employees",organizationId,text(r.employee_id)),supplierId:await external(client,"suppliers",organizationId,text(r.supplier_id))}};fields={Dokumentname:text(r.name),Typ:text(r.document_type),Kunde:text(r.customer_name),Projekt:text(r.project_name),Mitarbeiter:text(r.employee_name),Lieferant:text(r.supplier_name),Aktualisiert:iso(r.document_date),Status:status};row=[fields.Dokumentname,fields.Typ,fields.Projekt||fields.Kunde||fields.Mitarbeiter||fields.Lieferant||"Firma",fields.Aktualisiert,status];break;
  case"vertraege":metadata={relations:{customerId:await external(client,"customers",organizationId,text(r.customer_id)),supplierId:await external(client,"suppliers",organizationId,text(r.supplier_id))},recurring:text(r.billing_interval)!=="none"};fields={Vertrag:text(r.name),Kunde:text(r.customer_name),Lieferant:text(r.supplier_name),Start:iso(r.start_date),Ende:iso(r.end_date),"Wert CHF":String(r.contract_value??0),Intervall:text(r.billing_interval)==="monthly"?"Monatlich":text(r.billing_interval)==="yearly"?"Jährlich":"Einmalig","Rechnung automatisch vorbereiten":text(r.billing_interval)!=="none"?"Ja":"Nein",Status:status};row=[fields.Vertrag,fields.Kunde||fields.Lieferant||"–",fields.Ende?`${fields.Start}–${fields.Ende}`:fields.Intervall,money(r.contract_value),status];positions=await lines(client,moduleKey,organizationId,text(r.id));break;
  case"offerten":metadata={relations:{customerId:await external(client,"customers",organizationId,text(r.customer_id)),projectId:await external(client,"projects",organizationId,text(r.project_id))},net:Number(r.net_amount??0),vat:Number(r.vat_amount??0),gross:Number(r.total_amount??0),customerSnapshot:{address:text(r.recipient_address),contact:text(r.recipient_name),email:text(r.recipient_email),language:""}};fields={Nummer:text(r.quote_no),Kunde:text(r.customer_name),"E-Mail":text(r.recipient_email)||text(r.customer_email),Datum:iso(r.issue_date),"Gültig bis":iso(r.valid_until),Betrag:String(r.total_amount??0),Status:status,Einleitung:text(r.intro_text),Rabatt:`${Number(r.discount??0)} %`};row=[fields.Nummer,fields.Kunde,fields["Gültig bis"]||fields.Datum,money(r.total_amount),status];positions=await lines(client,moduleKey,organizationId,text(r.id));break;
  case"rechnungen":metadata={relations:{customerId:await external(client,"customers",organizationId,text(r.customer_id)),projectId:await external(client,"projects",organizationId,text(r.project_id)),orderId:await external(client,"orders",organizationId,text(r.order_id))},net:Number(r.subtotal??0),vat:Number(r.vat_amount??0),gross:Number(r.total_amount??0),paidAmount:Number(r.paid_amount??0),reminderLevel:Number(r.reminder_level??0),lastReminder:r.last_reminder_at,recurring:Boolean(r.recurring),customerSnapshot:{address:text(r.recipient_address),contact:text(r.recipient_name),email:text(r.recipient_email),language:""}};fields={Nummer:text(r.invoice_no),Kunde:text(r.customer_name),"E-Mail":text(r.recipient_email)||text(r.customer_email),Datum:iso(r.issue_date),Fällig:iso(r.due_date),Betrag:String(r.total_amount??0),Status:status,Einleitung:text(r.intro_text),Rabatt:`${Number(r.discount??0)} %`};row=[fields.Nummer,fields.Kunde,fields.Fällig,money(r.total_amount),status];positions=await lines(client,moduleKey,organizationId,text(r.id));break;
  case"zahlungen":metadata={relations:{customerId:await external(client,"customers",organizationId,text(r.payer_customer_id)),invoiceId:await external(client,"invoices",organizationId,text(r.invoice_id))}};fields={Datum:iso(r.payment_date),Zahler:text(r.payer_name),Referenz:text(r.reference),"Betrag CHF":String(r.amount??0),Rechnung:text(r.invoice_no),Zahlungsart:text(r.method),Zuordnung:text(r.allocation_status)==="partial"?"Teilzugeordnet":text(r.allocation_status)==="open"?"Offen":"Zugeordnet"};status=fields.Zuordnung;row=[fields.Datum,fields.Zahler||"–",fields.Referenz,money(r.amount),status];break;
  default: row=[];fields={};
 }
 const noteList=await notes(client,organizationId,moduleKey,id);if(noteList.length)metadata={...metadata,notes:noteList};
 return {id,module:moduleKey,status,row,fields,positions,metadata,createdBy:text(r.created_by_user_id)||null,createdAt:r.created_at as Date|undefined,updatedAt:r.updated_at as Date|undefined};
}

async function selectRows(client:PoolClient,organizationId:string,moduleKey:string,externalId?:string){
 const idClause=externalId?" and t.external_id=$2":"";const params=externalId?[organizationId,externalId]:[organizationId];
 switch(moduleKey){
  case"kunden":return (await client.query(`select t.*,0::numeric as revenue from customers t where t.organization_id=$1 and t.archived_at is null${idClause} order by t.updated_at desc limit 1000`,params)).rows;
  case"projekte":return (await client.query(`select t.*,c.name customer_name,e.name manager_name from projects t left join customers c on c.id=t.customer_id and c.organization_id=t.organization_id left join employees e on e.id=t.manager_employee_id and e.organization_id=t.organization_id where t.organization_id=$1 and t.archived_at is null${idClause} order by t.updated_at desc limit 1000`,params)).rows;
  case"produkte":return (await client.query(`select t.* from products_services t where t.organization_id=$1 and t.archived_at is null${idClause} order by t.updated_at desc limit 1000`,params)).rows;
  case"auftraege":return (await client.query(`select t.*,c.name customer_name,p.name project_name from orders t join customers c on c.id=t.customer_id and c.organization_id=t.organization_id left join projects p on p.id=t.project_id and p.organization_id=t.organization_id where t.organization_id=$1 and t.archived_at is null${idClause} order by t.updated_at desc limit 1000`,params)).rows;
  case"zeiterfassung":return (await client.query(`select t.*,p.name project_name,ps.name service_name from time_entries t left join projects p on p.id=t.project_id and p.organization_id=t.organization_id left join products_services ps on ps.id=t.product_service_id and ps.organization_id=t.organization_id where t.organization_id=$1 and t.archived_at is null${idClause} order by t.work_date desc,t.updated_at desc limit 1000`,params)).rows;
  case"spesen":return (await client.query(`select t.*,e.name employee_name,p.name project_name from expenses t left join employees e on e.id=t.employee_id and e.organization_id=t.organization_id left join projects p on p.id=t.project_id and p.organization_id=t.organization_id where t.organization_id=$1 and t.archived_at is null${idClause} order by t.expense_date desc,t.updated_at desc limit 1000`,params)).rows;
  case"lieferanten":return (await client.query(`select t.*,coalesce((select sum(si.total_amount) from supplier_invoices si where si.organization_id=t.organization_id and si.supplier_id=t.id and si.status<>'paid' and si.archived_at is null),0) open_amount from suppliers t where t.organization_id=$1 and t.archived_at is null${idClause} order by t.updated_at desc limit 1000`,params)).rows;
  case"eingangsrechnungen":return (await client.query(`select t.*,s.name supplier_name from supplier_invoices t join suppliers s on s.id=t.supplier_id and s.organization_id=t.organization_id where t.organization_id=$1 and t.archived_at is null${idClause} order by t.invoice_date desc,t.updated_at desc limit 1000`,params)).rows;
  case"personal":return (await client.query(`select t.* from employees t where t.organization_id=$1 and t.archived_at is null${idClause} order by t.updated_at desc limit 1000`,params)).rows;
  case"aufgaben":return (await client.query(`select t.*,c.name customer_name,p.name project_name,i.invoice_no,e.name assignee_name from tasks t left join customers c on c.id=t.customer_id and c.organization_id=t.organization_id left join projects p on p.id=t.project_id and p.organization_id=t.organization_id left join invoices i on i.id=t.invoice_id and i.organization_id=t.organization_id left join employees e on e.id=t.assignee_employee_id and e.organization_id=t.organization_id where t.organization_id=$1 and t.archived_at is null${idClause} order by t.updated_at desc limit 1000`,params)).rows;
  case"abwesenheiten":return (await client.query(`select t.*,e.name employee_name from absences t join employees e on e.id=t.employee_id and e.organization_id=t.organization_id where t.organization_id=$1 and t.archived_at is null${idClause} order by t.start_date desc,t.updated_at desc limit 1000`,params)).rows;
  case"buchhaltung":return (await client.query(`select t.* from accounting_entries t where t.organization_id=$1 and t.archived_at is null${idClause} order by t.entry_date desc,t.updated_at desc limit 1000`,params)).rows;
  case"bank":return (await client.query(`select t.* from bank_transactions t where t.organization_id=$1 and t.archived_at is null${idClause} order by t.booking_date desc,t.updated_at desc limit 1000`,params)).rows;
  case"mwst":return (await client.query(`select t.* from vat_periods t where t.organization_id=$1${idClause} order by t.period desc,t.updated_at desc limit 1000`,params)).rows;
  case"lohn":return (await client.query(`select t.*,e.name employee_name from payroll_runs t left join employees e on e.id=t.employee_id and e.organization_id=t.organization_id where t.organization_id=$1${idClause} order by t.period desc,t.updated_at desc limit 1000`,params)).rows;
  case"dokumente":return (await client.query(`select t.*,c.name customer_name,p.name project_name,e.name employee_name,s.name supplier_name from business_documents t left join customers c on c.id=t.customer_id and c.organization_id=t.organization_id left join projects p on p.id=t.project_id and p.organization_id=t.organization_id left join employees e on e.id=t.employee_id and e.organization_id=t.organization_id left join suppliers s on s.id=t.supplier_id and s.organization_id=t.organization_id where t.organization_id=$1${idClause} order by t.updated_at desc limit 1000`,params)).rows;
  case"vertraege":return (await client.query(`select t.*,c.name customer_name,s.name supplier_name from contracts t left join customers c on c.id=t.customer_id and c.organization_id=t.organization_id left join suppliers s on s.id=t.supplier_id and s.organization_id=t.organization_id where t.organization_id=$1 and t.archived_at is null${idClause} order by t.updated_at desc limit 1000`,params)).rows;
  case"offerten":return (await client.query(`select t.*,c.name customer_name,c.email customer_email,coalesce((select sum(ql.quantity*ql.unit_price) from quote_lines ql where ql.organization_id=t.organization_id and ql.quote_id=t.id),0)::float8 net_amount,coalesce((select sum(ql.quantity*ql.unit_price*ql.vat_rate/100) from quote_lines ql where ql.organization_id=t.organization_id and ql.quote_id=t.id),0)::float8 vat_amount,coalesce((select sum(ql.quantity*ql.unit_price*(1+ql.vat_rate/100)) from quote_lines ql where ql.organization_id=t.organization_id and ql.quote_id=t.id),0)::float8 total_amount from quotes t join customers c on c.id=t.customer_id and c.organization_id=t.organization_id where t.organization_id=$1 and t.archived_at is null${idClause} order by t.updated_at desc limit 1000`,params)).rows;
  case"rechnungen":return (await client.query(`select t.*,c.name customer_name,c.email customer_email from invoices t join customers c on c.id=t.customer_id and c.organization_id=t.organization_id where t.organization_id=$1 and t.archived_at is null${idClause} order by t.updated_at desc limit 1000`,params)).rows;
  case"zahlungen":return (await client.query(`select t.*,c.name payer_name,i.invoice_no from payments t left join customers c on c.id=t.payer_customer_id and c.organization_id=t.organization_id left join invoices i on i.id=t.invoice_id and i.organization_id=t.organization_id where t.organization_id=$1 and t.archived_at is null${idClause} order by t.payment_date desc,t.updated_at desc limit 1000`,params)).rows;
  default:return [];
 }
}

async function syncPositions(client:PoolClient,moduleKey:string,organizationId:string,parentId:string,positions?:unknown[]){
 if(!positions||!(moduleKey==="offerten"||moduleKey==="rechnungen"||moduleKey==="vertraege"))return;
 const def=moduleKey==="offerten"?{table:"quote_lines",fk:"quote_id"}:moduleKey==="rechnungen"?{table:"invoice_lines",fk:"invoice_id"}:{table:"contract_lines",fk:"contract_id"};
 await client.query(`delete from ${def.table} where organization_id=$1 and ${def.fk}=$2`,[organizationId,parentId]);
 for(let i=0;i<positions.length;i++){
  const position=positions[i];
  if(!position||typeof position!=="object"||Array.isArray(position))continue;
  const item=position as Obj;
  const baseColumns=`id,organization_id,external_id,${def.fk},sort_order,description,quantity,unit,unit_price,vat_rate`;
  const baseValues=[organizationId,`${moduleKey}-line-${randomUUID()}`,parentId,i,text(item.description)||"Position",num(item.quantity)||1,text(item.unit)||"Stück",num(item.unitPrice),num(item.vatRate)||domainConfig.defaultVatRate];
  if(moduleKey==="rechnungen"){
   await client.query(`insert into ${def.table}(${baseColumns},source_time_external_ids,source_expense_external_ids) values(gen_random_uuid(),$1,$2,$3,$4,$5,$6,$7,$8,$9,'{}'::text[],'{}'::text[])`,baseValues);
  }else{
   await client.query(`insert into ${def.table}(${baseColumns}) values(gen_random_uuid(),$1,$2,$3,$4,$5,$6,$7,$8,$9)`,baseValues);
  }
 }
}

async function insertRecord(client:PoolClient,organizationId:string,userId:string,input:RecordInput,id:string){const f=input.fields,r=relations(input),status=statusDb(input.module,input.status);switch(input.module){
 case"kunden":{const z=text(f["PLZ / Ort"]).match(/^(\d{4,5})\s*(.*)$/);await client.query(`insert into customers(id,organization_id,external_id,customer_no,name,legal_name,contact_name,email,phone,address,zip,city,country,uid,language,payment_days,discount,status,notes,created_by_user_id) values(gen_random_uuid(),$1,$2,$3,$4,$4,$5,$6,$7,$8,$9,$10,'Schweiz',$11,$12,$13,$14,$15,$16,$17)`,[organizationId,id,`K-${Date.now().toString().slice(-6)}`,text(f.Firmenname)||input.row[0],text(f.Kontaktperson),text(f["E-Mail"]),text(f.Telefon),text(f["Strasse und Nr."]),z?.[1]||null,z?.[2]||null,text(f.UID),text(f.Sprache)||"de",num(f.Zahlungsfrist)||30,num(f["Rabatt %"]),status,text(f.Notiz),userId]);break}
 case"projekte":await client.query(`insert into projects(organization_id,external_id,customer_id,manager_employee_id,name,team_text,budget,hours_budget,progress,start_date,end_date,status,notes,created_by_user_id) values($1,$2,$3,$4,$5,$6,$7,$8,$9,nullif($10,'')::date,nullif($11,'')::date,$12,$13,$14)`,[organizationId,id,await pk(client,"customers",organizationId,r.customerId),await pk(client,"employees",organizationId,r.managerId),text(f.Projektname)||input.row[0],text(f["Team / Ressourcen"]),num(f.Budget),num(f.Stundenbudget),num(f["Fortschritt %"]),text(f.Start),text(f.Ende),status,text(f.Projektbeschreibung),userId]);break;
 case"produkte":await client.query(`insert into products_services(organization_id,external_id,name,item_type,unit,unit_price,vat_rate,status,created_by_user_id) values($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[organizationId,id,text(f.Bezeichnung)||input.row[0],/artikel/i.test(text(f.Typ))?"product":"service",text(f.Einheit)||"Stunde",num(f["Preis CHF"]),num(f["MWST %"])||domainConfig.defaultVatRate,status,userId]);break;
 case"auftraege":await client.query(`insert into orders(organization_id,external_id,customer_id,project_id,name,budget_hours,sales_rate,cost_rate,billing_model,status,amount,start_date,end_date,notes,created_by_user_id) values($1,$2,$3,$4,$5,0,0,0,'fixed',$6,$7,nullif($8,'')::date,nullif($9,'')::date,$10,$11)`,[organizationId,id,await pk(client,"customers",organizationId,r.customerId),await pk(client,"projects",organizationId,r.projectId),text(f.Auftragsbezeichnung)||input.row[0],status,num(f.Auftragsvolumen),text(f.Start),text(f["Geplantes Ende"]),text(f.Notiz),userId]);break;
 case"zeiterfassung":{const emp=await pk(client,"employees",organizationId,r.employeeId);const project=await pk(client,"projects",organizationId,r.projectId);const service=await pk(client,"products_services",organizationId,r.productId);await client.query(`insert into time_entries(organization_id,external_id,order_id,employee_id,person_name,worker_type,work_date,hours,description,billable,approved,sales_rate,internal_cost_rate,project_id,product_service_id,start_time,end_time,break_minutes,created_by_user_id) values($1,$2,null,$3,$4,'employee',$5,$6,$7,$8,$9,0,0,$10,$11,nullif($12,'')::time,nullif($13,'')::time,$14,$15)`,[organizationId,id,emp,text(f.Mitarbeiter)||"Mitarbeiter",text(f.Datum),num(f["Dauer in Stunden"]),text(f.Notiz)||text(f.Leistung),yes(f.Verrechenbar),/freigegeben/i.test(text(f.Status)),project,service,text(f.Von),text(f.Bis),num(f["Pause Minuten"]),userId]);break}
 case"spesen":await client.query(`insert into expenses(organization_id,external_id,customer_id,order_id,contract_id,expense_date,description,category,quantity,unit_price,billable,employee_id,project_id,status,created_by_user_id) values($1,$2,null,null,null,$3,$4,$5,1,$6,$7,$8,$9,$10,$11)`,[organizationId,id,text(f.Datum),text(f.Beschreibung),(/material/i.test(text(f.Kategorie))?"material":/reise|fahrzeug/i.test(text(f.Kategorie))?"travel":"other"),num(f["Betrag CHF"]),yes(f.Weiterverrechenbar),await pk(client,"employees",organizationId,r.employeeId),await pk(client,"projects",organizationId,r.projectId),status,userId]);break;
 case"lieferanten":await client.query(`insert into suppliers(organization_id,external_id,supplier_no,name,contact_name,email,phone,address,iban,payment_days,status,created_by_user_id) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)`,[organizationId,id,`L-${Date.now().toString().slice(-6)}`,text(f.Firmenname)||input.row[0],text(f.Kontaktperson),text(f["E-Mail"]),text(f.Telefon),text(f.Adresse),text(f.IBAN),num(f.Zahlungsfrist)||30,status,userId]);break;
 case"eingangsrechnungen":{const supplier=await pk(client,"suppliers",organizationId,r.supplierId);await client.query(`insert into supplier_invoices(organization_id,external_id,supplier_id,order_id,supplier_invoice_no,invoice_date,due_date,net_amount,vat_amount,total_amount,status,note,expense_account,created_by_user_id) values($1,$2,$3,$4,$5,$6,$7,$8,0,$8,$9,null,$10,$11)`,[organizationId,id,supplier,await pk(client,"orders",organizationId,r.orderId),text(f.Rechnungsnummer)||input.row[0],text(f.Datum),text(f.Fällig)||text(f.Datum),num(f["Betrag CHF"]),status,text(f.Aufwandskonto),userId]);break}
 case"personal":await client.query(`insert into employees(organization_id,external_id,name,email,role,employment_type,target_hours,internal_cost_rate,active,title,phone,address,ahv_number,iban,workload_percent,weekly_hours,vacation_days,start_date,monthly_gross,child_allowance,withholding_tax_rate,bvg_deduction,created_by_user_id) values($1,$2,$3,$4,'employee','salary',0,0,$5,$6,$7,$8,$9,$10,$11,$12,$13,nullif($14,'')::date,$15,$16,$17,$18,$19)`,[organizationId,id,text(f.Name)||input.row[0],text(f["E-Mail"]),!/inaktiv|ausgetreten/i.test(text(f.Status)),text(f.Funktion),text(f.Telefon),text(f.Adresse),text(f["AHV-Nr."]),text(f.IBAN),num(f["Pensum %"])||100,num(f.Wochenstunden)||42,num(f["Ferientage / Jahr"])||25,text(f.Eintritt),num(f["Monatslohn brutto CHF"]),num(f["Kinderzulage CHF"]),num(f["Quellensteuer %"]),num(f["BVG Abzug CHF"]),userId]);break;
 case"aufgaben":await client.query(`insert into tasks(organization_id,external_id,title,customer_id,project_id,invoice_id,assignee_employee_id,due_date,priority,status,created_by_user_id) values($1,$2,$3,$4,$5,$6,$7,nullif($8,'')::date,$9,$10,$11)`,[organizationId,id,text(f.Aufgabe)||input.row[0],await pk(client,"customers",organizationId,r.customerId),await pk(client,"projects",organizationId,r.projectId),await pk(client,"invoices",organizationId,r.invoiceId),await pk(client,"employees",organizationId,r.employeeId),text(f.Fällig),/kritisch/i.test(text(f.Priorität))?"critical":/hoch/i.test(text(f.Priorität))?"high":"normal",status,userId]);break;
 case"abwesenheiten":await client.query(`insert into absences(organization_id,external_id,employee_id,absence_type,start_date,end_date,days,status,created_by_user_id) values($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[organizationId,id,await pk(client,"employees",organizationId,r.employeeId),/krank/i.test(text(f.Art))?"sick":/unbezahlt/i.test(text(f.Art))?"unpaid":/militär|zivil/i.test(text(f.Art))?"military_civil":/ferien/i.test(text(f.Art))?"vacation":"other",text(f.Von),text(f.Bis),num(f.Tage)||1,status,userId]);break;
 case"buchhaltung":await client.query(`insert into accounting_entries(organization_id,external_id,entry_date,document_ref,account_no,contra_account_no,amount,status,source_type,source_external_id,created_by_user_id) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,[organizationId,id,text(f.Datum),text(f.Beleg),text(f.Konto),text(f.Gegenkonto),num(f["Betrag CHF"]),status,text((input.metadata?.relations as Obj|undefined)?.supplierInvoiceId)?"supplier_invoice":null,text((input.metadata?.relations as Obj|undefined)?.supplierInvoiceId)||null,userId]);break;
 case"bank":await client.query(`insert into bank_transactions(organization_id,external_id,booking_date,account_label,description,amount,status,invoice_id,created_by_user_id) values($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[organizationId,id,text(f.Datum),text(f.Konto),text(f.Text),num(f["Betrag CHF"]),status,await pk(client,"invoices",organizationId,r.invoiceId),userId]);break;
 case"mwst":await client.query(`insert into vat_periods(organization_id,external_id,period,output_vat,input_vat,payable,status,created_by_user_id) values($1,$2,$3,$4,$5,$6,$7,$8)`,[organizationId,id,text(f.Periode)||input.row[0],num(f.Umsatzsteuer),num(f.Vorsteuer),num(f.Zahllast),status,userId]);break;
 case"lohn":await client.query(`insert into payroll_runs(organization_id,external_id,employee_id,period,gross_amount,deduction_amount,net_amount,status,created_by_user_id) values($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[organizationId,id,await pk(client,"employees",organizationId,r.employeeId),text(f.Periode)||new Date().toISOString().slice(0,7),num(f.Brutto),num(f.Abzüge),num(f.Netto),status,userId]);break;
 case"dokumente":await client.query(`insert into business_documents(organization_id,external_id,name,document_type,customer_id,project_id,employee_id,supplier_id,document_date,status,created_by_user_id) values($1,$2,$3,$4,$5,$6,$7,$8,nullif($9,'')::date,$10,$11)`,[organizationId,id,text(f.Dokumentname)||input.row[0],text(f.Typ)||"Andere",await pk(client,"customers",organizationId,r.customerId),await pk(client,"projects",organizationId,r.projectId),await pk(client,"employees",organizationId,r.employeeId),await pk(client,"suppliers",organizationId,r.supplierId),text(f.Aktualisiert),status,userId]);break;
 case"vertraege":{const customer=await pk(client,"customers",organizationId,r.customerId),supplier=await pk(client,"suppliers",organizationId,r.supplierId);await client.query(`insert into contracts(organization_id,external_id,contract_no,customer_id,supplier_id,name,start_date,end_date,status,auto_renew,notice_days,billing_interval,contract_value,created_by_user_id) values($1,$2,$3,$4,$5,$6,coalesce(nullif($7,'')::date,current_date),nullif($8,'')::date,$9,$10,0,$11,$12,$13)`,[organizationId,id,`VT-${Date.now().toString().slice(-6)}`,customer,supplier,text(f.Vertrag)||input.row[0],text(f.Start),text(f.Ende),status,yes(f["Rechnung automatisch vorbereiten"]),/monat/i.test(text(f.Intervall))?"monthly":/jähr/i.test(text(f.Intervall))?"yearly":"none",num(f["Wert CHF"]),userId]);break}
 case"offerten":case"rechnungen":{const isInvoice=input.module==="rechnungen";const customer=await pk(client,"customers",organizationId,r.customerId);if(!customer)throw new Error("Kunde fehlt.");const project=await pk(client,"projects",organizationId,r.projectId);const gross=num(input.metadata?.gross)||num(f.Betrag);const net=num(input.metadata?.net)||gross;const vat=num(input.metadata?.vat);const customerSnapshot=input.metadata?.customerSnapshot&&typeof input.metadata.customerSnapshot==="object"?input.metadata.customerSnapshot as Obj:{};if(isInvoice){const res=await client.query<{id:string}>(`insert into invoices(organization_id,external_id,invoice_no,customer_id,project_id,order_id,period,issue_date,due_date,status,subtotal,vat_amount,total_amount,paid_amount,recipient_name,recipient_address,recipient_email,intro_text,recurring,recurrence_interval,created_by_user_id) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21) returning id::text`,[organizationId,id,text(f.Nummer)||input.row[0],customer,project,await pk(client,"orders",organizationId,r.orderId),text(f.Datum).slice(0,7),text(f.Datum)||new Date().toISOString().slice(0,10),text(f.Fällig)||text(f.Datum),status,net,vat,gross,num(input.metadata?.paidAmount),text(customerSnapshot.contact),text(customerSnapshot.address),text(customerSnapshot.email)||text(f["E-Mail"]),text(f.Einleitung),Boolean(input.metadata?.recurring),text(input.metadata?.recurrence)||null,userId]);await syncPositions(client,input.module,organizationId,res.rows[0].id,input.positions)}else{const res=await client.query<{id:string}>(`insert into quotes(organization_id,external_id,quote_no,customer_id,project_id,title,issue_date,valid_until,status,version,recipient_name,recipient_address,recipient_email,intro_text,created_by_user_id) values($1,$2,$3,$4,$5,$6,$7,$8,$9,1,$10,$11,$12,$13,$14) returning id::text`,[organizationId,id,text(f.Nummer)||input.row[0],customer,project,text(f.Nummer)||"Offerte",text(f.Datum)||new Date().toISOString().slice(0,10),text(f["Gültig bis"])||text(f.Datum),status,text(customerSnapshot.contact),text(customerSnapshot.address),text(customerSnapshot.email)||text(f["E-Mail"]),text(f.Einleitung),userId]);await syncPositions(client,input.module,organizationId,res.rows[0].id,input.positions)}break}
 case"zahlungen":await client.query(`insert into payments(organization_id,external_id,invoice_id,payer_customer_id,payment_date,amount,method,reference,allocation_status,created_by_user_id) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,[organizationId,id,await pk(client,"invoices",organizationId,r.invoiceId),await pk(client,"customers",organizationId,r.customerId),text(f.Datum)||new Date().toISOString().slice(0,10),num(f["Betrag CHF"]),text(f.Zahlungsart)||"Bank",text(f.Referenz),/teil/i.test(input.status)?"partial":/offen/i.test(input.status)?"open":"matched",userId]);break;
 default:throw new Error(`Unsupported module ${input.module}`);
 }
 await syncNotes(client,organizationId,userId,input.module,id,input.metadata);
}

async function updateInPlace(client:PoolClient,organizationId:string,userId:string,id:string,moduleKey:string,input:RecordInput){
 const f=input.fields,r=relations(input),status=statusDb(moduleKey,input.status);
 switch(moduleKey){
  case"kunden":{const z=text(f["PLZ / Ort"]).match(/^(\d{4,5})\s*(.*)$/);await client.query(`update customers set name=$3,legal_name=$3,contact_name=$4,email=$5,phone=$6,address=$7,zip=$8,city=$9,uid=$10,language=$11,payment_days=$12,discount=$13,status=$14,notes=$15,updated_at=now() where organization_id=$1 and external_id=$2`,[organizationId,id,text(f.Firmenname)||input.row[0],text(f.Kontaktperson),text(f["E-Mail"]),text(f.Telefon),text(f["Strasse und Nr."]),z?.[1]||null,z?.[2]||null,text(f.UID),text(f.Sprache)||"de",num(f.Zahlungsfrist)||30,num(f["Rabatt %"]),status,text(f.Notiz)]);break}
  case"projekte":await client.query(`update projects set customer_id=$3,manager_employee_id=$4,name=$5,team_text=$6,budget=$7,hours_budget=$8,progress=$9,start_date=nullif($10,'')::date,end_date=nullif($11,'')::date,status=$12,notes=$13,version=version+1,updated_at=now() where organization_id=$1 and external_id=$2`,[organizationId,id,await pk(client,"customers",organizationId,r.customerId),await pk(client,"employees",organizationId,r.managerId),text(f.Projektname)||input.row[0],text(f["Team / Ressourcen"]),num(f.Budget),num(f.Stundenbudget),num(f["Fortschritt %"]),text(f.Start),text(f.Ende),status,text(f.Projektbeschreibung)]);break;
  case"produkte":await client.query(`update products_services set name=$3,item_type=$4,unit=$5,unit_price=$6,vat_rate=$7,status=$8,version=version+1,updated_at=now() where organization_id=$1 and external_id=$2`,[organizationId,id,text(f.Bezeichnung)||input.row[0],/artikel/i.test(text(f.Typ))?"product":"service",text(f.Einheit)||"Stunde",num(f["Preis CHF"]),num(f["MWST %"])||domainConfig.defaultVatRate,status]);break;
  case"auftraege":await client.query(`update orders set customer_id=$3,project_id=$4,name=$5,amount=$6,start_date=nullif($7,'')::date,end_date=nullif($8,'')::date,status=$9,notes=$10,updated_at=now() where organization_id=$1 and external_id=$2`,[organizationId,id,await pk(client,"customers",organizationId,r.customerId),await pk(client,"projects",organizationId,r.projectId),text(f.Auftragsbezeichnung)||input.row[0],num(f.Auftragsvolumen),text(f.Start),text(f["Geplantes Ende"]),status,text(f.Notiz)]);break;
  case"zeiterfassung":await client.query(`update time_entries set employee_id=$3,person_name=$4,work_date=$5,hours=$6,description=$7,billable=$8,approved=$9,project_id=$10,product_service_id=$11,start_time=nullif($12,'')::time,end_time=nullif($13,'')::time,break_minutes=$14,updated_at=now() where organization_id=$1 and external_id=$2`,[organizationId,id,await pk(client,"employees",organizationId,r.employeeId),text(f.Mitarbeiter)||"Mitarbeiter",text(f.Datum),num(f["Dauer in Stunden"]),text(f.Notiz)||text(f.Leistung),yes(f.Verrechenbar),/freigegeben/i.test(text(f.Status)),await pk(client,"projects",organizationId,r.projectId),await pk(client,"products_services",organizationId,r.productId),text(f.Von),text(f.Bis),num(f["Pause Minuten"])]);if(input.metadata?.invoicedBy!==undefined)await client.query(`update time_entries set invoiced_invoice_id=$3 where organization_id=$1 and external_id=$2`,[organizationId,id,await pk(client,"invoices",organizationId,text(input.metadata.invoicedBy))]);break;
  case"spesen":await client.query(`update expenses set expense_date=$3,description=$4,category=$5,quantity=1,unit_price=$6,billable=$7,employee_id=$8,project_id=$9,status=$10,updated_at=now() where organization_id=$1 and external_id=$2`,[organizationId,id,text(f.Datum),text(f.Beschreibung),/material/i.test(text(f.Kategorie))?"material":/reise|fahrzeug/i.test(text(f.Kategorie))?"travel":"other",num(f["Betrag CHF"]),yes(f.Weiterverrechenbar),await pk(client,"employees",organizationId,r.employeeId),await pk(client,"projects",organizationId,r.projectId),status]);if(input.metadata?.invoicedBy!==undefined)await client.query(`update expenses set invoiced_invoice_id=$3 where organization_id=$1 and external_id=$2`,[organizationId,id,await pk(client,"invoices",organizationId,text(input.metadata.invoicedBy))]);break;
  case"lieferanten":await client.query(`update suppliers set name=$3,contact_name=$4,email=$5,phone=$6,address=$7,iban=$8,payment_days=$9,status=$10,updated_at=now() where organization_id=$1 and external_id=$2`,[organizationId,id,text(f.Firmenname)||input.row[0],text(f.Kontaktperson),text(f["E-Mail"]),text(f.Telefon),text(f.Adresse),text(f.IBAN),num(f.Zahlungsfrist)||30,status]);break;
  case"eingangsrechnungen":await client.query(`update supplier_invoices set supplier_id=$3,order_id=$4,supplier_invoice_no=$5,invoice_date=$6,due_date=$7,net_amount=$8,total_amount=$8,status=$9,expense_account=$10,updated_at=now() where organization_id=$1 and external_id=$2`,[organizationId,id,await pk(client,"suppliers",organizationId,r.supplierId),await pk(client,"orders",organizationId,r.orderId),text(f.Rechnungsnummer)||input.row[0],text(f.Datum),text(f.Fällig)||text(f.Datum),num(f["Betrag CHF"]),status,text(f.Aufwandskonto)]);break;
  case"personal":await client.query(`update employees set name=$3,email=$4,active=$5,title=$6,phone=$7,address=$8,ahv_number=$9,iban=$10,workload_percent=$11,weekly_hours=$12,vacation_days=$13,start_date=nullif($14,'')::date,monthly_gross=$15,child_allowance=$16,withholding_tax_rate=$17,bvg_deduction=$18,updated_at=now() where organization_id=$1 and external_id=$2`,[organizationId,id,text(f.Name)||input.row[0],text(f["E-Mail"]),!/inaktiv|ausgetreten/i.test(text(f.Status)),text(f.Funktion),text(f.Telefon),text(f.Adresse),text(f["AHV-Nr."]),text(f.IBAN),num(f["Pensum %"])||100,num(f.Wochenstunden)||42,num(f["Ferientage / Jahr"])||25,text(f.Eintritt),num(f["Monatslohn brutto CHF"]),num(f["Kinderzulage CHF"]),num(f["Quellensteuer %"]),num(f["BVG Abzug CHF"])]);break;
  case"aufgaben":await client.query(`update tasks set title=$3,customer_id=$4,project_id=$5,invoice_id=$6,assignee_employee_id=$7,due_date=nullif($8,'')::date,priority=$9,status=$10,version=version+1,updated_at=now() where organization_id=$1 and external_id=$2`,[organizationId,id,text(f.Aufgabe)||input.row[0],await pk(client,"customers",organizationId,r.customerId),await pk(client,"projects",organizationId,r.projectId),await pk(client,"invoices",organizationId,r.invoiceId),await pk(client,"employees",organizationId,r.employeeId),text(f.Fällig),/kritisch/i.test(text(f.Priorität))?"critical":/hoch/i.test(text(f.Priorität))?"high":"normal",status]);break;
  case"abwesenheiten":await client.query(`update absences set employee_id=$3,absence_type=$4,start_date=$5,end_date=$6,days=$7,status=$8,version=version+1,updated_at=now() where organization_id=$1 and external_id=$2`,[organizationId,id,await pk(client,"employees",organizationId,r.employeeId),/krank/i.test(text(f.Art))?"sick":/unbezahlt/i.test(text(f.Art))?"unpaid":/militär|zivil/i.test(text(f.Art))?"military_civil":/ferien/i.test(text(f.Art))?"vacation":"other",text(f.Von),text(f.Bis),num(f.Tage)||1,status]);break;
  case"buchhaltung":await client.query(`update accounting_entries set entry_date=$3,document_ref=$4,account_no=$5,contra_account_no=$6,amount=$7,status=$8,version=version+1,updated_at=now() where organization_id=$1 and external_id=$2`,[organizationId,id,text(f.Datum),text(f.Beleg),text(f.Konto),text(f.Gegenkonto),num(f["Betrag CHF"]),status]);break;
  case"bank":await client.query(`update bank_transactions set booking_date=$3,account_label=$4,description=$5,amount=$6,status=$7,invoice_id=$8,version=version+1,updated_at=now() where organization_id=$1 and external_id=$2`,[organizationId,id,text(f.Datum),text(f.Konto),text(f.Text),num(f["Betrag CHF"]),status,await pk(client,"invoices",organizationId,r.invoiceId)]);break;
  case"mwst":await client.query(`update vat_periods set period=$3,output_vat=$4,input_vat=$5,payable=$6,status=$7,version=version+1,updated_at=now() where organization_id=$1 and external_id=$2`,[organizationId,id,text(f.Periode)||input.row[0],num(f.Umsatzsteuer),num(f.Vorsteuer),num(f.Zahllast),status]);break;
  case"lohn":await client.query(`update payroll_runs set employee_id=$3,period=$4,gross_amount=$5,deduction_amount=$6,net_amount=$7,status=$8,version=version+1,updated_at=now() where organization_id=$1 and external_id=$2`,[organizationId,id,await pk(client,"employees",organizationId,r.employeeId),text(f.Periode)||new Date().toISOString().slice(0,7),num(f.Brutto),num(f.Abzüge),num(f.Netto),status]);break;
  case"dokumente":await client.query(`update business_documents set name=$3,document_type=$4,customer_id=$5,project_id=$6,employee_id=$7,supplier_id=$8,document_date=nullif($9,'')::date,status=$10,version=version+1,updated_at=now() where organization_id=$1 and external_id=$2`,[organizationId,id,text(f.Dokumentname)||input.row[0],text(f.Typ)||"Andere",await pk(client,"customers",organizationId,r.customerId),await pk(client,"projects",organizationId,r.projectId),await pk(client,"employees",organizationId,r.employeeId),await pk(client,"suppliers",organizationId,r.supplierId),text(f.Aktualisiert),status]);break;
  case"vertraege":{const current=(await client.query<{id:string}>(`select id::text from contracts where organization_id=$1 and external_id=$2`,[organizationId,id])).rows[0];await client.query(`update contracts set customer_id=$3,supplier_id=$4,name=$5,start_date=coalesce(nullif($6,'')::date,start_date),end_date=nullif($7,'')::date,status=$8,auto_renew=$9,billing_interval=$10,contract_value=$11,updated_at=now() where organization_id=$1 and external_id=$2`,[organizationId,id,await pk(client,"customers",organizationId,r.customerId),await pk(client,"suppliers",organizationId,r.supplierId),text(f.Vertrag)||input.row[0],text(f.Start),text(f.Ende),status,yes(f["Rechnung automatisch vorbereiten"]),/monat/i.test(text(f.Intervall))?"monthly":/jähr/i.test(text(f.Intervall))?"yearly":"none",num(f["Wert CHF"])]);if(current)await syncPositions(client,moduleKey,organizationId,current.id,input.positions);break}
  case"offerten":{const current=(await client.query<{id:string}>(`select id::text from quotes where organization_id=$1 and external_id=$2`,[organizationId,id])).rows[0];const snap=input.metadata?.customerSnapshot&&typeof input.metadata.customerSnapshot==="object"?input.metadata.customerSnapshot as Obj:{};await client.query(`update quotes set customer_id=$3,project_id=$4,quote_no=$5,title=$5,issue_date=$6,valid_until=$7,status=$8,recipient_name=$9,recipient_address=$10,recipient_email=$11,intro_text=$12,updated_at=now() where organization_id=$1 and external_id=$2`,[organizationId,id,await pk(client,"customers",organizationId,r.customerId),await pk(client,"projects",organizationId,r.projectId),text(f.Nummer)||input.row[0],text(f.Datum)||new Date().toISOString().slice(0,10),text(f["Gültig bis"])||text(f.Datum),status,text(snap.contact),text(snap.address),text(snap.email)||text(f["E-Mail"]),text(f.Einleitung)]);if(current)await syncPositions(client,moduleKey,organizationId,current.id,input.positions);break}
  case"rechnungen":{const current=(await client.query<{id:string}>(`select id::text from invoices where organization_id=$1 and external_id=$2`,[organizationId,id])).rows[0];const snap=input.metadata?.customerSnapshot&&typeof input.metadata.customerSnapshot==="object"?input.metadata.customerSnapshot as Obj:{};const gross=num(input.metadata?.gross)||num(f.Betrag),net=num(input.metadata?.net)||gross,vat=num(input.metadata?.vat);await client.query(`update invoices set customer_id=$3,project_id=$4,order_id=$5,invoice_no=$6,issue_date=$7,due_date=$8,status=$9,subtotal=$10,vat_amount=$11,total_amount=$12,paid_amount=$13,recipient_name=$14,recipient_address=$15,recipient_email=$16,intro_text=$17,reminder_level=$18,last_reminder_at=$19,recurring=$20,recurrence_interval=$21,updated_at=now() where organization_id=$1 and external_id=$2`,[organizationId,id,await pk(client,"customers",organizationId,r.customerId),await pk(client,"projects",organizationId,r.projectId),await pk(client,"orders",organizationId,r.orderId),text(f.Nummer)||input.row[0],text(f.Datum)||new Date().toISOString().slice(0,10),text(f.Fällig)||text(f.Datum),status,net,vat,gross,num(input.metadata?.paidAmount),text(snap.contact),text(snap.address),text(snap.email)||text(f["E-Mail"]),text(f.Einleitung),num(input.metadata?.reminderLevel),input.metadata?.lastReminder?text(input.metadata.lastReminder):null,Boolean(input.metadata?.recurring),text(input.metadata?.recurrence)||null]);if(current)await syncPositions(client,moduleKey,organizationId,current.id,input.positions);break}
  case"zahlungen":await client.query(`update payments set invoice_id=$3,payer_customer_id=$4,payment_date=$5,amount=$6,method=$7,reference=$8,allocation_status=$9,updated_at=now() where organization_id=$1 and external_id=$2`,[organizationId,id,await pk(client,"invoices",organizationId,r.invoiceId),await pk(client,"customers",organizationId,r.customerId),text(f.Datum)||new Date().toISOString().slice(0,10),num(f["Betrag CHF"]),text(f.Zahlungsart)||"Bank",text(f.Referenz),/teil/i.test(input.status)?"partial":/offen/i.test(input.status)?"open":"matched"]);break;
  default:throw new Error(`Unsupported module ${moduleKey}`)
 }
 await syncNotes(client,organizationId,userId,moduleKey,id,input.metadata);
}

async function replaceRecord(client:PoolClient,organizationId:string,userId:string,id:string,moduleKey:string,input:Partial<RecordInput>){await protectBusinessRecord(client,organizationId,id,moduleKey);const currentRows=await selectRows(client,organizationId,moduleKey,id);if(!currentRows[0])return false;const current=await rowToDto(client,moduleKey,organizationId,currentRows[0]);const merged:RecordInput={module:moduleKey,status:input.status??current.status,row:input.row??current.row,fields:input.fields??current.fields,positions:input.positions??current.positions,metadata:{...current.metadata,...(input.metadata||{})}};await updateInPlace(client,organizationId,userId,id,moduleKey,merged);return true}
async function protectBusinessRecord(client:PoolClient,organizationId:string,id:string,moduleKey:string){
 if(moduleKey==='zahlungen')throw new ApiError(409,'payment_locked','Verbuchte Zahlungen müssen nachvollziehbar korrigiert werden.');
 if(moduleKey==='rechnungen'&&(await client.query("select id from invoices where organization_id=$1 and external_id=$2 and status<>'draft' for update",[organizationId,id])).rowCount)throw new ApiError(409,'document_locked','Ausgestellte Rechnungen können nicht geändert oder entfernt werden.');
 if(moduleKey==='offerten'&&(await client.query("select q.id from quotes q where q.organization_id=$1 and q.external_id=$2 and (q.status<>'draft' or exists(select 1 from invoices i where i.organization_id=q.organization_id and i.source_quote_id=q.id) or exists(select 1 from projects p where p.organization_id=q.organization_id and p.source_quote_id=q.id)) for update",[organizationId,id])).rowCount)throw new ApiError(409,'document_locked','Dieses Angebot hat bereits einen Geschäftsvorgang.');
 if(moduleKey==='zeiterfassung'&&(await client.query('select id from time_entries where organization_id=$1 and external_id=$2 and invoiced_invoice_id is not null for update',[organizationId,id])).rowCount)throw new ApiError(409,'time_locked','Verrechnete Zeiteinträge können nicht geändert oder entfernt werden.');
}
async function archiveRecord(client:PoolClient,organizationId:string,id:string,moduleKey:string){await protectBusinessRecord(client,organizationId,id,moduleKey);const table=moduleTables[moduleKey];if(!table)return false;if(["vat_periods","payroll_runs","business_documents"].includes(table)){const r=await client.query(`delete from ${table} where organization_id=$1 and external_id=$2`,[organizationId,id]);return Boolean(r.rowCount)}const r=await client.query(`update ${table} set archived_at=now(),updated_at=now() where organization_id=$1 and external_id=$2 and archived_at is null`,[organizationId,id]);return Boolean(r.rowCount)}

export async function getRecordHeader(organizationId:string,userId:string,id:string){return withTenant(organizationId,userId,async client=>{for(const moduleKey of Object.keys(moduleTables)){const rows=await selectRows(client,organizationId,moduleKey,id);if(rows[0])return {id,module:moduleKey,createdBy:text(rows[0].created_by_user_id)};}return null})}
export async function getRecord(organizationId:string,userId:string,id:string,ownOnly=false){return withTenant(organizationId,userId,async client=>{for(const moduleKey of Object.keys(moduleTables)){const rows=await selectRows(client,organizationId,moduleKey,id);const row=rows[0];if(!row)continue;if(ownOnly&&text(row.created_by_user_id)!==userId)return null;return rowToDto(client,moduleKey,organizationId,row)}return null})}
export async function listRecords(organizationId:string,userId:string,moduleKey:string,ownOnly=false){return withTenant(organizationId,userId,async client=>{if(!moduleTables[moduleKey])return [];const rows=await selectRows(client,organizationId,moduleKey);const filtered=ownOnly?rows.filter(r=>text(r.created_by_user_id)===userId):rows;return Promise.all(filtered.map(r=>rowToDto(client,moduleKey,organizationId,r)))})}
export async function createRecord(organizationId:string,userId:string,input:RecordInput){return withTenant(organizationId,userId,async client=>{const id=ext();await insertRecord(client,organizationId,userId,input,id);await audit(client,{organizationId,userId,action:`${input.module}.created`,entityType:input.module,entityId:id});const rows=await selectRows(client,organizationId,input.module,id);return rowToDto(client,input.module,organizationId,rows[0])})}
export async function updateRecord(organizationId:string,userId:string,id:string,input:Partial<RecordInput>,ownOnly=false){return withTenant(organizationId,userId,async client=>{const header=await getHeaderInClient(client,organizationId,id);if(!header||ownOnly&&header.createdBy!==userId)return null;const ok=await replaceRecord(client,organizationId,userId,id,header.module,input);if(!ok)return null;await audit(client,{organizationId,userId,action:`${header.module}.updated`,entityType:header.module,entityId:id});const rows=await selectRows(client,organizationId,header.module,id);return rowToDto(client,header.module,organizationId,rows[0])})}
export async function deleteRecord(organizationId:string,userId:string,id:string,ownOnly=false){return withTenant(organizationId,userId,async client=>{const header=await getHeaderInClient(client,organizationId,id);if(!header||ownOnly&&header.createdBy!==userId)return false;const ok=await archiveRecord(client,organizationId,id,header.module);if(ok)await audit(client,{organizationId,userId,action:`${header.module}.deleted`,entityType:header.module,entityId:id});return ok})}
async function getHeaderInClient(client:PoolClient,organizationId:string,id:string){for(const moduleKey of Object.keys(moduleTables)){const rows=await selectRows(client,organizationId,moduleKey,id);if(rows[0])return {id,module:moduleKey,createdBy:text(rows[0].created_by_user_id)}}return null}
