import "server-only";
import { randomUUID } from "node:crypto";
import { withTenant } from "@/lib/server/db";
import { audit } from "@/lib/server/audit";

export type RecordInput={module:string;status:string;row:string[];fields:Record<string,string>;positions?:unknown[];metadata?:Record<string,unknown>};

export async function getRecord(organizationId:string,userId:string,id:string,ownOnly=false){return withTenant(organizationId,userId,async client=>{const params:unknown[]=[id,organizationId];let sql=`select id,module,status,row_data as row,fields,positions,metadata,created_by as "createdBy",created_at as "createdAt",updated_at as "updatedAt" from records where id=$1 and organization_id=$2`;if(ownOnly){params.push(userId);sql+=" and created_by=$3"}return (await client.query(sql,params)).rows[0]||null})}
export async function getRecordHeader(organizationId:string,userId:string,id:string){return withTenant(organizationId,userId,async client=>(await client.query<{id:string;module:string;createdBy:string}>(`select id,module,created_by as "createdBy" from records where id=$1 and organization_id=$2`,[id,organizationId])).rows[0]||null)}
export async function listRecords(organizationId:string,userId:string,moduleKey:string,ownOnly=false){return withTenant(organizationId,userId,async client=>{const params:unknown[]=[organizationId,moduleKey];let sql=`select id,module,status,row_data as row,fields,positions,metadata,created_by as "createdBy",created_at as "createdAt",updated_at as "updatedAt" from records where organization_id=$1 and module=$2`;if(ownOnly){params.push(userId);sql+=" and created_by=$3"}sql+=" order by updated_at desc limit 1000";return (await client.query(sql,params)).rows})}
export async function createRecord(organizationId:string,userId:string,input:RecordInput){return withTenant(organizationId,userId,async client=>{const id=randomUUID();const result=await client.query(`insert into records (id,organization_id,module,status,row_data,fields,positions,metadata,created_by,updated_by) values ($1,$2,$3,$4,$5::jsonb,$6::jsonb,$7::jsonb,$8::jsonb,$9,$9) returning id,module,status,row_data as row,fields,positions,metadata,created_by as "createdBy",created_at as "createdAt",updated_at as "updatedAt"`,[id,organizationId,input.module,input.status,JSON.stringify(input.row),JSON.stringify(input.fields),JSON.stringify(input.positions||null),JSON.stringify(input.metadata||{}),userId]);await audit(client,{organizationId,userId,action:`${input.module}.created`,entityType:input.module,entityId:id});return result.rows[0]})}
export async function updateRecord(organizationId:string,userId:string,id:string,input:Partial<RecordInput>,ownOnly=false){return withTenant(organizationId,userId,async client=>{const params:unknown[]=[id,organizationId];let select=`select * from records where id=$1 and organization_id=$2`;if(ownOnly){params.push(userId);select+=" and created_by=$3"}const c=(await client.query(select,params)).rows[0];if(!c)return null;const result=await client.query(`update records set status=$1,row_data=$2::jsonb,fields=$3::jsonb,positions=$4::jsonb,metadata=$5::jsonb,updated_by=$6,updated_at=now() where id=$7 and organization_id=$8 returning id,module,status,row_data as row,fields,positions,metadata,created_by as "createdBy",created_at as "createdAt",updated_at as "updatedAt"`,[input.status??c.status,JSON.stringify(input.row??c.row_data),JSON.stringify(input.fields??c.fields),JSON.stringify(input.positions??c.positions),JSON.stringify(input.metadata??c.metadata),userId,id,organizationId]);await audit(client,{organizationId,userId,action:`${c.module}.updated`,entityType:c.module,entityId:id});return result.rows[0]})}
export async function deleteRecord(organizationId:string,userId:string,id:string,ownOnly=false){return withTenant(organizationId,userId,async client=>{const params:unknown[]=[id,organizationId];let sql=`delete from records where id=$1 and organization_id=$2`;if(ownOnly){params.push(userId);sql+=" and created_by=$3"}sql+=" returning module";const current=await client.query(sql,params);if(!current.rowCount)return false;await audit(client,{organizationId,userId,action:`${current.rows[0].module}.deleted`,entityType:current.rows[0].module,entityId:id});return true})}
