import {createHash,randomUUID} from "node:crypto";
import {NextRequest} from "next/server";
import type {PoolClient} from "pg";
import {limitsConfig} from "@/config/limits";
import {requireSession} from "@/lib/server/session";
import {authorize} from "@/lib/server/rbac";
import {withTenant} from "@/lib/server/db";
import {apiError,assertSameOrigin,json,readJson} from "@/lib/server/http";
import {asObject,stringField} from "@/lib/server/validation";
import {dataUrlToBuffer,putBlob} from "@/lib/server/storage";
export const runtime="nodejs";
const categoryDb=(v:string)=>/abrechn|billing/i.test(v)?"billing":/konto|account/i.test(v)?"account":/techn/i.test(v)?"technical":/nutzung|bedien|usage/i.test(v)?"usage":"other";
const priorityDb=(v:string)=>/dring|urgent/i.test(v)?"urgent":/hoch|high/i.test(v)?"high":/niedrig|low/i.test(v)?"low":"normal";
const statusUi=(v:string)=>({open:"Neu",in_progress:"In Bearbeitung",waiting_for_customer:"Warten auf Kunde",resolved:"Gelöst",closed:"Geschlossen"} as Record<string,string>)[v]||v;
type SupportListRow={status:string;[key:string]:unknown};
async function list(c:PoolClient,organizationId:string,id?:string){const params=id?[organizationId,id]:[organizationId];const idSql=id?" and t.id=$2":"";const r=await c.query<SupportListRow>(`select t.id,t.case_number as number,t.category,t.subject,t.description,t.priority,t.status,t.diagnostics,case when t.screenshot_file_id is not null then '/api/support/screenshot/'||t.id::text else null end as screenshot,t.created_at as "createdAt",t.updated_at as "updatedAt",coalesce((select json_agg(json_build_object('id',m.id,'author',coalesce(u.display_name,po.display_name,po.email,m.author_type),'text',m.message,'createdAt',m.created_at) order by m.created_at) from support_messages m left join app_users u on u.id=m.author_user_id left join platform_operator_assignments po on po.user_id=m.author_user_id where m.case_id=t.id and m.visibility='customer'),'[]'::json) messages,coalesce((select json_agg(json_build_object('id',f.id,'fileName',f.original_name,'mimeType',f.content_type,'sizeBytes',f.size_bytes,'href','/api/support/attachments/'||f.id::text) order by f.created_at) from file_objects f where f.support_case_id=t.id),'[]'::json) attachments from support_cases t where t.organization_id=$1${idSql} order by t.updated_at desc`,params);return r.rows.map(x=>({...x,status:statusUi(x.status)}))}
export async function GET(){try{const s=await requireSession();authorize(s,"support:read");return json({items:await withTenant(s.organizationId,s.userId,c=>list(c,s.organizationId))})}catch(e){return apiError(e)}}
export async function POST(request:NextRequest){try{assertSameOrigin(request);const s=await requireSession();authorize(s,"support:write");const b=asObject(await readJson(request,limitsConfig.maxSupportRequestBytes));const category=categoryDb(stringField(b,"category",{max:80}));const subject=stringField(b,"subject",{min:2,max:180});const description=stringField(b,"description",{min:2,max:8000});const priority=priorityDb(stringField(b,"priority",{max:30}));const diagnostics=b.diagnostics&&typeof b.diagnostics==="object"?b.diagnostics:{};const attachmentIds=Array.isArray(b.attachmentIds)?b.attachmentIds.filter(x=>typeof x==="string").slice(0,5):[];const screenshot=typeof b.screenshot==="string"&&b.screenshot.startsWith("data:image/")&&b.screenshot.length<limitsConfig.maxSupportScreenshotDataUrlChars?b.screenshot:null;const id=randomUUID();const item=await withTenant(s.organizationId,s.userId,async c=>{let screenshotFileId:string|null=null;if(screenshot){const file=dataUrlToBuffer(screenshot);if(file.buffer.length>limitsConfig.maxSupportScreenshotBytes)throw new Error("Screenshot ist zu gross.");const fid=randomUUID();const objectKey=`${s.organizationId}/support/screenshots/${fid}.jpg`;const url=await putBlob({path:objectKey,contentType:file.mimeType,body:file.buffer});if(url){screenshotFileId=fid;await c.query(`insert into file_objects(id,organization_id,object_key,original_name,content_type,size_bytes,sha256,scan_status,created_by,blob_url,purpose) values($1,$2,$3,'support-screenshot.jpg',$4,$5,$6,'clean',$7,$8,'support-screenshot')`,[fid,s.organizationId,objectKey,file.mimeType,file.buffer.length,createHash("sha256").update(file.buffer).digest("hex"),s.userId,url])}}const seq=Number((await c.query(`select nextval('support_case_number_seq')::bigint seq`)).rows[0]?.seq);const number=`SUP-${new Date().getFullYear()}-${String(seq).padStart(6,"0")}`;await c.query(`insert into support_cases(id,case_number,organization_id,created_by_user_id,category,subject,description,status,priority,diagnostics,screenshot_file_id,case_type) values($1,$2,$3,$4,$5,$6,$7,'open',$8,$9::jsonb,$10,'support')`,[id,number,s.organizationId,s.userId,category,subject,description,priority,JSON.stringify(diagnostics),screenshotFileId]);if(attachmentIds.length)await c.query(`update file_objects set support_case_id=$1 where organization_id=$2 and purpose='support' and support_case_id is null and id=any($3::uuid[])`,[id,s.organizationId,attachmentIds]);return (await list(c,s.organizationId,id))[0]});return json({item},201)}catch(e){return apiError(e,request)}}
