import Link from "next/link";
import { AppShell } from "./app-shell";
import { Button, Icon, Metric, SectionTitle, Status } from "./ui";

const customers = [
  ["Acme AG","Bauunternehmen","Zürich","Aktiv"], ["Müller GmbH","Immobilien","Bern","Aktiv"], ["Berger Bau AG","Bauunternehmen","Luzern","Aktiv"], ["Huber & Söhne","Elektro","St. Gallen","Aktiv"], ["Schmid Consulting","Beratung","Zug","Inaktiv"], ["Meier Handel AG","Handel","Basel","Aktiv"]
];
const invoices = [
  ["RE-2026-019","Acme AG","12.09.2026","CHF 4’346.40","Bezahlt"], ["RE-2026-018","Müller GmbH","10.09.2026","CHF 1’200.00","Offen"], ["RE-2026-017","Berger Bau AG","08.09.2026","CHF 3’700.00","Überfällig"], ["RE-2026-016","Huber & Söhne","28.08.2026","CHF 950.00","Bezahlt"], ["RE-2026-015","Schmid Consulting","20.08.2026","CHF 1’745.00","Offen"]
];

function tone(s:string): "success"|"danger"|"warning"|"neutral" { return s==="Bezahlt"||s==="Aktiv"||s==="Genehmigt"?"success":s==="Überfällig"||s==="Abgelehnt"?"danger":s==="Offen"||s==="Eingereicht"?"warning":"neutral" as const }

export function DashboardPage(){return <AppShell title="Guten Morgen, Thomas" subtitle="Hier ist die Übersicht zu deinem Unternehmen." active="dashboard" actions={<Button href="/rechnungen" icon="plus">Neue Rechnung</Button>}>
  <div className="metrics-grid"><Metric label="Umsatz im Monat" value="CHF 24’500" hint="+12% zum Vormonat" icon="chart"/><Metric label="Offene Rechnungen" value="CHF 12’800" hint="8 Rechnungen" icon="receipt"/><Metric label="Kunden" value="42" hint="+3 diesen Monat" icon="users"/><Metric label="Zeit diese Woche" value="28:15 h" hint="4 aktive Projekte" icon="clock"/></div>
  <div className="dashboard-grid"><section className="surface"><SectionTitle title="Umsatzentwicklung"/><div className="big-chart">{[42,54,47,68,61,76,70,84,72,90,86,96].map((h,i)=><div key={i}><i style={{height:`${h}%`}}/><span>{["Jan","Feb","Mär","Apr","Mai","Jun","Jul","Aug","Sep","Okt","Nov","Dez"][i]}</span></div>)}</div></section><section className="surface"><SectionTitle title="Letzte Aktivitäten" action={<Link href="/rechnungen">Alle anzeigen</Link>}/><div className="activity-list">{[["Rechnung bezahlt","Acme AG · CHF 4’346.40","receipt"],["Neuer Kunde","Berger Bau AG","users"],["Angebot versendet","Müller GmbH · CHF 3’200.00","file"],["Zeit erfasst","Website Redesign · 4:30 h","clock"]].map(([a,b,c])=><div key={a}><span className="activity-icon"><Icon name={c}/></span><div><b>{a}</b><small>{b}</small></div><Icon name="arrow" size={16}/></div>)}</div></section></div>
  <section><SectionTitle title="Schnellzugriff"/><div className="quick-grid"><Button href="/kunden" variant="secondary" icon="users">Kunde erfassen</Button><Button href="/angebote" variant="secondary" icon="file">Angebot erstellen</Button><Button href="/rechnungen" variant="secondary" icon="receipt">Rechnung erstellen</Button><Button href="/zeit" variant="secondary" icon="clock">Zeit erfassen</Button></div></section>
</AppShell>}

export function CustomersPage(){return <AppShell title="Kunden" subtitle="Kunden, Kontakte und Aktivitäten zentral verwalten." active="kunden" actions={<Button href="/kunden/acme" icon="plus">Neuer Kunde</Button>}><div className="toolbar"><label className="searchbox"><Icon name="search"/><input placeholder="Kunden suchen..."/></label><div className="chips"><button className="active">Alle</button><button>Aktiv</button><button>Inaktiv</button></div></div><div className="records">{customers.map(([name,sector,city,status])=><Link href="/kunden/acme" className="record" key={name}><span className="record-avatar">{name[0]}</span><div className="record-main"><b>{name}</b><small>{sector} · {city}</small></div><Status tone={tone(status)}>{status}</Status><Icon name="arrow" size={17}/></Link>)}</div></AppShell>}

export function CustomerDetail(){return <AppShell title="Acme AG" subtitle="Bauunternehmen · Zürich" active="kunden" actions={<><Button href="/angebote" variant="secondary">Angebot erstellen</Button><Button href="/rechnungen">Rechnung erstellen</Button></>}><div className="tabs"><button className="active">Übersicht</button><button>Kontakte</button><button>Belege</button><button>Notizen</button></div><div className="detail-grid"><section className="surface"><SectionTitle title="Kundendetails"/><dl className="detail-list"><div><dt>Firma</dt><dd>Acme AG</dd></div><div><dt>E-Mail</dt><dd>info@acme.ch</dd></div><div><dt>Telefon</dt><dd>+41 44 123 45 67</dd></div><div><dt>Adresse</dt><dd>Bahnhofstrasse 123<br/>8001 Zürich</dd></div><div><dt>UID</dt><dd>CHE-123.456.789</dd></div></dl></section><section className="surface"><SectionTitle title="Letzte Belege" action={<Link href="/rechnungen">Alle anzeigen</Link>}/><div className="compact-list"><div><b>RE-2026-019</b><span>CHF 4’346.40</span><Status tone="success">Bezahlt</Status></div><div><b>AN-2026-012</b><span>CHF 7’264.32</span><Status tone="warning">Gesendet</Status></div><div><b>RE-2026-015</b><span>CHF 1’200.00</span><Status tone="warning">Offen</Status></div></div></section></div></AppShell>}

export function InvoicesPage(){return <AppShell title="Rechnungen" subtitle="Erstellen, senden und Zahlungsstatus im Blick behalten." active="rechnungen" actions={<Button href="/rechnungen/RE-2026-019" icon="plus">Neue Rechnung</Button>}><div className="toolbar"><label className="searchbox"><Icon name="search"/><input placeholder="Rechnungen suchen..."/></label><div className="chips"><button className="active">Alle</button><button>Offen</button><button>Bezahlt</button><button>Überfällig</button></div></div><div className="records invoices">{invoices.map(([nr,name,date,amount,status])=><Link href="/rechnungen/RE-2026-019" className="record" key={nr}><div className="record-main"><b>{nr}</b><small>{name} · {date}</small></div><strong>{amount}</strong><Status tone={tone(status)}>{status}</Status><Icon name="arrow" size={17}/></Link>)}</div></AppShell>}

export function InvoiceEditor(){return <AppShell title="Rechnung erstellen" subtitle="Entwurf automatisch gespeichert" active="rechnungen" actions={<><Button variant="secondary">Speichern</Button><Button>Vorschau</Button></>}><div className="invoice-workspace"><section className="invoice-form"><div className="form-section"><h2>Kunde</h2><div className="select-card"><div><b>Acme AG</b><small>Bauunternehmen · Zürich</small></div><Icon name="arrow"/></div></div><div className="form-section"><h2>Rechnungsdetails</h2><div className="form-grid"><label>Rechnungsnummer<input defaultValue="RE-2026-019"/></label><label>Rechnungsdatum<input defaultValue="02.10.2026"/></label><label>Zahlungsziel<select defaultValue="30"><option value="30">30 Tage</option></select></label></div></div><div className="form-section"><div className="section-title"><h2>Positionen</h2><button className="text-action">+ Position hinzufügen</button></div><div className="line-items"><div className="line-head"><span>Beschreibung</span><span>Menge</span><span>Preis</span><span>Total</span></div><div><input defaultValue="Website Konzept"/><input defaultValue="24"/><input defaultValue="120.00"/><b>2’880.00</b></div><div><input defaultValue="Design & Umsetzung"/><input defaultValue="12"/><input defaultValue="95.00"/><b>1’140.00</b></div></div><div className="invoice-totals"><span>Zwischentotal <b>CHF 4’020.00</b></span><span>MwSt. 8.1% <b>CHF 326.40</b></span><strong>Total <b>CHF 4’346.40</b></strong></div></div></section><InvoicePreview/></div></AppShell>}

export function InvoicePreview(){return <aside className="invoice-preview"><div className="paper"><div className="paper-brand"><img src="/brand/logo-black.svg" alt="Binso"/><span>RECHNUNG</span></div><div className="paper-meta"><div><b>Acme AG</b><span>Bahnhofstrasse 123</span><span>8001 Zürich</span></div><div><small>Rechnung Nr.</small><b>RE-2026-019</b><small>Datum</small><b>02.10.2026</b></div></div><table><thead><tr><th>Beschreibung</th><th>Menge</th><th>Preis</th><th>Total</th></tr></thead><tbody><tr><td>Website Konzept</td><td>24</td><td>120.00</td><td>2’880.00</td></tr><tr><td>Design & Umsetzung</td><td>12</td><td>95.00</td><td>1’140.00</td></tr></tbody></table><div className="paper-total"><span>Zwischentotal <b>4’020.00</b></span><span>MwSt. 8.1% <b>326.40</b></span><strong>Total CHF <b>4’346.40</b></strong></div><footer>Binso GmbH · Weissbadstrasse 8b · 9050 Appenzell · Schweiz</footer></div></aside>}

export function TimePage(){return <AppShell title="Zeiterfassung" subtitle="Arbeitszeit einfach und präzise erfassen." active="zeit"><div className="time-layout"><section className="surface timer-card"><div className="tabs"><button className="active">Timer</button><button>Einträge</button></div><div className="timer-ring"><div><small>Läuft</small><strong>02:14:27</strong><span>Website Redesign</span><span>Acme AG</span></div></div><Button>Pause</Button></section><section className="surface"><SectionTitle title="Heute" action={<strong>4:28 h</strong>}/><div className="compact-list"><div><b>Website Redesign</b><span>Acme AG</span><strong>2:14</strong></div><div><b>Kundenmeeting</b><span>Müller GmbH</span><strong>1:30</strong></div><div><b>Planung</b><span>Intern</span><strong>0:44</strong></div></div></section></div><div className="running-timer"><span><i/>Zeitmessung läuft · Website Redesign</span><b>02:14:27</b><Button variant="secondary">Stoppen</Button></div></AppShell>}

export function SimpleModule({kind}:{kind:"angebote"|"zahlungen"|"produkte"|"mitarbeiter"|"spesen"|"support"|"einstellungen"}){
 const config={
  angebote:["Angebote","Professionelle Angebote in wenigen Klicks erstellen.",[["AN-2026-012","Acme AG","CHF 7’264.32","Gesendet"],["AN-2026-011","Müller GmbH","CHF 3’200.00","Entwurf"],["AN-2026-010","Berger Bau AG","CHF 9’480.00","Angenommen"]]],
  zahlungen:["Zahlungen","Eingänge und offene Beträge übersichtlich verwalten.",[["02.10.2026","Acme AG","CHF 4’346.40","Verbucht"],["30.09.2026","Müller GmbH","CHF 1’200.00","Verbucht"],["28.09.2026","Schmid Consulting","CHF 1’745.00","Ausstehend"]]],
  produkte:["Produkte","Produkte und Dienstleistungen zentral verwalten.",[["Beratung","Dienstleistung","CHF 120.00","Aktiv"],["Entwicklung","Dienstleistung","CHF 120.00","Aktiv"],["Hosting Paket","Produkt","CHF 25.00","Aktiv"]]],
  mitarbeiter:["Mitarbeiter","Team, Rollen und Stammdaten verwalten.",[["Thomas Müller","Inhaber","100%","Aktiv"],["Sarah Meier","Administration","80%","Aktiv"],["Lukas Weber","Projektleitung","100%","Aktiv"]]],
  spesen:["Spesen","Belege erfassen, prüfen und freigeben.",[["Hotel Schweizerhof","Thomas Müller","CHF 280.00","Eingereicht"],["SBB Zugticket","Sarah Meier","CHF 89.00","Genehmigt"],["Geschäftsessen","Lukas Weber","CHF 120.00","Genehmigt"]]],
  support:["Support","Hilfe direkt in Binso One – persönlich und nachvollziehbar.",[["#5832","Frage zur Rechnung","Offen","vor 12 Min."],["#5828","Zeiterfassung","In Bearbeitung","vor 1 Std."],["#5814","Datenexport","Gelöst","vor 1 Tag"]]],
  einstellungen:["Mehr","Einstellungen und weitere Bereiche.",[["Abonnement","Business · CHF 49 / Monat","Aktiv",""],["Benutzer & Rollen","5 Benutzer","Verwalten",""],["Sicherheit","Passwort & Sitzungen","Öffnen",""],["Benachrichtigungen","E-Mail & Push","Öffnen",""]]]
 } as const;
 const [title,sub,rows]=config[kind];
 return <AppShell title={title} subtitle={sub} active={kind} actions={kind!=="einstellungen"?<Button icon="plus">Neu</Button>:undefined}><div className="records">{rows.map((r)=><div className="record" key={r[0]}><span className="activity-icon"><Icon name={kind==="support"?"support":kind==="produkte"?"box":kind==="zahlungen"?"wallet":kind==="spesen"?"card":kind==="mitarbeiter"?"users":"file"}/></span><div className="record-main"><b>{r[0]}</b><small>{r[1]}</small></div><strong>{r[2]}</strong>{r[3] && <small>{r[3]}</small>}<Icon name="arrow" size={17}/></div>)}</div>{kind==="support"&&<div className="support-composer"><h2>Neues Ticket</h2><div className="form-grid"><label>Betreff<input placeholder="Worum geht es?"/></label><label>Kategorie<select><option>Allgemeine Frage</option><option>Rechnung</option><option>Technisches Problem</option></select></label><label className="full">Nachricht<textarea placeholder="Beschreibe dein Anliegen kurz..."/></label></div><Button>Ticket erstellen</Button></div>}</AppShell>
}
