"use client";
import Link from "next/link";
import {Bell,Headphones,Info,MessageSquarePlus,MonitorSmartphone,Newspaper,RefreshCw} from "lucide-react";
import ThemeToggle from "@/components/ui/theme-toggle";
import {useStandalone} from "@/hooks/use-standalone";
import {useLocale} from "@/components/locale-provider";
import {siteConfig} from "@/lib/site-config";
import {emitAppEvent,appEvents} from "@/lib/client/app-events";

export default function AppUserSettings(){const {t}=useLocale();const standalone=useStandalone();const notificationPermission=typeof Notification!=="undefined"?Notification.permission:"unsupported";return <div className="settings-grid app-settings-grid"><section className="workspace-card"><div className="section-title"><h2>{t("Darstellung und App")}</h2><MonitorSmartphone size={18}/></div><div className="settings-block"><div><strong>{t("Darstellung")}</strong><p>{t("Wähle Hell, Dunkel oder die Systemeinstellung. Die Auswahl gilt für dein Benutzerkonto.")}</p></div><ThemeToggle/></div><div className="app-runtime-grid"><div><span>{t("App-Modus")}</span><strong>{standalone?t("Installierte App (PWA)"):t("Webbrowser")}</strong></div><div><span>{t("Benachrichtigungen")}</span><strong>{notificationPermission==="granted"?t("Erlaubt"):notificationPermission==="denied"?t("Blockiert"):t("Nicht eingerichtet")}</strong></div></div><div className="settings-link-list"><Link href="/benachrichtigungen"><Bell size={17}/><span><strong>{t("Benachrichtigungen verwalten")}</strong><small>{t("Kanäle und Kategorien festlegen")}</small></span></Link><button type="button" onClick={()=>emitAppEvent(appEvents.pwaCheckUpdate)}><RefreshCw size={17}/><span><strong>{t("Auf App-Update prüfen")}</strong><small>{t("Verfügbare Version laden und App aktualisieren")}</small></span></button></div></section><aside className="workspace-card about-binso-card"><div className="section-title"><h2>{t("Über Binso One")}</h2><Info size={18}/></div><dl className="support-meta"><div><dt>{t("Version")}</dt><dd>{siteConfig.version}</dd></div><div><dt>{t("Build")}</dt><dd>{siteConfig.buildCommit}</dd></div><div><dt>{t("Betrieb")}</dt><dd>Microsoft Azure · Switzerland North</dd></div></dl><div className="settings-link-list"><Link href="/neuigkeiten"><Newspaper size={17}/><span><strong>{t("Neu in Binso One")}</strong><small>{t("Releases und Verbesserungen")}</small></span></Link><Link href="/support"><Headphones size={17}/><span><strong>{t("Support")}</strong><small>{t("Supporttickets und Antworten")}</small></span></Link><Link href="/support/neu"><MessageSquarePlus size={17}/><span><strong>{t("Supportticket erstellen")}</strong><small>{t("Version und technische Basisinformationen werden automatisch angehängt")}</small></span></Link></div></aside></div>}
