"use client";

import { useMemo, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import Link from "next/link";
import { ArrowRight, Check, Eye, EyeOff } from "lucide-react";
import { createAccount, createDemoAccount, login, plans, type BillingCycle, type PlanId } from "@/lib/saas-store";
import { notify } from "@/lib/notify";
import { apiFetch, isProductionMode } from "@/lib/client/runtime";

import { LanguageSwitcher } from "@/components/locale-provider";
import BrandLogo from "@/components/ui/brand-logo";
function AuthFrame({title,text,children}:{title:string;text:string;children:React.ReactNode}){
 return <div className="auth-shell"><Link href="/" className="auth-logo auth-logo-image" aria-label="Binso One"><BrandLogo/></Link><div className="auth-language"><LanguageSwitcher compact /></div><div className="auth-card"><div className="auth-intro"><h1>{title}</h1><p>{text}</p></div>{children}</div><p className="auth-foot">{isProductionMode()?"Sichere Anmeldung · Binso One":"Lokale Entwicklungsumgebung · keine echten Zahlungen"}</p></div>
}

export function LoginPage(){
 const router=useRouter(); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [mfaCode,setMfaCode]=useState(""); const [mfaRequired,setMfaRequired]=useState(false); const [show,setShow]=useState(false); const [error,setError]=useState("");
 async function submit(e:React.FormEvent){e.preventDefault();setError("");if(!email.trim()||!password){setError("Bitte prüfen Sie die markierten Pflichtfelder.");notify("Bitte prüfen Sie die markierten Pflichtfelder.","danger");return}try{if(isProductionMode()){const result=await apiFetch<{onboardingComplete?:boolean;mfaRequired?:boolean}>("/api/auth/login",{method:"POST",body:JSON.stringify({email,password,mfaCode:mfaRequired?mfaCode:undefined})});if(result.mfaRequired){setMfaRequired(true);return}router.push(result.onboardingComplete?"/dashboard":"/onboarding")}else{const {org}=login(email,password);router.push(org.onboardingComplete?"/dashboard":"/onboarding")}}catch(e){setError(e instanceof Error?e.message:"Anmeldung fehlgeschlagen.")}}
 return <AuthFrame title="Willkommen zurück" text="Melde dich bei deiner Firma an."><form onSubmit={submit} className="auth-form"><label><span>E-Mail *</span><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label><span>Passwort *</span><div className="password-input"><input type={show?"text":"password"} value={password} onChange={e=>setPassword(e.target.value)} required/><button type="button" onClick={()=>setShow(v=>!v)}>{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></label>{mfaRequired&&<label><span>MFA-Code *</span><input inputMode="numeric" autoComplete="one-time-code" value={mfaCode} onChange={e=>setMfaCode(e.target.value)} placeholder="6-stelliger Code oder Recovery-Code" required/></label>}{error&&<div className="auth-error">{error}</div>}<button className="marketing-primary auth-submit">{mfaRequired?"MFA bestätigen":"Anmelden"} <ArrowRight size={16}/></button><div className="auth-links"><Link href="/passwort-vergessen">Passwort vergessen?</Link><span>Noch kein Konto?</span><Link href="/registrieren">Registrieren</Link></div></form><div className="demo-login-note"><strong>Lokale Demo</strong><span>Demo über die Landingpage öffnen oder mit demo@binso.local / demo1234 anmelden.</span></div></AuthFrame>
}

export function RegisterPage(){
 const router=useRouter(); const params=useSearchParams(); const initial=(params.get("plan") as PlanId)||"business"; const trial=params.get("trial")==="1";
 const [plan,setPlan]=useState<PlanId>(["start","business","pro"].includes(initial)?initial:"business"); const [billing,setBilling]=useState<BillingCycle>("monthly"); const [v,setV]=useState({name:"",company:"",email:"",password:""}); const [accepted,setAccepted]=useState(false); const [error,setError]=useState("");
 const selected=useMemo(()=>plans.find(p=>p.id===plan)!,[plan]);
 async function submit(e:React.FormEvent){e.preventDefault();setError("");if(!v.name.trim()||!v.company.trim()||!v.email.trim()||v.password.length<(isProductionMode()?12:8)||!accepted){setError("Bitte prüfen Sie die markierten Pflichtfelder.");notify("Bitte prüfen Sie die markierten Pflichtfelder.","danger");return}if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v.email)){setError("Ungültige E-Mail-Adresse.");notify("Ungültige E-Mail-Adresse.","danger");return}try{if(isProductionMode()){await apiFetch("/api/auth/register",{method:"POST",body:JSON.stringify({...v,plan,billingCycle:billing,trial,acceptedTerms:true,termsVersion:"2026-09-29",privacyVersion:"2026-09-29"})})}else{createAccount({...v,plan,billingCycle:billing,trial})}router.push(trial?"/onboarding":`/checkout?plan=${plan}&billing=${billing}`)}catch(e){setError(e instanceof Error?e.message:"Registrierung fehlgeschlagen.")}}
 return <AuthFrame title={trial?"Kostenlos testen":"Konto erstellen"} text={trial?"14 Tage mit allen Business-Funktionen testen.":"Plan wählen, Firma anlegen und direkt mit dem Onboarding starten."}><form onSubmit={submit} className="auth-form"><div className="plan-picker">{plans.map(p=><button type="button" key={p.id} className={plan===p.id?"selected":""} onClick={()=>setPlan(p.id)}><strong>{p.name}</strong><span>CHF {p.monthly}/Mt.</span></button>)}</div><div className="billing-toggle"><button type="button" className={billing==="monthly"?"active":""} onClick={()=>setBilling("monthly")}>Monatlich</button><button type="button" className={billing==="yearly"?"active":""} onClick={()=>setBilling("yearly")}>Jährlich · 2 Monate gratis</button></div><label><span>Name *</span><input value={v.name} onChange={e=>setV(x=>({...x,name:e.target.value}))} required/></label><label><span>Firma *</span><input value={v.company} onChange={e=>setV(x=>({...x,company:e.target.value}))} required/></label><label><span>Geschäftliche E-Mail *</span><input type="email" value={v.email} onChange={e=>setV(x=>({...x,email:e.target.value}))} required/></label><label><span>Passwort *</span><input type="password" minLength={8} value={v.password} onChange={e=>setV(x=>({...x,password:e.target.value}))} required/></label><label className="auth-legal-consent"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)} required/><span>Ich akzeptiere die <Link href="/agb" target="_blank">AGB</Link> und habe die <Link href="/datenschutz" target="_blank">Datenschutzerklärung</Link> gelesen.</span></label>{error&&<div className="auth-error">{error}</div>}<div className="selected-plan-summary"><div><strong>{selected.name}</strong><span>{billing==="monthly"?`CHF ${selected.monthly} / Monat`:`CHF ${selected.yearly} / Jahr`}</span></div>{trial&&<em>14 Tage kostenlos</em>}</div><button className="marketing-primary auth-submit">{trial?"Testorganisation erstellen":"Weiter zur Zahlung"} <ArrowRight size={16}/></button><small className="auth-terms">Die Zustimmung wird im Produktivbetrieb mit der jeweiligen Dokumentversion protokolliert.</small></form></AuthFrame>
}

export function DemoPage(){
 const router=useRouter(); const [loading,setLoading]=useState(false);
 function open(){setLoading(true);const {org}=createDemoAccount();router.push(org.onboardingComplete?"/dashboard":"/onboarding")}
 return <AuthFrame title="Binso One Demo" text="Öffne eine vorbereitete Testfirma und spiele den kompletten Ablauf lokal durch."><div className="demo-benefits">{["Keine Registrierung nötig","Vorkonfigurierte Business-Funktionen","Daten bleiben nur in deinem Browser","Jederzeit zurücksetzbar"].map(x=><span key={x}><Check size={16}/>{x}</span>)}</div><button className="marketing-primary auth-submit" onClick={open} disabled={loading}>{loading?"Demo wird vorbereitet …":"Demo öffnen"} <ArrowRight size={16}/></button><Link className="marketing-secondary auth-submit" href="/registrieren?trial=1">Eigene Testfirma erstellen</Link></AuthFrame>
}
