"use client";

import Link from "next/link";
import { useSearchParams, useRouter } from "next/navigation";
import { useState } from "react";
import { Check, LockKeyhole } from "lucide-react";
import { getSession, plans, type BillingCycle, type PlanId, updateOrganization } from "@/lib/saas-store";
import { notify } from "@/lib/notify";
import { apiFetch, isProductionMode } from "@/lib/client/runtime";

import { LanguageSwitcher } from "@/components/locale-provider";
import BrandLogo from "@/components/ui/brand-logo";
export default function CheckoutPage(){
 const params=useSearchParams();const router=useRouter();const [card,setCard]=useState({name:"",number:"",expiry:"",cvc:""});const [error,setError]=useState("");const planId=(params.get("plan") as PlanId)||"business";const billing=(params.get("billing") as BillingCycle)||"monthly";const plan=plans.find(p=>p.id===planId)||plans[1];const price=billing==="yearly"?plan.yearly:plan.monthly;
 async function pay(){setError("");try{if(isProductionMode()){const result=await apiFetch<{url:string}>("/api/billing/checkout",{method:"POST",body:JSON.stringify({plan:plan.id,billing})});window.location.assign(result.url);return}if(!card.name.trim()||card.number.replace(/\s/g,"").length<12||!card.expiry.trim()||card.cvc.length<3){setError("Bitte prüfen Sie die markierten Pflichtfelder.");notify("Bitte prüfen Sie die markierten Pflichtfelder.","danger");return}const session=getSession();if(!session){router.push("/registrieren");return}updateOrganization(session.orgId,{plan:plan.id,billingCycle:billing,subscriptionStatus:"active"});notify("Zahlung wurde im Demo-Modus erfolgreich simuliert.");router.push("/onboarding")}catch(e){setError(e instanceof Error?e.message:"Checkout konnte nicht gestartet werden.")}}
 return <div className="checkout-shell"><div className="checkout-language"><LanguageSwitcher compact/></div><div className="checkout-wrap"><section className="checkout-main"><Link href="/" className="auth-logo auth-logo-image" aria-label="Binso One"><BrandLogo/></Link><h1>Abo abschliessen</h1><p>Lokale Zahlungssimulation für den vollständigen Registrierungsflow.</p><div className="workspace-card checkout-form"><div className="section-title"><h2>{isProductionMode()?"Sichere Zahlung":"Zahlungsdaten"}</h2><span><LockKeyhole size={14}/>{isProductionMode()?" Stripe":" Demo"}</span></div>{isProductionMode()?<p className="field-help">Die Kartendaten werden direkt bei Stripe erfasst und nicht von Binso One gespeichert.</p>:<><label><span>Karteninhaber</span><input required placeholder="Max Muster" value={card.name} onChange={e=>setCard(x=>({...x,name:e.target.value}))}/></label><label><span>Kartennummer</span><input required inputMode="numeric" placeholder="4242 4242 4242 4242" value={card.number} onChange={e=>setCard(x=>({...x,number:e.target.value}))}/></label><div className="form-grid"><label><span>Gültig bis</span><input required placeholder="12/30" value={card.expiry} onChange={e=>setCard(x=>({...x,expiry:e.target.value}))}/></label><label><span>CVC</span><input required inputMode="numeric" placeholder="123" value={card.cvc} onChange={e=>setCard(x=>({...x,cvc:e.target.value}))}/></label></div></>}{error&&<div className="form-error-summary">{error}</div>}<button className="marketing-primary auth-submit" onClick={pay}>{isProductionMode()?"Weiter zu Stripe":"Zahlung simulieren und fortfahren"}</button><small>{isProductionMode()?"Abrechnung über Stripe Checkout.":"Es wird keine echte Zahlung verarbeitet."}</small></div></section><aside className="checkout-summary"><div className="workspace-card"><h2>{plan.name}</h2><p>{plan.description}</p><div className="checkout-price"><strong>CHF {price}</strong><span>{billing==="yearly"?"/ Jahr":"/ Monat"}</span></div>{plan.features.map(f=><span className="checkout-feature" key={f}><Check size={15}/>{f}</span>)}</div></aside></div></div>
}
