"use client";
import {useEffect,useRef,useState} from "react";
import {AppShell} from "./app-shell";
import { Button, Field, Toast, Select, Input, Textarea, FormActions } from "./ui";
import {apiGet,apiPatch,isProductionBackendEnabled} from "@/lib/client/backend";
export function DocumentSettingsPage(){
 const [editing,setEditing]=useState(false),[toast,setToast]=useState<string|null>(null);
 const [loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[saving,setSaving]=useState(false);
 const busy=useRef(false);
 const [vatRate,setVatRate]=useState("8.1"),[terms,setTerms]=useState("30"),[iban,setIban]=useState(""),[qrIban,setQrIban]=useState("");
 const [invoiceIntro,setInvoiceIntro]=useState(""),[invoiceFooter,setInvoiceFooter]=useState(""),[quoteIntro,setQuoteIntro]=useState(""),[quoteFooter,setQuoteFooter]=useState("");
 useEffect(()=>{if(!isProductionBackendEnabled()){queueMicrotask(()=>setLoading(false));return;}apiGet<{item:Record<string,unknown>}>("/api/settings/documents").then(({item})=>queueMicrotask(()=>{setVatRate(String(item.vat_rate??"8.1"));setTerms(String(item.payment_terms_days??"30"));setIban(String(item.iban??""));setQrIban(String(item.qr_iban??""));setInvoiceIntro(String(item.invoice_intro_text??""));setInvoiceFooter(String(item.invoice_footer_text??""));setQuoteIntro(String(item.quote_intro_text??""));setQuoteFooter(String(item.quote_footer_text??""))})).catch(e=>setError(e instanceof Error?e.message:"Einstellungen konnten nicht geladen werden.")).finally(()=>setLoading(false))},[]);
 const save=async()=>{if(loading||error||busy.current)return;busy.current=true;setSaving(true);try{if(!isProductionBackendEnabled())throw new Error("Die Vorschau ist schreibgeschützt.");await apiPatch("/api/settings/documents",{vatRate:Number(vatRate),paymentTermsDays:Number(terms),iban,qrIban,invoiceIntroText:invoiceIntro,invoiceFooterText:invoiceFooter,quoteIntroText:quoteIntro,quoteFooterText:quoteFooter});setEditing(false);setToast("Dokumenteinstellungen gespeichert.")}catch(e){setToast(e instanceof Error?e.message:"Einstellungen konnten nicht gespeichert werden.")}finally{busy.current=false;setSaving(false)}window.setTimeout(()=>setToast(null),2400)};
 return <AppShell title="Rechnungen und Dokumente" subtitle="Standardwerte für neue Angebote und Rechnungen." active="einstellungen" editing={editing} unsavedChanges={editing} backHref="/einstellungen" backLabel="Einstellungen" actions={!editing?<Button requiresWrite disabled={loading||!!error} variant="secondary" icon="edit" onClick={()=>setEditing(true)}>Bearbeiten</Button>:undefined}>
  {loading?<p role="status">Einstellungen werden geladen …</p>:error?<div role="alert"><p>{error}</p><Button variant="secondary" onClick={()=>window.location.reload()}>Erneut versuchen</Button></div>:<div className="settings-detail-grid">{editing?<section className="settings-form"><div className="form-grid two"><Field label="Standard-MwSt."><Select value={vatRate} onChange={e=>setVatRate(e.target.value)}><option value="8.1">8.1%</option><option value="2.6">2.6%</option><option value="0">0%</option></Select></Field><Field label="Standard-Zahlungsfrist"><Select value={terms} onChange={e=>setTerms(e.target.value)}><option value="10">10 Tage</option><option value="30">30 Tage</option><option value="45">45 Tage</option><option value="60">60 Tage</option></Select></Field><Field label="IBAN"><Input value={iban} onChange={e=>setIban(e.target.value)}/></Field><Field label="QR-IBAN"><Input value={qrIban} onChange={e=>setQrIban(e.target.value)}/></Field><Field label="Rechnung – Einleitung" className="full"><Textarea value={invoiceIntro} onChange={e=>setInvoiceIntro(e.target.value)}/></Field><Field label="Rechnung – Schlusstext" className="full"><Textarea value={invoiceFooter} onChange={e=>setInvoiceFooter(e.target.value)}/></Field><Field label="Angebot – Einleitung" className="full"><Textarea value={quoteIntro} onChange={e=>setQuoteIntro(e.target.value)}/></Field><Field label="Angebot – Schlusstext" className="full"><Textarea value={quoteFooter} onChange={e=>setQuoteFooter(e.target.value)}/></Field></div><FormActions ><Button requiresWrite disabled={loading||!!error||saving} onClick={()=>void save()}>{saving?"Wird gespeichert…":"Speichern"}</Button></FormActions></section>:<section className="settings-readonly"><dl className="detail-list"><div><dt>Standard-MwSt.</dt><dd>{vatRate}%</dd></div><div><dt>Standard-Zahlungsfrist</dt><dd>{terms} Tage</dd></div><div><dt>IBAN</dt><dd>{iban||"—"}</dd></div><div><dt>QR-IBAN</dt><dd>{qrIban||"—"}</dd></div><div><dt>Rechnungstexte</dt><dd>{invoiceIntro||invoiceFooter?"Konfiguriert":"—"}</dd></div><div><dt>Angebotstexte</dt><dd>{quoteIntro||quoteFooter?"Konfiguriert":"—"}</dd></div></dl></section>}</div>}{toast&&<Toast title={toast} tone={toast==="Dokumenteinstellungen gespeichert."?"success":"danger"}/>}
 </AppShell>
}