"use client";
import {useEffect,useState} from "react";
import {AppShell} from "./app-shell";
import {Button,Field,Toast} from "./ui";
import {apiGet,apiPatch,isProductionBackendEnabled} from "@/lib/client/backend";
export function DocumentSettingsPage(){
 const [editing,setEditing]=useState(false),[toast,setToast]=useState<string|null>(null);
 const [vatRate,setVatRate]=useState("8.1"),[terms,setTerms]=useState("30"),[iban,setIban]=useState(""),[qrIban,setQrIban]=useState("");
 const [invoiceIntro,setInvoiceIntro]=useState(""),[invoiceFooter,setInvoiceFooter]=useState(""),[quoteIntro,setQuoteIntro]=useState(""),[quoteFooter,setQuoteFooter]=useState("");
 useEffect(()=>{if(!isProductionBackendEnabled())return;apiGet<{item:Record<string,unknown>}>("/api/settings/documents").then(({item})=>queueMicrotask(()=>{setVatRate(String(item.vat_rate??"8.1"));setTerms(String(item.payment_terms_days??"30"));setIban(String(item.iban??""));setQrIban(String(item.qr_iban??""));setInvoiceIntro(String(item.invoice_intro_text??""));setInvoiceFooter(String(item.invoice_footer_text??""));setQuoteIntro(String(item.quote_intro_text??""));setQuoteFooter(String(item.quote_footer_text??""))})).catch(()=>undefined)},[]);
 const save=async()=>{try{if(isProductionBackendEnabled())await apiPatch("/api/settings/documents",{vatRate:Number(vatRate),paymentTermsDays:Number(terms),iban,qrIban,invoiceIntroText:invoiceIntro,invoiceFooterText:invoiceFooter,quoteIntroText:quoteIntro,quoteFooterText:quoteFooter});setEditing(false);setToast("Dokumenteinstellungen gespeichert.")}catch(e){setToast(e instanceof Error?e.message:"Einstellungen konnten nicht gespeichert werden.")}window.setTimeout(()=>setToast(null),2400)};
 return <AppShell title="Rechnungen und Dokumente" subtitle="Standardwerte für neue Angebote und Rechnungen." active="einstellungen" backHref="/einstellungen" backLabel="Einstellungen" actions={editing?<Button onClick={()=>void save()}>Speichern</Button>:<Button variant="secondary" icon="edit" onClick={()=>setEditing(true)}>Bearbeiten</Button>}>
  <div className="settings-detail-grid">{editing?<section className="settings-form"><div className="form-grid two"><Field label="Standard-MwSt."><select value={vatRate} onChange={e=>setVatRate(e.target.value)}><option value="8.1">8.1%</option><option value="2.6">2.6%</option><option value="0">0%</option></select></Field><Field label="Standard-Zahlungsziel"><select value={terms} onChange={e=>setTerms(e.target.value)}><option value="10">10 Tage</option><option value="30">30 Tage</option><option value="45">45 Tage</option><option value="60">60 Tage</option></select></Field><Field label="IBAN"><input value={iban} onChange={e=>setIban(e.target.value)}/></Field><Field label="QR-IBAN"><input value={qrIban} onChange={e=>setQrIban(e.target.value)}/></Field><Field label="Rechnung – Einleitung" className="full"><textarea value={invoiceIntro} onChange={e=>setInvoiceIntro(e.target.value)}/></Field><Field label="Rechnung – Schlusstext" className="full"><textarea value={invoiceFooter} onChange={e=>setInvoiceFooter(e.target.value)}/></Field><Field label="Angebot – Einleitung" className="full"><textarea value={quoteIntro} onChange={e=>setQuoteIntro(e.target.value)}/></Field><Field label="Angebot – Schlusstext" className="full"><textarea value={quoteFooter} onChange={e=>setQuoteFooter(e.target.value)}/></Field></div><div className="mobile-sticky-save"><Button onClick={()=>void save()}>Speichern</Button></div></section>:<section className="settings-readonly"><dl className="detail-list"><div><dt>Standard-MwSt.</dt><dd>{vatRate}%</dd></div><div><dt>Standard-Zahlungsziel</dt><dd>{terms} Tage</dd></div><div><dt>IBAN</dt><dd>{iban||"—"}</dd></div><div><dt>QR-IBAN</dt><dd>{qrIban||"—"}</dd></div><div><dt>Rechnungstexte</dt><dd>{invoiceIntro||invoiceFooter?"Konfiguriert":"—"}</dd></div><div><dt>Angebotstexte</dt><dd>{quoteIntro||quoteFooter?"Konfiguriert":"—"}</dd></div></dl></section>}</div>{toast&&<Toast title={toast} tone={toast.includes("konnten")?"danger":"success"}/>}
 </AppShell>
}