"use client";
import {usePathname} from "next/navigation";
import Link from "next/link";
import {financialStatus,financialStatusLabels,documentDateLabel,formatCurrency,type FinancialDocument} from '@/lib/financial-status';
import {RecordsView,RecordRow} from './records';
export type DocumentListItem=FinancialDocument&{id?:string};
export function DocumentList({items,kind,loading=false,error=null,context='default'}:{items:DocumentListItem[];kind?:'offer'|'invoice';loading?:boolean;error?:string|null;context?:'default'|'customer'}){
 const rows=items.filter(item=>!kind||item.kind===kind).map(item=>[item.number??'',item.customer?.name??'',documentDateLabel(item),formatCurrency(item.total,item.currency),item.kind==='offer'?'Angebot':'Rechnung',financialStatusLabels[financialStatus(item)]??item.status??'']);
 const href=(row:string[])=>`${row[4]==='Angebot'?'/angebote/':'/rechnungen/'}${encodeURIComponent(row[0])}`;
 const label=kind==='invoice'?'Rechnungen':kind==='offer'?'Angebote':context==='customer'?'Einträge':'Finanzen';
 const placeholder=context==='customer'?'Angebote und Rechnungen suchen...':`${label} suchen...`;
 return <RecordsView items={rows} typeIndex={4} loading={loading} error={error} placeholder={placeholder} countLabel={label} chips={kind==='invoice'?['Alle','Entwurf','Offen','Überfällig','Bezahlt']:kind==='offer'?['Alle','Entwurf','Versendet','Angenommen','Abgelehnt','Abgelaufen']:['Alle','Angebote','Rechnungen']} statusGroups={{Offen:['Teilweise bezahlt','Überfällig']}} emptyLabel={chip=>chip==='Alle'?`Keine ${context==='customer'?'Angebote oder Rechnungen':label} erfasst`:kind==='invoice'?`Keine ${({'Entwurf':'Rechnungsentwürfe','Offen':'offenen Rechnungen','Überfällig':'überfälligen Rechnungen','Bezahlt':'bezahlten Rechnungen'} as Record<string,string>)[chip]??'Rechnungen'}`:kind==='offer'?({'Entwurf':'Keine Angebotsentwürfe','Versendet':'Keine versendeten Angebote','Angenommen':'Keine angenommenen Angebote','Abgelehnt':'Keine abgelehnten Angebote','Abgelaufen':'Keine abgelaufenen Angebote'} as Record<string,string>)[chip]??'Keine Angebote':`Keine ${chip.toLowerCase()} erfasst`} columns={[{label:'Nummer',index:0},{label:'Kunde',index:1},{label:'Datum / Fälligkeit',index:2},{label:'Betrag',index:3,align:'right'},{label:'Status',index:5,status:true}]} rowHref={href}>{row=><RecordRow href={href(row)} icon={row[4]==='Angebot'?'file':'receipt'} title={row[0]} meta={[row[1],row[2]].filter(Boolean).join(' · ')} value={row[3]} status={row[5]}/>}</RecordsView>;
}
export function FinanceTabs(){const path=usePathname();return <nav className="tabs" aria-label="Finanzen"><Link href="/finanzen" className={path==="/finanzen"?"active":""} aria-current={path==="/finanzen"?"page":undefined}>Übersicht</Link><Link href="/angebote" className={path==="/angebote"?"active":""} aria-current={path==="/angebote"?"page":undefined}>Angebote</Link><Link href="/rechnungen" className={path==="/rechnungen"?"active":""} aria-current={path==="/rechnungen"?"page":undefined}>Rechnungen</Link><Link href="/zahlungen" className={path==="/zahlungen"?"active":""} aria-current={path==="/zahlungen"?"page":undefined}>Zahlungen</Link></nav>;}
