"use client";

import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import {relationId} from "@/lib/relationships";
import {ArrowLeft,CheckCircle2,Copy,Eye,FilePlus2,Mail,Pencil,Plus,Printer,Save,Send,Trash2} from "lucide-react";
import {getModule} from "@/lib/modules";
import {getDemoModuleSeed} from "@/lib/demo/module-seeds";
import {defaultSettings,ensureSeedOverride,findSeedOverride,getLocalRecord,money,type LocalRecord} from "@/lib/local-store";
import {createAppRecord,getAppRecord,updateAppRecord} from "@/lib/client/data-service";
import {apiFetch,isProductionMode} from "@/lib/client/runtime";
import {loadOrganizationSettings} from "@/lib/client/organization-settings";
import {notify} from "@/lib/notify";
import {usePermissions} from "@/lib/client/use-permissions";
import ResponsiveOverlay from "@/components/ui/responsive-overlay";
import {Button} from "@/components/ui/button";
import {useLocale} from "@/components/locale-provider";
import {createDocumentNumber} from "@/lib/document-number";
import {domainConfig,isoDate} from "@/config/domain";
import {Input,Select,Textarea} from "@/components/ui/form-controls";
import {IconButton} from "@/components/ui/icon-button";
import {calculateDocumentTotals,type DocumentPosition} from "@/lib/documents/calculations";
import {createBlankDocumentPosition,initialDocumentPositions} from "@/lib/documents/defaults";

export default function DocumentDetail({kind,id}:{kind:"rechnung"|"offerte";id:string}){
 const router=useRouter();const permissions=usePermissions();const {t}=useLocale();const isInvoice=kind==="rechnung";const moduleKey=isInvoice?"rechnungen":"offerten";const canWrite=permissions.canModule(moduleKey,"write");const config=getModule(moduleKey);
 const seedIndex=Math.max(0,Number(id)-1);const demoRows=isProductionMode()?[]:getDemoModuleSeed(moduleKey).rows;const seed=demoRows[seedIndex]||demoRows[0]||[];
 const [rec,setRec]=useState<LocalRecord>();const [settings,setSettings]=useState(defaultSettings);const [editing,setEditing]=useState(false);const [previewOpen,setPreviewOpen]=useState(false);
 const [loading,setLoading]=useState(true);const [partialOpen,setPartialOpen]=useState(false);const [partialAmount,setPartialAmount]=useState("");const [partialError,setPartialError]=useState("");
 const [editCustomer,setEditCustomer]=useState(seed[1]||"");const [editDate,setEditDate]=useState("");const [editDue,setEditDue]=useState(seed[2]||"");const [editIntro,setEditIntro]=useState("");const [editPositions,setEditPositions]=useState<DocumentPosition[]>(()=>initialDocumentPositions(!isProductionMode()));const [editDiscount,setEditDiscount]=useState(0);
 useEffect(()=>{let active=true;const timer=window.setTimeout(()=>{void(async()=>{const r=isProductionMode()?await getAppRecord(id):(id.startsWith("local-")?getLocalRecord(id):findSeedOverride(moduleKey,id));if(active){if(r)setRec(r);setSettings(await loadOrganizationSettings());setLoading(false)}})()},0);return()=>{active=false;window.clearTimeout(timer)}},[id,moduleKey]);
 const customer=rec?.fields.Kunde||seed[1]||"Kunde";const number=rec?.fields.Nummer||seed[0]||`${isInvoice?"R":"O"}-${new Date().getFullYear()}-0001`;const status=rec?.status||seed[4]||"Offen";const positions=rec?.positions||initialDocumentPositions(!isProductionMode());const discount=Number(rec?.meta?.discount||0);
 const totals=useMemo(()=>calculateDocumentTotals(positions,discount),[positions,discount]);
 async function ensure(){if(rec)return rec;if(isProductionMode()){notify(t("Dokument wurde nicht gefunden."),"danger");return undefined}const fields={Nummer:number,Kunde:customer,Datum:isoDate(),[isInvoice?"Fällig":"Gültig bis"]:seed[2]||"",Betrag:money(totals.gross),Status:status,Einleitung:t(isInvoice?"Besten Dank. Nachfolgend finden Sie unsere Rechnung.":"Besten Dank. Nachfolgend finden Sie unsere Offerte.")};const r=ensureSeedOverride(moduleKey,id,[number,customer,seed[2]||"",money(totals.gross),status],fields);const fresh=await updateAppRecord(r.id,{positions,meta:{...(r.meta||{}),net:totals.net,vat:totals.vat,gross:totals.gross}});setRec(fresh||r);return fresh||r}
 async function patchStatus(nextStatus:string){if(!canWrite)return;const current=await ensure();if(!current)return;const u=await updateAppRecord(current.id,{status:nextStatus,row:[...current.row.slice(0,4),nextStatus],fields:{...current.fields,Status:nextStatus}});if(u)setRec(u);notify(`${t("Status auf")} «${t(nextStatus)}» ${t("gesetzt.")}`)}
 async function send(){if(!canWrite)return;const current=await ensure();if(!current)return;const nextStatus=isInvoice?"Offen":"Versendet";await patchStatus(nextStatus);const to=current.fields["E-Mail"]||String((current.meta?.customerSnapshot as Record<string,unknown>|undefined)?.email||"");if(isProductionMode()&&to){try{const result=await apiFetch<{delivered:boolean}>("/api/email/document",{method:"POST",body:JSON.stringify({module:moduleKey,to,subject:`${t(isInvoice?"Rechnung":"Offerte")} ${number} – ${settings.companyName}`,message:`${t("Guten Tag")}\n\n${t(isInvoice?"Sie erhalten die Rechnung":"Sie erhalten die Offerte")} ${number}.\n\n${t("Freundliche Grüsse")}\n${settings.companyName}`,number})});notify(result.delivered?t("E-Mail wurde versendet."):t("Dokument gespeichert. E-Mail-Dienst ist noch nicht konfiguriert."),result.delivered?"success":"info")}catch(e){notify(e instanceof Error?e.message:t("E-Mail-Versand fehlgeschlagen."),"danger")}}else if(!isProductionMode())notify(`${t("Demo-Versand von")} ${number} ${t("ausgeführt.")}`)}
 async function duplicate(){if(!canWrite)return;const n=createDocumentNumber(isInvoice?"R":"O");const copy=await createAppRecord({module:moduleKey,status:"Entwurf",row:[n,customer,rec?.fields[isInvoice?"Fällig":"Gültig bis"]||seed[2]||"",money(totals.gross),"Entwurf"],fields:{...(rec?.fields||{}),Nummer:n,Kunde:customer,Betrag:money(totals.gross),Status:"Entwurf"},positions,meta:{...(rec?.meta||{}),sourceDocument:number}});notify(t("Kopie als Entwurf erstellt."));router.push(`/${moduleKey}/${copy.id}`)}
 async function convert(){if(!canWrite)return;const current=await ensure();if(!current)return;const order=await createAppRecord({module:"auftraege",status:"Bereit",row:[`Auftrag aus ${number}`,customer,"–",money(totals.gross),"Bereit"],fields:{Auftrag:`Auftrag aus ${number}`,Kunde:customer,Projekt:"–",Volumen:money(totals.gross),Status:"Bereit"},positions,meta:{relations:{customerId:relationId(current,"customerId"),offerId:current.id},sourceOffer:number}});await patchStatus("Angenommen");notify(t("Offerte angenommen und Auftrag erstellt."));router.push(`/auftraege/${order.id}`)}
 async function reject(){await patchStatus("Abgelehnt")}
 async function remind(){if(!canWrite)return;const current=await ensure();if(!current)return;const level=Number(current.meta?.reminderLevel||0)+1;const u=await updateAppRecord(current.id,{meta:{...(current.meta||{}),reminderLevel:level,lastReminder:new Date().toISOString()}});if(u)setRec(u);notify(`${t("Mahnung")} ${level} ${t("wurde vorbereitet.")}`)}
 function openPartial(){if(!canWrite)return;setPartialAmount(String(Math.max(0,Math.round(remaining||totals.gross/2))));setPartialError("");setPartialOpen(true)}
 async function savePartial(){if(!canWrite)return;const amount=Number(partialAmount.replace(",","."));if(!Number.isFinite(amount)||amount<=0){setPartialError(t("Bitte geben Sie einen gültigen Betrag ein."));return}const current=await ensure();if(!current)return;const paid=Number(current.meta?.paidAmount||0)+amount;const newStatus=paid>=totals.gross?"Bezahlt":"Teilbezahlt";const u=await updateAppRecord(current.id,{status:newStatus,row:[...current.row.slice(0,4),newStatus],fields:{...current.fields,Status:newStatus},meta:{...(current.meta||{}),paidAmount:paid}});if(u)setRec(u);const paymentDate=isoDate();await createAppRecord({module:"zahlungen",status:"Zugeordnet",row:[paymentDate,customer,`PAY-${number}`,money(amount),"Zugeordnet"],fields:{Datum:paymentDate,Zahler:customer,Referenz:`PAY-${number}`,Betrag:money(amount),Rechnung:number,Zuordnung:"Zugeordnet"},meta:{relations:{invoiceId:current.id,customerId:relationId(current,"customerId")},invoice:number}});setPartialOpen(false);notify(`${money(amount)} ${t("als Zahlung erfasst.")}`)}
 async function recurring(){if(!canWrite)return;const current=await ensure();if(!current)return;const enabled=!Boolean(current.meta?.recurring);const u=await updateAppRecord(current.id,{meta:{...(current.meta||{}),recurring:enabled,recurrence:"monatlich"}});if(u)setRec(u);notify(t(enabled?"Monatliche Wiederholung aktiviert.":"Wiederholung deaktiviert."))}
 async function cancel(){await patchStatus("Storniert")}
 async function credit(){if(!canWrite)return;const current=await ensure();if(!current)return;const n=`G-${number}`;const creditRec=await createAppRecord({module:"rechnungen",status:"Gutschrift",row:[n,customer,isoDate(),money(-totals.gross),"Gutschrift"],fields:{Nummer:n,Kunde:customer,Datum:isoDate(),Betrag:money(-totals.gross),Status:"Gutschrift",Einleitung:`${t("Gutschrift zu")} ${number}`},positions:positions.map(p=>({...p,unitPrice:-Math.abs(p.unitPrice)})),meta:{relations:{invoiceId:current.id,customerId:relationId(current,"customerId")},sourceInvoice:number,credit:true}});notify(t("Gutschrift erstellt."));router.push(`/rechnungen/${creditRec.id}`)}
 function startEdit(){if(!canWrite)return;setEditCustomer(customer);setEditDate(rec?.fields.Datum||isoDate());setEditDue(rec?.fields[isInvoice?"Fällig":"Gültig bis"]||seed[2]||"");setEditIntro(rec?.fields.Einleitung||t(isInvoice?"Besten Dank. Nachfolgend finden Sie unsere Rechnung.":"Besten Dank. Nachfolgend finden Sie unsere Offerte."));setEditPositions(positions.map(p=>({...p})));setEditDiscount(discount);setEditing(true)}
 async function saveEdit(){if(!canWrite)return;const current=await ensure();if(!current)return;const baseNet=editPositions.reduce((s,p)=>s+p.quantity*p.unitPrice,0);const factor=Math.max(0,1-editDiscount/100);const net=baseNet*factor;const vat=editPositions.reduce((s,p)=>s+p.quantity*p.unitPrice*p.vatRate/100,0)*factor;const gross=net+vat;const fields={...current.fields,Kunde:editCustomer,Datum:editDate,[isInvoice?"Fällig":"Gültig bis"]:editDue,Einleitung:editIntro,Betrag:money(gross)};const u=await updateAppRecord(current.id,{fields,positions:editPositions,row:[number,editCustomer,editDue,money(gross),current.status],meta:{...(current.meta||{}),net,vat,gross,discount:editDiscount}});if(u)setRec(u);setEditing(false);notify(t("Dokument gespeichert."))}
 const paid=Number(rec?.meta?.paidAmount||0),remaining=Math.max(0,totals.gross-paid);
 if(loading)return <div className="page"><div className="empty-state">{t("Dokument wird geladen …")}</div></div>;
 if(isProductionMode()&&!rec)return <div className="page"><div className="empty-state"><strong>{t("Dokument nicht gefunden")}</strong><p>{t("Das Dokument existiert nicht oder Sie haben keinen Zugriff.")}</p><Link href={config.href}>{t("Zur Übersicht")}</Link></div></div>;
 const documentPreview=<section className="document-paper print-document"><div className="doc-brand"><strong>{settings.companyName}</strong><span>{settings.address} · {settings.zipCity}</span></div><div className="doc-address"><small>{settings.companyName} · {settings.address} · {settings.zipCity}</small><strong>{customer}</strong><span>{String((rec?.meta?.customerSnapshot as Record<string,unknown>|undefined)?.contact||t("z.H. Buchhaltung"))}</span><span>{String((rec?.meta?.customerSnapshot as Record<string,unknown>|undefined)?.address||t("Schweiz"))}</span></div><div className="doc-title"><div><h2>{t(isInvoice?"Rechnung":"Offerte")}</h2><strong>{number}</strong></div><div><span>{t("Status")}</span><strong>{t(status)}</strong><span>{t("Datum")}</span><strong>{rec?.fields.Datum||"–"}</strong></div></div><p className="doc-intro">{rec?.fields.Einleitung||t(isInvoice?"Besten Dank. Nachfolgend finden Sie unsere Rechnung.":"Besten Dank. Nachfolgend finden Sie unsere Offerte.")}</p><div className="doc-positions"><div className="doc-pos-head"><span>{t("Beschreibung")}</span><span>{t("Menge")}</span><span>{t("Preis")}</span><span>{t("MWST")}</span><span>{t("Total")}</span></div>{positions.map((p,i)=><div className="doc-pos" key={`${p.description}-${i}`}><span data-label={t("Beschreibung")}>{p.description}</span><span data-label={t("Menge")}>{p.quantity}</span><span data-label={t("Preis")}>{money(p.unitPrice)}</span><span data-label={t("MWST")}>{p.vatRate}%</span><span data-label={t("Total")}>{money(p.quantity*p.unitPrice)}</span></div>)}</div><div className="doc-totals"><div><span>{t("Zwischentotal")}</span><strong>{money(totals.baseNet)}</strong></div>{discount>0&&<div><span>{t("Rabatt")} {discount}%</span><strong>- {money(totals.baseNet-totals.net)}</strong></div>}<div><span>{t("MWST")}</span><strong>{money(totals.vat)}</strong></div><div className="doc-grand"><span>{t("Total")}</span><strong>{money(totals.gross)}</strong></div>{isInvoice&&paid>0&&<><div><span>{t("Bezahlt")}</span><strong>{money(paid)}</strong></div><div><span>{t("Offen")}</span><strong>{money(remaining)}</strong></div></>}</div>{isInvoice&&<div className="qr-demo"><div className="qr-box" aria-label={t("QR-Zahlteil")}><span>QR</span><i/><i/><i/></div><div><strong>{t("Schweizer QR-Zahlteil")}</strong><span>IBAN {settings.iban}</span><span>{t("Betrag")} {money(remaining||totals.gross)}</span><span>{t("Referenz")} {number.replaceAll("-","")}</span></div></div>}<div className="doc-footer"><span>{settings.companyName}</span><span>{settings.uid}</span><span>{settings.email}</span></div></section>;
 return <div className="page document-detail-page">
  <Link className="back-link" href={config.href}><ArrowLeft size={17}/>{t("Zurück zu")} {t(config.label)}</Link>
  <section className="detail-heading"><div><div className="eyebrow">{t(isInvoice?"Rechnung":"Offerte")} · {t(status)}</div><h1>{number}</h1><p>{customer}</p></div><div className="detail-actions">{canWrite&&<button className="detail-action-icon" onClick={startEdit} aria-label={t("Bearbeiten")}><Pencil size={17}/><span>{t("Bearbeiten")}</span></button>}<button className="detail-action-label" onClick={()=>setPreviewOpen(true)}><Eye size={17}/><span>{t("Vorschau anzeigen")}</span></button>{canWrite&&<button className="detail-action-label" onClick={send}><Mail size={17}/><span>{t("Versenden")}</span></button>}{canWrite&&<button className="detail-action-icon" onClick={duplicate} aria-label={t("Duplizieren")}><Copy size={17}/><span>{t("Duplizieren")}</span></button>}</div></section>
  <div className="document-detail-grid document-detail-workspace">
   <section className="workspace-card document-summary-card">
    <div className="section-title"><div><span className="eyebrow">{t("Dokument")}</span><h2>{t("Übersicht")}</h2></div><Button variant="secondary" icon={<Eye size={17}/>} onClick={()=>setPreviewOpen(true)}>{t("Vorschau anzeigen")}</Button></div>
    <div className="document-summary-grid">
     <div><span>{t("Kunde")}</span><strong>{customer}</strong></div><div><span>{t("Status")}</span><strong>{t(status)}</strong></div><div><span>{t("Datum")}</span><strong>{rec?.fields.Datum||"–"}</strong></div><div><span>{t(isInvoice?"Fällig":"Gültig bis")}</span><strong>{rec?.fields[isInvoice?"Fällig":"Gültig bis"]||seed[2]||"–"}</strong></div><div><span>{t("Positionen")}</span><strong>{positions.length}</strong></div><div><span>{t("Total")}</span><strong>{money(totals.gross)}</strong></div>{isInvoice&&<><div><span>{t("Bezahlt")}</span><strong>{money(paid)}</strong></div><div><span>{t("Offen")}</span><strong>{money(remaining)}</strong></div></>}
    </div>
    <div className="document-preview-gate"><Eye size={20}/><div><strong>{t("Dokumentvorschau")}</strong><p>{t("Die vollständige Dokumentansicht wird erst bei Bedarf geöffnet.")}</p></div><Button icon={<Eye size={17}/>} onClick={()=>setPreviewOpen(true)}>{t("Vorschau anzeigen")}</Button></div>
   </section>
   <aside className="document-actions-panel workspace-card"><h3>{t("Workflow")}</h3>{canWrite?<><div className="workflow-status"><span>{t("Aktueller Status")}</span><strong>{t(status)}</strong></div><button onClick={send}><Send size={17}/>{isProductionMode()?t("Versenden"):t("Demo-Versand")}</button>{isInvoice?<><button onClick={openPartial}><CheckCircle2 size={17}/>{t("Zahlung erfassen")}</button><button onClick={()=>void patchStatus("Bezahlt")}><CheckCircle2 size={17}/>{t("Als bezahlt markieren")}</button><button onClick={remind}><Mail size={17}/>{t("Mahnung erstellen")}</button><button onClick={credit}><FilePlus2 size={17}/>{t("Gutschrift erstellen")}</button><button onClick={recurring}><Copy size={17}/>{t(rec?.meta?.recurring?"Wiederholung aus":"Wiederkehrend")}</button><button onClick={cancel}><Trash2 size={17}/>{t("Stornieren")}</button></>:<><button onClick={convert}><FilePlus2 size={17}/>{t("Annehmen und Auftrag erstellen")}</button><button onClick={reject}><Trash2 size={17}/>{t("Ablehnen")}</button></>}<button onClick={duplicate}><Copy size={17}/>{t("Duplizieren")}</button><small>{t(isProductionMode()?"Workflow-Aktionen werden serverseitig gespeichert.":"Lokale Testsimulation.")}</small></>:<div className="empty-state compact"><strong>{t("Nur Lesen")}</strong><p>{t("Für diese Rolle sind keine Workflow-Aktionen freigegeben.")}</p></div>}</aside>
  </div>
  <ResponsiveOverlay open={previewOpen} title={t("Dokumentvorschau")} onClose={()=>setPreviewOpen(false)} size="document" actions={<Button variant="secondary" icon={<Printer size={17}/>} onClick={()=>window.print()}>{t("Drucken / PDF")}</Button>}><div className="modal-document-scroll">{documentPreview}</div></ResponsiveOverlay>
 <ResponsiveOverlay open={canWrite&&editing} title={`${t(isInvoice?"Rechnung":"Offerte")} ${t("bearbeiten")}`} onClose={()=>setEditing(false)} size="lg" actions={<><Button variant="secondary" onClick={()=>setEditing(false)}>{t("Abbrechen")}</Button><Button icon={<Save size={17}/>} onClick={saveEdit}>{t("Speichern")}</Button></>}><div className="form-grid"><label><span>{t("Kunde")}</span><Input value={editCustomer} onChange={e=>setEditCustomer(e.target.value)}/></label><label><span>{t("Datum")}</span><Input type="date" value={editDate} onChange={e=>setEditDate(e.target.value)}/></label><label><span>{t(isInvoice?"Fällig":"Gültig bis")}</span><Input type="date" value={editDue} onChange={e=>setEditDue(e.target.value)}/></label><label><span>{t("Rabatt")} %</span><Input type="number" min="0" max="100" step="0.1" value={editDiscount} onChange={e=>setEditDiscount(Number(e.target.value))}/></label><label className="full"><span>{t("Einleitung")}</span><Textarea rows={3} value={editIntro} onChange={e=>setEditIntro(e.target.value)}/></label></div><div className="section-title sub-section"><h3>{t("Positionen")}</h3><button onClick={()=>setEditPositions(v=>[...v,createBlankDocumentPosition()])}><Plus size={16}/>{t("Position")}</button></div><div className="positions-editor">{editPositions.map((p,i)=><div className="position-row document-position-row" key={i}><Input aria-label={t("Beschreibung")} placeholder={t("Beschreibung")} value={p.description} onChange={e=>setEditPositions(v=>v.map((x,j)=>j===i?{...x,description:e.target.value}:x))}/><Input aria-label={t("Menge")} placeholder={t("Menge")} type="number" value={p.quantity} onChange={e=>setEditPositions(v=>v.map((x,j)=>j===i?{...x,quantity:Number(e.target.value)}:x))}/><Input aria-label={t("Einzelpreis")} placeholder={t("Einzelpreis")} type="number" value={p.unitPrice} onChange={e=>setEditPositions(v=>v.map((x,j)=>j===i?{...x,unitPrice:Number(e.target.value)}:x))}/><Select value={p.vatRate} onChange={e=>setEditPositions(v=>v.map((x,j)=>j===i?{...x,vatRate:Number(e.target.value)}:x))}>{domainConfig.vatRates.map(rate=><option value={rate} key={rate}>{rate} %</option>)}</Select><IconButton aria-label={t("Position löschen")} onClick={()=>setEditPositions(v=>v.filter((_,j)=>j!==i))}><Trash2 size={16}/></IconButton></div>)}</div></ResponsiveOverlay>
 <ResponsiveOverlay open={canWrite&&partialOpen} title={t("Zahlung erfassen")} onClose={()=>setPartialOpen(false)} size="sm" actions={<><Button variant="secondary" onClick={()=>setPartialOpen(false)}>{t("Abbrechen")}</Button><Button onClick={savePartial}>{t("Speichern")}</Button></>}><div className="overlay-form"><label><span>{t("Betrag")} ({domainConfig.currency})</span><Input autoFocus inputMode="decimal" type="number" min="0.01" step="0.05" value={partialAmount} onChange={event=>{setPartialAmount(event.target.value);setPartialError("")}} aria-invalid={Boolean(partialError)}/></label>{partialError&&<p className="field-error" role="alert">{partialError}</p>}<small>{t("Offener Betrag")}: {money(remaining)}</small></div></ResponsiveOverlay>
 </div>
}
