import Link from "next/link";
import {ArrowRight,Check,ShieldCheck} from "lucide-react";
import BrandLogo from "@/components/ui/brand-logo";
import {LanguageSwitcher} from "@/components/locale-provider";
import MarketingFooter from "@/components/marketing/marketing-footer";
import {plans} from "@/lib/plans";

function Header(){return <header className="marketing-header"><Link href="/" className="marketing-logo marketing-logo-image" aria-label="Binso One"><BrandLogo/></Link><nav className="marketing-nav"><Link href="/features">Funktionen</Link><Link href="/preise">Preise</Link><Link href="/sicherheit">Sicherheit</Link><Link href="/kontakt">Kontakt</Link></nav><div className="marketing-actions"><LanguageSwitcher compact/><Link href="/portal/login">Anmelden</Link><Link className="marketing-primary" href="/portal/registrieren">Kostenlos starten <ArrowRight size={16}/></Link></div></header>}
export default function MarketingPricing(){return <div className="marketing-shell"><Header/><main><section className="pricing-hero"><div className="section-kicker">Preise</div><h1>Ein Plan, der mit deinem Unternehmen mitwächst.</h1><p>Transparent pro Firma. Starte mit dem passenden Funktionsumfang und wechsle später, wenn du mehr benötigst.</p><div className="pricing-trust"><span><Check size={15}/> 14 Tage testen</span><span><Check size={15}/> jederzeit Plan wechseln</span><span><ShieldCheck size={15}/> keine Kartendaten in Binso One</span></div></section><section className="marketing-section pricing-section pricing-page-grid"><div className="pricing-grid">{plans.map(p=><article key={p.id} className={p.popular?"pricing-card popular":"pricing-card"}>{p.popular&&<div className="popular-badge">Empfohlen</div>}<h3>{p.name}</h3><p>{p.description}</p><div className="price"><strong>CHF {p.monthly}</strong><span>/ Monat</span></div><Link className={p.popular?"marketing-primary plan-button":"marketing-secondary plan-button"} href={`/registrieren?plan=${p.id}`}>{p.name} wählen</Link><div className="plan-features">{p.features.map(f=><span key={f}><Check size={15}/>{f}</span>)}</div></article>)}</div><p className="pricing-footnote">Preise exkl. MWST. Die effektiven Vertrags- und Abrechnungsbedingungen werden im Checkout und in den AGB ausgewiesen.</p></section><section className="marketing-section"><div className="section-kicker">Häufige Fragen</div><h2>Vor dem Start</h2><div className="faq-grid"><article><h3>Kann ich zuerst testen?</h3><p>Ja. Die Demo kann ohne Registrierung geöffnet werden. Zusätzlich kann eine eigene Testorganisation gestartet werden.</p></article><article><h3>Kann ich später wechseln?</h3><p>Ja. Der Plan ist über die Abonnementverwaltung wechselbar. Abrechnung und Zahlungsdaten werden über Stripe verwaltet.</p></article><article><h3>Sind meine Daten getrennt?</h3><p>Produktive Organisationen werden mandantengetrennt verarbeitet. Rollen, serverseitige Berechtigungen und Datenbank-RLS ergänzen sich.</p></article><article><h3>Wo erhalte ich Unterstützung?</h3><p>Nach der Anmeldung steht das integrierte Supportsystem mit Ticketverlauf, Diagnose und optionalem Screenshot zur Verfügung.</p></article></div></section></main><MarketingFooter/></div>}

