import Link from "next/link";
import {ArrowRight,Check,Clock3,FileCheck2,FolderKanban,ReceiptText,ShieldCheck,Users,WalletCards} from "lucide-react";
import BrandLogo from "@/components/ui/brand-logo";
import {LanguageSwitcher} from "@/components/locale-provider";

const sections=[
 {icon:ReceiptText,title:"Verkauf und Rechnungen",text:"Kunden, Offerten, Aufträge, Rechnungen und Zahlungen bilden einen durchgängigen Ablauf.",items:["Kundenhistorie und Kontakte","Offerten mit Positionen und MWST","Auftrag aus angenommener Offerte","Rechnung und Teilzahlung","Dokumentversand und Status"]},
 {icon:FolderKanban,title:"Projekte und Zeit",text:"Projektarbeit, Aufgaben, Zeit und Spesen bleiben direkt mit Kunde und Abrechnung verbunden.",items:["Projektbudgets und Fortschritt","Aufgaben und Meilensteine","Zeiterfassung und Timer","Spesen mit Beleg","Weiterverrechnung in Rechnungen"]},
 {icon:WalletCards,title:"Finanzen und MWST",text:"Offene Beträge, Zahlungen, Einkauf, Buchhaltung und MWST werden an einem Ort sichtbar.",items:["Zahlungszuordnung","Lieferanten und Eingangsrechnungen","Buchhaltungsübersicht","MWST-Auswertung","Berichte und Exporte"]},
 {icon:Users,title:"Personal und Organisation",text:"Mitarbeitende, Abwesenheiten, Dokumente, Rollen und Berechtigungen zentral verwalten.",items:["Mitarbeiterstammdaten","Abwesenheiten","Lohnbereich","Dokumente und Verträge","Benutzer und Rollen"]},
];

function Header(){return <header className="marketing-header"><Link href="/" className="marketing-logo marketing-logo-image" aria-label="Binso One"><BrandLogo/></Link><nav className="marketing-nav"><Link href="/features">Funktionen</Link><Link href="/preise">Preise</Link><Link href="/sicherheit">Sicherheit</Link></nav><div className="marketing-actions"><LanguageSwitcher compact/><Link href="/login">Anmelden</Link><Link className="marketing-primary" href="/registrieren">Kostenlos starten <ArrowRight size={16}/></Link></div></header>}
function Footer(){return <footer className="marketing-footer"><div><BrandLogo/><span>KMU-Plattform für die Schweiz</span></div><div><Link href="/preise">Preise</Link><Link href="/kontakt">Kontakt</Link><Link href="/status">Status</Link><Link href="/impressum">Impressum</Link><Link href="/agb">AGB</Link><Link href="/datenschutz">Datenschutz</Link></div><small>© 2026 Binso GmbH</small></footer>}

export default function MarketingFeatures(){return <div className="marketing-shell"><Header/><main><section className="marketing-hero marketing-subhero"><div className="hero-copy"><div className="eyebrow-pill"><FileCheck2 size={15}/> Funktionen</div><h1>Ein durchgängiger Arbeitsablauf statt Insellösungen.</h1><p>Binso One verbindet die täglichen Abläufe eines Schweizer KMU – von Kunden und Offerten über Projekte und Zeit bis zu Rechnungen, Finanzen und Administration.</p><div className="hero-actions"><Link className="marketing-primary big" href="/registrieren?trial=1">14 Tage kostenlos testen <ArrowRight size={17}/></Link><Link className="marketing-secondary big" href="/demo">Demo öffnen</Link></div></div><div className="feature-summary-card"><ShieldCheck size={28}/><strong>Mandantenfähig und rollenbasiert</strong><p>Jede Firma arbeitet in ihrem eigenen Mandanten. Rollen und serverseitige Berechtigungen steuern den Zugriff.</p></div></section><section className="marketing-section"><div className="section-kicker">Module, die zusammenarbeiten</div><h2>Vom ersten Kontakt bis zum Abschluss.</h2><div className="feature-detail-grid">{sections.map(s=>{const Icon=s.icon;return <article className="feature-detail-card" key={s.title}><div className="marketing-icon"><Icon size={22}/></div><h3>{s.title}</h3><p>{s.text}</p><div>{s.items.map(i=><span key={i}><Check size={15}/>{i}</span>)}</div></article>})}</div></section><section className="workflow-band"><div><div className="section-kicker">Ein System</div><h2>Informationen werden weiterverwendet, nicht neu erfasst.</h2></div><div className="workflow-steps">{["Kunde","Offerte","Auftrag","Projekt","Zeit und Spesen","Rechnung","Zahlung","MWST"].map((x,i)=><div key={x}><span>{String(i+1).padStart(2,"0")}</span><strong>{x}</strong></div>)}</div></section><section className="marketing-section security-section"><div className="security-copy"><div className="section-kicker">Für den Alltag gebaut</div><h2>Desktop, Tablet, Mobile und PWA.</h2><p>Die Oberfläche passt sich an unterschiedliche Bildschirmgrössen an und bleibt mit Light-, Dark- und System-Modus konsistent.</p><div className="security-points"><span><Clock3 size={18}/> Zeiterfassung unterwegs</span><span><Users size={18}/> klare Rollen</span><span><ShieldCheck size={18}/> sichere Sessions</span></div></div><div className="security-card"><strong>Binso One selbst ausprobieren</strong><p>Öffne die Demo oder starte eine eigene Testorganisation.</p><Link className="marketing-primary big" href="/registrieren?trial=1">Jetzt testen <ArrowRight size={17}/></Link></div></section></main><Footer/></div>}
