import Link from "next/link";
import {ArrowRight,Check,ShieldCheck} from "lucide-react";
import BrandLogo from "@/components/ui/brand-logo";
import {LanguageSwitcher} from "@/components/locale-provider";
import {plans} from "@/lib/plans";

function Header(){return <header className="marketing-header"><Link href="/" className="marketing-logo marketing-logo-image" aria-label="Binso One"><BrandLogo/></Link><nav className="marketing-nav"><Link href="/features">Funktionen</Link><Link href="/preise">Preise</Link><Link href="/sicherheit">Sicherheit</Link></nav><div className="marketing-actions"><LanguageSwitcher compact/><Link href="/login">Anmelden</Link><Link className="marketing-primary" href="/registrieren">Kostenlos starten <ArrowRight size={16}/></Link></div></header>}
function Footer(){return <footer className="marketing-footer"><div><BrandLogo/><span>KMU-Plattform fÃ¼r die Schweiz</span></div><div><Link href="/features">Funktionen</Link><Link href="/kontakt">Kontakt</Link><Link href="/status">Status</Link><Link href="/impressum">Impressum</Link><Link href="/agb">AGB</Link><Link href="/datenschutz">Datenschutz</Link></div><small>Â© 2026 Binso GmbH</small></footer>}

export default function MarketingPricing(){return <div className="marketing-shell"><Header/><main><section className="pricing-hero"><div className="section-kicker">Preise</div><h1>Ein Plan, der mit deinem Unternehmen mitwÃ¤chst.</h1><p>Transparent pro Firma. Starte mit dem passenden Funktionsumfang und wechsle spÃ¤ter, wenn du mehr benÃ¶tigst.</p><div className="pricing-trust"><span><Check size={15}/> 14 Tage testen</span><span><Check size={15}/> jederzeit Plan wechseln</span><span><ShieldCheck size={15}/> keine Kartendaten in Binso One</span></div></section><section className="marketing-section pricing-section pricing-page-grid"><div className="pricing-grid">{plans.map(p=><article key={p.id} className={p.popular?"pricing-card popular":"pricing-card"}>{p.popular&&<div className="popular-badge">Empfohlen</div>}<h3>{p.name}</h3><p>{p.description}</p><div className="price"><strong>CHF {p.monthly}</strong><span>/ Monat</span></div><Link className={p.popular?"marketing-primary plan-button":"marketing-secondary plan-button"} href={`/registrieren?plan=${p.id}`}>{p.name} wÃ¤hlen</Link><div className="plan-features">{p.features.map(f=><span key={f}><Check size={15}/>{f}</span>)}</div></article>)}</div><p className="pricing-footnote">Preise exkl. MWST. Die effektiven Vertrags- und Abrechnungsbedingungen werden im Checkout und in den AGB ausgewiesen.</p></section><section className="marketing-section"><div className="section-kicker">HÃ¤ufige Fragen</div><h2>Vor dem Start</h2><div className="faq-grid"><article><h3>Kann ich zuerst testen?</h3><p>Ja. Die Demo kann ohne Registrierung geÃ¶ffnet werden. ZusÃ¤tzlich kann eine eigene Testorganisation gestartet werden.</p></article><article><h3>Kann ich spÃ¤ter wechseln?</h3><p>Ja. Der Plan ist Ã¼ber die Abonnementverwaltung wechselbar. Abrechnung und Zahlungsdaten werden Ã¼ber Stripe verwaltet.</p></article><article><h3>Sind meine Daten getrennt?</h3><p>Produktive Organisationen werden mandantengetrennt verarbeitet. Rollen, serverseitige Berechtigungen und Datenbank-RLS ergÃ¤nzen sich.</p></article><article><h3>Wo erhalte ich UnterstÃ¼tzung?</h3><p>Nach der Anmeldung steht das integrierte Supportsystem mit Ticketverlauf, Diagnose und optionalem Screenshot zur VerfÃ¼gung.</p></article></div></section></main><Footer/></div>}

