"use client";
import {useEffect,useRef,useState} from 'react';
import {useRouter,useSearchParams} from 'next/navigation';
import {apiGet,apiPost} from '@/lib/client/backend';
import {AppShell} from './app-shell';
import { Button, Field, Input, Select, FormActions } from "./ui";
export function ProjectForm(){const params=useSearchParams(),router=useRouter(),busy=useRef(false);const [name,setName]=useState(''),[customerId,setCustomerId]=useState(params.get('customerId')??''),[customers,setCustomers]=useState<Array<{id:string;name:string}>>([]),[error,setError]=useState<string|null>(null),[saving,setSaving]=useState(false);const sourceOffer=params.get('sourceOffer');
 useEffect(()=>{apiGet<{items:typeof customers}>('/api/customers').then(data=>setCustomers(data.items)).catch(e=>setError(e.message));if(sourceOffer)apiGet<{item:{title?:string;customer_id:string}}>('/api/documents/'+encodeURIComponent(sourceOffer)).then(data=>{setName(data.item.title??'');setCustomerId(data.item.customer_id)}).catch(e=>setError(e.message));},[sourceOffer]);
 const save=async()=>{if(busy.current)return;if(name.trim().length<2){setError("Bitte eine Bezeichnung mit mindestens zwei Zeichen erfassen.");return;}setError(null);busy.current=true;setSaving(true);try{const result=await apiPost<{item:{id:string}}>('/api/projects',{name:name.trim(),customerId,sourceOffer});router.push('/zeit?projectId='+result.item.id);}catch(e){setError(e instanceof Error?e.message:'Projekt konnte nicht erstellt werden.');}finally{busy.current=false;setSaving(false)}};
 return <AppShell title="Auftrag / Projekt starten" active="zeit" backHref={sourceOffer?'/angebote/'+encodeURIComponent(sourceOffer):'/zeit'}><div className="form-page narrow">{error&&<p role="alert">{error}</p>}<Field label="Bezeichnung"><Input required minLength={2} maxLength={200} value={name} onChange={e=>setName(e.target.value)} placeholder="z. B. Cloud Migration"/></Field><Field label="Kunde"><Select disabled={!!sourceOffer} value={customerId} onChange={e=>setCustomerId(e.target.value)}><option value="">Intern</option>{customers.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</Select></Field>{sourceOffer&&<p>Ursprungsangebot: {sourceOffer}</p>}<FormActions ><Button requiresWrite disabled={saving||name.trim().length<2} onClick={()=>void save()}>{saving?"Wird erstellt…":"Auftrag starten"}</Button></FormActions></div></AppShell>;
}
