"use client";
import {subscribeAppEvent,appEvents} from "@/lib/client/app-events";
import {useEffect,useMemo,useState} from "react";import Link from "next/link";import {Plus,Search,X} from "lucide-react";import type {ModuleKey} from "@/lib/modules";import {loadEntityOptions,type EntityOption} from "@/lib/relationships";import {useLocale} from "@/components/locale-provider";
export default function RelationshipPicker({module,label,value,onChange,required=false,createHref,placeholder}:{module:ModuleKey;label:string;value:string;onChange:(option:EntityOption|undefined)=>void;required?:boolean;createHref?:string;placeholder?:string}){
 const {t}=useLocale();
 const [open,setOpen]=useState(false),[query,setQuery]=useState(""),[options,setOptions]=useState<EntityOption[]>([]),[loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;const load=()=>void loadEntityOptions(module).then(items=>{if(active){setOptions(items);setLoading(false)}}).catch(()=>{if(active){setOptions([]);setLoading(false)}});load();const unsubscribe=subscribeAppEvent(appEvents.dataChanged,load);return()=>{active=false;unsubscribe()}},[module]);
 const selected=options.find(o=>o.id===value);const filtered=useMemo(()=>options.filter(o=>`${o.label} ${o.sub||""} ${Object.values(o.fields).join(" ")}`.toLowerCase().includes(query.toLowerCase())).slice(0,20),[options,query]);
 return <label className="relationship-field"><span>{t(label)}{required?" *":""}</span><div className="relationship-picker"><button type="button" className="relationship-trigger" onClick={()=>setOpen(v=>!v)} aria-expanded={open}><span>{selected?.label||(loading?t("Wird geladen …"):placeholder||`${t(label)} ${t("auswählen")}`)}</span>{selected?<span role="button" tabIndex={0} className="relationship-clear" aria-label={t("Auswahl löschen")} onClick={e=>{e.stopPropagation();onChange(undefined)}} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();onChange(undefined)}}}><X size={14}/></span>:<Search size={15}/>}</button>{open&&<div className="relationship-popover"><div className="relationship-search"><Search size={15}/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder={`${t(label)} ${t("suchen …")}`}/></div><div className="relationship-results">{loading?<p>{t("Wird geladen …")}</p>:filtered.length?filtered.map(option=><button type="button" key={option.id} className={option.id===value?"selected":""} onClick={()=>{onChange(option);setOpen(false);setQuery("")}}><strong>{option.label}</strong>{option.sub&&<small>{option.sub}</small>}</button>):<p>{t("Keine Treffer")}</p>}</div>{createHref&&<Link className="relationship-create" href={createHref}><Plus size={15}/>{t("Neu erstellen")}</Link>}</div>}</div></label>
}
