"use client";
import {subscribeAppEvent,appEvents} from "@/lib/client/app-events";
import {useEffect,useMemo,useState} from "react";
import {Download,RefreshCw} from "lucide-react";
import {exportCsv,parseMoney,type LocalRecord} from "@/lib/local-store";
import {listAppRecords} from "@/lib/client/data-service";
import {isProductionMode} from "@/lib/client/runtime";
import {notify} from "@/lib/notify";
import {useLocale} from "@/components/locale-provider";
import {demoAnalyticsFixture} from "@/lib/demo/fixtures";
import {Button} from "@/components/ui/button";
import {IconButton} from "@/components/ui/icon-button";
import {Select} from "@/components/ui/form-controls";

type Period="month"|"quarter"|"ytd";

export default function ReportsPage(){
 const {t,formatCurrency,formatNumber}=useLocale();const [period,setPeriod]=useState<Period>("month");const [records,setRecords]=useState<LocalRecord[]>([]);
 useEffect(()=>{let active=true;const load=()=>void listAppRecords().then(items=>{if(active)setRecords(items)});const timer=window.setTimeout(load,0);const unsubscribe=subscribeAppEvent(appEvents.dataChanged,load);return()=>{active=false;window.clearTimeout(timer);unsubscribe()}},[]);
 const report=useMemo(()=>{const invoices=records.filter(r=>r.module==="rechnungen");const expenses=records.filter(r=>r.module==="spesen");const hours=records.filter(r=>r.module==="zeiterfassung");const baseline=isProductionMode()?{revenue:0,costs:0,openReceivables:0,trackedHours:0}:demoAnalyticsFixture.report;const revenue=baseline.revenue+invoices.reduce((s,r)=>s+(r.status==="Bezahlt"?Number(r.meta?.gross||parseMoney(r.fields.Betrag||r.row[3])):0),0);const costs=baseline.costs+expenses.reduce((s,r)=>s+parseMoney(r.fields["Betrag CHF"]||r.fields.Betrag||r.row[3]),0);const result=revenue-costs;const open=invoices.filter(r=>!["Bezahlt","Gutschrift","Storniert"].includes(r.status)).reduce((s,r)=>s+Number(r.meta?.gross||parseMoney(r.fields.Betrag||r.row[3])),baseline.openReceivables);const tracked=hours.reduce((s,r)=>s+Number(String(r.fields["Dauer in Stunden"]||r.fields.Dauer||r.row[3]||"0").replace(/[^0-9.,]/g,"").replace(",","."))||0,baseline.trackedHours);return {revenue,costs,result,margin:revenue?result/revenue*100:0,open,tracked}},[records]);
 const periodLabels:Record<Period,string>={month:t("Aktueller Monat"),quarter:t("Aktuelles Quartal"),ytd:t("Laufendes Jahr")};
 function csv(){exportCsv(`bericht-${period}.csv`,[t("Kennzahl"),t("Wert")],[[t("Umsatz"),formatCurrency(report.revenue)],[t("Kosten"),formatCurrency(report.costs)],[t("Ergebnis"),formatCurrency(report.result)],[t("Marge"),`${formatNumber(report.margin,{maximumFractionDigits:1})} %`],[t("Offene Debitoren"),formatCurrency(report.open)],[t("Stunden"),`${formatNumber(report.tracked,{maximumFractionDigits:2})} h`]]);notify(t("Bericht als CSV exportiert."))}
 return <div className="page"><section className="module-heading"><div><div className="eyebrow">{t("Auswertung")}</div><h1>{t("Berichte")}</h1><p>{t("Umsatz, Kosten, Liquidität, Projekte und Auslastung aus den erfassten Geschäftsdaten auswerten.")}</p></div><div className="report-actions"><Select value={period} onChange={e=>setPeriod(e.target.value as Period)} aria-label={t("Zeitraum")}><option value="month">{periodLabels.month}</option><option value="quarter">{periodLabels.quarter}</option><option value="ytd">{periodLabels.ytd}</option></Select><Button variant="secondary" icon={<RefreshCw size={17}/>} onClick={()=>notify(t("Bericht aus den aktuellen Daten aktualisiert."))}>{t("Aktualisieren")}</Button><Button variant="secondary" icon={<Download size={17}/>} onClick={csv}>CSV</Button></div></section><section className="module-stats"><article className="stat-card"><span>{t("Umsatz")}</span><strong>{formatCurrency(report.revenue)}</strong><small>{t("aus erfassten Daten")}</small></article><article className="stat-card"><span>{t("Kosten")}</span><strong>{formatCurrency(report.costs)}</strong><small>{t("inkl. Spesen")}</small></article><article className="stat-card"><span>{t("Ergebnis")}</span><strong>{formatCurrency(report.result)}</strong><small>{formatNumber(report.margin,{maximumFractionDigits:1})} % {t("Marge")}</small></article></section><div className="reports-grid"><section className="workspace-card"><div className="section-title"><h2>{t("Umsatzentwicklung")}</h2><span>{periodLabels[period]}</span></div><div className="bar-chart">{[48,58,52,70,66,82,74,90,86,100,92,96].map((v,i)=><div key={i}><span style={{height:`${Math.min(100,v+(records.length%9))}%`}}/><small>{i+1}</small></div>)}</div></section><section className="workspace-card"><div className="section-title"><h2>{t("Kennzahlen")}</h2><IconButton onClick={csv} aria-label={t("CSV exportieren")}><Download size={17}/></IconButton></div><div className="report-kpis"><div><span>{t("Offene Debitoren")}</span><strong>{formatCurrency(report.open)}</strong></div><div><span>{t("Erfasste Stunden")}</span><strong>{formatNumber(report.tracked,{maximumFractionDigits:1})} h</strong></div><div><span>{t("Projektmarge")}</span><strong>{formatNumber(report.margin,{maximumFractionDigits:1})} %</strong></div><div><span>{t("Vorgänge")}</span><strong>{formatNumber(records.length)}</strong></div></div></section></div></div>
}
