"use client";
import {useEffect,useState} from "react";
import {Check,Plus,RotateCcw,Trash2} from "lucide-react";
import {clearDemoData,defaultSettings,listLocalRecords,loadAppPreferences,loadSettings,saveAppPreferences,saveSettings,type AppUser,type DemoSettings,type UserRole} from "@/lib/local-store";
import {notify} from "@/lib/notify";
import {confirmAction} from "@/lib/confirm";
import {useSearchParams} from "next/navigation";
import {useLocale} from "@/components/locale-provider";
import {usePermissions} from "@/lib/client/use-permissions";
import {isProductionMode} from "@/lib/client/runtime";
import TenantUserManagement from "@/components/tenant-user-management";
import ProductionProfileSettings from "@/components/production-profile-settings";
import AccountSecurity from "@/components/security/account-security";
import TenantAudit from "@/components/audit/tenant-audit";
import ToggleSwitch from "@/components/ui/toggle-switch";
import ProductionOrganizationSettings from "@/components/production-organization-settings";
import ProductionDocumentSettings from "@/components/production-document-settings";
import AppUserSettings from "@/components/app-user-settings";

type Tab="profil"|"app"|"sicherheit"|"firma"|"benutzer"|"nummern"|"vorlagen"|"integrationen";
type TextSettingKey="companyName"|"uid"|"address"|"zipCity"|"email"|"phone"|"iban"|"defaultVat"|"paymentDays"|"currency"|"vatMethod";
const roles:UserRole[]=["Inhaber","Admin","Finanzen","Personal","Projektleitung","Mitarbeiter","Lesen"];
const languages={de:"Deutsch",en:"English",fr:"Français",it:"Italiano",tr:"Türkçe"} as const;

export default function SettingsPage(){
 const params=useSearchParams();
 const {t,setLocale}=useLocale();
 const permissions=usePermissions();
 const [v,setV]=useState<DemoSettings>(defaultSettings);const [tab,setTab]=useState<Tab>("profil");const [recordCount,setRecordCount]=useState(0);const [activeUserId,setActiveUserId]=useState("u1");
 useEffect(()=>{const timer=window.setTimeout(()=>{const settings=loadSettings();const pref=loadAppPreferences();setV(settings);setRecordCount(listLocalRecords().length);setActiveUserId(pref.activeUserId);const requested=params.get("tab") as Tab|null;if(requested&&["profil","app","sicherheit","firma","benutzer","nummern","vorlagen","integrationen"].includes(requested))setTab(requested)},0);return()=>window.clearTimeout(timer)},[params]);
 const activeUser=v.users.find(u=>u.id===activeUserId)||v.users[0];
 function save(){saveSettings(v);notify(t("Einstellungen gespeichert."))}
 function saveProfile(){saveSettings(v);const user=v.users.find(u=>u.id===activeUserId);if(user?.language)setLocale(user.language);notify(t("Profil gespeichert."))}
 async function reset(){const ok=await confirmAction({title:t("Demo-Daten zurücksetzen"),message:t("Alle lokal erfassten Demo-Daten löschen?"),confirmLabel:t("Löschen"),cancelLabel:t("Abbrechen"),tone:"danger"});if(ok){clearDemoData();saveSettings(defaultSettings);setV(defaultSettings);setRecordCount(0);notify(t("Demo-Daten zurückgesetzt."),"info")}}
 function addUser(){const u:AppUser={id:`u-${Date.now()}`,name:t("Neuer Benutzer"),email:"benutzer@beispiel.ch",role:"Mitarbeiter",active:true,language:"de"};setV(x=>({...x,users:[...x.users,u]}))}
 function updateUser(id:string,patch:Partial<AppUser>){const current=v.users.find(u=>u.id===id);if(!current)return;if(patch.role==="Inhaber"&&activeUser?.role!=="Inhaber"){notify(t("Nur der Inhaber darf die Inhaberrolle vergeben."),"danger");return}if(current.role==="Inhaber"&&patch.role&&patch.role!=="Inhaber"&&v.users.filter(u=>u.role==="Inhaber"&&u.active).length<=1){notify(t("Der letzte aktive Inhaber kann nicht geändert werden."),"danger");return}if(current.role==="Inhaber"&&patch.active===false&&v.users.filter(u=>u.role==="Inhaber"&&u.active).length<=1){notify(t("Der letzte aktive Inhaber kann nicht deaktiviert werden."),"danger");return}setV(x=>({...x,users:x.users.map(u=>u.id===id?{...u,...patch}:u)}))}
 function removeUser(id:string){const current=v.users.find(u=>u.id===id);if(!current)return;if(current.role==="Inhaber"&&v.users.filter(u=>u.role==="Inhaber").length<=1){notify(t("Der letzte Inhaber kann nicht gelöscht werden."),"danger");return}setV(x=>({...x,users:x.users.filter(u=>u.id!==id)}))}
 const canManageOrg=permissions.can("organization:write");const canManageUsers=permissions.can("users:manage");
 const tabs:[Tab,string][]=[["profil","Mein Profil"],["app","App und Darstellung"],["sicherheit","Sicherheit"],...(canManageOrg?([["firma","Firmendaten"],["nummern","Nummernkreise"],["vorlagen","Vorlagen & Benachrichtigungen"],["integrationen","Integrationen & Audit"]] as [Tab,string][]):[]),...(canManageUsers?([["benutzer","Benutzer & Rollen"]] as [Tab,string][]):[])];
 const tabAllowed=tab==="profil"||tab==="app"||tab==="sicherheit"||(tab==="benutzer"?canManageUsers:canManageOrg);const visibleTab:Tab=tabAllowed?tab:"profil";
 const companyFields:[TextSettingKey,string][]=[["companyName","Firmenname"],["uid","UID / MWST"],["address","Adresse"],["zipCity","PLZ / Ort"],["email","E-Mail"],["phone","Telefon"],["iban","IBAN"],["defaultVat","Standard MWST %"],["paymentDays","Zahlungsfrist Tage"],["currency","Währung"],["vatMethod","MWST-Methode"]];
 return <div className="page"><section className="module-heading"><div><div className="eyebrow">{t("System")}</div><h1>{t("Einstellungen")}</h1><p>{t("Persönliche Einstellungen, App, Sicherheit und Unternehmenskonfiguration an einem Ort.")}</p></div></section><div className="settings-tabs">{tabs.map(([k,l])=><button key={k} className={visibleTab===k?"active":""} onClick={()=>setTab(k)}>{t(l)}</button>)}</div>
 {visibleTab==="profil"&&(isProductionMode()?<ProductionProfileSettings/>:<div className="settings-grid profile-settings-grid"><section className="workspace-card profile-settings-card"><div className="settings-profile-head"><div className="settings-profile-avatar">{(activeUser?.name||"B").split(" ").map(x=>x[0]).join("").slice(0,2).toUpperCase()}</div><div><h2>{activeUser?.name||t("Benutzer")}</h2><p>{activeUser?.email||""}</p><span>{activeUser?.role?t(activeUser.role):t("Benutzer")}</span></div></div>{activeUser&&<div className="form-grid"><label><span>{t("Name")}</span><input value={activeUser.name} onChange={e=>updateUser(activeUser.id,{name:e.target.value})}/></label><label><span>{t("E-Mail")}</span><input type="email" value={activeUser.email} onChange={e=>updateUser(activeUser.id,{email:e.target.value})}/></label><label><span>{t("Sprache")}</span><select value={activeUser.language||"de"} onChange={e=>updateUser(activeUser.id,{language:e.target.value as "de"|"en"|"fr"|"it"|"tr"})}>{Object.entries(languages).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><small className="field-help">{t("Diese Sprache gilt nur für dein Benutzerprofil.")}</small></label></div>}<button className="ui-button ui-button-primary ui-button-md settings-save" onClick={saveProfile}><Check size={17}/>{t("Profil speichern")}</button></section><aside className="workspace-card profile-settings-aside"><h2>{t("Persönliche Einstellungen")}</h2><p>{t("Die Sprache wird nicht mehr global für die Firma gesetzt, sondern pro Benutzer gespeichert.")}</p><div className="profile-setting-summary"><span>{t("Firma")}</span><strong>{v.companyName}</strong></div><div className="profile-setting-summary"><span>{t("Rolle")}</span><strong>{activeUser?.role?t(activeUser.role):"–"}</strong></div></aside></div>)}
 {visibleTab==="app"&&<AppUserSettings/>}
 {visibleTab==="sicherheit"&&(isProductionMode()?<AccountSecurity/>:<section className="workspace-card"><h2>{t("Sicherheit")}</h2><p className="field-help">{t("MFA und Sitzungsverwaltung sind im Produktivmodus verfügbar.")}</p></section>)}
 {visibleTab==="firma"&&(isProductionMode()?<ProductionOrganizationSettings/>:<div className="settings-grid"><section className="workspace-card"><div className="section-title"><h2>{t("Firmendaten")}</h2><span>{t("für Dokumente")}</span></div><div className="form-grid">{companyFields.map(([k,l])=><label key={k}><span>{t(l)}</span><input value={String(v[k])} onChange={e=>setV(x=>({...x,[k]:e.target.value}))}/></label>)}</div><button className="ui-button ui-button-primary ui-button-md settings-save" onClick={save}><Check size={17}/>{t("Änderungen speichern")}</button></section><aside className="workspace-card danger-zone"><h2>{t("Lokaler Demo-Modus")}</h2><p>{recordCount} {t("lokale Datensätze gespeichert.")}</p><p>{t("Alle Testdaten liegen ausschliesslich in diesem Browser.")}</p><button onClick={reset}><RotateCcw size={17}/>{t("Demo-Daten zurücksetzen")}</button></aside></div>)}
 {visibleTab==="benutzer"&&(isProductionMode()?<TenantUserManagement/>:<section className="workspace-card"><div className="section-title"><h2>{t("Benutzer und Rollen")}</h2><button onClick={addUser}><Plus size={16}/>{t("Benutzer")}</button></div><div className="settings-user-table"><div className="settings-user-row head"><span>{t("Name")}</span><span>{t("E-Mail")}</span><span>{t("Rolle")}</span><span>{t("Aktiv")}</span><span>{t("Aktion")}</span></div>{v.users.map(u=><div className="settings-user-row" key={u.id}><input aria-label={`${t("Name")} ${u.email}`} value={u.name} onChange={e=>updateUser(u.id,{name:e.target.value})}/><input aria-label={`${t("E-Mail")} ${u.name}`} value={u.email} onChange={e=>updateUser(u.id,{email:e.target.value})}/><select aria-label={`${t("Rolle")} ${u.name}`} value={u.role} onChange={e=>updateUser(u.id,{role:e.target.value as UserRole})}>{roles.map(r=><option key={r} value={r}>{t(r)}</option>)}</select><ToggleSwitch checked={u.active} onChange={active=>updateUser(u.id,{active})} label={`${t("Benutzer")} ${u.name}`}/><div className="settings-user-actions"><button className="text-button" onClick={()=>{const pref=loadAppPreferences();saveAppPreferences({...pref,activeUserId:u.id});setActiveUserId(u.id);if(u.language)setLocale(u.language);notify(`${t("Aktiver Testbenutzer")}: ${u.name}`)}}>{t("Testen")}</button><button className="ui-icon-button" aria-label={`${t("Benutzer löschen")} ${u.name}`} onClick={()=>removeUser(u.id)}><Trash2 size={16}/></button></div></div>)}</div><div className="role-info"><p><strong>{t("Inhaber")}:</strong> {t("Vollzugriff inkl. Abo und Rollenverwaltung.")}</p><p><strong>{t("Admin")}:</strong> {t("Vollzugriff im Mandanten, ausser Inhaber-/Abo-Sonderrechte.")}</p><p><strong>{t("Finanzen")}:</strong> {t("Verkauf, Rechnungen, Zahlungen, Einkauf, Buchhaltung, Bank und MWST.")}</p><p><strong>{t("Personal")}:</strong> {t("Mitarbeitende, Abwesenheiten und Lohn.")}</p><p><strong>{t("Projektleitung")}:</strong> {t("Kunden, Offerten/Aufträge, Projekte, Zeit, Spesen und Aufgaben.")}</p><p><strong>{t("Mitarbeiter")}:</strong> {t("Projekte lesen sowie eigene Zeit, Spesen und Aufgaben.")}</p><p><strong>{t("Lesen")}:</strong> {t("Lesender Zugriff auf nicht sensible Geschäftsbereiche; kein Lohn.")}</p></div></section>)}
 {visibleTab==="nummern"&&(isProductionMode()?<ProductionDocumentSettings mode="numbers"/>:<section className="workspace-card"><div className="section-title"><h2>{t("Nummernkreise")}</h2><span>{t("lokale Vorschau")}</span></div><div className="form-grid">{Object.entries(v.sequences).map(([k,val])=><label key={k}><span>{t(k)}</span><input value={val} onChange={e=>setV(x=>({...x,sequences:{...x.sequences,[k]:e.target.value}}))}/></label>)}</div><p className="legal-demo-note">{t("Platzhalter")}: {'{YYYY}'} {t("für Jahr und")} {'{####}'} {t("für laufende Nummer.")}</p><button className="ui-button ui-button-primary ui-button-md settings-save" onClick={save}><Check size={17}/>{t("Änderungen speichern")}</button></section>)}
 {visibleTab==="vorlagen"&&(isProductionMode()?<ProductionDocumentSettings mode="templates"/>:<section className="workspace-card"><div className="section-title"><h2>{t("Dokumentvorlagen")}</h2><span>{t("Offerten und Rechnungen")}</span></div><div className="form-grid"><label className="full"><span>{t("Einleitung Rechnung")}</span><textarea rows={4} value={v.invoiceIntro} onChange={e=>setV(x=>({...x,invoiceIntro:e.target.value}))}/></label><label className="full"><span>{t("Einleitung Offerte")}</span><textarea rows={4} value={v.quoteIntro} onChange={e=>setV(x=>({...x,quoteIntro:e.target.value}))}/></label><label><span>{t("Mahnung nach Tagen")}</span><input inputMode="numeric" value={v.reminderDays} onChange={e=>setV(x=>({...x,reminderDays:e.target.value}))}/></label></div><div className="toggle-list"><label><input type="checkbox" checked={v.notificationsEmail} onChange={e=>setV(x=>({...x,notificationsEmail:e.target.checked}))}/>{t("E-Mail-Benachrichtigungen")}</label><label><input type="checkbox" checked={v.notificationsPush} onChange={e=>setV(x=>({...x,notificationsPush:e.target.checked}))}/>{t("Push-Benachrichtigungen")}</label></div>{!isProductionMode()&&<button className="ui-button ui-button-primary ui-button-md settings-save" onClick={save}><Check size={17}/>{t("Änderungen speichern")}</button>}</section>)}
 {visibleTab==="integrationen"&&<div className="settings-grid"><section className="workspace-card"><div className="section-title"><h2>{t("Integrationen")}</h2><span>{t(isProductionMode()?"Produktionsstatus":"lokale Simulation")}</span></div><div className="integration-list">{[["bank","Bank / ISO 20022"],["email","E-Mail-Versand"],["estv","ESTV / MWST"],["storage","Dokumentenablage"]].map(([k,l])=><div key={k}><div><strong>{t(l)}</strong><span>{isProductionMode()?t("Über die Systemkonfiguration verwaltet"):(v.integrations[k]?t("Aktiv"):t("Nicht verbunden"))}</span></div>{isProductionMode()?<button type="button" disabled>{t("Systemverwaltet")}</button>:<button onClick={()=>{const active=v.integrations[k];setV(x=>({...x,integrations:{...x.integrations,[k]:!active}}));notify(`${t(l)}: ${active?t("getrennt"):t("Demo-Verbindung aktiviert")}.`)}}>{v.integrations[k]?t("Trennen"):t("Verbinden")}</button>}</div>)}</div>{!isProductionMode()&&<button className="ui-button ui-button-primary ui-button-md settings-save" onClick={save}><Check size={17}/>{t("Änderungen speichern")}</button>}</section><aside className="workspace-card"><h2>{t("Audit")}</h2>{isProductionMode()?<TenantAudit/>:<div className="audit-list"><p><strong>{t("Heute")}</strong><span>{t("Einstellungen geöffnet")}</span></p><p><strong>{t("Heute")}</strong><span>{recordCount} {t("lokale Geschäftsdatensätze vorhanden")}</span></p><p><strong>{t("System")}</strong><span>{t("Lokale Demo-Umgebung aktiv")}</span></p></div>}</aside></div>}
 </div>
}
