import type {Metadata} from "next";
import Link from "next/link";
import {LegalPage} from "@/components/legal-page";
import {legalConfig} from "@/config/legal";

export const metadata:Metadata={title:"Auftragsbearbeitung – Binso One",description:"Vereinbarung zur Auftragsbearbeitung für Binso One.",alternates:{canonical:"/auftragsbearbeitung"}};

export default function Page(){
 return <LegalPage eyebrow="DPA" title="Vereinbarung zur Auftragsbearbeitung" intro="Diese Vereinbarung gilt, soweit Binso GmbH Personendaten im Auftrag eines Geschäftskunden in Binso One bearbeitet.">
  <section><h2>1. Parteien und Gegenstand</h2><p>Der Kunde ist Verantwortlicher für die von ihm in Binso One eingebrachten Personendaten. Die Binso GmbH handelt hinsichtlich dieser Daten als Auftragsbearbeiter. Diese Vereinbarung ergänzt die AGB und gilt für die Dauer der Nutzung von Binso One.</p></section>
  <section><h2>2. Gegenstand, Art und Zweck der Bearbeitung</h2><p>Binso verarbeitet Kundendaten zum Hosting, Speichern, Anzeigen, Strukturieren, Sichern, Übermitteln, Exportieren und Löschen im Rahmen der vom Kunden genutzten Funktionen sowie für Support, Fehlerbehebung und Sicherheitsmassnahmen. Eine Bearbeitung für eigene, mit dem Auftrag unvereinbare Zwecke findet nicht statt.</p></section>
  <section><h2>3. Kategorien betroffener Personen und Daten</h2><p>Betroffen sein können insbesondere Mitarbeitende, Kunden, Interessenten, Lieferanten, Ansprechpartner und sonstige Geschäftskontakte des Kunden. Verarbeitet werden können Stammdaten, Kontaktdaten, Beschäftigungs- und Organisationsdaten, Leistungs- und Projektdaten, Zeit- und Spesendaten, Rechnungs- und Zahlungsinformationen, Dokumente, Kommunikationsdaten sowie technische Metadaten. Der Kunde entscheidet, welche Daten er in Binso One erfasst.</p></section>
  <section><h2>4. Weisungen</h2><p>Binso bearbeitet die Auftragsdaten nur im Rahmen des Vertrags, der Nutzung der Funktionen durch den Kunden und dokumentierter zusätzlicher Weisungen. Hält Binso eine Weisung für datenschutzwidrig, wird der Kunde darauf hingewiesen, soweit dies rechtlich zulässig ist.</p></section>
  <section><h2>5. Vertraulichkeit</h2><p>Personen mit Zugriff auf Auftragsdaten werden zur Vertraulichkeit verpflichtet und erhalten nur die für ihre Aufgaben erforderlichen Zugriffe.</p></section>
  <section><h2>6. Technische und organisatorische Massnahmen</h2><p>Binso trifft angemessene Massnahmen zum Schutz von Vertraulichkeit, Integrität und Verfügbarkeit. Dazu gehören insbesondere TLS-verschlüsselte Übertragung, rollenbasierte Berechtigungen, Mehrfaktor-Authentifizierung für privilegierte Zugriffe, getrennte Mandantenkontexte, sichere Sitzungen, Protokollierung, kontrollierte Deployments, Datenbanksicherungen und regelmässige technische Prüfungen. Die Massnahmen werden risikobasiert weiterentwickelt.</p></section>
  <section><h2>7. Unterauftragsbearbeiter</h2><p>Der Kunde erteilt Binso eine allgemeine Genehmigung zum Einsatz der unter <Link href="/unterauftragsbearbeiter">Unterauftragsbearbeiter</Link> aufgeführten Dienstleister. Wesentliche neue Unterauftragsbearbeiter werden durch Aktualisierung der Liste und, soweit angemessen, zusätzliche Mitteilung angekündigt. Der Kunde kann aus berechtigten Datenschutzgründen widersprechen. Ist keine zumutbare Alternative möglich, können die Parteien die betroffene Leistung beenden.</p></section>
  <section><h2>8. Auslandbekanntgabe</h2><p>Bei Bearbeitungen ausserhalb der Schweiz stellt Binso sicher, dass die gesetzlichen Voraussetzungen für die Bekanntgabe erfüllt sind. Soweit erforderlich, werden anerkannte Standardvertragsklauseln mit Schweizer Anpassungen oder andere zulässige Garantien eingesetzt.</p></section>
  <section><h2>9. Unterstützung des Kunden</h2><p>Binso unterstützt den Kunden im angemessenen Umfang bei Betroffenenanfragen, Datenschutz-Folgenabschätzungen, Sicherheitsfragen und der Erfüllung gesetzlicher Meldepflichten, soweit die betreffenden Informationen und Funktionen bei Binso liegen.</p></section>
  <section><h2>10. Verletzungen der Datensicherheit</h2><p>Binso informiert den Kunden ohne unangemessene Verzögerung über bestätigte Verletzungen der Datensicherheit, welche Auftragsdaten des Kunden betreffen, und stellt die verfügbaren Informationen bereit, die der Kunde zur Beurteilung seiner Melde- und Informationspflichten benötigt.</p></section>
  <section><h2>11. Rückgabe und Löschung</h2><p>Nach Vertragsende kann der Kunde vorhandene Exportmöglichkeiten nutzen. Binso löscht oder anonymisiert Auftragsdaten nach Ende der vereinbarten Aufbewahrungs- und Sicherungsprozesse, sofern keine gesetzliche Pflicht oder ein überwiegender rechtlicher Grund zur weiteren Aufbewahrung besteht. Backup-Kopien werden im Rahmen der regulären Backup-Zyklen überschrieben oder gelöscht.</p></section>
  <section><h2>12. Nachweise und Kontrollen</h2><p>Binso stellt auf angemessene Anfrage Informationen zur Verfügung, die zur Beurteilung der Einhaltung dieser Vereinbarung erforderlich sind. Audits sind unter Berücksichtigung von Vertraulichkeit, Sicherheit, Verhältnismässigkeit und Schutz anderer Kunden zu koordinieren. Bestehende Prüfberichte oder gleichwertige Nachweise können Vorrang vor Vor-Ort-Prüfungen haben.</p></section>
  <section><h2>13. Rangfolge</h2><p>Bei Widersprüchen zwischen dieser Vereinbarung und den AGB gehen für die Bearbeitung von Auftragsdaten die spezielleren Datenschutzbestimmungen dieser Vereinbarung vor. Im Übrigen gelten die AGB.</p></section>
  <p className="legal-version">Version {legalConfig.dpaVersion} · Stand: {legalConfig.versionDate}</p>
 </LegalPage>;
}
