export const schemaSql=`
CREATE TABLE IF NOT EXISTS organisations (id uuid PRIMARY KEY, name text NOT NULL, plan text NOT NULL, subscription_status text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS users (id uuid PRIMARY KEY, email text NOT NULL UNIQUE, name text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS memberships (organisation_id uuid NOT NULL REFERENCES organisations(id), user_id uuid NOT NULL REFERENCES users(id), role text NOT NULL, PRIMARY KEY(organisation_id,user_id));
CREATE TABLE IF NOT EXISTS customers (id uuid PRIMARY KEY, organisation_id uuid NOT NULL REFERENCES organisations(id), name text NOT NULL, email text, phone text, address text, postal_code text, city text, status text NOT NULL DEFAULT 'Aktiv', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS customers_org_idx ON customers(organisation_id);
CREATE TABLE IF NOT EXISTS projects (id uuid PRIMARY KEY, organisation_id uuid NOT NULL REFERENCES organisations(id), customer_id uuid NOT NULL REFERENCES customers(id), name text NOT NULL, status text NOT NULL DEFAULT 'Entwurf', description text, budget_minor bigint, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS projects_org_idx ON projects(organisation_id);
CREATE TABLE IF NOT EXISTS time_entries (id uuid PRIMARY KEY, organisation_id uuid NOT NULL REFERENCES organisations(id), user_id uuid NOT NULL REFERENCES users(id), project_id uuid NOT NULL REFERENCES projects(id), started_at timestamptz NOT NULL, ended_at timestamptz, note text, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS time_entries_org_idx ON time_entries(organisation_id);
CREATE TABLE IF NOT EXISTS offers (id uuid PRIMARY KEY, organisation_id uuid NOT NULL REFERENCES organisations(id), customer_id uuid NOT NULL REFERENCES customers(id), number text NOT NULL, status text NOT NULL, valid_until date NOT NULL, snapshot jsonb, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(organisation_id,number));
CREATE TABLE IF NOT EXISTS invoices (id uuid PRIMARY KEY, organisation_id uuid NOT NULL REFERENCES organisations(id), customer_id uuid NOT NULL REFERENCES customers(id), project_id uuid REFERENCES projects(id), number text NOT NULL, status text NOT NULL, currency text NOT NULL DEFAULT 'CHF', due_at date NOT NULL, snapshot jsonb, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(organisation_id,number));
CREATE TABLE IF NOT EXISTS payments (id uuid PRIMARY KEY, organisation_id uuid NOT NULL REFERENCES organisations(id), invoice_id uuid NOT NULL REFERENCES invoices(id), amount_minor bigint NOT NULL, currency text NOT NULL, paid_at timestamptz NOT NULL, reference text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS documents (id uuid PRIMARY KEY, organisation_id uuid NOT NULL REFERENCES organisations(id), kind text NOT NULL, name text NOT NULL, storage_key text NOT NULL, mime_type text NOT NULL, size bigint NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS audit_events (id uuid PRIMARY KEY, organisation_id uuid NOT NULL REFERENCES organisations(id), actor_id uuid, action text NOT NULL, entity text NOT NULL, entity_id text, metadata jsonb, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS audit_org_created_idx ON audit_events(organisation_id,created_at DESC);
`;