"use client";
import {useState} from "react";import {Send} from "lucide-react";import {apiFetch,isProductionMode} from "@/lib/client/runtime";import {createFeedback} from "@/lib/pilot-store";import {notify} from "@/lib/notify";import {useLocale} from "@/components/locale-provider";import {writeTextStorage} from "@/lib/client/browser-storage";
import {storageKeys} from "@/config/storage-keys";import {Button} from "@/components/ui/button";import {Select,Textarea,Checkbox} from "@/components/ui/form-controls";
export default function FeedbackForm({compact=false,onDone}:{compact?:boolean;onDone?:()=>void}){
 const {t}=useLocale();const [v,setV]=useState({rating:0,category:"Allgemein",text:"",contact:false});const [busy,setBusy]=useState(false);
 async function submit(){if(!v.rating||!v.text.trim()){notify(t("Bitte Bewertung und Feedback ausfüllen."),"danger");return}setBusy(true);try{const input={...v,context:typeof window!=="undefined"?window.location.pathname:""};if(isProductionMode())await apiFetch("/api/feedback",{method:"POST",body:JSON.stringify(input)});else createFeedback(input);writeTextStorage(storageKeys.feedbackLast,Date.now().toString());notify(t("Danke für dein Feedback."));onDone?.()}catch(e){notify(e instanceof Error?e.message:t("Feedback konnte nicht gesendet werden."),"danger")}finally{setBusy(false)}}
 const categories=["Allgemein","Bedienung","Funktion fehlt","Fehler","Idee"];
 return <div className={compact?"feedback-form compact":"feedback-form"}><div className="feedback-stars" aria-label={t("Bewertung")}>{[1,2,3,4,5].map(n=><button type="button" key={n} className={v.rating>=n?"active":""} onClick={()=>setV({...v,rating:n})} aria-label={`${n} ${t("von")} 5`}>★</button>)}</div><label><span>{t("Kategorie")}</span><Select value={v.category} onChange={e=>setV({...v,category:e.target.value})}>{categories.map(x=><option key={x} value={x}>{t(x)}</option>)}</Select></label><label><span>{t("Was können wir verbessern?")}</span><Textarea rows={compact?4:7} value={v.text} onChange={e=>setV({...v,text:e.target.value})} placeholder={t("Dein Feedback …")}/></label><Checkbox className="feedback-contact" checked={v.contact} onChange={e=>setV({...v,contact:e.target.checked})} label={<span className="feedback-contact-text">{t("Binso darf mich zu diesem Feedback kontaktieren.")}</span>}/><Button onClick={submit} loading={busy} icon={<Send size={16}/>}>{busy?t("Wird gesendet …"):t("Feedback senden")}</Button></div>
}
