"use client";
import {useEffect,useState} from "react";import {usePathname} from "next/navigation";import FeedbackForm from "@/components/feedback/feedback-form";import {useLocale} from "@/components/locale-provider";import {readTextStorage,writeTextStorage} from "@/lib/client/browser-storage";
import {storageKeys} from "@/config/storage-keys";import {domainConfig,milliseconds} from "@/config/domain";
const appPrefixes=["/dashboard","/kunden","/offerten","/auftraege","/projekte","/zeiterfassung","/spesen","/rechnungen","/zahlungen","/lieferanten","/eingangsrechnungen","/buchhaltung","/bank","/mwst","/berichte","/personal","/abwesenheiten","/lohn","/produkte","/dokumente","/vertraege","/aufgaben","/einstellungen","/support"];
export default function PilotFeedbackHost(){
 const {t}=useLocale();const pathname=usePathname();const [open,setOpen]=useState(false);
 useEffect(()=>{if(!appPrefixes.some(x=>pathname.startsWith(x)))return;const never=readTextStorage(storageKeys.feedbackNever)==="1";if(never)return;const last=Number(readTextStorage(storageKeys.feedbackLast,"0"));if(last&&Date.now()-last<domainConfig.pilotFeedbackCooldownDays*milliseconds.day)return;const views=Number(readTextStorage(storageKeys.feedbackViews,"0"))+1;writeTextStorage(storageKeys.feedbackViews,String(views));if(views<domainConfig.pilotFeedbackMinViews)return;const timer=window.setTimeout(()=>setOpen(true),domainConfig.pilotFeedbackPromptDelayMs);return()=>window.clearTimeout(timer)},[pathname]);
 if(!open)return null;
 return <div className="pilot-feedback-panel"><button className="pilot-feedback-close" onClick={()=>setOpen(false)} aria-label={t("Schliessen")}>×</button><div className="eyebrow">{t("Pilotphase")}</div><h2>{t("Wie läuft Binso One für dich?")}</h2><p>{t("Kurzes Feedback hilft uns, die nächsten Verbesserungen richtig zu priorisieren.")}</p><FeedbackForm compact onDone={()=>setOpen(false)}/><div className="pilot-feedback-secondary"><button onClick={()=>{writeTextStorage(storageKeys.feedbackLast,Date.now().toString());setOpen(false)}}>{t("Später")}</button><button onClick={()=>{writeTextStorage(storageKeys.feedbackNever,"1");setOpen(false)}}>{t("Nicht mehr anzeigen")}</button></div></div>
}
