import {NextRequest} from "next/server";
import {apiError,assertSameOrigin,json} from "@/lib/server/http";
import {requireSession} from "@/lib/server/session";
import {authorize} from "@/lib/server/rbac";
import {limitsConfig} from "@/config/limits";
export const runtime="nodejs";
type Field={valueString?:string;valueDate?:string;valueCurrency?:{amount?:number;currencyCode?:string};valueNumber?:number;confidence?:number;content?:string};
const safe=(v:string)=>v.normalize("NFKD").replace(/[^a-zA-Z0-9äöüÄÖÜ_-]+/g,"-").replace(/-+/g,"-").replace(/^-|-$/g,"").slice(0,60)||"Beleg";
export async function POST(request:NextRequest){try{assertSameOrigin(request);const s=await requireSession();authorize(s,"expenses:write");const form=await request.formData();const file=form.get("file");if(!(file instanceof File))return json({error:"file_required",message:"Beleg fehlt."},400);if(file.size>limitsConfig.maxFileUploadBytes)return json({error:"file_too_large",message:"Beleg ist zu gross."},413);if(!["application/pdf","image/png","image/jpeg","image/webp"].includes(file.type))return json({error:"file_type",message:"Dateityp wird für Belegerkennung nicht unterstützt."},400);
 const endpoint=(process.env.AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT||"").replace(/\/$/,""),key=process.env.AZURE_DOCUMENT_INTELLIGENCE_KEY||"";if(!endpoint||!key)return json({error:"receipt_scan_unavailable",message:"Belegerkennung ist noch nicht konfiguriert."},503);
 const body=Buffer.from(await file.arrayBuffer());const start=await fetch(endpoint+"/documentintelligence/documentModels/prebuilt-receipt:analyze?_overload=analyzeDocument&api-version=2024-11-30",{method:"POST",headers:{"Ocp-Apim-Subscription-Key":key,"Content-Type":file.type},body});if(!start.ok)throw new Error("Beleg konnte nicht analysiert werden.");const operation=start.headers.get("operation-location");if(!operation)throw new Error("Belegerkennung lieferte keinen Vorgang.");
 let result:any=null;for(let i=0;i<12;i++){await new Promise(r=>setTimeout(r,500));const poll=await fetch(operation,{headers:{"Ocp-Apim-Subscription-Key":key}});if(!poll.ok)throw new Error("Belegerkennung konnte nicht abgeschlossen werden.");result=await poll.json();if(result.status==="succeeded")break;if(result.status==="failed")throw new Error("Belegerkennung ist fehlgeschlagen.");}
 if(result?.status!=="succeeded")return json({error:"receipt_scan_timeout",message:"Belegerkennung dauert länger als erwartet. Bitte erneut versuchen."},504);
 const f=(result.analyzeResult?.documents?.[0]?.fields??{}) as Record<string,Field>;const merchant=f.MerchantName?.valueString||f.MerchantName?.content||"";const date=f.TransactionDate?.valueDate||"";const total=f.Total?.valueCurrency?.amount??f.Subtotal?.valueCurrency?.amount??null;const currency=f.Total?.valueCurrency?.currencyCode||"CHF";const tax=f.TotalTax?.valueCurrency?.amount??null;const confidence=Math.min(...["MerchantName","TransactionDate","Total"].map(k=>f[k]?.confidence??0));const ext=(file.name.split(".").pop()||"jpg").replace(/[^a-zA-Z0-9]/g,"").toLowerCase();const filename=`${date||new Date().toISOString().slice(0,10)}_${safe(merchant||"Beleg")}_${typeof total==="number"?total.toFixed(2):"Betrag"}-${currency}.${ext}`;
 return json({merchant,date,total,currency,tax,confidence,filename,fields:{merchant:f.MerchantName?.confidence??0,date:f.TransactionDate?.confidence??0,total:f.Total?.confidence??0,tax:f.TotalTax?.confidence??0}});
 }catch(e){return apiError(e)}}