import type { Locale } from './config'

type Catalog = Record<string, string>

const headings = {
  fr: {
    'Rechtliches':'Mentions légales','Übersetzungen dienen der besseren Verständlichkeit. Bei Abweichungen ist die deutsche Fassung massgebend.':'Les traductions sont fournies pour faciliter la compréhension. En cas de divergence, la version allemande fait foi.',
    '1. Anbieterin und Geltungsbereich':'1. Prestataire et champ d’application','2. Vertragsabschluss':'2. Conclusion du contrat','3. Registrierung und Vertretungsberechtigung':'3. Inscription et pouvoir de représentation','4. Leistungsumfang und Pläne':'4. Étendue des prestations et plans','5. Testphase':'5. Période d’essai','6. Preise, Steuern und Zahlung':'6. Prix, impôts et paiement','7. Zahlungsverzug und Sperrung':'7. Retard de paiement et suspension','8. Laufzeit, Verlängerung und Kündigung':'8. Durée, renouvellement et résiliation','9. Planwechsel':'9. Changement de plan','10. Zulässige Nutzung':'10. Utilisation autorisée','11. Kundendaten und Verantwortung':'11. Données clients et responsabilité','12. Auftragsbearbeitung und Datenschutz':'12. Traitement des données et protection des données','13. Datenausgabe und Datenlöschung':'13. Export et suppression des données','14. Verfügbarkeit, Wartung und Änderungen':'14. Disponibilité, maintenance et modifications','15. Support':'15. Assistance','16. Rechte an Binso One':'16. Droits sur Binso One','17. Gewährleistung und Haftung':'17. Garantie et responsabilité','18. Preis- und Vertragsänderungen':'18. Modifications de prix et de contrat','19. Übertragung und Beizug Dritter':'19. Transfert et recours à des tiers','20. Schlussbestimmungen':'20. Dispositions finales','21. Kontakt':'21. Contact',
    '1. Gegenstand und Geltung':'1. Objet et champ d’application','2. Gegenstand, Dauer und Zweck':'2. Objet, durée et finalité','3. Datenarten und betroffene Personen':'3. Types de données et personnes concernées','4. Weisungen':'4. Instructions','5. Vertraulichkeit und Zugriff':'5. Confidentialité et accès','6. Technische und organisatorische Massnahmen':'6. Mesures techniques et organisationnelles','7. Unterauftragsbearbeiter':'7. Sous-traitants','8. Auslandbearbeitung':'8. Traitement à l’étranger','9. Unterstützung des Kunden':'9. Assistance au client','10. Datenschutzverletzungen':'10. Violations de la sécurité des données','11. Rückgabe, Export und Löschung':'11. Restitution, export et suppression','12. Nachweise und Prüfungen':'12. Justificatifs et audits','13. Rangfolge':'13. Ordre de priorité','14. Kontakt':'14. Contact',
    '1. Verantwortliche Stelle':'1. Responsable du traitement','2. Welche Daten wir bearbeiten':'2. Données que nous traitons','3. Herkunft der Daten':'3. Origine des données','4. Zwecke der Bearbeitung':'4. Finalités du traitement','5. Anmeldung und Benutzerkonto':'5. Connexion et compte utilisateur','6. Hosting, Datenbank und Betrieb':'6. Hébergement, base de données et exploitation','7. Zahlungen und Abonnemente':'7. Paiements et abonnements','8. E-Mail-Versand':'8. Envoi d’e-mails','9. Cookies und lokale Speicherung':'9. Cookies et stockage local','10. Empfänger und Unterauftragsbearbeiter':'10. Destinataires et sous-traitants','11. Bekanntgabe ins Ausland':'11. Communication à l’étranger','12. Aufbewahrung und Löschung':'12. Conservation et suppression','13. Datenausgabe und Vertragsende':'13. Export des données et fin du contrat','14. Rechte betroffener Personen':'14. Droits des personnes concernées','15. Automatisierte Einzelentscheidungen':'15. Décisions individuelles automatisées','16. Datensicherheit':'16. Sécurité des données','17. Dienstleister im Überblick':'17. Aperçu des prestataires','18. Änderungen':'18. Modifications',
    'Allgemeine Geschäftsbedingungen':'Conditions générales','Datenschutzerklärung':'Déclaration de protection des données','Auftragsbearbeitungsvereinbarung':'Accord de traitement des données','Cookie- und Speicher-Richtlinie':'Politique relative aux cookies et au stockage','Unterauftragsbearbeiter und Datenstandorte für Binso One.':'Sous-traitants et lieux de traitement des données pour Binso One.',
  },
  it: {
    'Rechtliches':'Aspetti legali','Übersetzungen dienen der besseren Verständlichkeit. Bei Abweichungen ist die deutsche Fassung massgebend.':'Le traduzioni sono fornite per agevolare la comprensione. In caso di divergenze fa fede la versione tedesca.',
    '1. Anbieterin und Geltungsbereich':'1. Fornitore e ambito di applicazione','2. Vertragsabschluss':'2. Conclusione del contratto','3. Registrierung und Vertretungsberechtigung':'3. Registrazione e potere di rappresentanza','4. Leistungsumfang und Pläne':'4. Ambito delle prestazioni e piani','5. Testphase':'5. Periodo di prova','6. Preise, Steuern und Zahlung':'6. Prezzi, imposte e pagamento','7. Zahlungsverzug und Sperrung':'7. Ritardo di pagamento e sospensione','8. Laufzeit, Verlängerung und Kündigung':'8. Durata, rinnovo e disdetta','9. Planwechsel':'9. Cambio di piano','10. Zulässige Nutzung':'10. Uso consentito','11. Kundendaten und Verantwortung':'11. Dati del cliente e responsabilità','12. Auftragsbearbeitung und Datenschutz':'12. Trattamento dei dati e protezione dei dati','13. Datenausgabe und Datenlöschung':'13. Esportazione e cancellazione dei dati','14. Verfügbarkeit, Wartung und Änderungen':'14. Disponibilità, manutenzione e modifiche','15. Support':'15. Supporto','16. Rechte an Binso One':'16. Diritti su Binso One','17. Gewährleistung und Haftung':'17. Garanzia e responsabilità','18. Preis- und Vertragsänderungen':'18. Modifiche di prezzo e contratto','19. Übertragung und Beizug Dritter':'19. Trasferimento e ricorso a terzi','20. Schlussbestimmungen':'20. Disposizioni finali','21. Kontakt':'21. Contatto',
    '1. Gegenstand und Geltung':'1. Oggetto e ambito di applicazione','2. Gegenstand, Dauer und Zweck':'2. Oggetto, durata e finalità','3. Datenarten und betroffene Personen':'3. Tipi di dati e persone interessate','4. Weisungen':'4. Istruzioni','5. Vertraulichkeit und Zugriff':'5. Riservatezza e accesso','6. Technische und organisatorische Massnahmen':'6. Misure tecniche e organizzative','7. Unterauftragsbearbeiter':'7. Sub-responsabili','8. Auslandbearbeitung':'8. Trattamento all’estero','9. Unterstützung des Kunden':'9. Assistenza al cliente','10. Datenschutzverletzungen':'10. Violazioni della sicurezza dei dati','11. Rückgabe, Export und Löschung':'11. Restituzione, esportazione e cancellazione','12. Nachweise und Prüfungen':'12. Prove e verifiche','13. Rangfolge':'13. Ordine di priorità','14. Kontakt':'14. Contatto',
    '1. Verantwortliche Stelle':'1. Titolare del trattamento','2. Welche Daten wir bearbeiten':'2. Dati che trattiamo','3. Herkunft der Daten':'3. Origine dei dati','4. Zwecke der Bearbeitung':'4. Finalità del trattamento','5. Anmeldung und Benutzerkonto':'5. Accesso e account utente','6. Hosting, Datenbank und Betrieb':'6. Hosting, database e gestione','7. Zahlungen und Abonnemente':'7. Pagamenti e abbonamenti','8. E-Mail-Versand':'8. Invio di e-mail','9. Cookies und lokale Speicherung':'9. Cookie e archiviazione locale','10. Empfänger und Unterauftragsbearbeiter':'10. Destinatari e sub-responsabili','11. Bekanntgabe ins Ausland':'11. Comunicazione all’estero','12. Aufbewahrung und Löschung':'12. Conservazione e cancellazione','13. Datenausgabe und Vertragsende':'13. Esportazione dei dati e fine del contratto','14. Rechte betroffener Personen':'14. Diritti delle persone interessate','15. Automatisierte Einzelentscheidungen':'15. Decisioni individuali automatizzate','16. Datensicherheit':'16. Sicurezza dei dati','17. Dienstleister im Überblick':'17. Panoramica dei fornitori','18. Änderungen':'18. Modifiche',
    'Allgemeine Geschäftsbedingungen':'Condizioni generali','Datenschutzerklärung':'Informativa sulla protezione dei dati','Auftragsbearbeitungsvereinbarung':'Accordo sul trattamento dei dati','Cookie- und Speicher-Richtlinie':'Politica sui cookie e sull’archiviazione','Unterauftragsbearbeiter und Datenstandorte für Binso One.':'Sub-responsabili e sedi di trattamento dei dati per Binso One.',
  },
  en: {
    'Rechtliches':'Legal','Übersetzungen dienen der besseren Verständlichkeit. Bei Abweichungen ist die deutsche Fassung massgebend.':'Translations are provided for convenience. In case of discrepancies, the German version prevails.',
    '1. Anbieterin und Geltungsbereich':'1. Provider and scope','2. Vertragsabschluss':'2. Contract formation','3. Registrierung und Vertretungsberechtigung':'3. Registration and authority to represent','4. Leistungsumfang und Pläne':'4. Scope of services and plans','5. Testphase':'5. Trial period','6. Preise, Steuern und Zahlung':'6. Prices, taxes and payment','7. Zahlungsverzug und Sperrung':'7. Payment default and suspension','8. Laufzeit, Verlängerung und Kündigung':'8. Term, renewal and termination','9. Planwechsel':'9. Plan changes','10. Zulässige Nutzung':'10. Permitted use','11. Kundendaten und Verantwortung':'11. Customer data and responsibility','12. Auftragsbearbeitung und Datenschutz':'12. Data processing and privacy','13. Datenausgabe und Datenlöschung':'13. Data export and deletion','14. Verfügbarkeit, Wartung und Änderungen':'14. Availability, maintenance and changes','15. Support':'15. Support','16. Rechte an Binso One':'16. Rights in Binso One','17. Gewährleistung und Haftung':'17. Warranty and liability','18. Preis- und Vertragsänderungen':'18. Price and contract changes','19. Übertragung und Beizug Dritter':'19. Assignment and third parties','20. Schlussbestimmungen':'20. Final provisions','21. Kontakt':'21. Contact',
    '1. Gegenstand und Geltung':'1. Subject matter and scope','2. Gegenstand, Dauer und Zweck':'2. Subject matter, duration and purpose','3. Datenarten und betroffene Personen':'3. Data types and data subjects','4. Weisungen':'4. Instructions','5. Vertraulichkeit und Zugriff':'5. Confidentiality and access','6. Technische und organisatorische Massnahmen':'6. Technical and organisational measures','7. Unterauftragsbearbeiter':'7. Subprocessors','8. Auslandbearbeitung':'8. Processing abroad','9. Unterstützung des Kunden':'9. Customer assistance','10. Datenschutzverletzungen':'10. Data security breaches','11. Rückgabe, Export und Löschung':'11. Return, export and deletion','12. Nachweise und Prüfungen':'12. Evidence and audits','13. Rangfolge':'13. Order of precedence','14. Kontakt':'14. Contact',
    '1. Verantwortliche Stelle':'1. Controller','2. Welche Daten wir bearbeiten':'2. Data we process','3. Herkunft der Daten':'3. Sources of data','4. Zwecke der Bearbeitung':'4. Purposes of processing','5. Anmeldung und Benutzerkonto':'5. Sign-in and user account','6. Hosting, Datenbank und Betrieb':'6. Hosting, database and operations','7. Zahlungen und Abonnemente':'7. Payments and subscriptions','8. E-Mail-Versand':'8. Email sending','9. Cookies und lokale Speicherung':'9. Cookies and local storage','10. Empfänger und Unterauftragsbearbeiter':'10. Recipients and subprocessors','11. Bekanntgabe ins Ausland':'11. Disclosure abroad','12. Aufbewahrung und Löschung':'12. Retention and deletion','13. Datenausgabe und Vertragsende':'13. Data export and end of contract','14. Rechte betroffener Personen':'14. Rights of data subjects','15. Automatisierte Einzelentscheidungen':'15. Automated individual decisions','16. Datensicherheit':'16. Data security','17. Dienstleister im Überblick':'17. Service provider overview','18. Änderungen':'18. Changes',
    'Allgemeine Geschäftsbedingungen':'Terms and Conditions','Datenschutzerklärung':'Privacy Policy','Auftragsbearbeitungsvereinbarung':'Data Processing Agreement','Cookie- und Speicher-Richtlinie':'Cookie and Storage Policy','Unterauftragsbearbeiter und Datenstandorte für Binso One.':'Subprocessors and data locations for Binso One.',
  },
  tr: {
    'Rechtliches':'Yasal','Übersetzungen dienen der besseren Verständlichkeit. Bei Abweichungen ist die deutsche Fassung massgebend.':'Çeviriler anlaşılabilirliği kolaylaştırmak amacıyla sunulur. Farklılık olması hâlinde Almanca sürüm geçerlidir.',
    '1. Anbieterin und Geltungsbereich':'1. Sağlayıcı ve kapsam','2. Vertragsabschluss':'2. Sözleşmenin kurulması','3. Registrierung und Vertretungsberechtigung':'3. Kayıt ve temsil yetkisi','4. Leistungsumfang und Pläne':'4. Hizmet kapsamı ve planlar','5. Testphase':'5. Deneme süresi','6. Preise, Steuern und Zahlung':'6. Fiyatlar, vergiler ve ödeme','7. Zahlungsverzug und Sperrung':'7. Ödeme gecikmesi ve askıya alma','8. Laufzeit, Verlängerung und Kündigung':'8. Süre, yenileme ve fesih','9. Planwechsel':'9. Plan değişikliği','10. Zulässige Nutzung':'10. İzin verilen kullanım','11. Kundendaten und Verantwortung':'11. Müşteri verileri ve sorumluluk','12. Auftragsbearbeitung und Datenschutz':'12. Veri işleme ve gizlilik','13. Datenausgabe und Datenlöschung':'13. Veri dışa aktarma ve silme','14. Verfügbarkeit, Wartung und Änderungen':'14. Kullanılabilirlik, bakım ve değişiklikler','15. Support':'15. Destek','16. Rechte an Binso One':'16. Binso One üzerindeki haklar','17. Gewährleistung und Haftung':'17. Garanti ve sorumluluk','18. Preis- und Vertragsänderungen':'18. Fiyat ve sözleşme değişiklikleri','19. Übertragung und Beizug Dritter':'19. Devir ve üçüncü kişiler','20. Schlussbestimmungen':'20. Son hükümler','21. Kontakt':'21. İletişim',
    '1. Gegenstand und Geltung':'1. Konu ve kapsam','2. Gegenstand, Dauer und Zweck':'2. Konu, süre ve amaç','3. Datenarten und betroffene Personen':'3. Veri türleri ve ilgili kişiler','4. Weisungen':'4. Talimatlar','5. Vertraulichkeit und Zugriff':'5. Gizlilik ve erişim','6. Technische und organisatorische Massnahmen':'6. Teknik ve organizasyonel önlemler','7. Unterauftragsbearbeiter':'7. Alt işleyenler','8. Auslandbearbeitung':'8. Yurt dışında işleme','9. Unterstützung des Kunden':'9. Müşteriye destek','10. Datenschutzverletzungen':'10. Veri güvenliği ihlalleri','11. Rückgabe, Export und Löschung':'11. İade, dışa aktarma ve silme','12. Nachweise und Prüfungen':'12. Kanıtlar ve denetimler','13. Rangfolge':'13. Öncelik sırası','14. Kontakt':'14. İletişim',
    '1. Verantwortliche Stelle':'1. Veri sorumlusu','2. Welche Daten wir bearbeiten':'2. İşlediğimiz veriler','3. Herkunft der Daten':'3. Verilerin kaynağı','4. Zwecke der Bearbeitung':'4. İşleme amaçları','5. Anmeldung und Benutzerkonto':'5. Giriş ve kullanıcı hesabı','6. Hosting, Datenbank und Betrieb':'6. Barındırma, veritabanı ve işletim','7. Zahlungen und Abonnemente':'7. Ödemeler ve abonelikler','8. E-Mail-Versand':'8. E-posta gönderimi','9. Cookies und lokale Speicherung':'9. Çerezler ve yerel depolama','10. Empfänger und Unterauftragsbearbeiter':'10. Alıcılar ve alt işleyenler','11. Bekanntgabe ins Ausland':'11. Yurt dışına aktarım','12. Aufbewahrung und Löschung':'12. Saklama ve silme','13. Datenausgabe und Vertragsende':'13. Veri dışa aktarma ve sözleşme sonu','14. Rechte betroffener Personen':'14. İlgili kişilerin hakları','15. Automatisierte Einzelentscheidungen':'15. Otomatik bireysel kararlar','16. Datensicherheit':'16. Veri güvenliği','17. Dienstleister im Überblick':'17. Hizmet sağlayıcılar özeti','18. Änderungen':'18. Değişiklikler',
    'Allgemeine Geschäftsbedingungen':'Genel Şartlar','Datenschutzerklärung':'Gizlilik Bildirimi','Auftragsbearbeitungsvereinbarung':'Veri İşleme Sözleşmesi','Cookie- und Speicher-Richtlinie':'Çerez ve Depolama Politikası','Unterauftragsbearbeiter und Datenstandorte für Binso One.':'Binso One için alt işleyenler ve veri konumları.',
  },
} satisfies Record<Exclude<Locale, 'de'>, Catalog>

export const legalCopy = headings
