import type { Locale } from './config'
import { publicCopy } from './public-copy'
import { authCopy } from './auth-copy'
import { appCopy } from './app-copy'
import { legalCopy } from './legal-copy'

type Catalog = Record<string, string>

const fr: Catalog = {
  'Funktionen':'Fonctionnalités','Preise':'Tarifs','FAQ':'FAQ','Kontakt':'Contact','Anmelden':'Se connecter','30 Tage kostenlos testen':'Essai gratuit pendant 30 jours','30 Tage kostenlos testen →':'Essai gratuit pendant 30 jours →','So funktioniert es':'Comment ça marche','Sicherheit':'Sécurité','Admin-Zugang':'Accès admin','Produkt':'Produit','Support':'Assistance','Rechtliches':'Mentions légales','Datenschutz':'Protection des données','AGB':'CG','Auftragsbearbeitung':'Traitement des données','Unterauftragsbearbeiter':'Sous-traitants','Impressum':'Mentions légales','Systemstatus':'État du système','Konto erstellen':'Créer un compte','Cookie-Einstellungen':'Paramètres des cookies',
  'Bereit für Binso One?':'Prêt pour Binso One ?','Einfach starten. Erfolgreicher arbeiten.':'Démarrez simplement. Travaillez plus efficacement.','30 Tage kostenlos testen. Keine Zahlungsdaten beim Start.':'Essai gratuit pendant 30 jours. Aucune donnée de paiement au départ.','Demo ansehen':'Voir la démo','Navigation öffnen':'Ouvrir la navigation','Navigation schliessen':'Fermer la navigation','Hauptnavigation':'Navigation principale','Mobile Navigation':'Navigation mobile',
  'Einfacher arbeiten.':'Travaillez plus simplement.','Erfolgreicher wachsen.':'Développez-vous avec succès.','Für Schweizer Dienstleistungsunternehmen':'Pour les entreprises suisses de services','Weniger Administration. Mehr Zeit für die eigentliche Arbeit.':'Moins d’administration. Plus de temps pour votre vrai travail.','Vom Kunden bis zur Rechnung.':'Du client à la facture.','Alles, was deinen Arbeitsablauf verbindet.':'Tout ce qui relie votre flux de travail.','Projektmanagement':'Gestion de projets','Zeiterfassung':'Saisie du temps','Abrechnung':'Facturation','Kunden':'Clients','Angebote':'Offres','Aufträge':'Mandats','Rechnungen':'Factures','Finanzen':'Finances','Mitarbeitende':'Collaborateurs','Einstellungen':'Paramètres','Übersicht':'Aperçu','Arbeit':'Travail','Zeit':'Temps','Mehr':'Plus','Verträge':'Contrats','Offene Posten':'Postes ouverts','Daten':'Données','Organisation':'Organisation','Mein Konto':'Mon compte','Plattform':'Plateforme',
  'Suchen':'Rechercher','Suche öffnen':'Ouvrir la recherche','Neu erstellen':'Créer','Benachrichtigungen':'Notifications','Profil öffnen':'Ouvrir le profil','Demo-Arbeitsbereich':'Espace de démonstration','Fiktive Beispieldaten · keine Abrechnung oder externen Aktionen':'Données fictives · aucune facturation ni action externe',
  'Willkommen zurück':'Bon retour','Kunden-Login':'Connexion client','Mit E-Mail anmelden':'Se connecter par e-mail','Mit Microsoft anmelden':'Se connecter avec Microsoft','Noch kein Konto?':'Pas encore de compte ?','Zur Registrierung':'Créer un compte','E-Mail':'E-mail','Passwort':'Mot de passe','Weiter':'Continuer','Zurück':'Retour','Abbrechen':'Annuler','Speichern':'Enregistrer','Löschen':'Supprimer','Bearbeiten':'Modifier','Erstellen':'Créer','Neu':'Nouveau','Alle':'Tous','Aktiv':'Actif','In Bearbeitung':'En cours','Offen':'Ouvert','Abgeschlossen':'Terminé','Bezahlt':'Payé','Entwurf':'Brouillon','Gesendet':'Envoyé','Angenommen':'Accepté','Abgelehnt':'Refusé','Gekündigt':'Résilié','Pausiert':'En pause',
  'Unternehmen':'Entreprise','Firmenname':'Nom de l’entreprise','Vor- und Nachname':'Prénom et nom','Adresse':'Adresse','Strasse und Hausnummer':'Rue et numéro','PLZ':'NPA','Ort':'Localité','Land':'Pays','Telefon':'Téléphone','Bestätigen und weiter':'Confirmer et continuer','Angaben ändern':'Modifier les données','Unternehmen bestätigen':'Confirmer l’entreprise','Unternehmen ergänzen':'Compléter l’entreprise','Deine Eingaben werden beim Weitergehen gespeichert.':'Vos saisies sont enregistrées lorsque vous continuez.','Kein Pflichtfeld in diesem Schritt.':'Aucun champ obligatoire à cette étape.',
  'Demo registrieren':'Créer la démo','Demo einrichten':'Configurer la démo','Produktdemo':'Démo produit','Direkt abonnieren':'S’abonner directement','Abo abschliessen':'Souscrire','Abo aktivieren':'Activer l’abonnement','Abonnement aktivieren':'Activer l’abonnement','Weiter zum Abo':'Continuer vers l’abonnement','Keine Zahlungsdaten beim Start':'Aucune donnée de paiement au départ','Keine Kreditkarte nötig':'Aucune carte de crédit nécessaire','Ohne Karte':'Sans carte',
  'Datenschutzerklärung':'Déclaration de protection des données','Allgemeine Geschäftsbedingungen':'Conditions générales','Auftragsbearbeitungsvereinbarung':'Accord de traitement des données','Cookie-Richtlinie':'Politique relative aux cookies','Cookie-Informationen':'Informations sur les cookies','Alle akzeptieren':'Tout accepter','Nur notwendige':'Nécessaires uniquement','Notwendig':'Nécessaire','Statistik':'Statistiques','Immer aktiv':'Toujours actif','Optionale Statistik':'Statistiques facultatives','Du entscheidest, ob optionale Statistik verwendet werden darf.':'Vous décidez si les statistiques facultatives peuvent être utilisées.',
  'Hilfe':'Aide','Wo finde ich Hilfe?':'Où trouver de l’aide ?','Antworten auf häufige Fragen zu Nutzung, Anmeldung und Abrechnung.':'Réponses aux questions fréquentes sur l’utilisation, la connexion et la facturation.','Sprich mit Binso.':'Parlez à Binso.','Nachricht':'Message','Nachricht senden':'Envoyer le message','Thema':'Sujet','Allgemeine Anfrage':'Demande générale','Danke. Deine Nachricht wurde an Binso übermittelt.':'Merci. Votre message a été transmis à Binso.',
  'Keine Treffer.':'Aucun résultat.','Erneut versuchen':'Réessayer','Seite nicht gefunden':'Page introuvable','Die angeforderte Seite existiert nicht oder wurde verschoben.':'La page demandée n’existe pas ou a été déplacée.','Zum Dashboard':'Vers le tableau de bord','Zur Startseite':'Vers l’accueil',
  'Kunde':'Client','Kunde *':'Client *','Kunde erfassen':'Ajouter un client','Kunde speichern':'Enregistrer le client','Kunden suchen …':'Rechercher des clients…','Angebot':'Offre','Angebot erstellen':'Créer une offre','Angebot bearbeiten':'Modifier l’offre','Angebot versenden':'Envoyer l’offre','Auftrag':'Mandat','Auftrag erstellen':'Créer un mandat','Auftrag bearbeiten':'Modifier le mandat','Rechnung':'Facture','Rechnung erstellen':'Créer une facture','Rechnung bearbeiten':'Modifier la facture','Zeit erfassen':'Saisir le temps','Heute':'Aujourd’hui','Diese Woche':'Cette semaine','Monatlich':'Mensuel','Jährlich':'Annuel','Fällig':'Échéance','Status':'Statut','Name':'Nom','Firma':'Entreprise','Notiz':'Note','Positionen':'Postes','Menge':'Quantité','Preis':'Prix','MWST':'TVA','Total':'Total','Export':'Exporter','Import':'Importer','PDF':'PDF','E-Mail senden':'Envoyer l’e-mail',
  'Sprache':'Langue','Sprache ändern':'Changer de langue','Automatisch':'Automatique','Deutsch':'Allemand','Français':'Français','Italiano':'Italien','English':'Anglais','Türkçe':'Turc',
}

const it: Catalog = {
  'Funktionen':'Funzionalità','Preise':'Prezzi','FAQ':'FAQ','Kontakt':'Contatto','Anmelden':'Accedi','30 Tage kostenlos testen':'Prova gratuita per 30 giorni','30 Tage kostenlos testen →':'Prova gratuita per 30 giorni →','So funktioniert es':'Come funziona','Sicherheit':'Sicurezza','Admin-Zugang':'Accesso admin','Produkt':'Prodotto','Support':'Supporto','Rechtliches':'Aspetti legali','Datenschutz':'Protezione dei dati','AGB':'CG','Auftragsbearbeitung':'Trattamento dei dati','Unterauftragsbearbeiter':'Sub-responsabili','Impressum':'Impressum','Systemstatus':'Stato del sistema','Konto erstellen':'Crea account','Cookie-Einstellungen':'Impostazioni cookie',
  'Bereit für Binso One?':'Pronto per Binso One?','Einfach starten. Erfolgreicher arbeiten.':'Inizia facilmente. Lavora meglio.','30 Tage kostenlos testen. Keine Zahlungsdaten beim Start.':'Prova gratuita per 30 giorni. Nessun dato di pagamento all’inizio.','Demo ansehen':'Guarda la demo','Navigation öffnen':'Apri navigazione','Navigation schliessen':'Chiudi navigazione','Hauptnavigation':'Navigazione principale','Mobile Navigation':'Navigazione mobile',
  'Einfacher arbeiten.':'Lavora in modo più semplice.','Erfolgreicher wachsen.':'Cresci con successo.','Für Schweizer Dienstleistungsunternehmen':'Per aziende svizzere di servizi','Weniger Administration. Mehr Zeit für die eigentliche Arbeit.':'Meno amministrazione. Più tempo per il lavoro che conta.','Vom Kunden bis zur Rechnung.':'Dal cliente alla fattura.','Alles, was deinen Arbeitsablauf verbindet.':'Tutto ciò che collega il tuo flusso di lavoro.','Projektmanagement':'Gestione progetti','Zeiterfassung':'Registrazione del tempo','Abrechnung':'Fatturazione','Kunden':'Clienti','Angebote':'Offerte','Aufträge':'Mandati','Rechnungen':'Fatture','Finanzen':'Finanze','Mitarbeitende':'Collaboratori','Einstellungen':'Impostazioni','Übersicht':'Panoramica','Arbeit':'Lavoro','Zeit':'Tempo','Mehr':'Altro','Verträge':'Contratti','Offene Posten':'Partite aperte','Daten':'Dati','Organisation':'Organizzazione','Mein Konto':'Il mio account','Plattform':'Piattaforma',
  'Suchen':'Cerca','Suche öffnen':'Apri ricerca','Neu erstellen':'Crea','Benachrichtigungen':'Notifiche','Profil öffnen':'Apri profilo','Demo-Arbeitsbereich':'Area demo','Fiktive Beispieldaten · keine Abrechnung oder externen Aktionen':'Dati di esempio fittizi · nessuna fatturazione o azione esterna',
  'Willkommen zurück':'Bentornato','Kunden-Login':'Accesso clienti','Mit E-Mail anmelden':'Accedi con e-mail','Mit Microsoft anmelden':'Accedi con Microsoft','Noch kein Konto?':'Non hai ancora un account?','Zur Registrierung':'Alla registrazione','E-Mail':'E-mail','Passwort':'Password','Weiter':'Continua','Zurück':'Indietro','Abbrechen':'Annulla','Speichern':'Salva','Löschen':'Elimina','Bearbeiten':'Modifica','Erstellen':'Crea','Neu':'Nuovo','Alle':'Tutti','Aktiv':'Attivo','In Bearbeitung':'In lavorazione','Offen':'Aperto','Abgeschlossen':'Completato','Bezahlt':'Pagato','Entwurf':'Bozza','Gesendet':'Inviato','Angenommen':'Accettato','Abgelehnt':'Rifiutato','Gekündigt':'Disdetto','Pausiert':'In pausa',
  'Unternehmen':'Azienda','Firmenname':'Nome azienda','Vor- und Nachname':'Nome e cognome','Adresse':'Indirizzo','Strasse und Hausnummer':'Via e numero civico','PLZ':'NPA','Ort':'Località','Land':'Paese','Telefon':'Telefono','Bestätigen und weiter':'Conferma e continua','Angaben ändern':'Modifica dati','Unternehmen bestätigen':'Conferma azienda','Unternehmen ergänzen':'Completa azienda','Deine Eingaben werden beim Weitergehen gespeichert.':'I dati inseriti vengono salvati quando continui.','Kein Pflichtfeld in diesem Schritt.':'Nessun campo obbligatorio in questo passaggio.',
  'Demo registrieren':'Crea demo','Demo einrichten':'Configura demo','Produktdemo':'Demo prodotto','Direkt abonnieren':'Abbonati direttamente','Abo abschliessen':'Sottoscrivi','Abo aktivieren':'Attiva abbonamento','Abonnement aktivieren':'Attiva abbonamento','Weiter zum Abo':'Continua all’abbonamento','Keine Zahlungsdaten beim Start':'Nessun dato di pagamento all’inizio','Keine Kreditkarte nötig':'Nessuna carta di credito necessaria','Ohne Karte':'Senza carta',
  'Datenschutzerklärung':'Informativa sulla protezione dei dati','Allgemeine Geschäftsbedingungen':'Condizioni generali','Auftragsbearbeitungsvereinbarung':'Accordo sul trattamento dei dati','Cookie-Richtlinie':'Informativa sui cookie','Cookie-Informationen':'Informazioni sui cookie','Alle akzeptieren':'Accetta tutti','Nur notwendige':'Solo necessari','Notwendig':'Necessario','Statistik':'Statistiche','Immer aktiv':'Sempre attivo','Optionale Statistik':'Statistiche facoltative','Du entscheidest, ob optionale Statistik verwendet werden darf.':'Decidi tu se consentire le statistiche facoltative.',
  'Hilfe':'Aiuto','Wo finde ich Hilfe?':'Dove trovo aiuto?','Antworten auf häufige Fragen zu Nutzung, Anmeldung und Abrechnung.':'Risposte alle domande frequenti su utilizzo, accesso e fatturazione.','Sprich mit Binso.':'Parla con Binso.','Nachricht':'Messaggio','Nachricht senden':'Invia messaggio','Thema':'Tema','Allgemeine Anfrage':'Richiesta generale','Danke. Deine Nachricht wurde an Binso übermittelt.':'Grazie. Il tuo messaggio è stato inviato a Binso.',
  'Keine Treffer.':'Nessun risultato.','Erneut versuchen':'Riprova','Seite nicht gefunden':'Pagina non trovata','Die angeforderte Seite existiert nicht oder wurde verschoben.':'La pagina richiesta non esiste o è stata spostata.','Zum Dashboard':'Alla dashboard','Zur Startseite':'Alla pagina iniziale',
  'Kunde':'Cliente','Kunde *':'Cliente *','Kunde erfassen':'Aggiungi cliente','Kunde speichern':'Salva cliente','Kunden suchen …':'Cerca clienti…','Angebot':'Offerta','Angebot erstellen':'Crea offerta','Angebot bearbeiten':'Modifica offerta','Angebot versenden':'Invia offerta','Auftrag':'Mandato','Auftrag erstellen':'Crea mandato','Auftrag bearbeiten':'Modifica mandato','Rechnung':'Fattura','Rechnung erstellen':'Crea fattura','Rechnung bearbeiten':'Modifica fattura','Zeit erfassen':'Registra tempo','Heute':'Oggi','Diese Woche':'Questa settimana','Monatlich':'Mensile','Jährlich':'Annuale','Fällig':'Scadenza','Status':'Stato','Name':'Nome','Firma':'Azienda','Notiz':'Nota','Positionen':'Posizioni','Menge':'Quantità','Preis':'Prezzo','MWST':'IVA','Total':'Totale','Export':'Esporta','Import':'Importa','PDF':'PDF','E-Mail senden':'Invia e-mail',
  'Sprache':'Lingua','Sprache ändern':'Cambia lingua','Automatisch':'Automatico','Deutsch':'Tedesco','Français':'Francese','Italiano':'Italiano','English':'Inglese','Türkçe':'Turco',
}

const en: Catalog = {
  'Funktionen':'Features','Preise':'Pricing','FAQ':'FAQ','Kontakt':'Contact','Anmelden':'Sign in','30 Tage kostenlos testen':'Try free for 30 days','30 Tage kostenlos testen →':'Try free for 30 days →','So funktioniert es':'How it works','Sicherheit':'Security','Admin-Zugang':'Admin access','Produkt':'Product','Support':'Support','Rechtliches':'Legal','Datenschutz':'Privacy','AGB':'Terms','Auftragsbearbeitung':'Data processing','Unterauftragsbearbeiter':'Subprocessors','Impressum':'Imprint','Systemstatus':'System status','Konto erstellen':'Create account','Cookie-Einstellungen':'Cookie settings',
  'Bereit für Binso One?':'Ready for Binso One?','Einfach starten. Erfolgreicher arbeiten.':'Start simply. Work more successfully.','30 Tage kostenlos testen. Keine Zahlungsdaten beim Start.':'Try free for 30 days. No payment details required to start.','Demo ansehen':'View demo','Navigation öffnen':'Open navigation','Navigation schliessen':'Close navigation','Hauptnavigation':'Main navigation','Mobile Navigation':'Mobile navigation',
  'Einfacher arbeiten.':'Work more simply.','Erfolgreicher wachsen.':'Grow successfully.','Für Schweizer Dienstleistungsunternehmen':'For Swiss service companies','Weniger Administration. Mehr Zeit für die eigentliche Arbeit.':'Less administration. More time for the work that matters.','Vom Kunden bis zur Rechnung.':'From customer to invoice.','Alles, was deinen Arbeitsablauf verbindet.':'Everything that connects your workflow.','Projektmanagement':'Project management','Zeiterfassung':'Time tracking','Abrechnung':'Billing','Kunden':'Customers','Angebote':'Quotes','Aufträge':'Orders','Rechnungen':'Invoices','Finanzen':'Finance','Mitarbeitende':'Employees','Einstellungen':'Settings','Übersicht':'Overview','Arbeit':'Work','Zeit':'Time','Mehr':'More','Verträge':'Contracts','Offene Posten':'Open items','Daten':'Data','Organisation':'Organisation','Mein Konto':'My account','Plattform':'Platform',
  'Suchen':'Search','Suche öffnen':'Open search','Neu erstellen':'Create new','Benachrichtigungen':'Notifications','Profil öffnen':'Open profile','Demo-Arbeitsbereich':'Demo workspace','Fiktive Beispieldaten · keine Abrechnung oder externen Aktionen':'Fictitious sample data · no billing or external actions',
  'Willkommen zurück':'Welcome back','Kunden-Login':'Customer sign-in','Mit E-Mail anmelden':'Sign in with email','Mit Microsoft anmelden':'Sign in with Microsoft','Noch kein Konto?':'No account yet?','Zur Registrierung':'Create account','E-Mail':'Email','Passwort':'Password','Weiter':'Continue','Zurück':'Back','Abbrechen':'Cancel','Speichern':'Save','Löschen':'Delete','Bearbeiten':'Edit','Erstellen':'Create','Neu':'New','Alle':'All','Aktiv':'Active','In Bearbeitung':'In progress','Offen':'Open','Abgeschlossen':'Completed','Bezahlt':'Paid','Entwurf':'Draft','Gesendet':'Sent','Angenommen':'Accepted','Abgelehnt':'Declined','Gekündigt':'Cancelled','Pausiert':'Paused',
  'Unternehmen':'Company','Firmenname':'Company name','Vor- und Nachname':'Full name','Adresse':'Address','Strasse und Hausnummer':'Street and number','PLZ':'Postal code','Ort':'City','Land':'Country','Telefon':'Phone','Bestätigen und weiter':'Confirm and continue','Angaben ändern':'Edit details','Unternehmen bestätigen':'Confirm company','Unternehmen ergänzen':'Complete company','Deine Eingaben werden beim Weitergehen gespeichert.':'Your entries are saved when you continue.','Kein Pflichtfeld in diesem Schritt.':'No required field in this step.',
  'Demo registrieren':'Create demo','Demo einrichten':'Set up demo','Produktdemo':'Product demo','Direkt abonnieren':'Subscribe directly','Abo abschliessen':'Subscribe','Abo aktivieren':'Activate subscription','Abonnement aktivieren':'Activate subscription','Weiter zum Abo':'Continue to subscription','Keine Zahlungsdaten beim Start':'No payment details required to start','Keine Kreditkarte nötig':'No credit card required','Ohne Karte':'No card',
  'Datenschutzerklärung':'Privacy policy','Allgemeine Geschäftsbedingungen':'Terms and conditions','Auftragsbearbeitungsvereinbarung':'Data processing agreement','Cookie-Richtlinie':'Cookie policy','Cookie-Informationen':'Cookie information','Alle akzeptieren':'Accept all','Nur notwendige':'Necessary only','Notwendig':'Necessary','Statistik':'Analytics','Immer aktiv':'Always active','Optionale Statistik':'Optional analytics','Du entscheidest, ob optionale Statistik verwendet werden darf.':'You decide whether optional analytics may be used.',
  'Hilfe':'Help','Wo finde ich Hilfe?':'Where can I find help?','Antworten auf häufige Fragen zu Nutzung, Anmeldung und Abrechnung.':'Answers to common questions about use, sign-in and billing.','Sprich mit Binso.':'Talk to Binso.','Nachricht':'Message','Nachricht senden':'Send message','Thema':'Topic','Allgemeine Anfrage':'General enquiry','Danke. Deine Nachricht wurde an Binso übermittelt.':'Thank you. Your message has been sent to Binso.',
  'Keine Treffer.':'No results.','Erneut versuchen':'Try again','Seite nicht gefunden':'Page not found','Die angeforderte Seite existiert nicht oder wurde verschoben.':'The requested page does not exist or has been moved.','Zum Dashboard':'Go to dashboard','Zur Startseite':'Go to home page',
  'Kunde':'Customer','Kunde *':'Customer *','Kunde erfassen':'Add customer','Kunde speichern':'Save customer','Kunden suchen …':'Search customers…','Angebot':'Quote','Angebot erstellen':'Create quote','Angebot bearbeiten':'Edit quote','Angebot versenden':'Send quote','Auftrag':'Order','Auftrag erstellen':'Create order','Auftrag bearbeiten':'Edit order','Rechnung':'Invoice','Rechnung erstellen':'Create invoice','Rechnung bearbeiten':'Edit invoice','Zeit erfassen':'Track time','Heute':'Today','Diese Woche':'This week','Monatlich':'Monthly','Jährlich':'Yearly','Fällig':'Due','Status':'Status','Name':'Name','Firma':'Company','Notiz':'Note','Positionen':'Line items','Menge':'Quantity','Preis':'Price','MWST':'VAT','Total':'Total','Export':'Export','Import':'Import','PDF':'PDF','E-Mail senden':'Send email',
  'Sprache':'Language','Sprache ändern':'Change language','Automatisch':'Automatic','Deutsch':'German','Français':'French','Italiano':'Italian','English':'English','Türkçe':'Turkish',
}

const tr: Catalog = {
  'Funktionen':'Özellikler','Preise':'Fiyatlar','FAQ':'SSS','Kontakt':'İletişim','Anmelden':'Giriş yap','30 Tage kostenlos testen':'30 gün ücretsiz deneyin','30 Tage kostenlos testen →':'30 gün ücretsiz deneyin →','So funktioniert es':'Nasıl çalışır','Sicherheit':'Güvenlik','Admin-Zugang':'Yönetici girişi','Produkt':'Ürün','Support':'Destek','Rechtliches':'Yasal','Datenschutz':'Gizlilik','AGB':'Şartlar','Auftragsbearbeitung':'Veri işleme','Unterauftragsbearbeiter':'Alt işleyenler','Impressum':'Künye','Systemstatus':'Sistem durumu','Konto erstellen':'Hesap oluştur','Cookie-Einstellungen':'Çerez ayarları',
  'Bereit für Binso One?':'Binso One için hazır mısınız?','Einfach starten. Erfolgreicher arbeiten.':'Kolay başlayın. Daha verimli çalışın.','30 Tage kostenlos testen. Keine Zahlungsdaten beim Start.':'30 gün ücretsiz deneyin. Başlangıçta ödeme bilgisi gerekmez.','Demo ansehen':'Demoyu görüntüle','Navigation öffnen':'Menüyü aç','Navigation schliessen':'Menüyü kapat','Hauptnavigation':'Ana menü','Mobile Navigation':'Mobil menü',
  'Einfacher arbeiten.':'Daha kolay çalışın.','Erfolgreicher wachsen.':'Başarıyla büyüyün.','Für Schweizer Dienstleistungsunternehmen':'İsviçre hizmet şirketleri için','Weniger Administration. Mehr Zeit für die eigentliche Arbeit.':'Daha az idari iş. Asıl işe daha fazla zaman.','Vom Kunden bis zur Rechnung.':'Müşteriden faturaya.','Alles, was deinen Arbeitsablauf verbindet.':'İş akışınızı birbirine bağlayan her şey.','Projektmanagement':'Proje yönetimi','Zeiterfassung':'Zaman takibi','Abrechnung':'Faturalama','Kunden':'Müşteriler','Angebote':'Teklifler','Aufträge':'İşler','Rechnungen':'Faturalar','Finanzen':'Finans','Mitarbeitende':'Çalışanlar','Einstellungen':'Ayarlar','Übersicht':'Genel bakış','Arbeit':'İş','Zeit':'Zaman','Mehr':'Daha fazla','Verträge':'Sözleşmeler','Offene Posten':'Açık kalemler','Daten':'Veriler','Organisation':'Organizasyon','Mein Konto':'Hesabım','Plattform':'Platform',
  'Suchen':'Ara','Suche öffnen':'Aramayı aç','Neu erstellen':'Yeni oluştur','Benachrichtigungen':'Bildirimler','Profil öffnen':'Profili aç','Demo-Arbeitsbereich':'Demo çalışma alanı','Fiktive Beispieldaten · keine Abrechnung oder externen Aktionen':'Kurgusal örnek veriler · faturalama veya harici işlem yok',
  'Willkommen zurück':'Tekrar hoş geldiniz','Kunden-Login':'Müşteri girişi','Mit E-Mail anmelden':'E-posta ile giriş yap','Mit Microsoft anmelden':'Microsoft ile giriş yap','Noch kein Konto?':'Henüz hesabınız yok mu?','Zur Registrierung':'Kayıt ol','E-Mail':'E-posta','Passwort':'Parola','Weiter':'Devam','Zurück':'Geri','Abbrechen':'İptal','Speichern':'Kaydet','Löschen':'Sil','Bearbeiten':'Düzenle','Erstellen':'Oluştur','Neu':'Yeni','Alle':'Tümü','Aktiv':'Aktif','In Bearbeitung':'İşleniyor','Offen':'Açık','Abgeschlossen':'Tamamlandı','Bezahlt':'Ödendi','Entwurf':'Taslak','Gesendet':'Gönderildi','Angenommen':'Kabul edildi','Abgelehnt':'Reddedildi','Gekündigt':'İptal edildi','Pausiert':'Duraklatıldı',
  'Unternehmen':'Şirket','Firmenname':'Şirket adı','Vor- und Nachname':'Ad ve soyad','Adresse':'Adres','Strasse und Hausnummer':'Sokak ve kapı numarası','PLZ':'Posta kodu','Ort':'Şehir','Land':'Ülke','Telefon':'Telefon','Bestätigen und weiter':'Onayla ve devam et','Angaben ändern':'Bilgileri değiştir','Unternehmen bestätigen':'Şirketi onayla','Unternehmen ergänzen':'Şirket bilgilerini tamamla','Deine Eingaben werden beim Weitergehen gespeichert.':'Devam ettiğinizde girdileriniz kaydedilir.','Kein Pflichtfeld in diesem Schritt.':'Bu adımda zorunlu alan yok.',
  'Demo registrieren':'Demo oluştur','Demo einrichten':'Demoyu kur','Produktdemo':'Ürün demosu','Direkt abonnieren':'Doğrudan abone ol','Abo abschliessen':'Abone ol','Abo aktivieren':'Aboneliği etkinleştir','Abonnement aktivieren':'Aboneliği etkinleştir','Weiter zum Abo':'Aboneliğe devam et','Keine Zahlungsdaten beim Start':'Başlangıçta ödeme bilgisi gerekmez','Keine Kreditkarte nötig':'Kredi kartı gerekmez','Ohne Karte':'Kartsız',
  'Datenschutzerklärung':'Gizlilik bildirimi','Allgemeine Geschäftsbedingungen':'Genel şartlar','Auftragsbearbeitungsvereinbarung':'Veri işleme sözleşmesi','Cookie-Richtlinie':'Çerez politikası','Cookie-Informationen':'Çerez bilgileri','Alle akzeptieren':'Tümünü kabul et','Nur notwendige':'Yalnızca gerekli','Notwendig':'Gerekli','Statistik':'İstatistik','Immer aktiv':'Her zaman aktif','Optionale Statistik':'İsteğe bağlı istatistik','Du entscheidest, ob optionale Statistik verwendet werden darf.':'İsteğe bağlı istatistiklerin kullanılıp kullanılmayacağına siz karar verirsiniz.',
  'Hilfe':'Yardım','Wo finde ich Hilfe?':'Nereden yardım alabilirim?','Antworten auf häufige Fragen zu Nutzung, Anmeldung und Abrechnung.':'Kullanım, giriş ve faturalama hakkında sık sorulan soruların yanıtları.','Sprich mit Binso.':'Binso ile iletişime geçin.','Nachricht':'Mesaj','Nachricht senden':'Mesaj gönder','Thema':'Konu','Allgemeine Anfrage':'Genel talep','Danke. Deine Nachricht wurde an Binso übermittelt.':'Teşekkürler. Mesajınız Binso’ya iletildi.',
  'Keine Treffer.':'Sonuç yok.','Erneut versuchen':'Tekrar dene','Seite nicht gefunden':'Sayfa bulunamadı','Die angeforderte Seite existiert nicht oder wurde verschoben.':'İstenen sayfa mevcut değil veya taşınmış.','Zum Dashboard':'Kontrol paneline git','Zur Startseite':'Ana sayfaya git',
  'Kunde':'Müşteri','Kunde *':'Müşteri *','Kunde erfassen':'Müşteri ekle','Kunde speichern':'Müşteriyi kaydet','Kunden suchen …':'Müşteri ara…','Angebot':'Teklif','Angebot erstellen':'Teklif oluştur','Angebot bearbeiten':'Teklifi düzenle','Angebot versenden':'Teklifi gönder','Auftrag':'İş','Auftrag erstellen':'İş oluştur','Auftrag bearbeiten':'İşi düzenle','Rechnung':'Fatura','Rechnung erstellen':'Fatura oluştur','Rechnung bearbeiten':'Faturayı düzenle','Zeit erfassen':'Zaman kaydet','Heute':'Bugün','Diese Woche':'Bu hafta','Monatlich':'Aylık','Jährlich':'Yıllık','Fällig':'Vade','Status':'Durum','Name':'Ad','Firma':'Şirket','Notiz':'Not','Positionen':'Kalemler','Menge':'Miktar','Preis':'Fiyat','MWST':'KDV','Total':'Toplam','Export':'Dışa aktar','Import':'İçe aktar','PDF':'PDF','E-Mail senden':'E-posta gönder',
  'Sprache':'Dil','Sprache ändern':'Dili değiştir','Automatisch':'Otomatik','Deutsch':'Almanca','Français':'Fransızca','Italiano':'İtalyanca','English':'İngilizce','Türkçe':'Türkçe',
}

Object.assign(fr, publicCopy.fr, authCopy.fr, appCopy.fr, legalCopy.fr)
Object.assign(it, publicCopy.it, authCopy.it, appCopy.it, legalCopy.it)
Object.assign(en, publicCopy.en, authCopy.en, appCopy.en, legalCopy.en)
Object.assign(tr, publicCopy.tr, authCopy.tr, appCopy.tr, legalCopy.tr)

export const catalogs: Record<Exclude<Locale, 'de'>, Catalog> = { fr, it, en, tr }

const tokenCatalogs: Record<Exclude<Locale, 'de'>, Array<[RegExp, string]>> = {
  fr: [
    [/\bKunden\b/g,'Clients'],[/\bKunde\b/g,'Client'],[/\bAngebote\b/g,'Offres'],[/\bAngebot\b/g,'Offre'],[/\bAufträge\b/g,'Mandats'],[/\bAuftrag\b/g,'Mandat'],[/\bRechnungen\b/g,'Factures'],[/\bRechnung\b/g,'Facture'],[/\bZeiten\b/g,'Temps'],[/\bZahlungen\b/g,'Paiements'],[/\bEinstellungen\b/g,'Paramètres'],[/\bUnternehmen\b/g,'Entreprise'],[/\bSpeichern\b/g,'Enregistrer'],[/\bBearbeiten\b/g,'Modifier'],[/\bLöschen\b/g,'Supprimer'],[/\bErstellen\b/g,'Créer'],[/\bÖffnen\b/g,'Ouvrir'],[/\bSchliessen\b/g,'Fermer'],[/\bZurück\b/g,'Retour'],[/\bWeiter\b/g,'Continuer'],[/\bHeute\b/g,"Aujourd’hui"],[/\bOffen\b/g,'Ouvert'],[/\bAktiv\b/g,'Actif'],[/\bName\b/g,'Nom'],[/\bAdresse\b/g,'Adresse'],[/\bKontakt\b/g,'Contact'],[/\bSupport\b/g,'Assistance'],[/\bSicherheit\b/g,'Sécurité'],[/\bSprache\b/g,'Langue'],
  ],
  it: [
    [/\bKunden\b/g,'Clienti'],[/\bKunde\b/g,'Cliente'],[/\bAngebote\b/g,'Offerte'],[/\bAngebot\b/g,'Offerta'],[/\bAufträge\b/g,'Mandati'],[/\bAuftrag\b/g,'Mandato'],[/\bRechnungen\b/g,'Fatture'],[/\bRechnung\b/g,'Fattura'],[/\bZeiten\b/g,'Tempi'],[/\bZahlungen\b/g,'Pagamenti'],[/\bEinstellungen\b/g,'Impostazioni'],[/\bUnternehmen\b/g,'Azienda'],[/\bSpeichern\b/g,'Salva'],[/\bBearbeiten\b/g,'Modifica'],[/\bLöschen\b/g,'Elimina'],[/\bErstellen\b/g,'Crea'],[/\bÖffnen\b/g,'Apri'],[/\bSchliessen\b/g,'Chiudi'],[/\bZurück\b/g,'Indietro'],[/\bWeiter\b/g,'Continua'],[/\bHeute\b/g,'Oggi'],[/\bOffen\b/g,'Aperto'],[/\bAktiv\b/g,'Attivo'],[/\bName\b/g,'Nome'],[/\bAdresse\b/g,'Indirizzo'],[/\bKontakt\b/g,'Contatto'],[/\bSupport\b/g,'Supporto'],[/\bSicherheit\b/g,'Sicurezza'],[/\bSprache\b/g,'Lingua'],
  ],
  en: [
    [/\bKunden\b/g,'Customers'],[/\bKunde\b/g,'Customer'],[/\bAngebote\b/g,'Quotes'],[/\bAngebot\b/g,'Quote'],[/\bAufträge\b/g,'Orders'],[/\bAuftrag\b/g,'Order'],[/\bRechnungen\b/g,'Invoices'],[/\bRechnung\b/g,'Invoice'],[/\bZeiten\b/g,'Time entries'],[/\bZahlungen\b/g,'Payments'],[/\bEinstellungen\b/g,'Settings'],[/\bUnternehmen\b/g,'Company'],[/\bSpeichern\b/g,'Save'],[/\bBearbeiten\b/g,'Edit'],[/\bLöschen\b/g,'Delete'],[/\bErstellen\b/g,'Create'],[/\bÖffnen\b/g,'Open'],[/\bSchliessen\b/g,'Close'],[/\bZurück\b/g,'Back'],[/\bWeiter\b/g,'Continue'],[/\bHeute\b/g,'Today'],[/\bOffen\b/g,'Open'],[/\bAktiv\b/g,'Active'],[/\bName\b/g,'Name'],[/\bAdresse\b/g,'Address'],[/\bKontakt\b/g,'Contact'],[/\bSupport\b/g,'Support'],[/\bSicherheit\b/g,'Security'],[/\bSprache\b/g,'Language'],
  ],
  tr: [
    [/\bKunden\b/g,'Müşteriler'],[/\bKunde\b/g,'Müşteri'],[/\bAngebote\b/g,'Teklifler'],[/\bAngebot\b/g,'Teklif'],[/\bAufträge\b/g,'İşler'],[/\bAuftrag\b/g,'İş'],[/\bRechnungen\b/g,'Faturalar'],[/\bRechnung\b/g,'Fatura'],[/\bZeiten\b/g,'Zaman kayıtları'],[/\bZahlungen\b/g,'Ödemeler'],[/\bEinstellungen\b/g,'Ayarlar'],[/\bUnternehmen\b/g,'Şirket'],[/\bSpeichern\b/g,'Kaydet'],[/\bBearbeiten\b/g,'Düzenle'],[/\bLöschen\b/g,'Sil'],[/\bErstellen\b/g,'Oluştur'],[/\bÖffnen\b/g,'Aç'],[/\bSchliessen\b/g,'Kapat'],[/\bZurück\b/g,'Geri'],[/\bWeiter\b/g,'Devam'],[/\bHeute\b/g,'Bugün'],[/\bOffen\b/g,'Açık'],[/\bAktiv\b/g,'Aktif'],[/\bName\b/g,'Ad'],[/\bAdresse\b/g,'Adres'],[/\bKontakt\b/g,'İletişim'],[/\bSupport\b/g,'Destek'],[/\bSicherheit\b/g,'Güvenlik'],[/\bSprache\b/g,'Dil'],
  ],
}

export function translateSourceText(source: string, locale: Locale): string {
  if (locale === 'de') return source
  const direct = catalogs[locale][source]
  if (direct) return direct

  // Conservative fallback for short UI strings. Long prose is never word-by-word
  // rewritten because that would produce misleading legal or business copy.
  if (source.length > 90) return source
  let translated = source
  for (const [pattern, replacement] of tokenCatalogs[locale]) translated = translated.replace(pattern, replacement)
  return translated
}
