import type {AppLocale} from "./config";
export const messages={
de:{nav:{home:"Start",customers:"Kunden",offers:"Angebote",invoices:"Rechnungen",payments:"Zahlungen",products:"Produkte",time:"Zeiterfassung",expenses:"Spesen",employees:"Mitarbeiter",features:"Funktionen",pricing:"Preise",login:"Anmelden",admin:"Admin"},common:{back:"Zurück",close:"Schliessen",search:"Suchen",save:"Speichern",cancel:"Abbrechen",more:"Mehr",notifications:"Benachrichtigungen",settings:"Einstellungen",language:"Sprache"},marketing:{tagline:"Business-Software für Schweizer KMU.",trial:"30 Tage kostenlos testen",demo:"Demo starten",productPreview:"Binso One Produktvorschau"}},
fr:{nav:{home:"Accueil",customers:"Clients",offers:"Offres",invoices:"Factures",payments:"Paiements",products:"Produits",time:"Saisie du temps",expenses:"Frais",employees:"Collaborateurs",features:"Fonctions",pricing:"Prix",login:"Connexion",admin:"Admin"},common:{back:"Retour",close:"Fermer",search:"Rechercher",save:"Enregistrer",cancel:"Annuler",more:"Plus",notifications:"Notifications",settings:"Paramètres",language:"Langue"},marketing:{tagline:"Logiciel de gestion pour les PME suisses.",trial:"Essayer gratuitement pendant 30 jours",demo:"Démarrer la démo",productPreview:"Aperçu de Binso One"}},
it:{nav:{home:"Home",customers:"Clienti",offers:"Offerte",invoices:"Fatture",payments:"Pagamenti",products:"Prodotti",time:"Registrazione ore",expenses:"Spese",employees:"Collaboratori",features:"Funzioni",pricing:"Prezzi",login:"Accedi",admin:"Admin"},common:{back:"Indietro",close:"Chiudi",search:"Cerca",save:"Salva",cancel:"Annulla",more:"Altro",notifications:"Notifiche",settings:"Impostazioni",language:"Lingua"},marketing:{tagline:"Software gestionale per PMI svizzere.",trial:"Prova gratis per 30 giorni",demo:"Avvia demo",productPreview:"Anteprima di Binso One"}},
en:{nav:{home:"Home",customers:"Customers",offers:"Quotes",invoices:"Invoices",payments:"Payments",products:"Products",time:"Time tracking",expenses:"Expenses",employees:"Employees",features:"Features",pricing:"Pricing",login:"Sign in",admin:"Admin"},common:{back:"Back",close:"Close",search:"Search",save:"Save",cancel:"Cancel",more:"More",notifications:"Notifications",settings:"Settings",language:"Language"},marketing:{tagline:"Business software for Swiss SMEs.",trial:"Try free for 30 days",demo:"Start demo",productPreview:"Binso One product preview"}},
tr:{nav:{home:"Ana sayfa",customers:"Müşteriler",offers:"Teklifler",invoices:"Faturalar",payments:"Ödemeler",products:"Ürünler",time:"Zaman takibi",expenses:"Masraflar",employees:"Çalışanlar",features:"Özellikler",pricing:"Fiyatlar",login:"Giriş yap",admin:"Yönetim"},common:{back:"Geri",close:"Kapat",search:"Ara",save:"Kaydet",cancel:"İptal",more:"Daha fazla",notifications:"Bildirimler",settings:"Ayarlar",language:"Dil"},marketing:{tagline:"İsviçre KOBİ'leri için iş yazılımı.",trial:"30 gün ücretsiz dene",demo:"Demoyu başlat",productPreview:"Binso One ürün önizlemesi"}}
} as const;
export type Messages=(typeof messages)["de"];
export function getMessages(locale:AppLocale):Messages{return messages[locale] as unknown as Messages;}