import LegalPage from "@/components/legal/legal-page";import {legalConfig as c,subprocessors} from "@/lib/legal";
export const metadata={title:"Datenschutz"};
export default function Page(){return <LegalPage title="Datenschutzerklärung" lead="Informationen zur Bearbeitung von Personendaten bei der Nutzung von Binso One.">
<h2>1. Verantwortliche Stelle</h2><p><strong>{c.company}</strong>, {c.address}, {c.zipCity}, {c.country}. Datenschutzanfragen: <a href={`mailto:${c.privacyEmail}`}>{c.privacyEmail}</a>.</p>
<h2>2. Welche Daten wir bearbeiten</h2><p>Je nach Nutzung bearbeiten wir insbesondere Konto- und Kontaktdaten, Firmen- und Vertragsdaten, Login- und Sicherheitsdaten, Supportkommunikation, Abrechnungs- und Zahlungsreferenzen, technische Protokolldaten sowie diejenigen Geschäftsdaten, welche Kundinnen und Kunden in Binso One erfassen.</p>
<h2>3. Zwecke</h2><p>Wir bearbeiten Daten zur Bereitstellung und Absicherung der Plattform, Authentifizierung und Benutzerverwaltung, Mandantentrennung, Vertragserfüllung und Abrechnung, Support, Fehleranalyse, Missbrauchsprävention, Produktverbesserung, Pilotfeedback sowie zur Erfüllung gesetzlicher Pflichten.</p>
<h2>4. Kundendaten und Auftragsbearbeitung</h2><p>Bei Geschäftsdaten, welche ein Kunde als Verantwortlicher in Binso One erfasst, handelt Binso GmbH im Rahmen der vereinbarten Leistungen grundsätzlich als Auftragsbearbeiterin. Ergänzende Bestimmungen enthält die Seite <a href="/auftragsbearbeitung">Auftragsbearbeitung</a>.</p>
<h2>5. Empfänger und Dienstleister</h2><p>Wir geben Personendaten nur weiter, soweit dies für den Betrieb, die Vertragserfüllung, Sicherheit oder gesetzliche Pflichten erforderlich ist. Vorgesehene technische Dienstleister sind:</p><ul>{subprocessors.map(x=><li key={x.name}><strong>{x.name}</strong>: {x.purpose}. {x.region}.</li>)}</ul>
<h2>6. Datenstandorte und Auslandbekanntgabe</h2><p>Wir wählen für Kernsysteme soweit möglich geeignete Schweizer oder europäische Regionen. Bei international tätigen Dienstleistern können Daten in weitere Staaten gelangen. In solchen Fällen werden die vertraglichen und gesetzlichen Anforderungen an eine zulässige Bekanntgabe berücksichtigt.</p>
<h2>7. Aufbewahrung</h2><p>Daten werden nur so lange aufbewahrt, wie dies für die jeweiligen Zwecke, Vertragsbeziehungen, Sicherheitsnachweise oder gesetzliche Aufbewahrungspflichten erforderlich ist. Support-, Audit- und Sicherheitsdaten können von operativen Geschäftsdaten abweichende Fristen haben.</p>
<h2>8. Sicherheit</h2><p>Binso One setzt technische und organisatorische Massnahmen ein, darunter Mandantentrennung, rollenbasierte Berechtigungen, verschlüsselte Übertragung, serverseitige Sessions, Auditierung und Zugriffsbeschränkungen. Weitere Informationen stehen unter <a href="/sicherheit">Sicherheit</a>.</p>
<h2>9. Cookies und ähnliche Technologien</h2><p>Technisch notwendige Speicherungen dienen insbesondere Sitzung, Sicherheit und Spracheinstellungen. Optionale Analysefunktionen werden nur entsprechend der im Privacy Center gewählten Einstellung aktiviert. Details stehen unter <a href="/cookies">Cookies</a>.</p>
<h2>10. Rechte betroffener Personen</h2><p>Betroffene Personen können im Rahmen des anwendbaren Datenschutzrechts insbesondere Auskunft, Berichtigung und gegebenenfalls Löschung oder Herausgabe ihrer Personendaten verlangen. Bei Daten innerhalb eines Kundenmandanten ist häufig zuerst der jeweilige Kunde als Verantwortlicher zuständig.</p>
<h2>11. Änderungen</h2><p>Diese Erklärung kann angepasst werden, wenn sich Funktionen, Dienstleister oder rechtliche Anforderungen ändern. Die jeweils aktuelle Version wird auf dieser Seite veröffentlicht.</p>
<p><small>Version {c.privacyVersion}</small></p>
</LegalPage>}
