import type {Metadata} from "next";
import Link from "next/link";
import {LegalPage} from "@/components/legal-page";
import {legalConfig} from "@/config/legal";

export const metadata:Metadata={title:"Datenschutz – Binso One",description:"Datenschutzerklärung der Binso GmbH für Binso One.",alternates:{canonical:"/datenschutz"}};

export default function Page(){
 const c=legalConfig.company;
 return <LegalPage eyebrow="DATENSCHUTZ" title="Datenschutzerklärung" intro="Diese Erklärung beschreibt, wie Binso GmbH Personendaten im Zusammenhang mit Binso One und den öffentlichen Websites bearbeitet.">
  <section><h2>1. Verantwortliche Stelle</h2><p><strong>{c.name}</strong><br/>{c.address}, {c.postalCode} {c.city}, {c.country}<br/>E-Mail: <a href={"mailto:"+c.email}>{c.email}</a><br/>Telefon: {c.phone}</p></section>
  <section><h2>2. Welche Daten wir bearbeiten</h2><p>Je nach Nutzung bearbeiten wir insbesondere Kontakt- und Stammdaten, Firmen- und Kontodaten, Authentifizierungs- und Sicherheitsdaten, Vertrags- und Abrechnungsdaten, Supportkommunikation, technische Protokoll- und Gerätedaten sowie Inhalte, die Kunden in Binso One erfassen oder hochladen. Dazu können Daten über Mitarbeitende, Kunden, Lieferanten und andere Geschäftskontakte des Kunden gehören.</p></section>
  <section><h2>3. Zwecke</h2><p>Wir bearbeiten Personendaten, um Binso One bereitzustellen und zu betreiben, Benutzer zu authentifizieren, Berechtigungen durchzusetzen, Abonnemente und Zahlungen abzuwickeln, Support zu leisten, Missbrauch und Sicherheitsvorfälle zu verhindern, die Plattform technisch zu überwachen und weiterzuentwickeln sowie gesetzliche Pflichten zu erfüllen.</p></section>
  <section><h2>4. Herkunft der Daten</h2><p>Daten erhalten wir direkt von Benutzern und Kunden, aus deren Nutzung der Plattform, aus von Kunden importierten oder hochgeladenen Geschäftsdaten sowie von eingesetzten Dienstleistern, soweit dies für Authentifizierung, Zahlungsabwicklung, E-Mail-Zustellung oder technischen Betrieb erforderlich ist.</p></section>
  <section><h2>5. Rollen nach Datenschutzrecht</h2><p>Für Konto-, Vertrags-, Sicherheits-, Abrechnungs- und eigene Kommunikationsdaten ist Binso in der Regel selbst Verantwortliche. Für Personendaten, die ein Geschäftskunde in Binso One über seine eigenen Mitarbeitenden, Kunden oder Geschäftspartner bearbeitet, handelt Binso grundsätzlich als Auftragsbearbeiter. Dafür gilt die <Link href="/auftragsbearbeitung">Vereinbarung zur Auftragsbearbeitung</Link>.</p></section>
  <section><h2>6. Empfänger und Dienstleister</h2><p>Wir geben Personendaten nur weiter, soweit dies für die genannten Zwecke erforderlich ist. Dazu gehören insbesondere Microsoft Azure für Hosting und Datenbankdienste, Stripe für Zahlungs- und Abonnementabwicklung sowie Microsoft Graph / Microsoft 365 für transaktionale E-Mails. Die aktuelle Liste ist unter <Link href="/unterauftragsbearbeiter">Unterauftragsbearbeiter</Link> verfügbar.</p></section>
  <section><h2>7. Datenbearbeitung im Ausland</h2><p>Die produktive Webanwendung wird derzeit in Microsoft Azure in der Region Switzerland North betrieben. Einzelne Dienstleister oder deren Unterauftragsbearbeiter können Daten ausserhalb der Schweiz bearbeiten. Stripe kann Daten weltweit, insbesondere auch in den USA, bearbeiten. Für transaktionale E-Mails wird Microsoft Graph / Microsoft 365 eingesetzt; je nach Microsoft-Dienst und Support können dabei weitere Verarbeitungsorte beteiligt sein. Wo ein Empfängerstaat kein angemessenes Datenschutzniveau bietet, stützen wir die Übermittlung auf geeignete Garantien, insbesondere anerkannte Standardvertragsklauseln mit den für die Schweiz erforderlichen Anpassungen oder andere zulässige Transfermechanismen.</p></section>
  <section><h2>8. Cookies und lokale Speicherung</h2><p>Binso One verwendet technisch notwendige Cookies und vergleichbare Speichermechanismen für Anmeldung, Sicherheit, Sitzungen, Demo-Funktionen und Benutzereinstellungen. Zum Stand dieser Erklärung setzt die öffentliche Binso-One-Oberfläche keine Werbe- oder Cross-Site-Tracking-Cookies für personalisierte Werbung ein. Werden solche Technologien künftig eingeführt, wird diese Erklärung angepasst und, soweit erforderlich, eine entsprechende Auswahlmöglichkeit bereitgestellt.</p></section>
  <section><h2>9. Microsoft Entra ID</h2><p>Interne Mitarbeitende der Binso GmbH können für administrative Zugriffe über Microsoft Entra ID authentifiziert werden. Microsoft übernimmt dabei insbesondere Anmeldung und Mehrfaktor-Authentifizierung. Diese interne Authentifizierung ist vom Kundenlogin getrennt.</p></section>
  <section><h2>10. Zahlungsdaten</h2><p>Bei kostenpflichtigen Abonnements wird der Checkout durch Stripe bereitgestellt. Vollständige Kartendaten werden nicht in Binso One gespeichert. Binso speichert nur die für Vertrags- und Abrechnungsstatus erforderlichen Referenzen und Statusinformationen.</p></section>
  <section><h2>11. E-Mail-Kommunikation</h2><p>Für sicherheits- und transaktionsbezogene E-Mails, beispielsweise Bestätigungscodes oder Passwort-Wiederherstellung, wird in der produktiven Umgebung Microsoft Graph / Microsoft 365 eingesetzt. Dabei werden insbesondere Empfängeradresse, Nachrichtentext und technische Zustellinformationen verarbeitet.</p></section>
  <section><h2>12. Aufbewahrung und Löschung</h2><p>Wir bewahren Personendaten nur so lange auf, wie dies für den jeweiligen Zweck, die Vertragsabwicklung, Sicherheit, Beweissicherung oder gesetzliche Pflichten erforderlich ist. Geschäftsbücher und zugehörige Belege können gesetzlichen Aufbewahrungsfristen von zehn Jahren unterliegen. Kundendaten werden nach Vertragsende entsprechend dem vereinbarten Lösch- und Exportprozess entfernt, soweit keine gesetzlichen oder überwiegenden Gründe eine weitere Aufbewahrung verlangen. Sicherungskopien werden im Rahmen der jeweiligen Backup-Zyklen überschrieben oder gelöscht.</p></section>
  <section><h2>13. Datensicherheit</h2><p>Wir setzen dem Risiko angemessene technische und organisatorische Massnahmen ein, darunter verschlüsselte Übertragung, rollenbasierte Zugriffe, Mehrfaktor-Authentifizierung für privilegierte Konten, getrennte Kundenbereiche, Protokollierung sicherheitsrelevanter Vorgänge und kontrollierte Produktionszugriffe.</p></section>
  <section><h2>14. Rechte betroffener Personen</h2><p>Betroffene Personen können im Rahmen des anwendbaren Datenschutzrechts insbesondere Auskunft, Berichtigung, Herausgabe oder Übertragung ihrer Daten sowie die Löschung oder Einschränkung einer Bearbeitung verlangen. Rechte können über die oben genannten Kontaktdaten geltend gemacht werden. Soweit Daten im Auftrag eines Geschäftskunden verarbeitet werden, ist dieser grundsätzlich die erste Anlaufstelle.</p></section>
  <section><h2>15. Änderungen</h2><p>Wir können diese Datenschutzerklärung aktualisieren, wenn sich unsere Datenbearbeitungen, eingesetzten Dienstleister oder rechtlichen Anforderungen ändern. Die jeweils aktuelle Version wird auf dieser Seite veröffentlicht.</p></section>
  <p className="legal-version">Version {legalConfig.privacyVersion} · Stand: {legalConfig.versionDate}</p>
 </LegalPage>;
}
