import {PGlite} from '@electric-sql/pglite';
import {pgcrypto} from '@electric-sql/pglite/contrib/pgcrypto';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import ts from 'typescript';
const db=new PGlite({extensions:{pgcrypto}});
const demo='00000000-0000-4000-8000-000000000099';
try{
 await db.exec('create extension pgcrypto; create role schema_owner; grant usage,create on schema public to schema_owner; set role schema_owner');
 for(const file of (await fs.readdir('database/migrations')).filter(x=>x.endsWith('.sql')).sort()){
  await db.exec('begin');
  try{await db.exec(await fs.readFile('database/migrations/'+file,'utf8'));await db.exec('commit')}catch(e){await db.exec('rollback');throw new Error(file+': '+e.message)}
 }
 await db.exec('reset role');
 await db.exec(`create role tenant_probe; grant usage on schema public to tenant_probe; grant select,insert,update,delete on all tables in schema public to tenant_probe;`);
 await db.exec('set role tenant_probe');
 assert.equal((await db.query('select count(*)::int n from invoices')).rows[0].n,0);
 await db.query("select set_config('app.organization_id',$1,false)",[demo]);
 assert.ok((await db.query('select count(*)::int n from invoices')).rows[0].n>20);
 assert.equal((await db.query("select count(*)::int n from operating_costs where scope='platform'")).rows[0].n,0);
 await db.query("select set_config('app.organization_id',$1,false)",['00000000-0000-4000-8000-000000000001']);
 assert.equal((await db.query('select count(*)::int n from invoices')).rows[0].n,0);
 await db.query("select set_config('app.platform_operator','true',false)");
 assert.equal((await db.query('select count(*)::int n from platform_billing_payments')).rows[0].n,22);
 assert.equal((await db.query("select count(*)::int n from operating_costs where scope='platform' and not is_demo")).rows[0].n,0);
 await db.exec('reset role');
 // Re-running the deterministic fixture cannot create duplicate customers/payments.
 const before=(await db.query('select count(*)::int n from payments')).rows[0].n;
 await db.exec('begin');await db.exec(await fs.readFile('database/migrations/0023_finance_and_demo_fixture.sql','utf8'));await db.exec('commit');
 assert.equal((await db.query('select count(*)::int n from payments')).rows[0].n,before);
 const dataModule=source=>'data:text/javascript;base64,'+Buffer.from(ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext}}).outputText).toString('base64');
 const permissions=dataModule(await fs.readFile('lib/permissions.ts','utf8'));
 const audit=dataModule((await fs.readFile('lib/server/audit.ts','utf8')).replace('import "server-only";',''));
 const http=dataModule('export class ApiError extends Error {constructor(status,code,message){super(message);this.status=status;this.code=code}}');
 const businessSource=(await fs.readFile('lib/server/repositories/business-api.ts','utf8')).replace('import "server-only";','').replace('"../http"',JSON.stringify(http)).replace('"../audit"',JSON.stringify(audit)).replace('"@/lib/permissions"',JSON.stringify(permissions));
 const {listApiBusiness,mutateApiBusiness}=await import(dataModule(businessSource));
 const client={query:async(...args)=>{const result=await db.query(...args);return {...result,rowCount:result.rows.length}}};
 const session={organizationId:demo,userId:'demo-readonly',role:'owner'};
 await db.query("select set_config('app.organization_id',$1,false)",[demo]);
 for(const table of ['customers','customer_contacts','products','employees','expenses','documents','payments'])assert.ok((await listApiBusiness(client,session,table,'')).length>0,table+' must have readable canonical fixture data');
 assert.equal((await listApiBusiness(client,session,'documents','number=eq.RE-2026-019')).length,1);
 const documentArgs={p_kind:'invoice',p_customer_id:'10000000-0000-4000-8000-000000000001',p_number:'TEST-001',p_issue_date:'2026-10-04',p_due_date:'2026-11-04',p_vat_rate:8.1,p_currency:'CHF',p_note:'Test',p_items:[{description:'Consulting',quantity:2,unit_price:100}]};
 const document=await mutateApiBusiness(client,session,'create_document_atomic',documentArgs);
 assert.equal(Number(document.total),216.2);
 await db.query("update invoices set status='sent' where id=$1",[document.id]);
 const paymentArgs={p_invoice_id:document.id,p_paid_on:'2026-10-04',p_amount:216.2,p_method:'bank',p_note:'Test',p_idempotency_key:'test-payment-0001'};
 const payment=await mutateApiBusiness(client,session,'create_payment_idempotent',paymentArgs);
 const retry=await mutateApiBusiness(client,session,'create_payment_idempotent',paymentArgs);
 assert.equal(payment.id,retry.id);
 assert.equal((await db.query('select status from invoices where id=$1',[document.id])).rows[0].status,'paid');
 await assert.rejects(mutateApiBusiness(client,session,'create_payment_idempotent',{...paymentArgs,p_amount:2}),e=>e.status===409);
 await assert.rejects(db.query("insert into tasks(organization_id,external_id,title,project_id) values('00000000-0000-4000-8000-000000000001','cross-tenant','Blocked','30000000-0000-4000-8000-000000000001')"),e=>e.code==='23503');
 const {dashboardAnalytics}=await import(dataModule((await fs.readFile('lib/server/repositories/dashboard.ts','utf8')).replace("import 'server-only';",'')));
 const analytics=await dashboardAnalytics(client,demo);
 const october=analytics.analyticsInvoices.find(row=>new Date(row.issue_date).toISOString().startsWith('2026-10'));
 assert.ok(october&&Number(october.invoice_count)>=1&&Number(october.customer_count)>=1);
 assert.ok(analytics.analyticsPayments.length>12);
 const fixtureSource=(await fs.readFile('lib/server/repositories/demo-fixture.ts','utf8')).replace('import "server-only";','').replace("'../http'",JSON.stringify(http));
 const {seedDatabaseDemo}=await import(dataModule(fixtureSource));
 const sandbox='00000000-0000-4000-8000-000000000098';
 await db.query("insert into organizations(id,name,slug,is_demo,status) values($1,'Synthetic sandbox','sandbox-test',true,'trial')",[sandbox]);
 await db.query("insert into app_users(id,email,display_name,status) values('sandbox-user','sandbox-user@example.invalid','Demo','active')");
 await db.query("select set_config('app.organization_id',$1,false)",[sandbox]);
 await seedDatabaseDemo(client,sandbox,'sandbox-user');
 const sandboxInvoices=await db.query('select id from invoices where organization_id=$1',[sandbox]);
 assert.ok(sandboxInvoices.rows.length>20);
 await seedDatabaseDemo(client,sandbox,'sandbox-user');
 assert.equal((await db.query('select count(*)::int n from invoices where organization_id=$1',[sandbox])).rows[0].n,sandboxInvoices.rows.length);
 await db.query("select set_config('app.organization_id',$1,false)",[sandbox]);
 const clonedSession={...session,organizationId:sandbox,userId:'sandbox-user'};
 const clonedCustomer=(await listApiBusiness(client,clonedSession,'customers',''))[0];
 assert.notEqual(clonedCustomer.id,'10000000-0000-4000-8000-000000000001');
 const {translateBusinessWrite}=await import(dataModule(businessSource));
 const expenseWrite=translateBusinessWrite('expenses',{merchant:'Test Hotel',category:'Reise',expense_date:'2026-10-04',amount:123.45,currency:'CHF',vat_rate:8.1,description:'Test expense',status:'submitted'},true);
 const fields={...expenseWrite.data,organization_id:sandbox};const keys=Object.keys(fields);
 const persistedExpense=await client.query(`insert into expenses(${keys.join(',')}) values(${keys.map((_,i)=>'$'+(i+1)).join(',')}) returning id`,Object.values(fields));
 const loadedExpense=(await listApiBusiness(client,clonedSession,'expenses','id=eq.'+persistedExpense.rows[0].id))[0];
 assert.equal(loadedExpense.category,'Reise');assert.equal(loadedExpense.status,'submitted');assert.equal(Number(loadedExpense.amount),123.45);
 const tenantWrapper=dataModule('export async function withTenant(org,user,fn){return globalThis.__customerPersistenceTest(org,user,fn)}');
 globalThis.__customerPersistenceTest=async(org,user,fn)=>{await db.query("select set_config('app.organization_id',$1,false)",[org]);return fn(client)};
 const customerSource=(await fs.readFile('lib/server/repositories/customers.ts','utf8')).replace('import "server-only";','').replace('"@/lib/server/db"',JSON.stringify(tenantWrapper)).replace('"@/lib/server/audit"',JSON.stringify(audit)).replace('"@/lib/server/http"',JSON.stringify(http));
 const customerRepository=await import(dataModule(customerSource));
 const input={name:'Persistence Test AG',email:'test@example.invalid',phone:'+41 00 000 00 00',city:'Zürich',postalCode:'8000',sector:'Beratung',address:'Testweg 1',uid:'TEST',language:'de',paymentDays:45,discount:5};
 const created=await customerRepository.createCustomer(sandbox,'sandbox-user',input);
 const updated=await customerRepository.updateCustomer(sandbox,'sandbox-user',created.id,{city:'Bern',sector:'Handel'});
 assert.equal(updated.city,'Bern');assert.equal(updated.sector,'Handel');assert.equal(updated.email,input.email);assert.equal(Number(updated.paymentDays),45);
 assert.equal((await customerRepository.listCustomers(sandbox,'sandbox-user')).find(row=>row.id===created.id).postal_code,'8000');
 await db.query("select set_config('app.organization_id',$1,false)",[demo]);
 assert.equal((await listApiBusiness(client,session,'customers','id=eq.'+created.id)).length,0);
 const fileId='f0000000-0000-4000-8000-000000000031';
 await db.query("insert into file_objects(id,organization_id,object_key,original_name,content_type,size_bytes,sha256,created_by,purpose,expense_id) values($1,$2,$3,'test.txt','text/plain',4,encode(digest('test','sha256'),'hex'),'sandbox-user','expense_receipt',$4)",[fileId,sandbox,sandbox+'/files/test.txt',persistedExpense.rows[0].id]);
 await db.query("insert into file_contents(file_id,organization_id,body) values($1,$2,convert_to('test','utf8'))",[fileId,sandbox]);
 assert.equal((await db.query("select convert_from(body,'utf8') value from file_contents where file_id=$1",[fileId])).rows[0].value,'test');
 await assert.rejects(db.query("update file_contents set body=convert_to('fail','utf8') where file_id=$1",[fileId]),e=>e.code==='23514');
 await db.exec('set role tenant_probe');await db.query("select set_config('app.organization_id',$1,false)",[demo]);
 assert.equal((await db.query('select * from file_contents where file_id=$1',[fileId])).rows.length,0);
 await db.exec('reset role');
 assert.equal((await db.query("select count(*)::int n from pg_constraint where contype='f' and not convalidated")).rows[0].n,0);
 const domain=dataModule(await fs.readFile('config/domain.ts','utf8'));
 const plans=dataModule((await fs.readFile('lib/plans.ts','utf8')).replaceAll('"@/config/domain"',JSON.stringify(domain)));
 const fixture=dataModule(fixtureSource);
 const transactions=dataModule('export async function withTransaction(fn){return globalThis.__provisionTest(fn)}');
 globalThis.__provisionTest=async(fn)=>{await db.exec('begin');try{const result=await fn(client);await db.exec('commit');return result}catch(e){await db.exec('rollback');throw e}};
 const provisionSource=(await fs.readFile('lib/server/provisioning.ts','utf8')).replace('import "server-only";','').replace('"./repositories/demo-fixture"',JSON.stringify(fixture)).replace('"@/lib/server/db"',JSON.stringify(transactions)).replace('"@/config/domain"',JSON.stringify(domain)).replace('"@/lib/plans"',JSON.stringify(plans));
 const {provisionOrganization}=await import(dataModule(provisionSource));
 const provisioned=await provisionOrganization({userId:'demo-provision-test',email:'demo-provision-test@example.invalid',name:'Demo Test',companyName:'Demo',plan:'business',mode:'demo'});
 assert.equal((await db.query('select is_demo from organizations where id=$1',[provisioned.organizationId])).rows[0].is_demo,true);
 assert.ok((await db.query('select count(*)::int n from invoices where organization_id=$1',[provisioned.organizationId])).rows[0].n>20);
 delete globalThis.__provisionTest;
 delete globalThis.__customerPersistenceTest;
 console.log('PostgreSQL migrations, deterministic fixtures and tenant/platform RLS passed.');
}finally{await db.close()}
