import {PGlite} from '@electric-sql/pglite';
import {pgcrypto} from '@electric-sql/pglite/contrib/pgcrypto';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import ts from 'typescript';
import { SwissQRBill } from 'swissqrbill/svg';
import { isQRReferenceValid } from 'swissqrbill/utils';
const db=new PGlite({extensions:{pgcrypto}});
const demo='00000000-0000-4000-8000-000000000099';
try{
 await db.exec('create extension pgcrypto; create role schema_owner; grant usage,create on schema public to schema_owner; set role schema_owner');
 for(const file of (await fs.readdir('database/migrations')).filter(x=>x.endsWith('.sql')).sort()){
  await db.exec('begin');
  try{await db.exec(await fs.readFile('database/migrations/'+file,'utf8'));await db.exec('commit')}catch(e){await db.exec('rollback');throw new Error(file+': '+e.message)}
 }
 await db.exec('reset role');
 await db.exec(`create role tenant_probe; grant usage on schema public to tenant_probe; grant select,insert,update,delete on all tables in schema public to tenant_probe;`);
 await db.exec('set role tenant_probe');
 assert.equal((await db.query('select count(*)::int n from invoices')).rows[0].n,0);
 await db.query("select set_config('app.organization_id',$1,false)",[demo]);
 assert.ok((await db.query('select count(*)::int n from invoices')).rows[0].n>20);
 assert.equal((await db.query("select count(*)::int n from operating_costs where scope='platform'")).rows[0].n,0);
 await db.query("select set_config('app.organization_id',$1,false)",['00000000-0000-4000-8000-000000000001']);
 assert.equal((await db.query('select count(*)::int n from invoices')).rows[0].n,0);
 await db.query("select set_config('app.platform_operator','true',false)");
 assert.equal((await db.query('select count(*)::int n from platform_billing_payments')).rows[0].n,22);
 assert.equal((await db.query("select count(*)::int n from operating_costs where scope='platform' and not is_demo")).rows[0].n,0);
 await db.exec('reset role');
 // Re-running the deterministic fixture cannot create duplicate customers/payments.
 const before=(await db.query('select count(*)::int n from payments')).rows[0].n;
 await db.exec('begin');await db.exec(await fs.readFile('database/migrations/0023_finance_and_demo_fixture.sql','utf8'));await db.exec('commit');
 assert.equal((await db.query('select count(*)::int n from payments')).rows[0].n,before);
 const dataModule=source=>'data:text/javascript;base64,'+Buffer.from(ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext}}).outputText).toString('base64');
 const permissions=dataModule(await fs.readFile('lib/permissions.ts','utf8'));
 const audit=dataModule((await fs.readFile('lib/server/audit.ts','utf8')).replace('import "server-only";',''));
 const http=dataModule('export class ApiError extends Error {constructor(status,code,message){super(message);this.status=status;this.code=code}}');
 const qrSource=(await fs.readFile('lib/qr-bill.ts','utf8')).replace('"swissqrbill/utils"',JSON.stringify(new URL('../node_modules/swissqrbill/lib/esm/shared/utils.js',import.meta.url).href));
 const qrModule=dataModule(qrSource);
 const businessSource=(await fs.readFile('lib/server/repositories/business-api.ts','utf8')).replace('import "server-only";','').replace('"../http"',JSON.stringify(http)).replace('"../audit"',JSON.stringify(audit)).replace('"@/lib/permissions"',JSON.stringify(permissions)).replace('"@/lib/qr-bill"',JSON.stringify(qrModule));
 const {listApiBusiness,mutateApiBusiness}=await import(dataModule(businessSource));
 const client={query:async(...args)=>{const result=await db.query(...args);return {...result,rowCount:result.rows.length}}};
 const session={organizationId:demo,userId:'demo-readonly',role:'owner'};
 await db.query("select set_config('app.organization_id',$1,false)",[demo]);
 for(const table of ['customers','customer_contacts','products','employees','expenses','documents','payments'])assert.ok((await listApiBusiness(client,session,table,'')).length>0,table+' must have readable canonical fixture data');
 assert.equal((await listApiBusiness(client,session,'documents','number=eq.RE-2026-019')).length,1);
 const documentArgs={p_kind:'invoice',p_customer_id:'10000000-0000-4000-8000-000000000001',p_number:'TEST-001',p_issue_date:'2026-10-04',p_due_date:'2026-11-04',p_vat_rate:8.1,p_currency:'CHF',p_note:'Test',p_items:[{description:'Consulting',quantity:2,unit_price:100}]};
 const company=(await db.query('select * from organizations where id=$1',[demo])).rows[0];
 await db.query('update organizations set iban=null,qr_iban=null where id=$1',[demo]);
 await assert.rejects(()=>mutateApiBusiness(client,session,'create_document_atomic',documentArgs),e=>e.code==='invoice_payment_setup_required');
 await db.query('update organizations set iban=$2 where id=$1',[demo,company.iban]);
 const document=await mutateApiBusiness(client,session,'create_document_atomic',documentArgs);
 assert.equal(document.issue_date,'2026-10-04');assert.equal(document.due_date,'2026-11-04');assert.equal(document.status,'draft');
 const {createQrBillData,validSwissIban}=await import(qrModule);
 assert.equal(validSwissIban('CH9300762011623852958'),false);
 const qrData=createQrBillData(company,{reference:document.qr_reference,number:document.number,total:Number(document.total),currency:document.currency});
 assert.equal(qrData.amount,216.2);assert.equal(qrData.creditor.account,company.iban);assert.equal(qrData.reference,undefined);
 const qrReference=createQrBillData({...company,qr_iban:'CH4431999123000889012'},{reference:document.qr_reference,number:document.number,total:Number(document.total)});
 assert.equal(isQRReferenceValid(qrReference.reference),true);assert.equal(qrReference.reference,document.qr_reference);
 assert.equal((await db.query('select qr_reference from invoices where id=$1',[document.id])).rows[0].qr_reference,qrReference.reference);
 const unsafeName={...qrData,creditor:{...qrData.creditor,name:'Test <img src=x onerror=alert(1)>'}};
 const svg=new SwissQRBill(unsafeName,{language:'DE'}).toString();assert.ok(svg.includes('&lt;img'));assert.ok(!svg.includes('<img'));

 assert.equal(Number(document.total),216.2);
 await db.query("update invoices set status='sent' where id=$1",[document.id]);
 const paymentArgs={p_invoice_id:document.id,p_paid_on:'2026-10-04',p_amount:216.2,p_method:'bank',p_note:'Test',p_idempotency_key:'test-payment-0001'};
 const payment=await mutateApiBusiness(client,session,'create_payment_idempotent',paymentArgs);
 const retry=await mutateApiBusiness(client,session,'create_payment_idempotent',paymentArgs);
 assert.equal(payment.id,retry.id);
 assert.equal((await db.query('select status from invoices where id=$1',[document.id])).rows[0].status,'paid');
 await assert.rejects(mutateApiBusiness(client,session,'create_payment_idempotent',{...paymentArgs,p_amount:2}),e=>e.status===409);
 await assert.rejects(db.query("insert into tasks(organization_id,external_id,title,project_id) values('00000000-0000-4000-8000-000000000001','cross-tenant','Blocked','30000000-0000-4000-8000-000000000001')"),e=>e.code==='23503');
 const {dashboardAnalytics}=await import(dataModule((await fs.readFile('lib/server/repositories/dashboard.ts','utf8')).replace("import 'server-only';",'')));
 const analytics=await dashboardAnalytics(client,demo);
 const october=analytics.analyticsInvoices.find(row=>new Date(row.issue_date).toISOString().startsWith('2026-10'));
 assert.ok(october&&Number(october.invoice_count)>=1&&Number(october.customer_count)>=1);
 assert.ok(analytics.analyticsPayments.length>12);
 const fixtureSource=(await fs.readFile('lib/server/repositories/demo-fixture.ts','utf8')).replace('import "server-only";','').replace("'../http'",JSON.stringify(http));
 const {seedDatabaseDemo}=await import(dataModule(fixtureSource));
 const sandbox='00000000-0000-4000-8000-000000000098';
 await db.query("insert into organizations(id,name,slug,is_demo,status) values($1,'Synthetic sandbox','sandbox-test',true,'trial')",[sandbox]);
 await db.query("insert into app_users(id,email,display_name,status) values('sandbox-user','sandbox-user@example.invalid','Demo','active')");
 await db.query("select set_config('app.organization_id',$1,false)",[sandbox]);
 await seedDatabaseDemo(client,sandbox,'sandbox-user');
 const sandboxInvoices=await db.query('select id from invoices where organization_id=$1',[sandbox]);
 assert.ok(sandboxInvoices.rows.length>20);
 await seedDatabaseDemo(client,sandbox,'sandbox-user');
 assert.equal((await db.query('select count(*)::int n from invoices where organization_id=$1',[sandbox])).rows[0].n,sandboxInvoices.rows.length);
 await db.query("select set_config('app.organization_id',$1,false)",[sandbox]);
 const clonedSession={...session,organizationId:sandbox,userId:'sandbox-user'};
 const clonedCustomer=(await listApiBusiness(client,clonedSession,'customers',''))[0];
 assert.notEqual(clonedCustomer.id,'10000000-0000-4000-8000-000000000001');
 const {translateBusinessWrite}=await import(dataModule(businessSource));
 const expenseWrite=translateBusinessWrite('expenses',{merchant:'Test Hotel',category:'Reise',expense_date:'2026-10-04',amount:123.45,currency:'CHF',vat_rate:8.1,description:'Test expense',status:'submitted'},true);
 const fields={...expenseWrite.data,organization_id:sandbox};const keys=Object.keys(fields);
 const persistedExpense=await client.query(`insert into expenses(${keys.join(',')}) values(${keys.map((_,i)=>'$'+(i+1)).join(',')}) returning id`,Object.values(fields));
 const loadedExpense=(await listApiBusiness(client,clonedSession,'expenses','id=eq.'+persistedExpense.rows[0].id))[0];
 assert.equal(loadedExpense.category,'Reise');assert.equal(loadedExpense.status,'submitted');assert.equal(Number(loadedExpense.amount),123.45);
 const tenantWrapper=dataModule('export async function withTenant(org,user,fn){return globalThis.__customerPersistenceTest(org,user,fn)}');
 globalThis.__customerPersistenceTest=async(org,user,fn)=>{await db.query("select set_config('app.organization_id',$1,false)",[org]);return fn(client)};
 const customerSource=(await fs.readFile('lib/server/repositories/customers.ts','utf8')).replace('import "server-only";','').replace('"@/lib/server/db"',JSON.stringify(tenantWrapper)).replace('"@/lib/server/audit"',JSON.stringify(audit)).replace('"@/lib/server/http"',JSON.stringify(http));
 const customerRepository=await import(dataModule(customerSource));
 const input={name:'Persistence Test AG',email:'test@example.invalid',phone:'+41 00 000 00 00',city:'Zürich',postalCode:'8000',sector:'Beratung',address:'Testweg 1',uid:'TEST',language:'de',paymentDays:45,discount:5,notes:'Persistente interne Kundennotiz'};
 const created=await customerRepository.createCustomer(sandbox,'sandbox-user',input);
 const updated=await customerRepository.updateCustomer(sandbox,'sandbox-user',created.id,{city:'Bern',sector:'Handel'});
 assert.equal(updated.notes,input.notes);assert.equal(updated.uid,input.uid);assert.equal(updated.address,input.address);assert.equal(updated.city,'Bern');assert.equal(updated.sector,'Handel');assert.equal(updated.email,input.email);assert.equal(Number(updated.paymentDays),45);
 assert.equal((await customerRepository.listCustomers(sandbox,'sandbox-user')).find(row=>row.id===created.id).postal_code,'8000');
 await db.query("select set_config('app.organization_id',$1,false)",[demo]);
 assert.equal((await listApiBusiness(client,session,'customers','id=eq.'+created.id)).length,0);
 const fileId='f0000000-0000-4000-8000-000000000031';
 await db.query("insert into file_objects(id,organization_id,object_key,original_name,content_type,size_bytes,sha256,created_by,purpose,expense_id) values($1,$2,$3,'test.txt','text/plain',4,encode(digest('test','sha256'),'hex'),'sandbox-user','expense_receipt',$4)",[fileId,sandbox,sandbox+'/files/test.txt',persistedExpense.rows[0].id]);
 await db.query("insert into file_contents(file_id,organization_id,body) values($1,$2,convert_to('test','utf8'))",[fileId,sandbox]);
 assert.equal((await db.query("select convert_from(body,'utf8') value from file_contents where file_id=$1",[fileId])).rows[0].value,'test');
 await assert.rejects(db.query("update file_contents set body=convert_to('fail','utf8') where file_id=$1",[fileId]),e=>e.code==='23514');
 await db.exec('set role tenant_probe');await db.query("select set_config('app.organization_id',$1,false)",[demo]);
 assert.equal((await db.query('select * from file_contents where file_id=$1',[fileId])).rows.length,0);
 await db.exec('reset role');
 assert.equal((await db.query("select count(*)::int n from pg_constraint where contype='f' and not convalidated")).rows[0].n,0);
 const domain=dataModule(await fs.readFile('config/domain.ts','utf8'));
 const plans=dataModule((await fs.readFile('lib/plans.ts','utf8')).replaceAll('"@/config/domain"',JSON.stringify(domain)));
 const fixture=dataModule(fixtureSource);
 const transactions=dataModule('export async function withTransaction(fn){return globalThis.__provisionTest(fn)}');
 globalThis.__provisionTest=async(fn)=>{await db.exec('begin');try{const result=await fn(client);await db.exec('commit');return result}catch(e){await db.exec('rollback');throw e}};
 const provisionSource=(await fs.readFile('lib/server/provisioning.ts','utf8')).replace('import "server-only";','').replace('"./repositories/demo-fixture"',JSON.stringify(fixture)).replace('"@/lib/server/db"',JSON.stringify(transactions)).replace('"@/config/domain"',JSON.stringify(domain)).replace('"@/lib/plans"',JSON.stringify(plans));
 const entitlementModule=dataModule((await fs.readFile('lib/subscription-plans.ts','utf8')).replace("'@/config/domain'",JSON.stringify(domain)));
 const {provisionOrganization}=await import(dataModule(provisionSource.replace("'@/lib/subscription-plans'",JSON.stringify(entitlementModule))));
 const provisioned=await provisionOrganization({userId:'demo-provision-test',email:'demo-provision-test@example.invalid',name:'Demo Test',companyName:'Demo',plan:'business',mode:'demo'});
 assert.equal((await db.query('select is_demo from organizations where id=$1',[provisioned.organizationId])).rows[0].is_demo,true);
 assert.ok((await db.query('select count(*)::int n from invoices where organization_id=$1',[provisioned.organizationId])).rows[0].n>20);
 // Exercise real provisioning for 50 independent production-style trial tenants.
 const trialTenants=[];
 for(let i=0;i<50;i++){
  const trial=await provisionOrganization({userId:`trial-probe-${i}`,email:`trial-probe-${i}@example.invalid`,name:`Synthetic ${i}`,companyName:`Synthetic Company ${i}`,plan:'business',mode:'trial'});
  trialTenants.push(trial.organizationId);
  await db.query("select set_config('app.organization_id',$1,false)",[trial.organizationId]);
  await db.query("insert into customers(organization_id,external_id,customer_no,name) values($1,'same-external-id','K-001',$2)",[trial.organizationId,`Customer ${i}`]);
 }
 assert.equal(new Set(trialTenants).size,50);
 await db.exec('set role tenant_probe');
 for(const [i,organizationId] of trialTenants.entries()){
  await db.query("select set_config('app.organization_id',$1,false)",[organizationId]);
  const visible=await db.query('select organization_id,name from customers');
  assert.equal(visible.rows.length,1);assert.equal(visible.rows[0].organization_id,organizationId);assert.equal(visible.rows[0].name,`Customer ${i}`);
  const foreignTenant=trialTenants[(i+1)%trialTenants.length];
  await assert.rejects(db.query("insert into customers(organization_id,external_id,customer_no,name) values($1,'forbidden','K-002','Cross tenant')",[foreignTenant]),e=>e.code==='42501');
  assert.equal((await db.query("update customers set name='forbidden' where organization_id=$1 returning id",[foreignTenant])).rows.length,0);
  assert.equal((await db.query('delete from customers where organization_id=$1 returning id',[foreignTenant])).rows.length,0);
 }
 await db.query("select set_config('app.organization_id','',false)");
 assert.equal((await db.query('select * from customers')).rows.length,0);
 await db.exec('reset role');
 console.log('50 independently provisioned trial tenants: read/write/delete isolation passed (non-superuser RLS).');

 // Expired unpaid trials must become read-only while paid/Stripe-linked trials stay untouched.
 const lifecycleDb=dataModule('export async function query(text,params=[]){return globalThis.__lifecycleQuery(text,params)}');
 globalThis.__lifecycleQuery=(text,params)=>db.query(text,params);
 const lifecycleSource=(await fs.readFile('lib/server/subscription-lifecycle.ts','utf8')).replace('import "server-only";','').replace('"@/lib/server/db"',JSON.stringify(lifecycleDb));
 const {expireUnpaidTrials}=await import(dataModule(lifecycleSource));
 const expiredTrial=await provisionOrganization({userId:'expired-trial-user',email:'expired-trial@example.invalid',name:'Expired Trial',companyName:'Expired Trial AG',plan:'start',mode:'trial'});
 await db.query("update organization_subscriptions set trial_until=now()-interval '1 day' where organization_id=$1",[expiredTrial.organizationId]);
 await expireUnpaidTrials();
 assert.equal((await db.query('select status from organization_subscriptions where organization_id=$1',[expiredTrial.organizationId])).rows[0].status,'expired');
 assert.equal((await db.query('select status from organizations where id=$1',[expiredTrial.organizationId])).rows[0].status,'read_only');
 assert.equal((await db.query('select platform_status from platform_tenants where organization_id=$1',[expiredTrial.organizationId])).rows[0].platform_status,'read_only');
 const linkedTrial=await provisionOrganization({userId:'linked-trial-user',email:'linked-trial@example.invalid',name:'Linked Trial',companyName:'Linked Trial AG',plan:'start',mode:'trial'});
 await db.query("update organization_subscriptions set trial_until=now()-interval '1 day',billing_subscription_id='sub_pending' where organization_id=$1",[linkedTrial.organizationId]);
 await expireUnpaidTrials();
 assert.equal((await db.query('select status from organization_subscriptions where organization_id=$1',[linkedTrial.organizationId])).rows[0].status,'trial');
 delete globalThis.__lifecycleQuery;
 // Use the actual Stripe transport/signature code with an isolated HTTP fixture.
 globalThis.__billingEnv={stripeSecretKey:'sk_test_fixture',stripeWebhookSecret:'whsec_fixture',appUrl:'https://example.invalid',stripePrices:{start:{monthly:'price_start_m'},business:{yearly:'price_business_y'},pro:{}}};
 const billingEnv=dataModule('export const env=globalThis.__billingEnv');
 const billingLimits=dataModule(await fs.readFile('config/limits.ts','utf8'));
 let stripeSource=(await fs.readFile('lib/server/stripe.ts','utf8')).replace("import 'server-only';",'').replace("'@/lib/server/env'",JSON.stringify(billingEnv)).replace("'@/lib/server/http'",JSON.stringify(http)).replace("'@/config/limits'",JSON.stringify(billingLimits));
 const stripeModule=dataModule(stripeSource);
 let billingSource=(await fs.readFile('lib/server/repositories/stripe-billing.ts','utf8')).replace("import 'server-only';",'').replace("'../http'",JSON.stringify(http)).replace("'../env'",JSON.stringify(billingEnv)).replace("'../stripe'",JSON.stringify(stripeModule)).replace("'@/lib/subscription-plans'",JSON.stringify(entitlementModule));
 const {startBillingCheckout,processStripeEvent}=await import(dataModule(billingSource));
 const {verifyStripeSignature,stripeApiVersion}=await import(stripeModule);
 const {createHmac}=await import('node:crypto');
 const payload='{"id":"evt_test"}',timestamp=Math.floor(Date.now()/1000);
 const digest=createHmac('sha256','whsec_fixture').update(timestamp+'.'+payload).digest('hex');
 assert.equal(verifyStripeSignature(payload,`t=${timestamp},v1=${digest}`),true);
 assert.equal(verifyStripeSignature(payload,`t=NaN,v1=${digest}`),false);
 assert.equal(verifyStripeSignature(payload,`t=${timestamp},v1=xyz`),false);
 assert.equal(verifyStripeSignature(payload+'x',`t=${timestamp},v1=${digest}`),false);
 assert.equal(verifyStripeSignature(payload,`t=${timestamp-600},v1=${digest}`),false);
 const billingTenant=await provisionOrganization({userId:'billing-probe',email:'billing-probe@example.invalid',name:'Billing Probe',companyName:'Billing Probe',plan:'start',mode:'trial'});
 const billingSession={organizationId:billingTenant.organizationId,userId:'billing-probe',email:'billing-probe@example.invalid',role:'owner'};
 const prices={price_start_m:{id:'price_start_m',active:true,livemode:false,currency:'chf',unit_amount:2900,recurring:{interval:'month',interval_count:1}},price_business_y:{id:'price_business_y',active:true,livemode:false,currency:'chf',unit_amount:69000,recurring:{interval:'year',interval_count:1}}};
 let authoritative={id:'sub_fixture',customer:'cus_fixture',metadata:{organization_id:billingTenant.organizationId},status:'active',cancel_at_period_end:true,items:{data:[{quantity:1,price:prices.price_business_y,current_period_end:timestamp+86400}]}};
 let failInvoice=false,checkoutCalls=0,expireCalls=0,checkoutState="open";
 const originalFetch=globalThis.fetch;
 globalThis.fetch=async(url,options)=>{
  assert.equal(options.headers['Stripe-Version'],stripeApiVersion);
  const path=new URL(url).pathname;
  if(path.startsWith('/v1/prices/'))return Response.json(prices[path.split('/').pop()]);
  if(path==='/v1/customers'){assert.ok(options.headers['Idempotency-Key']);return Response.json({id:'cus_fixture'});}
  if(path==='/v1/checkout/sessions'){checkoutCalls++;const form=options.body;assert.ok(options.headers['Idempotency-Key']);assert.equal(form.get('success_url'),'https://example.invalid/einstellungen/abonnement?checkout=success');assert.equal(form.get('customer'),'cus_fixture');return Response.json({id:'cs_fixture_'+checkoutCalls,url:'https://checkout.stripe.com/c/pay_fixture',expires_at:timestamp+86400});}
  if(path.startsWith('/v1/checkout/sessions/')&&options.method==='GET')return Response.json({status:checkoutState});
  if(path.startsWith('/v1/checkout/sessions/')&&path.endsWith('/expire')){expireCalls++;return Response.json({status:'expired'});}
  if(path==='/v1/subscriptions/sub_fixture')return Response.json(authoritative);
  if(path==='/v1/invoices/in_fixture'){if(failInvoice)throw new Error('Simulated failure');return Response.json({id:'in_fixture',customer:'cus_fixture',status:'paid',amount_paid:69000,currency:'chf',status_transitions:{paid_at:timestamp}});}
  throw new Error('Unexpected Stripe request: '+path);
 };
 await db.query("select set_config('app.organization_id',$1,false)",[billingTenant.organizationId]);
 const requestKey='00000000-0000-4000-8000-000000000034';
 const checkout=await globalThis.__provisionTest(c=>startBillingCheckout(c,billingSession,'business','yearly',requestKey));
 assert.ok(checkout.url.startsWith('https://checkout.stripe.com/'));
 const sameCheckout=await globalThis.__provisionTest(c=>startBillingCheckout(c,billingSession,'business','yearly','00000000-0000-4000-8000-000000000035'));
 assert.equal(checkout.url,sameCheckout.url);assert.equal(checkoutCalls,1);
 checkoutState='complete';
 await assert.rejects(globalThis.__provisionTest(c=>startBillingCheckout(c,billingSession,'business','yearly',requestKey)),e=>e.code==='checkout_pending');
 checkoutState='expired';
 await assert.rejects(globalThis.__provisionTest(c=>startBillingCheckout(c,billingSession,'business','yearly',requestKey)),e=>e.code==='checkout_request_expired');
 assert.equal(checkoutCalls,1);checkoutState='open';
 await assert.rejects(globalThis.__provisionTest(c=>startBillingCheckout(c,billingSession,'start','monthly',requestKey)),e=>e.code==='checkout_request_reused');
 await assert.rejects(globalThis.__provisionTest(c=>startBillingCheckout(c,{...billingSession,organizationId:provisioned.organizationId},'start','monthly',requestKey)),e=>e.status===403);
 await globalThis.__provisionTest(c=>startBillingCheckout(c,billingSession,'start','monthly','00000000-0000-4000-8000-000000000036'));
 assert.equal(expireCalls,1);assert.equal(checkoutCalls,2);
 assert.equal((await db.query('select count(*)::int total from billing_checkout_sessions where organization_id=$1 and expires_at>now()',[billingTenant.organizationId])).rows[0].total,1);
 const invoiceEvent={id:'evt_fixture',livemode:false,type:'invoice.paid',data:{object:{id:'in_fixture',customer:'cus_fixture',parent:{subscription_details:{subscription:'sub_fixture'}}}}};
 failInvoice=true;
 await assert.rejects(globalThis.__provisionTest(c=>processStripeEvent(c,invoiceEvent)),e=>e.code==='stripe_unavailable');
 assert.equal((await db.query("select * from billing_webhook_events where external_event_id='evt_fixture'")).rows.length,0);
 assert.equal((await db.query('select status from organization_subscriptions where organization_id=$1',[billingTenant.organizationId])).rows[0].status,'trial');
 failInvoice=false;
 assert.equal((await globalThis.__provisionTest(c=>processStripeEvent(c,invoiceEvent))).processed,true);
 assert.equal((await globalThis.__provisionTest(c=>processStripeEvent(c,invoiceEvent))).duplicate,true);
 const billed=(await db.query('select * from organization_subscriptions where organization_id=$1',[billingTenant.organizationId])).rows[0];
 assert.equal(billed.plan,'business');assert.equal(billed.status,'active');assert.equal(billed.billing_interval,'yearly');assert.equal(Number(billed.unit_amount_chf),690);assert.equal(billed.cancel_at_period_end,true);
 assert.equal((await db.query('select max_users from organization_entitlements where organization_id=$1',[billingTenant.organizationId])).rows[0].max_users,15);
 const ledger=(await db.query("select * from platform_billing_payments where external_id='in_fixture'")).rows;
 assert.equal(ledger.length,1);assert.equal(Number(ledger[0].amount),690);
 // A stale cancellation event must use current provider state (still active).
 await globalThis.__provisionTest(c=>processStripeEvent(c,{id:'evt_stale',livemode:false,type:'customer.subscription.deleted',data:{object:{id:'sub_fixture',customer:'cus_fixture',status:'canceled'}}}));
 assert.equal((await db.query('select status from organization_subscriptions where organization_id=$1',[billingTenant.organizationId])).rows[0].status,'active');
 await db.query("update organizations set status='suspended' where id=$1",[billingTenant.organizationId]);
 await globalThis.__provisionTest(c=>processStripeEvent(c,{...invoiceEvent,id:'evt_suspended'}));
 assert.equal((await db.query('select status from organizations where id=$1',[billingTenant.organizationId])).rows[0].status,'suspended');
 await assert.rejects(globalThis.__provisionTest(c=>processStripeEvent(c,{...invoiceEvent,id:'evt_wrong_mode',livemode:true})),e=>e.code==='stripe_mode_mismatch');
 authoritative={...authoritative,metadata:{organization_id:demo}};
 await assert.rejects(globalThis.__provisionTest(c=>processStripeEvent(c,{...invoiceEvent,id:'evt_wrong_tenant'})),e=>e.code==='subscription_mapping_invalid');
 await db.exec('set role tenant_probe');await db.query("select set_config('app.organization_id',$1,false)",[demo]);
 assert.equal((await db.query('select * from billing_checkout_sessions')).rows.length,0);
 await db.exec('reset role');
 globalThis.fetch=originalFetch;delete globalThis.__billingEnv;
 console.log('Stripe signature, persisted checkout retries, duplicate/stale events, rollback, billing ledger, entitlements and tenant mapping passed (HTTP fixtures).');

 delete globalThis.__provisionTest;
 delete globalThis.__customerPersistenceTest;
 console.log('PostgreSQL migrations, deterministic fixtures and tenant/platform RLS passed.');
}finally{await db.close()}
