import {randomUUID} from "node:crypto";
import {PGlite} from '@electric-sql/pglite';
import {pgcrypto} from '@electric-sql/pglite/contrib/pgcrypto';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import ts from 'typescript';
import { SwissQRBill } from 'swissqrbill/svg';
import { isQRReferenceValid } from 'swissqrbill/utils';
const db=new PGlite({extensions:{pgcrypto}});
const demo='00000000-0000-4000-8000-000000000099';
try{
 await db.exec('create extension pgcrypto; create role schema_owner; grant usage,create on schema public to schema_owner; set role schema_owner');
 for(const file of (await fs.readdir('database/migrations')).filter(x=>x.endsWith('.sql')).sort()){
  await db.exec('begin');
  try{
   const presentation=file==='0037_demo_document_presentation.sql';
   const probe='00000000-0000-4000-8000-000000000077';
   if(presentation)await db.query("insert into organizations(id,name,legal_name,slug,is_demo) values($1,'Binso Demo AG','Binso Demo AG','presentation-production-probe',false)",[probe]);
   if(presentation)await db.query("select set_config('app.organization_id',$1,true)",[demo]);
   const snapshotMigration=file==='0045_document_snapshots.sql';
   const snapshotBefore=snapshotMigration?(await db.query("select to_jsonb(i)-'issuer_snapshot'-'customer_snapshot'-'payment_snapshot'-'document_snapshot' data from invoices i order by id")).rows:null;
   const before=presentation?(await db.query('select id,organization_id,customer_id,subtotal,vat_amount,total_amount,paid_amount from invoices order by id')).rows:null;
   await db.exec(await fs.readFile('database/migrations/'+file,'utf8'));
   if(snapshotMigration){
    assert.deepEqual((await db.query("select to_jsonb(i)-'issuer_snapshot'-'customer_snapshot'-'payment_snapshot'-'document_snapshot' data from invoices i order by id")).rows,snapshotBefore,'Snapshot migration must preserve every other persisted invoice field');
    assert.equal((await db.query("select count(*)::int n from invoices where not document_snapshot ? 'version'")).rows[0].n,0,'Legacy invoices are frozen with explicit provenance');
   }
   if(presentation){
    assert.deepEqual((await db.query('select id,organization_id,customer_id,subtotal,vat_amount,total_amount,paid_amount from invoices order by id')).rows,before,'Demo presentation migration must preserve IDs, links and financial amounts');
    assert.equal((await db.query('select name from organizations where id=$1',[probe])).rows[0].name,'Binso Demo AG','Non-demo organizations must remain untouched');
    assert.equal((await db.query('select legal_name from organizations where id=$1',[demo])).rows[0].legal_name,'Alpenblick Digital AG');
    assert.equal((await db.query("select count(*)::int n from invoices where organization_id=$1 and invoice_no like 'DEMO-%'",[demo])).rows[0].n,0);
    await db.query('delete from organizations where id=$1',[probe]);
   }
   await db.exec('commit')
  }catch(e){await db.exec('rollback');throw new Error(file+': '+e.message)}
 }
 await db.exec('reset role');
 const demoProfiles=(await db.query("select c.id,c.city,c.address,c.email,(select count(*)::int from customer_contacts cc where cc.organization_id=c.organization_id and cc.customer_id=c.id and cc.is_primary and cc.archived_at is null) primary_contacts from customers c where c.organization_id=$1 and c.external_id in ('demo-customer-acme','demo-customer-alpin','demo-customer-nova')",[demo])).rows;
 assert.equal(demoProfiles.length,3);assert.ok(demoProfiles.every(c=>c.city&&c.address&&c.email&&!c.email.endsWith('example.invalid')&&c.primary_contacts===1),'Every canonical demo customer needs a plausible profile and one main contact');
 await db.exec(`create role tenant_probe; grant usage on schema public to tenant_probe; grant select,insert,update,delete on all tables in schema public to tenant_probe;`);
 await db.exec('set role tenant_probe');
 assert.equal((await db.query('select count(*)::int n from invoices')).rows[0].n,0);
 await db.query("select set_config('app.organization_id',$1,false)",[demo]);
 assert.ok((await db.query('select count(*)::int n from invoices')).rows[0].n>20);
 assert.equal((await db.query("select count(*)::int n from operating_costs where scope='platform'")).rows[0].n,0);
 await db.query("select set_config('app.organization_id',$1,false)",['00000000-0000-4000-8000-000000000001']);
 assert.equal((await db.query('select count(*)::int n from invoices')).rows[0].n,0);
 await db.query("select set_config('app.platform_operator','true',false)");
 assert.equal((await db.query('select count(*)::int n from platform_billing_payments')).rows[0].n,22);
 assert.equal((await db.query("select count(*)::int n from operating_costs where scope='platform' and not is_demo")).rows[0].n,0);
 await db.exec('reset role');
 // Re-running the deterministic fixture cannot create duplicate customers/payments.
 const before=(await db.query('select count(*)::int n from payments')).rows[0].n;
 await db.exec('begin');await db.exec(await fs.readFile('database/migrations/0023_finance_and_demo_fixture.sql','utf8'));await db.exec('commit');
 assert.equal((await db.query('select count(*)::int n from payments')).rows[0].n,before);
 const dataModule=source=>'data:text/javascript;base64,'+Buffer.from(ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext}}).outputText).toString('base64');
 const permissions=dataModule(await fs.readFile('lib/permissions.ts','utf8'));
 const audit=dataModule((await fs.readFile('lib/server/audit.ts','utf8')).replace('import "server-only";',''));
 const http=dataModule('export class ApiError extends Error {constructor(status,code,message){super(message);this.status=status;this.code=code}}');
 const qrSource=(await fs.readFile('lib/qr-bill.ts','utf8')).replace('"swissqrbill/utils"',JSON.stringify(new URL('../node_modules/swissqrbill/lib/esm/shared/utils.js',import.meta.url).href));
 const qrModule=dataModule(qrSource);
 const moneyModule=dataModule(await fs.readFile("lib/money.ts","utf8"));
 const financialModule=dataModule((await fs.readFile("lib/financial-status.ts","utf8")).replace('"./money"',JSON.stringify(moneyModule)));
 const idempotencyModule=dataModule((await fs.readFile('lib/server/business-idempotency.ts','utf8')).replace("import 'server-only';",'').replace("'./http'",JSON.stringify(http)));
 const businessSource=(await fs.readFile('lib/server/repositories/business-api.ts','utf8')).replace('import "server-only";','').replace('"../business-idempotency"',JSON.stringify(idempotencyModule)).replace('"../http"',JSON.stringify(http)).replace('"../audit"',JSON.stringify(audit)).replace('"@/lib/permissions"',JSON.stringify(permissions)).replace('"@/lib/qr-bill"',JSON.stringify(qrModule)).replace('"@/lib/financial-status"',JSON.stringify(financialModule));
 const {listApiBusiness,mutateApiBusiness:rawMutation}=await import(dataModule(businessSource));
 const mutateApiBusiness=(c,s,operation,args)=>rawMutation(c,s,operation,{...args,p_idempotency_key:args.p_idempotency_key??randomUUID()});
 const client={query:async(...args)=>{const result=await db.query(...args);return {...result,rowCount:result.rows.length}}};
 const session={organizationId:demo,userId:'demo-readonly',role:'owner'};
 await db.query("select set_config('app.organization_id',$1,false)",[demo]);
 for(const table of ['customers','customer_contacts','products','employees','expenses','documents','payments'])assert.ok((await listApiBusiness(client,session,table,'')).length>0,table+' must have readable canonical fixture data');
 assert.equal((await listApiBusiness(client,session,'documents','number=eq.RE-2026-019')).length,1);
 const documentArgs={p_kind:'invoice',p_customer_id:'10000000-0000-4000-8000-000000000001',p_number:'TEST-001',p_issue_date:'2026-10-04',p_due_date:'2026-11-04',p_vat_rate:8.1,p_currency:'CHF',p_note:'Test',p_items:[{description:'Consulting',quantity:2,unit_price:100}]};
 const company=(await db.query('select * from organizations where id=$1',[demo])).rows[0];
 await db.query('update organizations set iban=null,qr_iban=null where id=$1',[demo]);
 await assert.rejects(()=>mutateApiBusiness(client,session,'create_document_atomic',documentArgs),e=>e.code==='invoice_payment_setup_required');
 await db.query('update organizations set iban=$2 where id=$1',[demo,company.iban]);
 const document=await mutateApiBusiness(client,session,'create_document_atomic',documentArgs);
 // Real trigger tests: template inheritance, explicit replacement, all write
 // paths, issue snapshots, later company changes and frozen historical texts.
 await db.query("update organizations set invoice_intro_text='Invoice original',invoice_footer_text='Invoice closing',quote_intro_text='Offer original',quote_footer_text='Offer closing' where id=$1",[demo]);
 const snapshotInvoice=await mutateApiBusiness(client,session,'create_document_atomic',{...documentArgs,p_number:'SNAPSHOT-INVOICE',p_note:''});
 const snapshotOffer=await mutateApiBusiness(client,session,'create_document_atomic',{...documentArgs,p_kind:'offer',p_number:'SNAPSHOT-OFFER',p_valid_until:'2026-11-04',p_note:''});
 assert.equal(snapshotInvoice.document_snapshot.intro,'Invoice original');assert.equal(snapshotInvoice.document_snapshot.closing,'Invoice closing');
 assert.equal(snapshotOffer.document_snapshot.intro,'Offer original');assert.equal(snapshotOffer.document_snapshot.closing,'Offer closing');
 await db.query("update invoices set note='Individual replacement' where id=$1",[snapshotInvoice.id]);
 assert.equal((await listApiBusiness(client,session,'documents','id=eq.'+snapshotInvoice.id))[0].document_snapshot.intro,'Individual replacement');
 await db.query("update invoices set note='' where id=$1",[snapshotInvoice.id]);
 await db.query("update organizations set invoice_intro_text='Invoice newer',invoice_footer_text='New closing',quote_intro_text='Offer newer' where id=$1",[demo]);
 await db.query("update invoices set status='sent' where id=$1",[snapshotInvoice.id]);await db.query("update quotes set status='sent' where id=$1",[snapshotOffer.id]);
 const frozenInvoice=(await listApiBusiness(client,session,'documents','id=eq.'+snapshotInvoice.id))[0];
 assert.equal(frozenInvoice.document_snapshot.intro,'Invoice original');assert.equal(frozenInvoice.document_snapshot.closing,'Invoice closing');assert.equal(frozenInvoice.payment_snapshot.iban,company.iban);
 await db.query("update invoices set document_snapshot='{\"intro\":\"tampered\"}',paid_amount=20 where id=$1",[snapshotInvoice.id]);
 assert.deepEqual((await listApiBusiness(client,session,'documents','id=eq.'+snapshotInvoice.id))[0].document_snapshot,frozenInvoice.document_snapshot,'Issued snapshots cannot be rewritten by a payment or alternate write');
 const newer=await mutateApiBusiness(client,session,'create_document_atomic',{...documentArgs,p_kind:'offer',p_number:'SNAPSHOT-NEWER',p_valid_until:'2026-11-04',p_note:''});assert.equal(newer.document_snapshot.intro,'Offer newer');
 assert.equal((await listApiBusiness(client,session,'documents','id=eq.'+snapshotOffer.id))[0].document_snapshot.intro,'Offer original');
 await db.query('update organizations set invoice_intro_text=$2,invoice_footer_text=$3,quote_intro_text=$4,quote_footer_text=$5 where id=$1',[demo,company.invoice_intro_text,company.invoice_footer_text,company.quote_intro_text,company.quote_footer_text]);
 console.log('Document snapshots: creation defaults, individual replacement/reset, later template changes, invoice/offer issue and immutable payment/history passed.');
 assert.equal(document.issue_date,'2026-10-04');assert.equal(document.due_date,'2026-11-04');assert.equal(document.status,'draft');
 const {createQrBillData,validSwissIban}=await import(qrModule);
 assert.equal(validSwissIban('CH9300762011623852958'),false);
 const qrData=createQrBillData(company,{reference:document.qr_reference,number:document.number,total:Number(document.total),currency:document.currency});
 assert.equal(qrData.amount,216.2);assert.equal(qrData.creditor.account,company.iban);assert.equal(qrData.reference,undefined);
 const qrReference=createQrBillData({...company,qr_iban:'CH4431999123000889012'},{reference:document.qr_reference,number:document.number,total:Number(document.total)});
 assert.equal(isQRReferenceValid(qrReference.reference),true);assert.equal(qrReference.reference,document.qr_reference);
 assert.equal((await db.query('select qr_reference from invoices where id=$1',[document.id])).rows[0].qr_reference,qrReference.reference);
 const unsafeName={...qrData,creditor:{...qrData.creditor,name:'Test <img src=x onerror=alert(1)>'}};
 const svg=new SwissQRBill(unsafeName,{language:'DE'}).toString();assert.ok(svg.includes('&lt;img'));assert.ok(!svg.includes('<img'));

 assert.equal(Number(document.total),216.2);
 await db.query("update invoices set status='sent' where id=$1",[document.id]);
 const paymentArgs={p_invoice_id:document.id,p_paid_on:'2026-10-04',p_amount:216.2,p_method:'bank',p_note:'Test',p_idempotency_key:'test-payment-0001'};
 const payment=await mutateApiBusiness(client,session,'create_payment_idempotent',paymentArgs);
 const retry=await mutateApiBusiness(client,session,'create_payment_idempotent',paymentArgs);
 assert.equal(payment.id,retry.id);
 assert.equal((await db.query('select status from invoices where id=$1',[document.id])).rows[0].status,'paid');
 await assert.rejects(mutateApiBusiness(client,session,'create_payment_idempotent',{...paymentArgs,p_amount:2}),e=>e.status===409);
 await assert.rejects(db.query("insert into tasks(organization_id,external_id,title,project_id) values('00000000-0000-4000-8000-000000000001','cross-tenant','Blocked','30000000-0000-4000-8000-000000000001')"),e=>e.code==='23503');
 const {dashboardAnalytics}=await import(dataModule((await fs.readFile('lib/server/repositories/dashboard.ts','utf8')).replace("import 'server-only';",'')));
 const analytics=await dashboardAnalytics(client,demo);
 const october=analytics.analyticsInvoices.find(row=>new Date(row.issue_date).toISOString().startsWith('2026-10'));
 assert.ok(october&&Number(october.invoice_count)>=1&&Number(october.customer_count)>=1);
 assert.ok(analytics.analyticsPayments.length>12);
 assert.equal(analytics.customerCount,Number((await db.query('select count(*) count from customers where organization_id=$1 and archived_at is null',[demo])).rows[0].count),'Dashboard counts all current customers, independently of month invoices');
 const fixtureSource=(await fs.readFile('lib/server/repositories/demo-fixture.ts','utf8')).replace('import "server-only";','').replace("'../http'",JSON.stringify(http));
 const {seedDatabaseDemo}=await import(dataModule(fixtureSource));
 const sandbox='00000000-0000-4000-8000-000000000098';
 await db.query("insert into organizations(id,name,slug,is_demo,status) values($1,'Synthetic sandbox','sandbox-test',true,'trial')",[sandbox]);
 await db.query("insert into app_users(id,email,display_name,status) values('sandbox-user','sandbox-user@example.invalid','Demo','active')");
 await db.query("select set_config('app.organization_id',$1,false)",[sandbox]);
 await seedDatabaseDemo(client,sandbox,'sandbox-user');
 const sandboxInvoices=await db.query('select id from invoices where organization_id=$1',[sandbox]);
 assert.ok(sandboxInvoices.rows.length>20);
 await seedDatabaseDemo(client,sandbox,'sandbox-user');
 assert.equal((await db.query('select count(*)::int n from invoices where organization_id=$1',[sandbox])).rows[0].n,sandboxInvoices.rows.length);
 await db.query("select set_config('app.organization_id',$1,false)",[sandbox]);
 const clonedSession={...session,organizationId:sandbox,userId:'sandbox-user'};
 const clonedCustomer=(await listApiBusiness(client,clonedSession,'customers',''))[0];
 assert.notEqual(clonedCustomer.id,'10000000-0000-4000-8000-000000000001');
 const {translateBusinessWrite}=await import(dataModule(businessSource));
 const employeeWrite=translateBusinessWrite('employees',{first_name:'Test',last_name:'Person',email:'employee-qa@example.invalid',start_date:'2026-10-08',weekly_hours:37.5,workload_percent:80,vacation_days:25},true);
 assert.equal(employeeWrite.data.start_date,'2026-10-08','Employee entry date survives API-to-storage translation');
 assert.equal(translateBusinessWrite('employees',{email:'employee-qa@example.invalid',entry_date:'2026-10-01'},false).data.start_date,'2026-10-01');
 assert.equal(translateBusinessWrite('employees',{email:'employee-qa@example.invalid',start_date:null,entry_date:'2026-10-01'},false).data.start_date,null,'An intentional cleared date does not resurrect a stale alias');
 const expenseWrite=translateBusinessWrite('expenses',{merchant:'Test Hotel',category:'Reise',expense_date:'2026-10-04',amount:123.45,currency:'CHF',vat_rate:8.1,description:'Test expense',status:'submitted'},true);
 const fields={...expenseWrite.data,organization_id:sandbox};const keys=Object.keys(fields);
 const persistedExpense=await client.query(`insert into expenses(${keys.join(',')}) values(${keys.map((_,i)=>'$'+(i+1)).join(',')}) returning id`,Object.values(fields));
 const loadedExpense=(await listApiBusiness(client,clonedSession,'expenses','id=eq.'+persistedExpense.rows[0].id))[0];
 assert.equal(loadedExpense.category,'Reise');assert.equal(loadedExpense.status,'submitted');assert.equal(Number(loadedExpense.amount),123.45);
 const tenantWrapper=dataModule('export async function withTenant(org,user,fn){return globalThis.__customerPersistenceTest(org,user,fn)}');
 globalThis.__customerPersistenceTest=async(org,user,fn)=>{await db.query("select set_config('app.organization_id',$1,false)",[org]);return fn(client)};
 const customerSource=(await fs.readFile('lib/server/repositories/customers.ts','utf8')).replace('import "server-only";','').replace('"@/lib/server/db"',JSON.stringify(tenantWrapper)).replace('"@/lib/server/audit"',JSON.stringify(audit)).replace('"@/lib/server/http"',JSON.stringify(http));
 const customerRepository=await import(dataModule(customerSource));
 const input={name:'Persistence Test AG',email:'test@example.invalid',phone:'+41 00 000 00 00',city:'Zürich',postalCode:'8000',sector:'Beratung',address:'Testweg 1',uid:'TEST',language:'de',paymentDays:45,discount:5,notes:'Persistente interne Kundennotiz'};
 const created=await customerRepository.createCustomer(sandbox,'sandbox-user',input);
 const updated=await customerRepository.updateCustomer(sandbox,'sandbox-user',created.id,{city:'Bern',sector:'Handel'});
 assert.equal(updated.notes,input.notes);assert.equal(updated.uid,input.uid);assert.equal(updated.address,input.address);assert.equal(updated.city,'Bern');assert.equal(updated.sector,'Handel');assert.equal(updated.email,input.email);assert.equal(Number(updated.paymentDays),45);
 assert.equal((await customerRepository.listCustomers(sandbox,'sandbox-user')).find(row=>row.id===created.id).postal_code,'8000');
 await db.query("select set_config('app.organization_id',$1,false)",[demo]);
 assert.equal((await listApiBusiness(client,session,'customers','id=eq.'+created.id)).length,0);
 const fileId='f0000000-0000-4000-8000-000000000031';
 await db.query("insert into file_objects(id,organization_id,object_key,original_name,content_type,size_bytes,sha256,created_by,purpose,expense_id) values($1,$2,$3,'test.txt','text/plain',4,encode(digest('test','sha256'),'hex'),'sandbox-user','expense_receipt',$4)",[fileId,sandbox,sandbox+'/files/test.txt',persistedExpense.rows[0].id]);
 await db.query("insert into file_contents(file_id,organization_id,body) values($1,$2,convert_to('test','utf8'))",[fileId,sandbox]);
 assert.equal((await db.query("select convert_from(body,'utf8') value from file_contents where file_id=$1",[fileId])).rows[0].value,'test');
 await assert.rejects(db.query("update file_contents set body=convert_to('fail','utf8') where file_id=$1",[fileId]),e=>e.code==='23514');
 await db.exec('set role tenant_probe');await db.query("select set_config('app.organization_id',$1,false)",[demo]);
 assert.equal((await db.query('select * from file_contents where file_id=$1',[fileId])).rows.length,0);
 await db.exec('reset role');
 assert.equal((await db.query("select count(*)::int n from pg_constraint where contype='f' and not convalidated")).rows[0].n,0);
 const domain=dataModule(await fs.readFile('config/domain.ts','utf8'));
 const plans=dataModule((await fs.readFile('lib/plans.ts','utf8')).replaceAll('"@/config/domain"',JSON.stringify(domain)));
 const fixture=dataModule(fixtureSource);
 const transactions=dataModule('export async function withTransaction(fn){return globalThis.__provisionTest(fn)}');
 globalThis.__provisionTest=async(fn)=>{await db.exec('begin');try{const result=await fn(client);await db.exec('commit');return result}catch(e){await db.exec('rollback');throw e}};
 const provisionSource=(await fs.readFile('lib/server/provisioning.ts','utf8')).replace('import "server-only";','').replace('"./repositories/demo-fixture"',JSON.stringify(fixture)).replace('"@/lib/server/db"',JSON.stringify(transactions)).replace('"@/config/domain"',JSON.stringify(domain)).replace('"@/lib/plans"',JSON.stringify(plans));
 const entitlementModule=dataModule((await fs.readFile('lib/subscription-plans.ts','utf8')).replace("'@/config/domain'",JSON.stringify(domain)));
 const {provisionOrganization}=await import(dataModule(provisionSource.replace("'@/lib/subscription-plans'",JSON.stringify(entitlementModule))));
 const provisioned=await provisionOrganization({userId:'demo-provision-test',email:'demo-provision-test@example.invalid',name:'Demo Test',companyName:'Demo',plan:'business',mode:'demo'});
 assert.equal((await db.query('select email from employees where organization_id=$1 order by external_id limit 1',[provisioned.organizationId])).rows[0].email,'demo-provision-test@example.invalid','Writable demo timers must resolve the seeded user employee');
 assert.equal((await db.query('select is_demo from organizations where id=$1',[provisioned.organizationId])).rows[0].is_demo,true);
 assert.ok((await db.query('select count(*)::int n from invoices where organization_id=$1',[provisioned.organizationId])).rows[0].n>20);
 // Exercise real provisioning for 50 independent production-style trial tenants.
 const trialTenants=[];
 for(let i=0;i<50;i++){
  const trial=await provisionOrganization({userId:`trial-probe-${i}`,email:`trial-probe-${i}@example.invalid`,name:`Synthetic ${i}`,companyName:`Synthetic Company ${i}`,plan:'business',mode:'trial'});
  trialTenants.push(trial.organizationId);
  await db.query("select set_config('app.organization_id',$1,false)",[trial.organizationId]);
  await db.query("insert into customers(organization_id,external_id,customer_no,name) values($1,'same-external-id','K-001',$2)",[trial.organizationId,`Customer ${i}`]);
 }
 assert.equal(new Set(trialTenants).size,50);
 await db.exec('set role tenant_probe');
 for(const [i,organizationId] of trialTenants.entries()){
  await db.query("select set_config('app.organization_id',$1,false)",[organizationId]);
  const visible=await db.query('select organization_id,name from customers');
  assert.equal(visible.rows.length,1);assert.equal(visible.rows[0].organization_id,organizationId);assert.equal(visible.rows[0].name,`Customer ${i}`);
  const foreignTenant=trialTenants[(i+1)%trialTenants.length];
  await assert.rejects(db.query("insert into customers(organization_id,external_id,customer_no,name) values($1,'forbidden','K-002','Cross tenant')",[foreignTenant]),e=>e.code==='42501');
  assert.equal((await db.query("update customers set name='forbidden' where organization_id=$1 returning id",[foreignTenant])).rows.length,0);
  assert.equal((await db.query('delete from customers where organization_id=$1 returning id',[foreignTenant])).rows.length,0);
 }
 await db.query("select set_config('app.organization_id','',false)");
 assert.equal((await db.query('select * from customers')).rows.length,0);
 await db.exec('reset role');
 console.log('50 independently provisioned trial tenants: read/write/delete isolation passed (non-superuser RLS).');

 // Expired unpaid trials must become read-only while paid/Stripe-linked trials stay untouched.
 const lifecycleDb=dataModule('export async function query(text,params=[]){return globalThis.__lifecycleQuery(text,params)}');
 globalThis.__lifecycleQuery=(text,params)=>db.query(text,params);
 const lifecycleSource=(await fs.readFile('lib/server/subscription-lifecycle.ts','utf8')).replace('import "server-only";','').replace('"@/lib/server/db"',JSON.stringify(lifecycleDb));
 const {expireUnpaidTrials}=await import(dataModule(lifecycleSource));
 const expiredTrial=await provisionOrganization({userId:'expired-trial-user',email:'expired-trial@example.invalid',name:'Expired Trial',companyName:'Expired Trial AG',plan:'start',mode:'trial'});
 await db.query("update organization_subscriptions set trial_until=now()-interval '1 day' where organization_id=$1",[expiredTrial.organizationId]);
 await expireUnpaidTrials();
 assert.equal((await db.query('select status from organization_subscriptions where organization_id=$1',[expiredTrial.organizationId])).rows[0].status,'expired');
 assert.equal((await db.query('select status from organizations where id=$1',[expiredTrial.organizationId])).rows[0].status,'read_only');
 assert.equal((await db.query('select platform_status from platform_tenants where organization_id=$1',[expiredTrial.organizationId])).rows[0].platform_status,'read_only');
 const linkedTrial=await provisionOrganization({userId:'linked-trial-user',email:'linked-trial@example.invalid',name:'Linked Trial',companyName:'Linked Trial AG',plan:'start',mode:'trial'});
 await db.query("update organization_subscriptions set trial_until=now()-interval '1 day',billing_subscription_id='sub_pending' where organization_id=$1",[linkedTrial.organizationId]);
 await expireUnpaidTrials();
 assert.equal((await db.query('select status from organization_subscriptions where organization_id=$1',[linkedTrial.organizationId])).rows[0].status,'trial');
 delete globalThis.__lifecycleQuery;
 // Use the actual Stripe transport/signature code with an isolated HTTP fixture.
 globalThis.__billingEnv={stripeSecretKey:'sk_test_fixture',stripeWebhookSecret:'whsec_fixture',appUrl:'https://example.invalid',stripePrices:{start:{monthly:'price_start_m'},business:{yearly:'price_business_y'},pro:{}}};
 const billingEnv=dataModule('export const env=globalThis.__billingEnv');
 const billingLimits=dataModule(await fs.readFile('config/limits.ts','utf8'));
 let stripeSource=(await fs.readFile('lib/server/stripe.ts','utf8')).replace("import 'server-only';",'').replace("'@/lib/server/env'",JSON.stringify(billingEnv)).replace("'@/lib/server/http'",JSON.stringify(http)).replace("'@/config/limits'",JSON.stringify(billingLimits));
 const stripeModule=dataModule(stripeSource);
 let billingSource=(await fs.readFile('lib/server/repositories/stripe-billing.ts','utf8')).replace("import 'server-only';",'').replace("'../http'",JSON.stringify(http)).replace("'../env'",JSON.stringify(billingEnv)).replace("'../stripe'",JSON.stringify(stripeModule)).replace("'@/lib/subscription-plans'",JSON.stringify(entitlementModule));
 const {startBillingCheckout,processStripeEvent}=await import(dataModule(billingSource));
 const {verifyStripeSignature,stripeApiVersion}=await import(stripeModule);
 const {createHmac}=await import('node:crypto');
 const payload='{"id":"evt_test"}',timestamp=Math.floor(Date.now()/1000);
 const digest=createHmac('sha256','whsec_fixture').update(timestamp+'.'+payload).digest('hex');
 assert.equal(verifyStripeSignature(payload,`t=${timestamp},v1=${digest}`),true);
 assert.equal(verifyStripeSignature(payload,`t=NaN,v1=${digest}`),false);
 assert.equal(verifyStripeSignature(payload,`t=${timestamp},v1=xyz`),false);
 assert.equal(verifyStripeSignature(payload+'x',`t=${timestamp},v1=${digest}`),false);
 assert.equal(verifyStripeSignature(payload,`t=${timestamp-600},v1=${digest}`),false);
 const billingTenant=await provisionOrganization({userId:'billing-probe',email:'billing-probe@example.invalid',name:'Billing Probe',companyName:'Billing Probe',plan:'start',mode:'trial'});
 const billingSession={organizationId:billingTenant.organizationId,userId:'billing-probe',email:'billing-probe@example.invalid',role:'owner'};
 const prices={price_start_m:{id:'price_start_m',active:true,livemode:false,currency:'chf',unit_amount:2900,recurring:{interval:'month',interval_count:1}},price_business_y:{id:'price_business_y',active:true,livemode:false,currency:'chf',unit_amount:69000,recurring:{interval:'year',interval_count:1}}};
 let authoritative={id:'sub_fixture',customer:'cus_fixture',metadata:{organization_id:billingTenant.organizationId},status:'active',cancel_at_period_end:true,items:{data:[{quantity:1,price:prices.price_business_y,current_period_end:timestamp+86400}]}};
 let failInvoice=false,checkoutCalls=0,expireCalls=0,checkoutState="open";
 const originalFetch=globalThis.fetch;
 globalThis.fetch=async(url,options)=>{
  assert.equal(options.headers['Stripe-Version'],stripeApiVersion);
  const path=new URL(url).pathname;
  if(path.startsWith('/v1/prices/'))return Response.json(prices[path.split('/').pop()]);
  if(path==='/v1/customers'){assert.ok(options.headers['Idempotency-Key']);return Response.json({id:'cus_fixture'});}
  if(path==='/v1/checkout/sessions'){checkoutCalls++;const form=options.body;assert.ok(options.headers['Idempotency-Key']);assert.equal(form.get('success_url'),'https://example.invalid/einstellungen/abonnement?checkout=success');assert.equal(form.get('customer'),'cus_fixture');return Response.json({id:'cs_fixture_'+checkoutCalls,url:'https://checkout.stripe.com/c/pay_fixture',expires_at:timestamp+86400});}
  if(path.startsWith('/v1/checkout/sessions/')&&options.method==='GET')return Response.json({status:checkoutState});
  if(path.startsWith('/v1/checkout/sessions/')&&path.endsWith('/expire')){expireCalls++;return Response.json({status:'expired'});}
  if(path==='/v1/subscriptions/sub_fixture')return Response.json(authoritative);
  if(path==='/v1/invoices/in_fixture'){if(failInvoice)throw new Error('Simulated failure');return Response.json({id:'in_fixture',customer:'cus_fixture',status:'paid',amount_paid:69000,currency:'chf',status_transitions:{paid_at:timestamp}});}
  throw new Error('Unexpected Stripe request: '+path);
 };
 await db.query("select set_config('app.organization_id',$1,false)",[billingTenant.organizationId]);
 const requestKey='00000000-0000-4000-8000-000000000034';
 const checkout=await globalThis.__provisionTest(c=>startBillingCheckout(c,billingSession,'business','yearly',requestKey));
 assert.ok(checkout.url.startsWith('https://checkout.stripe.com/'));
 const sameCheckout=await globalThis.__provisionTest(c=>startBillingCheckout(c,billingSession,'business','yearly','00000000-0000-4000-8000-000000000035'));
 assert.equal(checkout.url,sameCheckout.url);assert.equal(checkoutCalls,1);
 checkoutState='complete';
 await assert.rejects(globalThis.__provisionTest(c=>startBillingCheckout(c,billingSession,'business','yearly',requestKey)),e=>e.code==='checkout_pending');
 checkoutState='expired';
 await assert.rejects(globalThis.__provisionTest(c=>startBillingCheckout(c,billingSession,'business','yearly',requestKey)),e=>e.code==='checkout_request_expired');
 assert.equal(checkoutCalls,1);checkoutState='open';
 await assert.rejects(globalThis.__provisionTest(c=>startBillingCheckout(c,billingSession,'start','monthly',requestKey)),e=>e.code==='checkout_request_reused');
 await assert.rejects(globalThis.__provisionTest(c=>startBillingCheckout(c,{...billingSession,organizationId:provisioned.organizationId},'start','monthly',requestKey)),e=>e.status===403);
 await globalThis.__provisionTest(c=>startBillingCheckout(c,billingSession,'start','monthly','00000000-0000-4000-8000-000000000036'));
 assert.equal(expireCalls,1);assert.equal(checkoutCalls,2);
 assert.equal((await db.query('select count(*)::int total from billing_checkout_sessions where organization_id=$1 and expires_at>now()',[billingTenant.organizationId])).rows[0].total,1);
 const invoiceEvent={id:'evt_fixture',livemode:false,type:'invoice.paid',data:{object:{id:'in_fixture',customer:'cus_fixture',parent:{subscription_details:{subscription:'sub_fixture'}}}}};
 failInvoice=true;
 await assert.rejects(globalThis.__provisionTest(c=>processStripeEvent(c,invoiceEvent)),e=>e.code==='stripe_unavailable');
 assert.equal((await db.query("select * from billing_webhook_events where external_event_id='evt_fixture'")).rows.length,0);
 assert.equal((await db.query('select status from organization_subscriptions where organization_id=$1',[billingTenant.organizationId])).rows[0].status,'trial');
 failInvoice=false;
 assert.equal((await globalThis.__provisionTest(c=>processStripeEvent(c,invoiceEvent))).processed,true);
 assert.equal((await globalThis.__provisionTest(c=>processStripeEvent(c,invoiceEvent))).duplicate,true);
 const billed=(await db.query('select * from organization_subscriptions where organization_id=$1',[billingTenant.organizationId])).rows[0];
 assert.equal(billed.plan,'business');assert.equal(billed.status,'active');assert.equal(billed.billing_interval,'yearly');assert.equal(Number(billed.unit_amount_chf),690);assert.equal(billed.cancel_at_period_end,true);
 assert.equal((await db.query('select max_users from organization_entitlements where organization_id=$1',[billingTenant.organizationId])).rows[0].max_users,15);
 const ledger=(await db.query("select * from platform_billing_payments where external_id='in_fixture'")).rows;
 assert.equal(ledger.length,1);assert.equal(Number(ledger[0].amount),690);
 // A stale cancellation event must use current provider state (still active).
 await globalThis.__provisionTest(c=>processStripeEvent(c,{id:'evt_stale',livemode:false,type:'customer.subscription.deleted',data:{object:{id:'sub_fixture',customer:'cus_fixture',status:'canceled'}}}));
 assert.equal((await db.query('select status from organization_subscriptions where organization_id=$1',[billingTenant.organizationId])).rows[0].status,'active');
 await db.query("update organizations set status='suspended' where id=$1",[billingTenant.organizationId]);
 await globalThis.__provisionTest(c=>processStripeEvent(c,{...invoiceEvent,id:'evt_suspended'}));
 assert.equal((await db.query('select status from organizations where id=$1',[billingTenant.organizationId])).rows[0].status,'suspended');
 await assert.rejects(globalThis.__provisionTest(c=>processStripeEvent(c,{...invoiceEvent,id:'evt_wrong_mode',livemode:true})),e=>e.code==='stripe_mode_mismatch');
 authoritative={...authoritative,metadata:{organization_id:demo}};
 await assert.rejects(globalThis.__provisionTest(c=>processStripeEvent(c,{...invoiceEvent,id:'evt_wrong_tenant'})),e=>e.code==='subscription_mapping_invalid');
 await db.exec('set role tenant_probe');await db.query("select set_config('app.organization_id',$1,false)",[demo]);
 assert.equal((await db.query('select * from billing_checkout_sessions')).rows.length,0);
 await db.exec('reset role');
 globalThis.fetch=originalFetch;delete globalThis.__billingEnv;
 console.log('Stripe signature, persisted checkout retries, duplicate/stale events, rollback, billing ledger, entitlements and tenant mapping passed (HTTP fixtures).');

 delete globalThis.__provisionTest;
 delete globalThis.__customerPersistenceTest;
 // Execute the actual timer handlers against the migrated database.
 const timerSession={organizationId:provisioned.organizationId,userId:'demo-provision-test',name:'Demo Test',email:'demo-provision-test@example.invalid',role:'owner'};
 globalThis.__timerSession=timerSession;
 globalThis.__timerTenant=async(org,user,task)=>{await db.exec('begin');try{await db.query("select set_config('app.organization_id',$1,true),set_config('app.user_id',$2,true)",[org,user]);const result=await task(client);await db.exec('commit');return result;}catch(e){await db.exec('rollback');throw e;}};
 const timerHttp=dataModule(`export class ApiError extends Error {constructor(status,code,message){super(message);this.status=status;this.code=code}} export const apiError=e=>({error:e.code,status:e.status});export const json=x=>x;export const assertSameOrigin=()=>{};export const cleanText=(x)=>typeof x==='string'?x.trim():'';export const readJson=async x=>x.body;`);
 let timerSource=await fs.readFile('app/api/time-tracker/route.ts','utf8');
 const timerDependencies={"@/lib/server/session":dataModule('export const requireSession=async()=>globalThis.__timerSession;'),"@/lib/server/rbac":dataModule('export const authorize=()=>{};'),"@/lib/server/db":dataModule('export const withTenant=(...args)=>globalThis.__timerTenant(...args);'),"@/lib/server/http":timerHttp};
 for(const [key,url] of Object.entries(timerDependencies))timerSource=timerSource.replaceAll(JSON.stringify(key),JSON.stringify(url));
 const timer=await import(dataModule(timerSource));
 await db.query("select set_config('app.organization_id',$1,false)",[timerSession.organizationId]);
 const timerCustomer=(await db.query('select id from customers where organization_id=$1 order by id limit 1',[timerSession.organizationId])).rows[0].id;
 const started=await timer.POST({body:{action:'start',project:'Direct customer work',customerId:timerCustomer,projectId:null}});
 assert.equal(started.tracker.customer_id,timerCustomer);
 assert.equal((await timer.GET()).tracker.customer_id,timerCustomer,'Reload retains customer without a project');
 await db.query('update active_time_trackers set accumulated_seconds=3600,active_since=now() where organization_id=$1 and user_id=$2',[timerSession.organizationId,timerSession.userId]);
 assert.equal((await timer.POST({body:{action:'project',project:'Other work',customerId:null,projectId:null}})).error,'tracker_context_locked');
 const paused=await timer.POST({body:{action:'pause'}});assert.equal(paused.tracker.customer_id,timerCustomer);assert.equal(paused.tracker.state,'paused');
 const finished=await timer.POST({body:{action:'finish'}});assert.ok(finished.item.id);
 const finishedTime=(await db.query('select customer_id,project_id,billable,hours from time_entries where id=$1',[finished.item.id])).rows[0];
 assert.equal(finishedTime.customer_id,timerCustomer);assert.equal(finishedTime.project_id,null);assert.equal(finishedTime.billable,true);assert.ok(Number(finishedTime.hours)>=1);
 assert.equal((await timer.GET()).tracker,null);
 const internal=await timer.POST({body:{action:'start',project:'Internal work',customerId:null,projectId:null}});assert.equal(internal.tracker.billable,false);
 const invalid=await timer.POST({body:{action:'project',project:'Invalid',customerId:'00000000-0000-4000-8000-000000000001',projectId:null}});assert.equal(invalid.error,'customer_invalid');
 await db.query("update active_time_trackers set state='paused', accumulated_seconds=1,active_since=null where organization_id=$1 and user_id=$2",[timerSession.organizationId,timerSession.userId]);
 const shortFinished=await timer.POST({body:{action:'finish'}});
 assert.ok(shortFinished.item.id,'A one-second timer must create a valid entry');
 assert.ok(Math.abs(Number(shortFinished.item.hours)*3600-1)<0.002,'Timer seconds must survive database persistence');
 assert.equal((await timer.GET()).tracker,null);
 assert.deepEqual(await timer.POST({body:{action:'finish'}}),{tracker:null},'Repeated stop must not duplicate an entry');
 delete globalThis.__timerSession;delete globalThis.__timerTenant;
 console.log('Timer customer-only start/reload/pause/finish, context lock and internal work passed.');

 // Exercise the process implementations against migrated PostgreSQL, not source strings.
 const processHttp=dataModule(`export class ApiError extends Error{constructor(status,code,message){super(message);this.status=status;this.code=code}};export const assertSameOrigin=()=>{};export const cleanText=(v)=>typeof v==='string'?v:'';export const readJson=async r=>r.body;export const json=(data,status=200)=>({data,status});export const validEmail=v=>/^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/.test(v);export const apiError=e=>({status:e instanceof Response?e.status:e.status??500,data:{error:e.code,message:e.message}});`);
 const processRbac=dataModule((await fs.readFile('lib/server/rbac.ts','utf8')).replace('import "server-only";','').replace('"@/lib/permissions"',JSON.stringify(permissions)));
 const processSession=dataModule('export async function requireSession(){return globalThis.__processSession}');
 const processDb=dataModule('export async function withTenant(org,user,fn){return globalThis.__processTransaction(org,fn)} export async function withPlatform(fn){return globalThis.__processPlatform(fn)}');
 globalThis.__processSession={...session,isDemo:false,organizationStatus:'active',email:'process@example.invalid'};
 globalThis.__processTransaction=async(org,fn)=>{await db.exec('begin');try{await db.query("select set_config('app.organization_id',$1,true)",[org]);const r=await fn(client);await db.exec('commit');return r}catch(e){await db.exec('rollback');throw e}};
 globalThis.__processPlatform=async(fn)=>{await db.exec('begin');try{await db.query("select set_config('app.platform_operator','true',true)");const r=await fn(client);await db.exec('commit');return r}catch(e){await db.exec('rollback');throw e}};
 const manualTimeSource=(await fs.readFile('app/api/time-entries/route.ts','utf8')).replace('"@/lib/money"',JSON.stringify(moneyModule)).replace('"@/lib/server/http"',JSON.stringify(processHttp)).replace('"@/lib/server/session"',JSON.stringify(processSession)).replace('"@/lib/server/rbac"',JSON.stringify(processRbac)).replace('"@/lib/server/db"',JSON.stringify(processDb)).replace('"@/lib/permissions"',JSON.stringify(permissions));
 const manualTimeHandler=await import(dataModule(manualTimeSource));globalThis.__processSession={...globalThis.__processSession,name:'Fixture Person'};
 const manualCreated=await manualTimeHandler.POST({body:{customerId:documentArgs.p_customer_id,projectName:'Arbeitszeit',description:'Manual fixture',durationMinutes:60,startedAt:'2026-10-06T12:00:00'}});
 assert.equal(manualCreated.status,201);assert.equal(manualCreated.data.item.customer_id,documentArgs.p_customer_id);assert.equal(manualCreated.data.item.billable,true);assert.equal(manualCreated.data.item.employee_name,'Fixture Person');
 const manualReloaded=(await manualTimeHandler.GET({nextUrl:new URL('https://example.invalid/api/time-entries')})).data.items.find(i=>i.id===manualCreated.data.item.id);
 assert.ok(manualCreated.data.item.customer_name);assert.equal(manualCreated.data.item.customer_name,manualReloaded.customer_name,'Customer label must match the reloaded record immediately');assert.equal(manualReloaded.employee_name,'Fixture Person');

 // Contacts retain structured names and exactly one selected primary under a customer lock.
 const contactSource=(await fs.readFile('lib/server/repositories/contacts.ts','utf8')).replace('import "server-only";','').replace('"../db"',JSON.stringify(processDb)).replace('"../http"',JSON.stringify(processHttp)).replace('"../audit"',JSON.stringify(audit));
 const contactRepository=await import(dataModule(contactSource));
 const contactA=await contactRepository.saveCustomerContact(globalThis.__processSession,documentArgs.p_customer_id,null,{firstName:'Anna Maria',lastName:'von Beispiel',email:'anna@example.invalid',isPrimary:true});
 assert.equal(contactA.first_name,'Anna Maria');assert.equal(contactA.last_name,'von Beispiel');assert.equal(contactA.is_primary,true);
 const contactB=await contactRepository.saveCustomerContact(globalThis.__processSession,documentArgs.p_customer_id,null,{firstName:'Max',lastName:'Test',isPrimary:true});
 const contactRows=await listApiBusiness(client,session,'customer_contacts','customer_id=eq.'+documentArgs.p_customer_id);
 assert.equal(contactRows.filter(c=>c.is_primary).length,1);assert.equal(contactRows.find(c=>c.id===contactA.id).first_name,'Anna Maria');assert.equal(contactRows.find(c=>c.id===contactA.id).is_primary,false);
 const editedContact=await contactRepository.saveCustomerContact(globalThis.__processSession,documentArgs.p_customer_id,contactA.id,{firstName:'Anna Maria',lastName:'von Beispiel',jobTitle:'Buchhaltung',isPrimary:true});
 assert.equal(editedContact.job_title,'Buchhaltung');assert.equal(editedContact.is_primary,true);
 await assert.rejects(()=>contactRepository.saveCustomerContact({...globalThis.__processSession,organizationId:sandbox},documentArgs.p_customer_id,contactA.id,{firstName:'Cross',lastName:'Tenant'}),e=>e.code==='not_found');
 await assert.rejects(()=>contactRepository.saveCustomerContact(globalThis.__processSession,documentArgs.p_customer_id,null,{firstName:'Bad',lastName:'Email',email:'invalid'}),e=>e.code==='email_invalid');
 await contactRepository.archiveCustomerContact(globalThis.__processSession,documentArgs.p_customer_id,contactB.id);
 assert.equal((await listApiBusiness(client,session,'customer_contacts','id=eq.'+contactB.id)).length,0);
 assert.ok((await db.query('select archived_at from customer_contacts where id=$1',[contactB.id])).rows[0].archived_at,'Archiving preserves contact references');
 const manualInternal=await manualTimeHandler.POST({body:{customerId:documentArgs.p_customer_id,projectName:'Arbeitszeit',durationMinutes:45,startedAt:'2026-10-06T12:00:00',billable:false,salesRate:125}});
 assert.equal(manualInternal.data.item.billable,false);assert.equal(Number(manualInternal.data.item.sales_rate),125);
 assert.equal((await manualTimeHandler.POST({body:{durationMinutes:60,billable:true}})).data.error,'billable_customer_required');
 assert.equal((await manualTimeHandler.POST({body:{durationMinutes:60,salesRate:-10}})).data.error,'rate_invalid');

 const contactHttpDependencies={"@/lib/server/http":processHttp,"@/lib/server/database":dataModule('export async function requireTenantFeature(){return {session:globalThis.__processSession}}'),"@/lib/server/rbac":processRbac,"@/lib/server/repositories/contacts":dataModule(contactSource)};
 let contactRouteSource=await fs.readFile('app/api/customers/[id]/contacts/[contactId]/route.ts','utf8');
 for(const [key,url] of Object.entries(contactHttpDependencies))contactRouteSource=contactRouteSource.replaceAll(JSON.stringify(key),JSON.stringify(url));
 const contactRoute=await import(dataModule(contactRouteSource));
 globalThis.__processSession={...session,role:'employee'};
 assert.equal((await contactRoute.DELETE({},{params:Promise.resolve({id:documentArgs.p_customer_id,contactId:contactA.id})})).status,403);
 globalThis.__processSession={...session,organizationStatus:'read_only'};
 assert.equal((await contactRoute.PATCH({body:{firstName:'A',lastName:'B'}},{params:Promise.resolve({id:documentArgs.p_customer_id,contactId:contactA.id})})).status,403);
 globalThis.__processSession={...session,isDemo:false,organizationStatus:'active',email:'process@example.invalid'};
 assert.equal((await contactRoute.PATCH({body:{firstName:'Anna Maria',lastName:'von Beispiel',isPrimary:true}},{params:Promise.resolve({id:documentArgs.p_customer_id,contactId:contactA.id})})).status,200);
 console.log('Contact structured names, primary replacement, edit/archive, tenant isolation and manual time rates passed.');
 const processSource=(await fs.readFile('lib/server/document-process.ts','utf8')).replace('"@/lib/qr-bill"',JSON.stringify(qrModule)).replace('"@/lib/financial-status"',JSON.stringify(financialModule)).replace('"@/lib/server/plan-access"',JSON.stringify(dataModule('export async function requireModuleEntitlement(){}'))).replace('import "server-only";','').replace('"./http"',JSON.stringify(processHttp)).replace('"./rbac"',JSON.stringify(processRbac)).replace('"./audit"',JSON.stringify(audit));
 const {changeDocumentStatus}=await import(dataModule(processSource));
 const processQuote=await mutateApiBusiness(client,session,'create_document_atomic',{...documentArgs,p_kind:'offer',p_number:'FLOW-QUOTE',p_valid_until:'2099-12-31'});
 await assert.rejects(()=>changeDocumentStatus(client,session,processQuote.number,'accept',''),e=>e.code==='transition_invalid');
 await changeDocumentStatus(client,session,processQuote.number,'issue','');
 await assert.rejects(()=>changeDocumentStatus(client,{...session,role:'reader'},processQuote.number,'accept',''));
 await changeDocumentStatus(client,session,processQuote.number,'accept','Telephone acceptance');
 assert.equal((await db.query('select status from quotes where id=$1',[processQuote.id])).rows[0].status,'accepted');
 await assert.rejects(()=>mutateApiBusiness(client,session,'update_document_atomic',{...documentArgs,p_kind:'offer',p_current_number:processQuote.number,p_number:processQuote.number}),e=>e.code==='document_locked');
 const converted=await mutateApiBusiness(client,session,'create_document_atomic',{...documentArgs,p_number:'FLOW-INVOICE',p_source_offer:processQuote.number});
 assert.equal((await db.query('select source_quote_id from invoices where id=$1',[converted.id])).rows[0].source_quote_id,processQuote.id);
 await assert.rejects(()=>mutateApiBusiness(client,session,'create_document_atomic',{...documentArgs,p_number:'FLOW-DUP',p_source_offer:processQuote.number}),e=>e.code==='offer_already_invoiced');
 await changeDocumentStatus(client,session,converted.number,'issue','');
 await assert.rejects(()=>mutateApiBusiness(client,session,'update_document_atomic',{...documentArgs,p_current_number:converted.number,p_number:converted.number}),e=>e.code==='document_locked');
 await changeDocumentStatus(client,session,converted.number,'cancel','Cancelled before payment');
 const expired=await mutateApiBusiness(client,session,'create_document_atomic',{...documentArgs,p_kind:'offer',p_number:'FLOW-EXPIRED',p_valid_until:'2000-01-01'});
 await changeDocumentStatus(client,session,expired.number,'issue','');
 await assert.rejects(()=>changeDocumentStatus(client,session,expired.number,'accept',''),e=>e.code==='offer_expired');
 // Failed/pending delivery must block edits; sent requests cannot rewrite issued documents.
 const pending=await mutateApiBusiness(client,session,'create_document_atomic',{...documentArgs,p_number:'FLOW-PENDING'});
 await db.query("insert into document_deliveries(organization_id,kind,document_id,recipient,status,request_key,created_by_user_id) values($1,'invoice',$2,'fixture@example.invalid','sending','flow-key','fixture')",[demo,pending.id]);
 await assert.rejects(()=>mutateApiBusiness(client,session,'update_document_atomic',{...documentArgs,p_current_number:pending.number,p_number:pending.number}),e=>e.code==='delivery_pending');
 await assert.rejects(()=>changeDocumentStatus(client,session,pending.number,'issue',''),e=>e.code==='delivery_pending');
 const databaseSource=(await fs.readFile('lib/server/database.ts','utf8')).replace('import "server-only";','').replace('"./repositories/business-api"',JSON.stringify(businessUrlForProcess())).replace('"./plan-access"',JSON.stringify(dataModule('export async function requireModuleEntitlement(){}'))).replace('"./audit"',JSON.stringify(audit)).replace('"@/lib/permissions"',JSON.stringify(permissions)).replace('"./http"',JSON.stringify(processHttp)).replace('"./rbac"',JSON.stringify(processRbac)).replace('"./session"',JSON.stringify(processSession)).replace('"./db"',JSON.stringify(processDb)).replace('"./repositories/operator-api"',JSON.stringify(dataModule('export function listOperatorBusiness(){}export function insertOperatorBusiness(){}export function updateOperatorBusiness(){}'))).replace('"./operator/audit"',JSON.stringify(dataModule('export function platformAudit(){}'))).replace('"./operator/session"',JSON.stringify(dataModule('export function requireOperatorSession(){}')));
 function businessUrlForProcess(){return dataModule(businessSource)}
 const databaseProcess=await import(dataModule(databaseSource));
 const employeeValidation=dataModule(await fs.readFile('lib/employee-validation.ts','utf8'));
 const employeeRouteSource=(await fs.readFile('app/api/employees/route.ts','utf8')).replace('"@/lib/employee-validation"',JSON.stringify(employeeValidation)).replace('"@/lib/money"',JSON.stringify(moneyModule)).replace('"@/lib/server/http"',JSON.stringify(processHttp)).replace('"@/lib/server/database"',JSON.stringify(dataModule(databaseSource)));
 const employeeRoute=await import(dataModule(employeeRouteSource));
 const employeeBody={firstName:'Regression',lastName:'Employee',email:'regression-employee@example.invalid',jobTitle:'ICT',workloadPercent:80,weeklyHours:37.5,vacationDays:25,entryDate:'2026-10-08'};
 assert.equal((await employeeRoute.POST({body:{...employeeBody,email:'bad-email'}})).status,400);
 assert.equal((await employeeRoute.POST({body:{...employeeBody,entryDate:'2026-02-30'}})).status,400);
 const createdEmployee=await employeeRoute.POST({body:employeeBody});assert.equal(createdEmployee.status,201);
 assert.equal(String((await db.query('select start_date::text from employees where id=$1',[createdEmployee.data.item.id])).rows[0].start_date),'2026-10-08');
 const employeeEditSource=(await fs.readFile('app/api/employees/[id]/route.ts','utf8')).replace('"@/lib/employee-validation"',JSON.stringify(employeeValidation)).replace('"@/lib/money"',JSON.stringify(moneyModule)).replace('"@/lib/server/http"',JSON.stringify(processHttp)).replace('"@/lib/server/database"',JSON.stringify(dataModule(databaseSource)));
 const employeeEdit=await import(dataModule(employeeEditSource));
 assert.equal((await employeeEdit.PATCH({body:{...employeeBody,weeklyHours:38}},{params:Promise.resolve({id:createdEmployee.data.item.id})})).status,200);
 assert.equal(String((await db.query('select start_date::text from employees where id=$1',[createdEmployee.data.item.id])).rows[0].start_date),'2026-10-08','Editing hours must not clear the employee entry date');
 const expenseBody={employee_id:null,customer_id:documentArgs.p_customer_id,billable:true,merchant:'Fixture meal',expense_date:'2026-10-06',category:'Verpflegung',amount:42,currency:'CHF',vat_rate:8.1,status:'submitted'};
 const expenseId=(await databaseProcess.tenantInsert('expenses',expenseBody))[0].id;
 const repeatedExpense=(await databaseProcess.tenantInsert('expenses',expenseBody,'expense-process-retry'))[0].id;
 assert.equal((await databaseProcess.tenantInsert('expenses',expenseBody,'expense-process-retry'))[0].id,repeatedExpense,'Creation retry must return the same expense');
 await assert.rejects(()=>databaseProcess.tenantInsert('expenses',{...expenseBody,amount:99},'expense-process-retry'),e=>e.code==='idempotency_conflict');
 await assert.rejects(()=>databaseProcess.tenantInsert('expenses',{...expenseBody,status:'approved'}),e=>e.code==='submission_required');
 globalThis.__processSession={...session,role:'project_manager'};
 await assert.rejects(()=>databaseProcess.tenantUpdate('expenses',expenseId,{...expenseBody,status:'approved'}),e=>e.code==='self_approval_forbidden');
 globalThis.__processSession=session;
 await databaseProcess.tenantUpdate('expenses',expenseId,{...expenseBody,status:'approved'});
 await assert.rejects(()=>databaseProcess.tenantUpdate('expenses',expenseId,{...expenseBody,amount:99,status:'submitted'}),e=>e.code==='expense_locked');
 const expenseInvoice=await mutateApiBusiness(client,session,'create_document_atomic',{...documentArgs,p_number:'FLOW-EXPENSE',p_items:[{description:'Fixture meal',quantity:1,unit_price:42,expense_ids:[expenseId]}]});
 assert.equal((await db.query('select invoiced_invoice_id from expenses where id=$1',[expenseId])).rows[0].invoiced_invoice_id,expenseInvoice.id);
 await assert.rejects(()=>globalThis.__processTransaction(demo,c=>mutateApiBusiness(c,session,'create_document_atomic',{...documentArgs,p_number:'FLOW-EXPENSE-DUP',p_items:[{description:'Fixture meal',quantity:1,unit_price:42,expense_ids:[expenseId]}]})),e=>e.code==='expenses_changed');
 assert.equal((await db.query("select count(*)::int n from invoices where invoice_no='FLOW-EXPENSE-DUP'")).rows[0].n,0,'Failed duplicate billing rolls back the invoice');
 const reimbursementSource=(await fs.readFile('app/api/expenses/[id]/reimbursement/route.ts','utf8')).replace('"@/lib/server/plan-access"',JSON.stringify(dataModule('export async function requireModuleEntitlement(){}'))).replace('"@/lib/money"',JSON.stringify(moneyModule)).replace('"@/lib/server/http"',JSON.stringify(processHttp)).replace('"@/lib/server/session"',JSON.stringify(processSession)).replace('"@/lib/server/rbac"',JSON.stringify(processRbac)).replace('"@/lib/server/db"',JSON.stringify(processDb)).replace('"@/lib/server/audit"',JSON.stringify(audit));
 const reimburse=await import(dataModule(reimbursementSource));
 globalThis.__processSession={...session,role:'member'};
 assert.equal((await reimburse.POST({body:{reference:'fixture-transfer'}},{params:Promise.resolve({id:expenseId})})).status,403);
 assert.equal((await db.query('select reimbursed_at from expenses where id=$1',[expenseId])).rows[0].reimbursed_at,null);
 globalThis.__processSession={...session,role:'finance'};
 assert.equal((await reimburse.POST({body:{reference:'fixture-transfer'}},{params:Promise.resolve({id:expenseId})})).status,200);
 assert.equal((await reimburse.POST({body:{reference:'fixture-transfer'}},{params:Promise.resolve({id:expenseId})})).status,200);
 assert.equal((await reimburse.POST({body:{reference:'another-transfer'}},{params:Promise.resolve({id:expenseId})})).status,409);
 // The real team GET must read the entitlement/subscription tables and return names.
 globalThis.__processSession=session;
 const invitePasswords=dataModule((await fs.readFile('lib/server/password.ts','utf8')).replace('import "server-only";',''));
 const inviteMail=dataModule('export function mailLayout(title,body,cta){return body+cta.url} export async function sendMail(mail){globalThis.__invitationMails.push(mail);if(globalThis.__invitationMailMode==="uncertain")throw new Error("ambiguous transport");return {delivered:globalThis.__invitationMailMode!=="unavailable"}}');
 let invitationServiceSource=(await fs.readFile('lib/server/invitations.ts','utf8')).replace('import "server-only";','');
 for(const [specifier,url] of Object.entries({'./http':processHttp,'./db':processDb,'./password':invitePasswords,'./email':inviteMail,'./env':dataModule('export const env={appUrl:"https://fixture.invalid"}'),'./rbac':processRbac,'./audit':audit,'./business-idempotency':idempotencyModule})){invitationServiceSource=invitationServiceSource.replaceAll(JSON.stringify(specifier),JSON.stringify(url));}
 const invitationService=dataModule(invitationServiceSource);
 globalThis.__invitationMails=[];globalThis.__invitationMailMode='accepted';
 const teamSource=(await fs.readFile('app/api/settings/team/invitations/route.ts','utf8')).replace('"@/lib/money"',JSON.stringify(moneyModule)).replace('"@/lib/server/http"',JSON.stringify(processHttp)).replace('"@/lib/server/session"',JSON.stringify(processSession)).replace('"@/lib/server/rbac"',JSON.stringify(processRbac)).replace('"@/lib/server/db"',JSON.stringify(processDb)).replace('"@/lib/server/invitations"',JSON.stringify(invitationService));
 const team=await import(dataModule(teamSource));const teamResult=await team.GET();assert.equal(teamResult.status,200);assert.ok(teamResult.data.members.every(m=>m.email&&m.name));assert.ok(teamResult.data.userLimit>0);assert.ok(teamResult.data.plan);
 await db.query("select set_config('app.organization_id',$1,false)",[demo]);
 await globalThis.__processTransaction(demo,c=>c.query("insert into organization_entitlements(organization_id,max_users) values($1,50) on conflict(organization_id) do update set max_users=50",[demo]));
 const inviteRequest=(email,role,key)=>({body:{email,role},headers:new Headers({'Idempotency-Key':key})});
 const atomicInvite=await team.POST(inviteRequest('atomic-invite@fixture.invalid','finance','invitation-atomic-fixture'));assert.equal(atomicInvite.status,201,JSON.stringify(atomicInvite));
 assert.equal((await team.POST(inviteRequest('atomic-invite@fixture.invalid','finance','invitation-atomic-fixture'))).data.id,atomicInvite.data.id);assert.equal(globalThis.__invitationMails.length,1,'A timeout replay does not send twice');
 assert.equal((await team.POST(inviteRequest('atomic-invite@fixture.invalid','reader','invitation-atomic-fixture'))).status,409,'A changed role cannot reuse a replay key');
 assert.equal((await team.POST(inviteRequest('atomic-invite@fixture.invalid','finance','invitation-other-key'))).status,409,'A fresh key cannot duplicate a pending invitation');
 globalThis.__invitationMailMode='unavailable';
 const unavailableInvite=await team.POST(inviteRequest('retry-invite@fixture.invalid','reader','invitation-retry-fixture'));assert.equal(unavailableInvite.status,503);
 const persistedInvite=(await db.query("select i.id,m.role,m.status,o.status delivery,t.metadata from organization_invitations i join mail_outbox o on o.entity_id=i.id::text and o.organization_id=i.organization_id join app_users u on u.email=i.email join organization_memberships m on m.user_id=u.id and m.organization_id=i.organization_id join auth_tokens t on t.user_id=u.id and t.organization_id=i.organization_id and t.metadata->>'invitation_id'=i.id::text where i.organization_id=$1 and i.email='retry-invite@fixture.invalid'",[demo])).rows[0];
 assert.equal(persistedInvite.delivery,'failed');assert.equal(persistedInvite.role,'reader');assert.equal(persistedInvite.status,'invited');assert.equal(persistedInvite.metadata.invitation_id,persistedInvite.id);
 globalThis.__invitationMailMode='accepted';assert.equal((await team.POST(inviteRequest('retry-invite@fixture.invalid','reader','invitation-retry-fixture'))).data.id,persistedInvite.id);
 globalThis.__invitationMailMode='uncertain';assert.equal((await team.POST(inviteRequest('uncertain-invite@fixture.invalid','member','invitation-uncertain-fixture'))).status,503);const attempts=globalThis.__invitationMails.length;
 globalThis.__invitationMailMode='accepted';assert.equal((await team.POST(inviteRequest('uncertain-invite@fixture.invalid','member','invitation-uncertain-fixture'))).status,409);assert.equal(globalThis.__invitationMails.length,attempts,'Ambiguous mail is never blindly sent again');
 globalThis.__processSession={...session,role:'member'};assert.equal((await team.POST(inviteRequest('forbidden-invite@fixture.invalid','admin','invitation-forbidden-fixture'))).status,403);globalThis.__processSession=session;
 // A database failure at the final outbox step rolls back identity, membership,
 // invitation and token. It must not leave a partially invited business user.
 await db.exec("create function reject_fixture_mail() returns trigger language plpgsql as $$ begin if new.recipient='rollback-invite@fixture.invalid' then raise exception 'synthetic outbox failure'; end if; return new; end $$; create trigger reject_fixture_mail before insert on mail_outbox for each row execute function reject_fixture_mail()");
 assert.equal((await team.POST(inviteRequest('rollback-invite@fixture.invalid','member','invitation-rollback-fixture'))).status,500);
 assert.equal((await db.query("select count(*)::int n from app_users where email='rollback-invite@fixture.invalid'")).rows[0].n,0);assert.equal((await db.query("select count(*)::int n from organization_invitations where email='rollback-invite@fixture.invalid'")).rows[0].n,0);
 await db.exec('drop trigger reject_fixture_mail on mail_outbox;drop function reject_fixture_mail()');
 delete globalThis.__invitationMails;delete globalThis.__invitationMailMode;
 console.log('Atomic invitation identity/membership/token/outbox, same-key replay, failed-delivery recovery, ambiguous-delivery protection, roles and database rollback passed.');

 for(const table of ['organization_invitations','document_deliveries']){await db.exec('set role tenant_probe');await db.query("select set_config('app.platform_operator','',false)");await db.query("select set_config('app.organization_id',$1,false)",[sandbox]);assert.equal((await db.query('select * from '+table+' where organization_id=$1',[demo])).rows.length,0);await db.exec('reset role');}
 await db.query("select set_config('app.organization_id',$1,false)",[demo]);

 const processTime=(await db.query("insert into time_entries(organization_id,external_id,customer_id,person_name,worker_type,work_date,hours,description,billable,approved,sales_rate) values($1,'process-time',$2,'Fixture person','employee','2026-10-06',2,'Fixture time',true,true,100) returning id",[demo,documentArgs.p_customer_id])).rows[0].id;
 const timeDraft=await mutateApiBusiness(client,session,'create_document_atomic',{...documentArgs,p_number:'FLOW-TIME',p_items:[{description:'Work',quantity:2,unit_price:100,time_entry_ids:[processTime]}]});
 assert.equal((await db.query('select invoiced_invoice_id from time_entries where id=$1',[processTime])).rows[0].invoiced_invoice_id,timeDraft.id);
 await changeDocumentStatus(client,session,timeDraft.number,'cancel','');
 assert.equal((await db.query('select invoiced_invoice_id from time_entries where id=$1',[processTime])).rows[0].invoiced_invoice_id,null,'Cancellation releases time for a corrected invoice');
 // Actual PDF generator, including the full Swiss QR page.
 const pdfSource=(await fs.readFile('lib/server/document-pdf.ts','utf8')).replace('import "server-only";','').replace('"pdfkit"',JSON.stringify(new URL('../node_modules/pdfkit/js/pdfkit.js',import.meta.url).href)).replace('"swissqrbill/pdf"',JSON.stringify(new URL('../node_modules/swissqrbill/lib/esm/pdf/index.js',import.meta.url).href)).replace('"@/lib/qr-bill"',JSON.stringify(qrModule)).replace('"@/lib/financial-status"',JSON.stringify(financialModule));
 const pdfModule=dataModule(pdfSource);const {documentPdf}=await import(pdfModule);
 const pdfInvoice=(await listApiBusiness(client,session,'documents','number=eq.'+pending.number))[0];
 const draftPdf=await documentPdf(pdfInvoice,company);
 const generatedPdf=await documentPdf({...pdfInvoice,status:'sent'},company);
 assert.ok(draftPdf.length<generatedPdf.length,'Draft PDF never exposes a payable QR code');
 assert.ok(generatedPdf.toString('latin1').includes('/FontFile2'),'The real PDF embeds font outlines for consistent preview/download typography');
 assert.ok(generatedPdf.toString('latin1').includes('+LiberationSans-Bold')&&generatedPdf.toString('latin1').includes('+LiberationSans'),'The PDF includes regular and bold faces');
 if(process.env.BINSO_PDF_QA_DIR){await fs.mkdir(process.env.BINSO_PDF_QA_DIR,{recursive:true});for(const [name,doc] of [['invoice',{...pdfInvoice,status:'sent'}],['partial',{...pdfInvoice,status:'partial',paid_amount:100}],['draft',pdfInvoice],['long',{...pdfInvoice,status:'sent',items:Array.from({length:75},(_,i)=>({...pdfInvoice.items[0],description:'Position '+(i+1)+' – professionelle Beratung und Implementation'}))}],['oversized',{...pdfInvoice,status:'sent',items:[{...pdfInvoice.items[0],description:'Lange Beschreibung mit vollständigem Inhalt. '.repeat(300)+'ENDMARKER'}]}]])await fs.writeFile(process.env.BINSO_PDF_QA_DIR+'/'+name+'.pdf',await documentPdf(doc,company));}
 assert.equal(generatedPdf.subarray(0,4).toString(),'%PDF');assert.ok(generatedPdf.length>10000);assert.ok(generatedPdf.toString('latin1').includes('/Count 2'),'Payable invoice and QR slip occupy separate A4 pages');
 const cancelledPdf=await documentPdf((await listApiBusiness(client,session,'documents','number=eq.'+timeDraft.number))[0],company);assert.ok(cancelledPdf.length<generatedPdf.length,'Cancelled document has no payable QR code');
 const previewSource=(await fs.readFile('app/api/documents/preview/route.ts','utf8')).replace('"@/lib/money"',JSON.stringify(moneyModule)).replace('"@/lib/server/http"',JSON.stringify(processHttp)).replace('"@/lib/server/session"',JSON.stringify(processSession)).replace('"@/lib/server/db"',JSON.stringify(processDb)).replace('"@/lib/server/rbac"',JSON.stringify(processRbac)).replace('"@/lib/server/plan-access"',JSON.stringify(dataModule('export async function requireModuleEntitlement(){}'))).replace('"@/lib/server/document-pdf"',JSON.stringify(pdfModule)).replace('"@/lib/server/document-logo"',JSON.stringify(dataModule('export async function documentLogo(){return undefined}')));
 const previewRoute=await import(dataModule(previewSource));
 const previewBody={kind:'Rechnung',customerId:documentArgs.p_customer_id,number:'PREVIEW',date:'2026-10-08',due:'30',currency:'CHF',positions:[{description:'Draft preview',quantity:2,price:100,vatRate:8.1}]};
 const beforePreview=Number((await db.query('select count(*) n from invoices where organization_id=$1',[demo])).rows[0].n);
 const previewResponse=await previewRoute.POST({body:previewBody});assert.equal(previewResponse.status,200);assert.equal(Buffer.from(await previewResponse.arrayBuffer()).subarray(0,4).toString(),'%PDF');
 assert.equal(Number((await db.query('select count(*) n from invoices where organization_id=$1',[demo])).rows[0].n),beforePreview,'Preview does not persist or finalize an invoice');
 assert.equal((await previewRoute.POST({body:{...previewBody,customerId:clonedCustomer.id}})).status,404,'Preview cannot read another tenant customer');
 assert.equal((await previewRoute.POST({body:{...previewBody,positions:[{quantity:-1,price:100}]}})).status,400);
 globalThis.__sendCount=0;globalThis.__sendFail=false;
 const mailFixture=dataModule(`export const mailLayout=(title,body)=>title+body;export async function sendMail(mail){globalThis.__sendCount++;if(!mail.attachments[0].content.subarray(0,4).toString().includes('%PDF'))throw Error('Missing PDF');if(globalThis.__sendFail)throw Error('Fixture provider failure');return {delivered:true}}`);
 const sendSource=(await fs.readFile('app/api/documents/[number]/send/route.ts','utf8')).replace('"@/lib/money"',JSON.stringify(moneyModule)).replace('"@/lib/server/http"',JSON.stringify(processHttp)).replace('"@/lib/server/session"',JSON.stringify(processSession)).replace('"@/lib/server/db"',JSON.stringify(processDb)).replace('"@/lib/server/document-process"',JSON.stringify(dataModule(processSource))).replace('"@/lib/server/repositories/business-api"',JSON.stringify(businessUrlForProcess())).replace('"@/lib/server/document-pdf"',JSON.stringify(pdfModule)).replace('"@/lib/server/document-logo"',JSON.stringify(dataModule('export async function documentLogo(){return undefined}'))).replace('"@/lib/server/email"',JSON.stringify(mailFixture)).replace('"@/lib/server/audit"',JSON.stringify(audit));
 const sender=await import(dataModule(sendSource));
 const sendInvoice=await mutateApiBusiness(client,session,'create_document_atomic',{...documentArgs,p_number:'FLOW-SEND'});
 const sendRequest={body:{recipient:'fixture@example.invalid',requestKey:'send-success'}};
 globalThis.__processSession={...session,isDemo:false};
 assert.equal((await sender.POST(sendRequest,{params:Promise.resolve({number:sendInvoice.number})})).status,409,'Draft sends are blocked before any mail or delivery record');
 assert.equal(globalThis.__sendCount,0);
 await changeDocumentStatus(client,session,sendInvoice.number,'issue','');
 assert.equal((await sender.POST(sendRequest,{params:Promise.resolve({number:sendInvoice.number})})).status,200);
 assert.equal((await sender.POST(sendRequest,{params:Promise.resolve({number:sendInvoice.number})})).status,200);
 assert.equal(globalThis.__sendCount,1,'Identical send requests deliver once');
 assert.equal((await db.query('select status from invoices where id=$1',[sendInvoice.id])).rows[0].status,'sent');
 const failedInvoice=await mutateApiBusiness(client,session,'create_document_atomic',{...documentArgs,p_number:'FLOW-SEND-FAIL'});globalThis.__sendFail=true;
 await changeDocumentStatus(client,session,failedInvoice.number,'issue','');
 const failedRequest={body:{recipient:'fixture@example.invalid',requestKey:'send-failure'}};
 assert.equal((await sender.POST(failedRequest,{params:Promise.resolve({number:failedInvoice.number})})).status,502);
 assert.equal((await db.query('select status from invoices where id=$1',[failedInvoice.id])).rows[0].status,'sent');
 assert.equal((await sender.POST(failedRequest,{params:Promise.resolve({number:failedInvoice.number})})).status,409);
 assert.equal(globalThis.__sendCount,2,'Unconfirmed sends do not retry automatically');
 globalThis.__processSession={...session,isDemo:true};
 assert.equal((await sender.POST({body:{recipient:'fixture@example.invalid',requestKey:'demo-block'}},{params:Promise.resolve({number:failedInvoice.number})})).status,403);
 delete globalThis.__sendCount;delete globalThis.__sendFail;
 // Invitation activation is atomic, expires/revokes safely and never resets an existing password.
 const passwords=dataModule((await fs.readFile('lib/server/password.ts','utf8')).replace('import "server-only";',''));const {hashPassword}=await import(passwords);
 const invitationSource=(await fs.readFile('app/api/auth/invitation/route.ts','utf8')).replace('"@/lib/money"',JSON.stringify(moneyModule)).replace('"@/lib/server/http"',JSON.stringify(processHttp)).replace('"@/lib/server/db"',JSON.stringify(processDb)).replace('"@/lib/server/password"',JSON.stringify(passwords)).replace('"@/lib/server/rate-limit"',JSON.stringify(dataModule('export async function enforceRateLimit(){}')));
 const invitationHandler=await import(dataModule(invitationSource));
 const {createHash}=await import('node:crypto');
 const seedInvitation=async(userId,email,status,password,token)=>{
  await db.query("insert into app_users(id,email,display_name,status,password_hash) values($1,$2,'Fixture invitee',$3,$4)",[userId,email,status,await hashPassword(password)]);
  await db.query("insert into organization_memberships(organization_id,user_id,email,role,status) values($1,$2,$3,'finance','invited')",[demo,userId,email]);
  const inv=(await db.query("insert into organization_invitations(organization_id,email,role,expires_at,created_by_user_id) values($1,$2,'finance',now()+interval '1 day','fixture') returning id",[demo,email])).rows[0].id;
  await db.query("insert into auth_tokens(user_id,organization_id,email,token_hash,token_type,metadata,expires_at) values($1,$2,$3,$4,'invitation',$5::jsonb,now()+interval '1 day')",[userId,demo,email,createHash('sha256').update(token).digest('hex'),JSON.stringify({invitation_id:inv})]);return inv;
 };
 await db.query("insert into organization_entitlements(organization_id,max_users) values($1,50) on conflict(organization_id) do update set max_users=50",[demo]);
 const originalPassword='Fixture original password 123';
 const newInvitation=await seedInvitation('flow-new-user','flow-new@example.invalid','invited',originalPassword,'flow-new-token');
 assert.equal((await invitationHandler.GET({nextUrl:new URL('https://example.invalid/?token=flow-new-token')})).data.existingAccount,false);
 assert.equal((await invitationHandler.POST({body:{token:'flow-new-token',password:'short'}})).status,400);
 const acceptedNew=await invitationHandler.POST({body:{token:'flow-new-token',password:'Fixture new password 456',name:'New colleague'}});assert.equal(acceptedNew.status,200,JSON.stringify(acceptedNew));
 assert.equal((await db.query('select role,status from organization_memberships where organization_id=$1 and user_id=$2',[demo,'flow-new-user'])).rows[0].role,'finance');
 assert.equal((await db.query('select status from organization_invitations where id=$1',[newInvitation])).rows[0].status,'accepted');
 assert.equal((await invitationHandler.POST({body:{token:'flow-new-token',password:'Fixture new password 456'}})).status,400);
 const existingInvitation=await seedInvitation('flow-existing-user','flow-existing@example.invalid','active',originalPassword,'flow-existing-token');
 const originalHash=(await db.query('select password_hash from app_users where id=$1',['flow-existing-user'])).rows[0].password_hash;
 assert.equal((await invitationHandler.POST({body:{token:'flow-existing-token',password:'Fixture wrong password 789'}})).status,403);
 assert.equal((await db.query('select status from organization_invitations where id=$1',[existingInvitation])).rows[0].status,'pending');
 assert.equal((await invitationHandler.POST({body:{token:'flow-existing-token',password:originalPassword}})).status,200);
 assert.equal((await db.query('select password_hash from app_users where id=$1',['flow-existing-user'])).rows[0].password_hash,originalHash);
 const revoked=await seedInvitation('flow-revoked-user','flow-revoked@example.invalid','invited',originalPassword,'flow-revoked-token');await db.query("update organization_invitations set status='revoked' where id=$1",[revoked]);
 assert.equal((await invitationHandler.POST({body:{token:'flow-revoked-token',password:originalPassword}})).status,400);
 console.log('PDF/QR generation, send idempotency/failure/demo guards, cancellation release and new/existing/revoked invitation acceptance passed with synthetic fixtures only.');
 console.log('Team schema, entitlement limits, document status/locks/conversion, expense approval/reimbursement/billing and tenant isolation passed.');

 // Full business process and short paths use actual handlers against isolated PostgreSQL fixtures.
 const loadProcessRoute=async path=>{let source=await fs.readFile(path,'utf8');for(const [specifier,url] of Object.entries({'@/lib/money':moneyModule,'@/lib/server/http':processHttp,'@/lib/server/session':processSession,'@/lib/server/db':processDb,'@/lib/server/rbac':processRbac,'@/lib/server/audit':audit,'@/lib/permissions':permissions,'@/lib/server/validation':dataModule(await fs.readFile('lib/server/validation.ts','utf8').then(source=>source.replace('import "server-only";','').replace('"./http"',JSON.stringify(processHttp))))})){source=source.replaceAll(JSON.stringify(specifier),JSON.stringify(url)).replaceAll("'"+specifier+"'",JSON.stringify(url));}return import(dataModule(source));};
 const projectHandler=await loadProcessRoute('app/api/projects/route.ts');
 globalThis.__processSession={...session,name:'Process Owner',email:'owner@fixture.invalid'};
 const projectCreated=await projectHandler.POST({body:{name:'Cloud Migration',customerId:documentArgs.p_customer_id,sourceOffer:processQuote.number}});
 assert.equal(projectCreated.status,201,JSON.stringify(projectCreated));
 const projectReplay=await projectHandler.POST({body:{name:'Cloud Migration',customerId:documentArgs.p_customer_id,sourceOffer:processQuote.number}});
 assert.equal(projectCreated.data.item.id,projectReplay.data.item.id,'An offer starts exactly one project');
 assert.equal((await projectHandler.POST({body:{name:'Wrong tenant',customerId:'10000000-0000-4000-8000-000000000002',sourceOffer:processQuote.number}})).status,409);
 const timeCreated=await manualTimeHandler.POST({body:{projectId:projectCreated.data.item.id,description:'Migration and rollout',durationMinutes:750,startedAt:'2026-10-01',billable:true,salesRate:180}});
 assert.equal(timeCreated.status,201,JSON.stringify(timeCreated));assert.equal(timeCreated.data.item.customer_id,documentArgs.p_customer_id,'Project supplies customer without redundant selection');
 const timeReview=await loadProcessRoute('app/api/time-entries/[id]/route.ts');
 const submitted=await timeReview.PATCH({body:{action:'submit'}},{params:Promise.resolve({id:timeCreated.data.item.id})});assert.equal(submitted.status,200,JSON.stringify(submitted));assert.ok(submitted.data.item.submitted_at);
 assert.equal((await timeReview.PATCH({body:{action:'approve'}},{params:Promise.resolve({id:timeCreated.data.item.id})})).status,200);
 const serviceArgs={...documentArgs,p_number:'PROCESS-TIME-INVOICE',p_items:[{description:'IT-Support September',quantity:12.5,unit:'Std.',unit_price:180,vat_rate:8.1,time_entry_ids:[timeCreated.data.item.id]},{description:'A long description for the rollout of adapters and workplace connectivity',quantity:2,unit:'Stück',unit_price:60,vat_rate:8.1}]};
 const atomic=(operation,args)=>globalThis.__processTransaction(demo,c=>mutateApiBusiness(c,session,operation,args));
 const timeInvoice=await atomic('create_document_atomic',serviceArgs);assert.equal(Number(timeInvoice.total),2561.97);
 await assert.rejects(()=>atomic('create_document_atomic',{...serviceArgs,p_number:'PROCESS-TIME-DUP'}),e=>e.code==='time_entries_changed');
 assert.equal((await db.query('select count(*)::int n from invoices where organization_id=$1 and invoice_no=$2',[demo,'PROCESS-TIME-DUP'])).rows[0].n,0,'Failed double billing rolls back the whole invoice');
 const unusedTime=await manualTimeHandler.POST({body:{customerId:documentArgs.p_customer_id,description:'Direct customer work',durationMinutes:60,startedAt:'2026-10-01',billable:true,salesRate:180}});
 await timeReview.PATCH({body:{action:'approve'}},{params:Promise.resolve({id:unusedTime.data.item.id})});
 await assert.rejects(()=>atomic('create_document_atomic',{...serviceArgs,p_number:'PROCESS-INTRA-DUP',p_items:[{description:'One',quantity:1,unit_price:180,time_entry_ids:[unusedTime.data.item.id]},{description:'Two',quantity:1,unit_price:180,time_entry_ids:[unusedTime.data.item.id]}]}),e=>e.code==='duplicate_service');
 assert.equal((await db.query('select invoiced_invoice_id from time_entries where id=$1',[unusedTime.data.item.id])).rows[0].invoiced_invoice_id,null);
 await changeDocumentStatus(client,session,timeInvoice.number,'issue','');
 const paymentBase={p_invoice_id:timeInvoice.id,p_method:'bank',p_note:'Process payment'};
 await assert.rejects(()=>atomic('create_payment_idempotent',{...paymentBase,p_paid_on:'2026-10-01',p_amount:2561.98,p_idempotency_key:'process-overpay'}),e=>e.code==='payment_exceeds_balance');
 await atomic('create_payment_idempotent',{...paymentBase,p_paid_on:'2026-10-03',p_amount:1000,p_idempotency_key:'process-payment-1'});
 let reloaded=(await listApiBusiness(client,session,'documents','id=eq.'+timeInvoice.id))[0];assert.equal(reloaded.payment_status,'partial');assert.equal(reloaded.paid_on,null);assert.equal((await import(financialModule)).openAmount(reloaded),1561.97);
 await atomic('create_payment_idempotent',{...paymentBase,p_paid_on:'2026-10-01',p_amount:500,p_idempotency_key:'process-payment-2'});
 const finalArgs={...paymentBase,p_paid_on:'2026-10-06',p_amount:1061.97,p_idempotency_key:'process-payment-3'};const finalPayment=await atomic('create_payment_idempotent',finalArgs);assert.equal((await atomic('create_payment_idempotent',finalArgs)).id,finalPayment.id);
 reloaded=(await listApiBusiness(client,session,'documents','id=eq.'+timeInvoice.id))[0];assert.equal(reloaded.payment_status,'paid');assert.equal(reloaded.paid_on,'2026-10-06','Completion date comes from chronologically accumulated actual payments');
 await assert.rejects(()=>atomic('create_payment_idempotent',{...finalArgs,p_idempotency_key:'process-paid-duplicate',p_amount:1}),e=>e.code==='payment_exceeds_balance');
 assert.equal((await timeReview.PATCH({body:{action:'approve'}},{params:Promise.resolve({id:timeCreated.data.item.id})})).status,404,'Invoiced time is locked');
 const notificationRoute=await loadProcessRoute('app/api/notifications/route.ts');
 const notificationId=(await db.query("insert into in_app_notifications(organization_id,user_id,kind,title,body) values($1,$2,'system','Synthetic notification','No personal data') returning id",[demo,session.userId])).rows[0].id;
 const foreignNotificationId=(await db.query("insert into in_app_notifications(organization_id,user_id,kind,title,body) values($1,null,'system','Foreign synthetic notification','No personal data') returning id",[sandbox])).rows[0].id;
 assert.equal((await notificationRoute.PATCH({body:{all:true}})).status,200);assert.ok((await db.query('select read_at from in_app_notifications where id=$1',[notificationId])).rows[0].read_at);assert.equal((await db.query('select read_at from in_app_notifications where id=$1',[foreignNotificationId])).rows[0].read_at,null,'Read all cannot affect another tenant');
 const policy=await loadProcessRoute('app/api/time-entries/policy/route.ts');assert.equal((await policy.PATCH({body:{required:false}})).status,200);
 const immediate=await manualTimeHandler.POST({body:{customerId:documentArgs.p_customer_id,description:'Direct approved work',durationMinutes:60,billable:true}});assert.equal(immediate.data.item.approved,true);
 const internalProcessTime=await manualTimeHandler.POST({body:{projectName:'Weiterbildung',description:'Internal training',durationMinutes:90,billable:false}});assert.equal(internalProcessTime.status,201);assert.equal(internalProcessTime.data.item.customer_id,null);assert.equal(internalProcessTime.data.item.billable,false);
 await policy.PATCH({body:{required:true}});
 globalThis.__processSession={...globalThis.__processSession,role:'member'};assert.equal((await policy.PATCH({body:{required:false}})).status,403);assert.equal((await projectHandler.POST({body:{name:'Forbidden'}})).status,403);
 globalThis.__processSession={...session,name:'Process Owner',email:'owner@fixture.invalid'};
 assert.equal((await listApiBusiness(client,session,'documents','number=eq.'+processQuote.number))[0].project_id,projectCreated.data.item.id);
 assert.equal((await listApiBusiness(client,session,'documents','id=eq.'+converted.id))[0].source_offer,processQuote.number);

 const summarySource=(await fs.readFile('lib/server/repositories/financial-summary.ts','utf8')).replace('import "server-only";','').replace("'@/lib/permissions'",JSON.stringify(permissions));
 const {financialSummary}=await import(dataModule(summarySource));
 const ownerSummary=await financialSummary(client,session,documentArgs.p_customer_id);assert.ok(ownerSummary.invoices.length);assert.ok(Number(ownerSummary.time.ready_hours)>=1);
 const restrictedSummary=await financialSummary(client,{...session,role:'member'},documentArgs.p_customer_id);assert.equal(restrictedSummary.invoices.length,0);assert.equal(restrictedSummary.offers,null,'A shared workspace cannot expose restricted finance data');
 const activitySource=(await fs.readFile('lib/server/repositories/customer-activity.ts','utf8')).replace('import "server-only";','').replace('"@/lib/permissions"',JSON.stringify(permissions));
 const activityModule=dataModule(activitySource);
 const workspaceSource=(await fs.readFile('lib/server/repositories/customer-workspace.ts','utf8')).replace('import "server-only";','').replace('"@/lib/permissions"',JSON.stringify(permissions)).replace('"../http"',JSON.stringify(http)).replace('"./business-api"',JSON.stringify(dataModule(businessSource))).replace('"./financial-summary"',JSON.stringify(dataModule(summarySource))).replace('"./customer-activity"',JSON.stringify(activityModule));
 const {customerWorkspace}=await import(dataModule(workspaceSource));
 const workspace=await customerWorkspace(client,session,documentArgs.p_customer_id);assert.equal(workspace.item.id,documentArgs.p_customer_id);assert.deepEqual(workspace.summary,ownerSummary);assert.ok(workspace.documents.some(item=>item.id===timeInvoice.id));assert.ok(workspace.activity.some(item=>item.title==='Zahlung erhalten'));
 for(const table of ['customers','customer_contacts','documents','payments','products','employees','expenses','projects','time_entries','support_tickets']){
  const ownRows=await listApiBusiness(client,session,table,'');assert.ok(ownRows.length,table+' positive tenant fixture exists');
  const foreignRows=await listApiBusiness(client,{...session,organizationId:sandbox,userId:'sandbox-user'},table,'id=eq.'+encodeURIComponent(String(ownRows[0].id)));assert.equal(foreignRows.length,0,table+' rejects a foreign direct ID in the canonical repository');
 }
 console.log('All ten canonical business repository sources reject foreign direct IDs with positive source fixtures.');
 const restrictedWorkspace=await customerWorkspace(client,{...session,role:'member'},documentArgs.p_customer_id);assert.equal(restrictedWorkspace.documents.length,0);assert.equal(restrictedWorkspace.summary.invoices.length,0);assert.ok(!restrictedWorkspace.activity.some(item=>item.title==='Zahlung erhalten'));
 await assert.rejects(()=>customerWorkspace(client,{...session,organizationId:sandbox},documentArgs.p_customer_id),e=>e.code==='not_found');
 const activityRouteSource=(await fs.readFile('app/api/customers/[id]/activity/route.ts','utf8')).replace("'@/lib/server/repositories/customer-activity'",JSON.stringify(activityModule));
 let compiledActivity=activityRouteSource;for(const [specifier,url] of Object.entries({'@/lib/server/http':processHttp,'@/lib/server/session':processSession,'@/lib/server/db':processDb,'@/lib/server/rbac':processRbac})){compiledActivity=compiledActivity.replaceAll("'"+specifier+"'",JSON.stringify(url));}
 const activity=await import(dataModule(compiledActivity));

 const customerEvents=await activity.GET({}, {params:Promise.resolve({id:documentArgs.p_customer_id})});assert.equal(customerEvents.status,200,JSON.stringify(customerEvents));for(const title of ['Rechnung erstellt','Angebot angenommen','Zahlung erhalten','Projekt erstellt','Arbeitszeit erfasst'])assert.ok(customerEvents.data.items.some(item=>item.title===title),title);
 // Document retry replay, payload conflict and central counter behavior.
 const retryArgs={...documentArgs,p_idempotency_key:'document-repeat-fixture'};
 const createdOnce=await atomic('create_document_atomic',retryArgs);
 const replay=await atomic('create_document_atomic',retryArgs);
 assert.equal(replay.id,createdOnce.id);assert.equal(replay.number,createdOnce.number);
 await assert.rejects(()=>atomic('create_document_atomic',{...retryArgs,p_note:'Different payload'}),e=>e.code==='idempotency_conflict');
 assert.ok(createdOnce.number.startsWith('RE-'));assert.notEqual(createdOnce.number,retryArgs.p_number,'Incoming numbers cannot bypass the counter');
 await assert.rejects(()=>atomic('update_document_atomic',{...documentArgs,p_current_number:createdOnce.number,p_number:'RENAMED'}),e=>e.code==='number_immutable');
 const numberBefore=(await db.query('select next_value from business_document_counters where organization_id=$1 and kind=\'invoice\' order by period desc limit 1',[demo])).rows[0].next_value;
 const invoiceCountBefore=(await db.query('select count(*)::int n from invoices where organization_id=$1',[demo])).rows[0].n;
 await assert.rejects(()=>atomic('create_document_atomic',{...serviceArgs,p_idempotency_key:'document-rollback-fixture'}),e=>e.code==='time_entries_changed');
 assert.equal((await db.query('select next_value from business_document_counters where organization_id=$1 and kind=\'invoice\' order by period desc limit 1',[demo])).rows[0].next_value,numberBefore,'Failed transaction does not commit a counter reservation');
 assert.equal((await db.query('select count(*)::int n from invoices where organization_id=$1',[demo])).rows[0].n,invoiceCountBefore,'Failed linked billing commits no invoice');
 const roundedOffer=await atomic('create_document_atomic',{...documentArgs,p_kind:'offer',p_items:[{description:'Precision fixture',quantity:1.11,unit_price:0.05,vat_rate:8.1},{description:'Second line',quantity:0.33,unit_price:1.01,vat_rate:8.1}]});
 const {documentTotals}=await import(moneyModule);
 const precision=documentTotals([{quantity:1.11,unit_price:0.05,vat_rate:8.1},{quantity:0.33,unit_price:1.01,vat_rate:8.1}]);
 assert.equal(Number(roundedOffer.total),precision.total);assert.equal(Number(roundedOffer.subtotal),precision.subtotal);assert.equal(Number(roundedOffer.vat_amount),precision.vat);
 const financeRepository=dataModule((await fs.readFile('lib/server/repositories/finance.ts','utf8')).replace("import 'server-only';",''));
 const {financeData}=await import(financeRepository);
 const cash=await financeData(client,demo);const expectedCash=(await db.query("select coalesce(sum(p.amount),0) amount from payments p join invoices i on i.id=p.invoice_id and i.organization_id=p.organization_id where p.organization_id=$1 and p.archived_at is null and p.allocation_status='matched' and i.currency='CHF'",[demo])).rows[0].amount;
 assert.equal(cash.payments.reduce((sum,row)=>sum+Math.round(Number(row.amount)*100),0),Math.round(Number(expectedCash)*100));
 const allDocuments=await listApiBusiness(client,session,'documents','kind=eq.invoice');
 const summaryCheck=await financialSummary(client,session,null);
 for(const bucket of summaryCheck.invoices){const unpaid=allDocuments.filter(row=>row.currency===bucket.currency&&!['draft','cancelled'].includes(row.status));assert.equal(unpaid.reduce((sum,row)=>sum+Math.round(financialOpen(row)*100),0),Math.round(Number(bucket.open_amount)*100));}
 function financialOpen(row){return Math.max(0,Math.round(Number(row.total)*100)-Math.round(Number(row.paid_amount)*100))/100;}
 console.log('V21.3 document idempotency/payload conflict, immutable server numbers, transaction/counter rollback, quote precision and cash/open-balance parity passed.');
 // Real upload/download handlers share tenant relations and enforce purpose permissions.
 const fileRelations=dataModule(await fs.readFile('lib/file-associations.ts','utf8'));
 const validation=dataModule((await fs.readFile('lib/server/file-validation.ts','utf8')).replace("'./http'",JSON.stringify(processHttp)));
 const limits=dataModule(await fs.readFile('config/limits.ts','utf8'));
 const fileRoute=async path=>{let source=await fs.readFile(path,'utf8');for(const [specifier,url] of Object.entries({'@/lib/server/file-relations':fileRelations,'@/lib/server/file-validation':validation,'@/config/limits':limits,'@/lib/server/http':processHttp,'@/lib/server/session':processSession,'@/lib/server/db':processDb,'@/lib/server/rbac':processRbac,'@/lib/permissions':permissions,'@/lib/server/storage':dataModule('export async function getBlobByUrl(){throw new Error("External storage must not be contacted by isolated tests")}')})){source=source.replaceAll(JSON.stringify(specifier),JSON.stringify(url)).replaceAll("'"+specifier+"'",JSON.stringify(url));}return import(dataModule(source));};
 const fileUpload=await fileRoute('app/api/files/route.ts'),fileDownload=await fileRoute('app/api/files/[id]/download/route.ts');
 const uploadRequest=(entityId,mime='text/plain',bytes='synthetic attachment')=>{const form=new FormData();form.set('purpose','customer_document');form.set('entityId',entityId);form.set('file',new File([bytes],'fixture.txt',{type:mime}));return {formData:async()=>form};};
 const uploaded=await fileUpload.POST(uploadRequest(documentArgs.p_customer_id));assert.equal(uploaded.status,201,JSON.stringify(uploaded));assert.equal(uploaded.data.item.customer_id,documentArgs.p_customer_id);
 const downloaded=await fileDownload.GET({}, {params:Promise.resolve({id:uploaded.data.item.id})});assert.equal(downloaded.status,200);assert.equal(await downloaded.text(),'synthetic attachment');assert.equal(downloaded.headers.get('cache-control'),'private, no-store');
 const listed=await fileUpload.GET({nextUrl:new URL('https://fixture.invalid/api/files?customerId='+documentArgs.p_customer_id)});assert.ok(listed.data.items.some(row=>row.id===uploaded.data.item.id));
 assert.equal((await fileUpload.POST(uploadRequest(documentArgs.p_customer_id,'application/pdf','not a PDF'))).status,400);
 globalThis.__processSession={...session,organizationId:sandbox};
 assert.equal((await fileDownload.GET({}, {params:Promise.resolve({id:uploaded.data.item.id})})).status,404);
 assert.equal((await fileUpload.POST(uploadRequest(documentArgs.p_customer_id))).status,404);
 globalThis.__processSession={...session,role:'employee'};
 assert.equal((await fileDownload.GET({}, {params:Promise.resolve({id:uploaded.data.item.id})})).status,403);
 globalThis.__processSession=session;
 console.log('Actual file upload/list/download, content signature, cross-tenant association/download denial and role denial passed.');
 // The unused generic record writer was removed. Public finance routes expose no
 // alternate PATCH/DELETE ledger writer that can bypass canonical transitions.
 for(const file of ['app/api/payments/[id]/route.ts','app/api/payments/route.ts']){const source=await fs.readFile(file,'utf8');assert.ok(!/export async function (PATCH|DELETE)/.test(source));}
 console.log('Full customer/offer/project/time/invoice/partial-payment process, direct customer work, internal time, optional approval, exact completion date, overpayment and double-billing protection passed.');
 delete globalThis.__processSession;delete globalThis.__processTransaction;delete globalThis.__processPlatform;
 console.log('PostgreSQL migrations, deterministic fixtures and tenant/platform RLS passed.');
}finally{await db.close()}
